 * The {@link YamlThingDTOTest} contains tests for the {@link YamlThingDTO} class.
public class YamlThingDTOTest {
        YamlThingDTO th = new YamlThingDTO();
        assertFalse(th.isValid(null, null));
        th.uid = "id";
        th.uid = "binding:id";
        th.uid = "binding:type:@id";
        th.uid = "binding:type:id";
        assertTrue(th.isValid(null, null));
        th.uid = "binding:type:$idBridge:id";
        th.uid = "binding:type:idBridge:id";
        th.bridge = "idBridge";
        th.bridge = "binding:idBridge";
        th.bridge = "binding:type:id#Bridge";
        th.bridge = "binding:type:idBridge";
        th.channels = Map.of("channel", ch);
        th.channels = Map.of("channel@name", ch);
        th.channels = Map.of("group#channel", ch);
        YamlThingDTO th1 = new YamlThingDTO();
        YamlThingDTO th2 = new YamlThingDTO();
        th1.uid = "binding:type:id";
        th2.uid = "binding:type:id2";
        assertFalse(th1.equals(th2));
        th2.uid = "binding:type:id";
        assertTrue(th1.equals(th2));
        assertEquals(th1.hashCode(), th2.hashCode());
        th1.isBridge = true;
        th2.isBridge = true;
        th1.bridge = "binding:bridge:idBridge";
        th2.bridge = "binding:bridge:idBridge";
        th1.label = "A label";
        th2.label = "A label";
        th1.location = "A location";
        th2.location = "A location";
        th1.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "val 2"));
        th2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "val 2"));
        th1.channels = Map.of("channel", ch1);
        th2.channels = Map.of("channel", ch2);
        th1.label = null;
        th2.label = null;
        th2.label = "A different label";
    public void testEqualsWithLocation() throws IOException {
        th1.location = null;
        th2.location = null;
        th2.location = "A different location";
    public void testEqualsWithIsBridge() throws IOException {
        th1.isBridge = null;
        th2.isBridge = null;
        th1.isBridge = false;
        th2.isBridge = false;
    public void testEqualsWithBridge() throws IOException {
        th1.bridge = null;
        th2.bridge = null;
        th2.bridge = "binding:bridge:idBridge2";
        th1.config = null;
        th2.config = null;
        th1.config = Map.of();
        th2.config = Map.of();
        th2.config = Map.of("param1", "other value", "param2", 50, "param3", true, "param4", List.of("val 1", "val 2"));
        th2.config = Map.of("param1", "value", "param2", 25, "param3", true, "param4", List.of("val 1", "val 2"));
        th2.config = Map.of("param1", "value", "param2", 50, "param3", false, "param4", List.of("val 1", "val 2"));
        th2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "value 2"));
        th2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1"));
        th2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", 75);
        th2.config = Map.of("param1", "value", "param2", 50, "param3", true);
        th2.config = Map.of("param4", List.of("val 1", "val 2"), "param3", true, "param2", 50, "param1", "value");
        ch2.type = "channel-other-type";
        YamlChannelDTO ch3 = new YamlChannelDTO();
        ch3.type = "channel-type";
        YamlChannelDTO ch4 = new YamlChannelDTO();
        ch4.type = "channel-other-type";
        th1.channels = Map.of("channel1", ch1);
        th2.channels = Map.of("channel1", ch3);
        th1.channels = Map.of("channel1", ch1, "channel2", ch2);
        th2.channels = Map.of("channel1", ch3, "channel2", ch4);
        th2.channels = Map.of("channel2", ch4, "channel1", ch3);
        th2.channels = null;
        th2.channels = Map.of();
        th1.channels = null;
        th1.channels = Map.of();
        th2.channels = Map.of("channel1", ch4);
