 * The {@link YamlChannelDTOTest} contains tests for the {@link YamlChannelDTO} class.
public class YamlChannelDTOTest {
        YamlChannelDTO ch = new YamlChannelDTO();
        assertFalse(ch.isValid(err, warn));
        ch.type = "channel-type";
        assertTrue(ch.isValid(err, warn));
        ch.type = "$channel-type";
        ch.type = null;
        ch.itemType = "String";
        ch.itemType = "string";
        ch.itemType = "Other";
        ch.itemType = "Number";
        ch.itemDimension = "Dimensionless";
        ch.itemType = "number";
        ch.itemDimension = "dimensionless";
        ch.itemDimension = "Other";
        ch.itemType = "Color";
        ch.itemDimension = null;
        ch.kind = "wrong";
        YamlChannelDTO ch1 = new YamlChannelDTO();
        YamlChannelDTO ch2 = new YamlChannelDTO();
        ch1.type = "channel-type";
        ch2.type = "channel-type";
        assertTrue(ch1.equals(ch2));
        assertEquals(ch1.hashCode(), ch2.hashCode());
        ch1.type = null;
        ch1.itemType = "String";
        ch2.type = null;
        ch2.itemType = "String";
        ch1.kind = "trigger";
        ch2.kind = "TRIGGER";
        ch1.label = "A label";
        ch2.label = "A label";
        ch1.description = "A description";
        ch2.description = "A description";
        ch1.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "val 2"));
        ch2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "val 2"));
    public void testEqualsWithTypeOrItemType() throws IOException {
        ch2.type = "channel-type2";
        assertFalse(ch1.equals(ch2));
        ch2.itemType = "Number";
        ch1.itemType = "Number";
        ch2.itemType = "number";
        ch1.itemDimension = "Temperature";
        ch2.itemDimension = "Humidity";
        ch2.itemDimension = "Temperature";
        ch2.itemDimension = "temperature";
        ch1.itemType = null;
        ch1.itemDimension = null;
        ch2.itemDimension = null;
        ch2.itemType = null;
        ch1.itemType = "Switch";
        ch1.kind = "state";
        ch2.itemType = "Switch";
        ch2.kind = "state";
        ch2.kind = "trigger";
        ch2.kind = "Trigger";
        ch1.kind = "Trigger";
        ch1.kind = null;
        ch2.kind = null;
        ch1.label = null;
        ch2.label = null;
        ch2.label = "A different label";
    public void testEqualsWithDescription() throws IOException {
        ch1.description = null;
        ch2.description = null;
        ch2.description = "A different description";
        ch1.config = null;
        ch2.config = null;
        ch1.config = Map.of();
        ch2.config = Map.of();
        ch2.config = Map.of("param1", "other value", "param2", 50, "param3", true, "param4", List.of("val 1", "val 2"));
        ch2.config = Map.of("param1", "value", "param2", 25, "param3", true, "param4", List.of("val 1", "val 2"));
        ch2.config = Map.of("param1", "value", "param2", 50, "param3", false, "param4", List.of("val 1", "val 2"));
        ch2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "value 2"));
        ch2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1"));
        ch2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", 75);
        ch2.config = Map.of("param1", "value", "param2", 50, "param3", true);
        ch2.config = Map.of("param4", List.of("val 1", "val 2"), "param3", true, "param2", 50, "param1", "value");
