 * The {@link YamlRuleDTOTest} contains tests for the {@link YamlRuleDTO} class.
public class YamlRuleDTOTest {
        Action action = ActionBuilder.create().withId("action1").withTypeUID("type1").build();
        Rule rule = RuleBuilder.create("rule1").withActions(action).withName("Rule 1").build();
        assertNotNull(new YamlRuleDTO(rule));
        Condition condition = ConditionBuilder.create().withId("condition1").withTypeUID("type1").build();
        rule = RuleBuilder.create(rule).withConditions(condition).build();
        Trigger trigger = TriggerBuilder.create().withId("trigger1").withTypeUID("type1").build();
        rule = RuleBuilder.create(rule).withTriggers(trigger).build();
        rule = RuleBuilder.create(rule).withConfigurationDescriptions(
                List.of(ConfigDescriptionParameterBuilder.create("number", Type.DECIMAL).build())).build();
        YamlRuleDTO ruleDTO = new YamlRuleDTO(rule);
        assertNotNull(ruleDTO);
                "YamlRuleDTO [uid=rule1, templateState=no-template, label=Rule 1, tags=[], visibility=VISIBLE, config={}, configDescriptions={number=YamlConfigDescriptionParameterDTO [required=false, type=DECIMAL, readOnly=false, multiple=false, advanced=false, verify=false, limitToOptions=true, ]}, conditions=[YamlConditionDTO [inputs={}, id=condition1, type=type1, config={}]], actions=[YamlActionDTO [inputs={}, id=action1, type=type1, config={}]], triggers=[YamlModuleDTO [id=trigger1, type=type1, config={}]]]",
                ruleDTO.toString());
        rule = RuleBuilder.create(rule).withTemplateUID("templateUID").withActions(List.of())
                .withDescription("Rule description").build();
        ruleDTO = new YamlRuleDTO(rule);
                "YamlRuleDTO [uid=rule1, template=templateUID, templateState=no-template, label=Rule 1, tags=[], description=Rule description, visibility=VISIBLE, config={}, configDescriptions={number=YamlConfigDescriptionParameterDTO [required=false, type=DECIMAL, readOnly=false, multiple=false, advanced=false, verify=false, limitToOptions=true, ]}, conditions=[YamlConditionDTO [inputs={}, id=condition1, type=type1, config={}]], triggers=[YamlModuleDTO [id=trigger1, type=type1, config={}]]]",
        YamlRuleDTO rule = new YamlRuleDTO();
        assertFalse(rule.isValid(null, null));
        rule.uid = " ";
        rule.label = "Test";
        rule.config = new HashMap<>();
        rule.config.put("foo", "bar");
        rule.uid = "id";
        assertTrue(rule.isValid(null, null));
        rule.uid = "rule:id";
        rule.uid = "rule:type:@id";
        rule.uid = "rule:type:id";
        rule.uid = "rule:type:$subType:id";
        rule.uid = "rule:type:subType:id";
        rule.label = null;
        rule.label = "\t";
        rule.config.clear();
        rule.triggers = new ArrayList<>();
        rule.triggers.add(new YamlModuleDTO());
        rule.triggers.clear();
        rule.conditions = new ArrayList<>();
        rule.conditions.add(new YamlConditionDTO());
        rule.conditions.clear();
        rule.actions = new ArrayList<>();
        rule.actions.add(new YamlActionDTO());
        YamlModuleDTO trigger = new YamlModuleDTO();
        trigger.id = "1";
        rule.triggers.add(trigger);
        trigger2.id = "1";
        rule.triggers.add(trigger2);
        trigger2.id = "3";
        YamlConditionDTO condition = new YamlConditionDTO();
        condition.id = "3";
        rule.conditions.add(condition);
        condition.id = "2";
        YamlActionDTO action = new YamlActionDTO();
        action.id = "script";
        rule.actions.add(action);
        action = new YamlActionDTO();
        action.id = "1";
        action.id = "2";
        action.id = "3";
        action.id = "4";
        YamlRuleDTO rule1 = new YamlRuleDTO();
        YamlRuleDTO rule2 = new YamlRuleDTO();
        assertNotNull(rule1);
        assertTrue(rule1.equals(rule1));
        assertFalse(rule1.equals(new Object()));
        assertEquals(rule1.hashCode(), rule2.hashCode());
        rule1.uid = "rule:id";
        rule2.uid = "rule:id2";
        assertFalse(rule1.equals(rule2));
        assertNotEquals(rule1.hashCode(), rule2.hashCode());
        rule2.uid = "rule:id";
        assertTrue(rule1.equals(rule2));
        rule1.label = "A label";
        rule2.label = "Another label";
        rule2.label = "A label";
        rule1.description = "A description";
        rule2.description = "Another description";
        rule2.description = "A description";
        rule1.visibility = Visibility.VISIBLE;
        rule2.visibility = Visibility.EXPERT;
        rule1.visibility = Visibility.EXPERT;
        rule1.template = "template:1";
        rule2.template = "template:2";
        rule2.template = "template:1";
        rule1.tags = new HashSet<>();
        rule1.tags.add("Tag1");
        rule2.tags = new HashSet<>();
        rule2.tags.add("Tag2");
        rule2.tags.add("Tag1");
        rule2.tags.remove("Tag2");
        rule1.actions = new ArrayList<>();
        YamlActionDTO action1 = new YamlActionDTO();
        rule1.actions.add(action1);
        rule2.actions = new ArrayList<>();
        rule2.actions.add(action2);
        action1.id = "action1";
        action2.id = "action2";
        action2.id = "action1";
        rule1.conditions = new ArrayList<>();
        YamlConditionDTO condition1 = new YamlConditionDTO();
        rule1.conditions.add(condition1);
        rule2.conditions = new ArrayList<>();
        rule2.conditions.add(condition2);
        condition1.id = "condition1";
        condition2.id = "condition2";
        condition2.id = "condition1";
        rule1.triggers = new ArrayList<>();
        YamlModuleDTO trigger1 = new YamlModuleDTO();
        rule1.triggers.add(trigger1);
        rule2.triggers = new ArrayList<>();
        rule2.triggers.add(trigger2);
        trigger1.id = "trigger1";
        trigger2.id = "trigger2";
        trigger2.id = "trigger1";
        rule1.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "val 2"));
        rule2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "val 2"));
        YamlConfigDescriptionParameterDTO configDescParam1 = new YamlConfigDescriptionParameterDTO();
        configDescParam1.context = "Item";
        configDescParam1.type = Type.TEXT;
        YamlConfigDescriptionParameterDTO configDescParam2 = new YamlConfigDescriptionParameterDTO();
        configDescParam2.defaultValue = "4";
        configDescParam2.type = Type.INTEGER;
        configDescParam2.step = BigDecimal.ONE;
        rule1.configDescriptions = Map.of("stateItem", configDescParam1, "iterations", configDescParam2);
        rule2.configDescriptions = Map.of("stateItem", configDescParam1, "iterations", configDescParam2);
        YamlConfigDescriptionParameterDTO configDescParam3 = new YamlConfigDescriptionParameterDTO();
        configDescParam3.defaultValue = "true";
        configDescParam3.type = Type.BOOLEAN;
        rule2.configDescriptions = Map.of("stateItem", configDescParam1, "iterations", configDescParam2, "assertive",
                configDescParam3);
        rule1.config = null;
        rule2.config = null;
        rule2.config = Map.of("param1", "other value", "param2", 50, "param3", true, "param4",
                List.of("val 1", "val 2"));
        rule2.config = Map.of("param1", "value", "param2", 25, "param3", true, "param4", List.of("val 1", "val 2"));
        rule2.config = Map.of("param1", "value", "param2", 50, "param3", false, "param4", List.of("val 1", "val 2"));
        rule2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1", "value 2"));
        rule2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", List.of("val 1"));
        rule2.config = Map.of("param1", "value", "param2", 50, "param3", true, "param4", 75);
        rule2.config = Map.of("param1", "value", "param2", 50, "param3", true);
