import { MJUserEntity } from '@memberjunction/core-entities';
@RegisterClass(BaseFormComponent, 'MJ: Users') // Tell MemberJunction about this class
    selector: 'gen-mjuser-form',
    templateUrl: './mjuser.form.component.html'
export class MJUserFormComponent extends BaseFormComponent {
    public record!: MJUserEntity;
            { sectionKey: 'userIdentity', sectionName: 'User Identity', isExpanded: true },
            { sectionKey: 'accountSettings', sectionName: 'Account Settings', isExpanded: true },
            { sectionKey: 'entityLinks', sectionName: 'Entity Links', isExpanded: false },
            { sectionKey: 'employeeDetails', sectionName: 'Employee Details', isExpanded: false },
            { sectionKey: 'actionExecutionLogs', sectionName: 'Action Execution Logs', isExpanded: false },
            { sectionKey: 'communicationRuns', sectionName: 'Communication Runs', isExpanded: false },
            { sectionKey: 'dataContexts', sectionName: 'Data Contexts', isExpanded: false },
            { sectionKey: 'queryCategories', sectionName: 'Query Categories', isExpanded: false },
            { sectionKey: 'recommendationRuns', sectionName: 'Recommendation Runs', isExpanded: false },
            { sectionKey: 'recordChangeReplayRuns', sectionName: 'Record Change Replay Runs', isExpanded: false },
            { sectionKey: 'templates', sectionName: 'Templates', isExpanded: false },
            { sectionKey: 'mJUserApplications', sectionName: 'MJ: User Applications', isExpanded: false },
            { sectionKey: 'roles', sectionName: 'Roles', isExpanded: false },
            { sectionKey: 'userViewRuns', sectionName: 'User View Runs', isExpanded: false },
            { sectionKey: 'workspaces', sectionName: 'Workspaces', isExpanded: false },
            { sectionKey: 'mJAPIKeys', sectionName: 'MJ: API Keys', isExpanded: false },
            { sectionKey: 'mJArtifactPermissions', sectionName: 'MJ: Artifact Permissions', isExpanded: false },
            { sectionKey: 'mJDashboardCategoryPermissions', sectionName: 'MJ: Dashboard Category Permissions', isExpanded: false },
            { sectionKey: 'mJDashboardUserPreferences', sectionName: 'MJ: Dashboard User Preferences', isExpanded: false },
            { sectionKey: 'mJListShares', sectionName: 'MJ: List Shares', isExpanded: false },
            { sectionKey: 'mJPublicLinks', sectionName: 'MJ: Public Links', isExpanded: false },
            { sectionKey: 'mJReportUserStates', sectionName: 'MJ: Report User States', isExpanded: false },
            { sectionKey: 'mJScheduledJobRuns', sectionName: 'MJ: Scheduled Job Runs', isExpanded: false },
            { sectionKey: 'mJScheduledJobs', sectionName: 'MJ: Scheduled Jobs', isExpanded: false },
            { sectionKey: 'mJUserNotificationPreferences', sectionName: 'MJ: User Notification Preferences', isExpanded: false },
            { sectionKey: 'mJUserSettings', sectionName: 'MJ: User Settings', isExpanded: false },
            { sectionKey: 'mJVersionLabelRestores', sectionName: 'MJ: Version Label Restores', isExpanded: false },
            { sectionKey: 'aIAgentRequests1', sectionName: 'AI Agent Requests', isExpanded: false },
            { sectionKey: 'mJAPIKeys1', sectionName: 'MJ: API Keys', isExpanded: false },
            { sectionKey: 'mJArtifactPermissions1', sectionName: 'MJ: Artifact Permissions', isExpanded: false },
            { sectionKey: 'mJDashboardCategoryPermissions1', sectionName: 'MJ: Dashboard Category Permissions', isExpanded: false },
            { sectionKey: 'mJDashboardPermissions1', sectionName: 'MJ: Dashboard Permissions', isExpanded: false },
            { sectionKey: 'mJScheduledJobs1', sectionName: 'MJ: Scheduled Jobs', isExpanded: false },
            { sectionKey: 'mJCollectionPermissions1', sectionName: 'MJ: Collection Permissions', isExpanded: false },
