 * @fileoverview OAuth Proxy Authorization Server Types
 * Type definitions for the OAuth proxy that enables dynamic client registration
 * and proxies OAuth flows to upstream providers (Azure AD, Auth0, etc.).
 * This allows MCP clients like Claude Code to use OAuth without requiring
 * manual client registration in Azure AD.
 * @module @memberjunction/ai-mcp-server/auth/OAuthProxyTypes
 * RFC 7591 Dynamic Client Registration Request
 * @see https://datatracker.ietf.org/doc/html/rfc7591#section-2
export interface ClientRegistrationRequest {
  /** Array of redirect URIs for the client */
  /** Human-readable name of the client */
  client_name?: string;
  /** URL of the client's home page */
  client_uri?: string;
  /** URL of the client's logo */
  logo_uri?: string;
  /** Array of OAuth grant types the client will use */
  /** Array of OAuth response types the client will use */
  token_endpoint_auth_method?: 'none' | 'client_secret_post' | 'client_secret_basic';
  /** Array of scopes the client will request */
  /** Software statement (JWT) */
  software_statement?: string;
  /** Software ID */
  software_id?: string;
  /** Software version */
  software_version?: string;
 * RFC 7591 Dynamic Client Registration Response
 * @see https://datatracker.ietf.org/doc/html/rfc7591#section-3.2.1
export interface ClientRegistrationResponse {
  /** Unique client identifier */
  /** Client secret (for confidential clients) */
  /** Timestamp when client_id was issued */
  /** Timestamp when client_secret expires (0 = never) */
  /** All fields from the registration request are echoed back */
 * Registered client information stored in the registry
export interface RegisteredClient {
  /** Client secret (for confidential clients, hashed) */
  clientSecretHash?: string;
  /** Plain client secret (only returned once at registration) */
  /** Timestamp when client was registered */
  registeredAt: number;
  secretExpiresAt: number;
  /** Human-readable name */
  /** Home page URL */
  clientUri?: string;
  /** Logo URL */
  logoUri?: string;
  /** Allowed grant types */
  /** Allowed response types */
  /** Token endpoint auth method */
  tokenEndpointAuthMethod: string;
 * OAuth Authorization Server Metadata per RFC 8414
 * @see https://datatracker.ietf.org/doc/html/rfc8414
export interface AuthorizationServerMetadata {
  /** Authorization server's issuer identifier (URL) */
  /** URL of the dynamic client registration endpoint */
  /** URL of the JWKS endpoint */
  /** Array of supported token endpoint auth methods */
  /** Array of supported PKCE code challenge methods */
  /** URL of the service documentation */
  service_documentation?: string;
 * State stored during authorization flow
export interface AuthorizationState {
  /** State parameter from the original request */
  originalState?: string;
  /** Client ID that initiated the flow */
  /** Redirect URI to send the user back to */
  /** PKCE code verifier (if provided) */
  codeVerifier?: string;
  /** PKCE code challenge (if provided) */
  codeChallenge?: string;
  /** PKCE code challenge method */
  codeChallengeMethod?: string;
  /** Timestamp when this state was created */
  createdAt: number;
  /** Nonce for OpenID Connect */
  nonce?: string;
  /** PKCE code verifier for upstream provider (generated by proxy) */
  upstreamCodeVerifier?: string;
 * Token request parameters
export interface TokenRequest {
  /** Grant type (authorization_code, refresh_token) */
  grant_type: string;
  /** Authorization code (for authorization_code grant) */
  code?: string;
  /** Redirect URI (must match the one used in authorization) */
  redirect_uri?: string;
  /** Client ID */
  client_id?: string;
  /** PKCE code verifier */
  code_verifier?: string;
  /** Refresh token (for refresh_token grant) */
  /** Requested scopes (for refresh_token grant) */
 * Token response
  /** Token type (usually "Bearer") */
  /** Refresh token */
  /** ID token (for OpenID Connect) */
  id_token?: string;
 * Token error response per RFC 6749
export interface TokenErrorResponse {
  /** URI with more information about the error */
 * Configuration for the OAuth proxy
export interface OAuthProxyConfig {
  /** Upstream OAuth provider configuration */
    /** Authorization endpoint of the upstream provider */
    authorizationEndpoint: string;
    /** Token endpoint of the upstream provider */
    tokenEndpoint: string;
    /** Client ID registered with the upstream provider */
    /** Client secret (if confidential client) */
    /** Scopes to request from upstream */
    scopes: string[];
    /** Provider name (for audit logging) */
  /** Whether to enable dynamic client registration */
  enableDynamicRegistration: boolean;
   * JWT signing configuration for proxy-issued tokens.
   * If not provided, upstream tokens are passed through instead.
  jwt?: {
    /** HS256 signing secret */
    /** Token expiration (e.g., '1h') */
    /** Issuer claim */
   * When enabled, users will see a UI to approve/deny scope requests.
   * When disabled, all available scopes are granted automatically.
  enableConsentScreen?: boolean;
 * Authorization code stored temporarily
export interface StoredAuthorizationCode {
  /** The authorization code */
  code: string;
  /** Client ID that owns this code */
  /** Redirect URI used */
  /** Scopes granted */
  /** PKCE code challenge */
  /** The actual tokens from upstream */
  upstreamTokens: TokenResponse;
  /** Timestamp when code was created */
  /** Timestamp when code expires */
   * Validated user information (populated if JWT signing is enabled).
   * Used to issue proxy-signed JWTs at the token endpoint.
  validatedUser?: {
    /** MemberJunction User ID */
    /** User email */
    /** Upstream provider name */
    /** Subject claim from upstream token */
