 * An API token represents long-term credentials generated by (or for) a user, giving the bearer access for a certain
 * scope on behalf of this user.
public class UserApiToken {
    private final String apiToken;
    private final Date createdTime;
     * Constructs an API token.
     * @param name the name of the token, for identification purposes
     * @param apiToken the serialization of the token
     * @param scope the scope this token is valid for
    public UserApiToken(String name, String apiToken, String scope) {
        this.apiToken = apiToken;
        this.createdTime = new Date();
     * Gets the name identifying the token
     * @return the API token
     * Get the serialization of the opaque API token which can be passed in requests as a "Bearer" token in the
     * Authorization HTTP header.
    public String getApiToken() {
        return apiToken;
     * Gets the time when this token was created.
     * @return the date of creation
    public Date getCreatedTime() {
        return createdTime;
     * Gets the scope this token is valid for.
     * @return the scope
        return "name=" + name + ", createdTime=" + createdTime + ", scope=" + scope;
