from .chat_completion_message_custom_tool_call import ChatCompletionMessageCustomToolCall
from .chat_completion_message_function_tool_call import Function as Function, ChatCompletionMessageFunctionToolCall
__all__ = ["Function", "ChatCompletionMessageToolCallUnion"]
ChatCompletionMessageToolCallUnion: TypeAlias = Annotated[
    Union[ChatCompletionMessageFunctionToolCall, ChatCompletionMessageCustomToolCall],
ChatCompletionMessageToolCall: TypeAlias = ChatCompletionMessageFunctionToolCall
