    "ChatCompletionChunk",
    "Choice",
    "ChoiceDelta",
    "ChoiceDeltaFunctionCall",
    "ChoiceDeltaToolCall",
    "ChoiceDeltaToolCallFunction",
    "ChoiceLogprobs",
class ChoiceDeltaFunctionCall(BaseModel):
class ChoiceDeltaToolCallFunction(BaseModel):
class ChoiceDeltaToolCall(BaseModel):
    function: Optional[ChoiceDeltaToolCallFunction] = None
    """The type of the tool. Currently, only `function` is supported."""
class ChoiceDelta(BaseModel):
    """A chat completion delta generated by streamed model responses."""
    content: Optional[str] = None
    """The contents of the chunk message."""
    function_call: Optional[ChoiceDeltaFunctionCall] = None
    """The refusal message generated by the model."""
    role: Optional[Literal["developer", "system", "user", "assistant", "tool"]] = None
    """The role of the author of this message."""
    tool_calls: Optional[List[ChoiceDeltaToolCall]] = None
    delta: ChoiceDelta
    finish_reason: Optional[Literal["stop", "length", "tool_calls", "content_filter", "function_call"]] = None
class ChatCompletionChunk(BaseModel):
    Represents a streamed chunk of a chat completion response returned
    by the model, based on the provided input.
    [Learn more](https://platform.openai.com/docs/guides/streaming-responses).
    """A unique identifier for the chat completion. Each chunk has the same ID."""
    Can contain more than one elements if `n` is greater than 1. Can also be empty
    for the last chunk if you set `stream_options: {"include_usage": true}`.
    """The Unix timestamp (in seconds) of when the chat completion was created.
    Each chunk has the same timestamp.
    """The model to generate the completion."""
    object: Literal["chat.completion.chunk"]
    """The object type, which is always `chat.completion.chunk`."""
    This fingerprint represents the backend configuration that the model runs with.
    An optional field that will only be present when you set
    `stream_options: {"include_usage": true}` in your request. When present, it
    contains a null value **except for the last chunk** which contains the token
    usage statistics for the entire request.
    **NOTE:** If the stream is interrupted or cancelled, you may not receive the
    final usage chunk which contains the total token usage for the request.
