__all__ = ["ChatCompletionAudio"]
class ChatCompletionAudio(BaseModel):
    If the audio output modality is requested, this object contains data
    about the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).
    """Unique identifier for this audio response."""
    data: str
    Base64 encoded audio bytes generated by the model, in the format specified in
    the request.
    The Unix timestamp (in seconds) for when this audio response will no longer be
    accessible on the server for use in multi-turn conversations.
    """Transcript of the audio generated by the model."""
