__all__ = ["ChatCompletionMessageCustomToolCall", "Custom"]
class Custom(BaseModel):
    """The custom tool that the model called."""
    """The input for the custom tool call generated by the model."""
    """The name of the custom tool to call."""
class ChatCompletionMessageCustomToolCall(BaseModel):
    """A call to a custom tool created by the model."""
    custom: Custom
    """The type of the tool. Always `custom`."""
