  MJArtifactVersionEntity
  AIAgentRunEntityExtended
} from "@memberjunction/ai-core-plus";
 * Peripheral data loaded for a conversation detail message
 * Contains related entities like agent runs and artifacts
export interface ConversationDetailPeripheralData {
  /** Agent run information if this message was generated by an agent */
  agentRun?: AIAgentRunEntityExtended;
  /** Artifact information if this message has an output artifact */
  artifact?: {
    /** The artifact entity */
    /** The specific version of the artifact */
 * Type-safe maps for peripheral data indexed by ConversationDetailID
export interface PeripheralDataMaps {
  /** Map of ConversationDetailID -> AIAgentRun */
  agentRunsByDetailId: Map<string, AIAgentRunEntityExtended>;
  /** Map of ConversationDetailID -> {artifact, version} */
  artifactsByDetailId: Map<string, {
 * Represents an active agent process
export interface AgentProcess {
  agentColor: string;
  status: 'pending' | 'in_progress' | 'complete' | 'failed';
 * Options for filtering tasks
export interface TaskFilters {
  projectId?: string;
  assignedToUserId?: string;
  assignedToAgentId?: string;
  environmentId?: string;
 * Options for creating public links
export interface PublicLinkOptions {
  maxViews?: number;
 * Tab types for the main navigation
export type NavigationTab = 'conversations' | 'collections' | 'tasks';
 * Layout modes for the workspace
export type WorkspaceLayout = 'full' | 'compact' | 'embedded';
 * View modes for collections
 * Sort options for artifacts
export type ArtifactSortBy = 'name' | 'date' | 'type' | 'modified';
 * Grouping options for conversations
export type ConversationGroupBy = 'project' | 'date' | 'none';
 * Type of entity being mentioned
export type MentionType = 'agent' | 'user';
 * Represents a mention in a message (@Agent or @User)
export interface Mention {
  type: MentionType;
  configurationId?: string; // Optional AI configuration preset ID for agents
 * Result of parsing mentions from a message
export interface MentionParseResult {
  mentions: Mention[];
  agentMention: Mention | null; // Single agent mention (first one found)
  userMentions: Mention[]; // All user mentions
 * Suggested response option for quick user replies
 * These are displayed as interactive buttons below AI messages to streamline conversation flow
export interface SuggestedResponse {
  /** Display text for the button or input placeholder */
  /** Whether to show an input field (uses text as placeholder) instead of a button */
  allowInput: boolean;
  /** Optional Font Awesome icon class (e.g., "fa fa-leaf", "fa fa-pencil") */
  /** Optional data payload to include when response is selected */
 * Parse result for suggested responses from a conversation detail
export interface ParsedSuggestedResponses {
  /** Array of suggested response objects */
  responses: SuggestedResponse[];
  /** Whether any response allows input */
  hasInputOption: boolean;
  /** The specific response that allows input (if any) */
  inputResponse: SuggestedResponse | null;
  /** All responses that are regular buttons (no input) */
  regularResponses: SuggestedResponse[];
