    /// Types of trigger for the feedback provider.
    public enum FeedbackTrigger
        /// The last command line executed successfully.
        Success = 0x0001,
        /// The last command line failed due to a command-not-found error.
        /// This is a special case of <see cref="Error"/>.
        CommandNotFound = 0x0002,
        /// The last command line failed with an error record.
        /// This includes the case of command-not-found error.
        Error = CommandNotFound | 0x0004,
        /// All possible triggers.
        All = Success | Error
    /// Layout for displaying the recommended actions.
    public enum FeedbackDisplayLayout
        /// Display one recommended action per row.
        Portrait,
        /// Display all recommended actions in the same row.
        Landscape,
    /// Context information about the last command line.
    public sealed class FeedbackContext
        /// Gets the feedback trigger.
        public FeedbackTrigger Trigger { get; }
        /// Gets the last command line that was just executed.
        public string CommandLine { get; }
        /// Gets the abstract syntax tree (AST) generated from parsing the last command line.
        public Ast CommandLineAst { get; }
        /// Gets the tokens generated from parsing the last command line.
        public IReadOnlyList<Token> CommandLineTokens { get; }
        /// Gets the current location of the default session.
        public PathInfo CurrentLocation { get; }
        /// Gets the last error record generated from executing the last command line.
        public ErrorRecord? LastError { get; }
        /// Initializes a new instance of the <see cref="FeedbackContext"/> class.
        /// <param name="trigger">The trigger of this feedback call.</param>
        /// <param name="commandLine">The command line that was just executed.</param>
        /// <param name="cwd">The current location of the default session.</param>
        /// <param name="lastError">The error that was triggerd by the last command line.</param>
        public FeedbackContext(FeedbackTrigger trigger, string commandLine, PathInfo cwd, ErrorRecord? lastError)
            ArgumentException.ThrowIfNullOrEmpty(commandLine);
            ArgumentNullException.ThrowIfNull(cwd);
            Trigger = trigger;
            CommandLine = commandLine;
            CommandLineAst = Parser.ParseInput(commandLine, out Token[] tokens, out _);
            CommandLineTokens = tokens;
            LastError = lastError;
            CurrentLocation = cwd;
        /// <param name="commandLineAst">The abstract syntax tree (AST) from parsing the last command line.</param>
        /// <param name="commandLineTokens">The tokens from parsing the last command line.</param>
        public FeedbackContext(FeedbackTrigger trigger, Ast commandLineAst, Token[] commandLineTokens, PathInfo cwd, ErrorRecord? lastError)
            ArgumentNullException.ThrowIfNull(commandLineAst);
            ArgumentNullException.ThrowIfNull(commandLineTokens);
            CommandLine = commandLineAst.Extent.Text;
            CommandLineAst = commandLineAst;
            CommandLineTokens = commandLineTokens;
    /// The class represents a feedback item generated by the feedback provider.
    public sealed class FeedbackItem
        /// Gets the description message about this feedback.
        public string Header { get; }
        /// Gets the footer message about this feedback.
        public string? Footer { get; }
        /// Gets the recommended actions -- command lines or even code snippets to run.
        public List<string>? RecommendedActions { get; }
        /// Gets the layout to use for displaying the recommended actions.
        public FeedbackDisplayLayout Layout { get; }
        /// Gets or sets the next feedback item, if there is one.
        public FeedbackItem? Next { get; set; }
        /// Initializes a new instance of the <see cref="FeedbackItem"/> class.
        /// <param name="header">The description message (must be not null or empty).</param>
        /// <param name="actions">The recommended actions to take (optional).</param>
        public FeedbackItem(string header, List<string>? actions)
            : this(header, actions, footer: null, FeedbackDisplayLayout.Portrait)
        /// <param name="layout">The layout for displaying the actions.</param>
        public FeedbackItem(string header, List<string>? actions, FeedbackDisplayLayout layout)
            : this(header, actions, footer: null, layout)
        /// <param name="footer">The footer message (optional).</param>
        public FeedbackItem(string header, List<string>? actions, string? footer, FeedbackDisplayLayout layout)
            ArgumentException.ThrowIfNullOrEmpty(header);
            RecommendedActions = actions;
            Footer = footer;
            Layout = layout;
    /// Interface for implementing a feedback provider on command failures.
    public interface IFeedbackProvider : ISubsystem
        /// Default implementation. No function is required for a feedback provider.
        /// Gets the types of trigger for this feedback provider.
        /// The default implementation triggers a feedback provider by <see cref="FeedbackTrigger.CommandNotFound"/> only.
        FeedbackTrigger Trigger => FeedbackTrigger.CommandNotFound;
        /// Gets feedback based on the given commandline and error record.
        /// <param name="context">The context for the feedback call.</param>
        /// <param name="token">The cancellation token to cancel the operation.</param>
        /// <returns>The feedback item.</returns>
        FeedbackItem? GetFeedback(FeedbackContext context, CancellationToken token);
    internal sealed class GeneralCommandErrorFeedback : IFeedbackProvider
        private readonly Guid _guid;
        internal GeneralCommandErrorFeedback()
            _guid = new Guid("A3C6B07E-4A89-40C9-8BE6-2A9AAD2786A4");
        public Guid Id => _guid;
        public string Name => "General Feedback";
        public string Description => "The built-in general feedback source for command errors.";
        public FeedbackItem? GetFeedback(FeedbackContext context, CancellationToken token)
            var rsToUse = Runspace.DefaultRunspace;
            if (rsToUse is null)
            // This feedback provider is only triggered by 'CommandNotFound' error, so the
            // 'LastError' property is guaranteed to be not null.
            ErrorRecord lastError = context.LastError!;
            SessionState sessionState = rsToUse.ExecutionContext.SessionState;
            var target = (string)lastError.TargetObject;
            CommandInvocationIntrinsics invocation = sessionState.InvokeCommand;
            // See if target is actually an executable file in current directory.
            var localTarget = Path.Combine(".", target);
            var command = invocation.GetCommand(
                localTarget,
                CommandTypes.Application | CommandTypes.ExternalScript);
            if (command is not null)
                return new FeedbackItem(
                    StringUtil.Format(SuggestionStrings.Suggestion_CommandExistsInCurrentDirectory, target),
                    new List<string> { localTarget });
            // Check fuzzy matching command names.
            var pwsh = PowerShell.Create(RunspaceMode.CurrentRunspace);
            var results = pwsh.AddCommand("Get-Command")
                    .AddParameter("UseFuzzyMatching")
                    .AddParameter("FuzzyMinimumDistance", 1)
                    .AddParameter("Name", target)
                .AddCommand("Select-Object")
                    .AddParameter("First", 5)
                    .AddParameter("Unique")
                    .AddParameter("ExpandProperty", "Name")
                .Invoke<string>();
				ApplicationInsightsTelemetry.SendUseTelemetry("FuzzyMatching", "CommandNotFound");
					SuggestionStrings.Suggestion_CommandNotFound,
					new List<string>(results),
					FeedbackDisplayLayout.Landscape);
