__all__ = ["ImageGenerateParamsBase", "ImageGenerateParamsNonStreaming", "ImageGenerateParamsStreaming"]
class ImageGenerateParamsBase(TypedDict, total=False):
    The maximum length is 32000 characters for the GPT image models, 1000 characters
    for `dall-e-2` and 4000 characters for `dall-e-3`.
    One of `dall-e-2`, `dall-e-3`, or a GPT image model (`gpt-image-1`,
    `gpt-image-1-mini`, `gpt-image-1.5`). Defaults to `dall-e-2` unless a parameter
    specific to the GPT image models is used.
    moderation: Optional[Literal["low", "auto"]]
    Control the content-moderation level for images generated by the GPT image
    """The number of images to generate.
    Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.
    `jpeg`, or `webp`.
    quality: Optional[Literal["standard", "hd", "low", "medium", "high", "auto"]]
    """The quality of the image that will be generated.
    """The format in which generated images with `dall-e-2` and `dall-e-3` are
    image has been generated. This parameter isn't supported for the GPT image
    models, which always return base64-encoded images.
    `auto` (default value) for the GPT image models, one of `256x256`, `512x512`, or
    `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`, or `1024x1792`
    for `dall-e-3`.
    style: Optional[Literal["vivid", "natural"]]
    """The style of the generated images.
    This parameter is only supported for `dall-e-3`. Must be one of `vivid` or
    `natural`. Vivid causes the model to lean towards generating hyper-real and
    dramatic images. Natural causes the model to produce more natural, less
    hyper-real looking images.
class ImageGenerateParamsNonStreaming(ImageGenerateParamsBase, total=False):
    """Generate the image in streaming mode.
class ImageGenerateParamsStreaming(ImageGenerateParamsBase):
ImageGenerateParams = Union[ImageGenerateParamsNonStreaming, ImageGenerateParamsStreaming]
