//  <auto-generated>
//      This code was generated by a tool. DO NOT EDIT
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
    /// This control presents a dropdown listbox with associated organizing actions that can be performed on it.
    /// If a custom template is provided for this control, then the template MUST provide the following template parts:
    ///     PART_Picker - A required template part which must be of type PickerBase.  This control provides basic functionality for Picker-like controls.
    [TemplatePart(Name="PART_Picker", Type=typeof(PickerBase))]
    partial class ListOrganizer
        // Fields
        private PickerBase picker;
        // ItemDeleted RoutedEvent
        /// Identifies the ItemDeleted RoutedEvent.
        public static readonly RoutedEvent ItemDeletedEvent = EventManager.RegisterRoutedEvent("ItemDeleted",RoutingStrategy.Bubble,typeof(EventHandler<DataRoutedEventArgs<object>>),typeof(ListOrganizer));
        /// Occurs when an item is deleted from the list.
        public event EventHandler<DataRoutedEventArgs<object>> ItemDeleted
            add
                AddHandler(ItemDeletedEvent,value);
            remove
                RemoveHandler(ItemDeletedEvent,value);
        // ItemSelected RoutedEvent
        /// Identifies the ItemSelected RoutedEvent.
        public static readonly RoutedEvent ItemSelectedEvent = EventManager.RegisterRoutedEvent("ItemSelected",RoutingStrategy.Bubble,typeof(EventHandler<DataRoutedEventArgs<object>>),typeof(ListOrganizer));
        /// Occurs when an item is selected in the list.
        public event EventHandler<DataRoutedEventArgs<object>> ItemSelected
                AddHandler(ItemSelectedEvent,value);
                RemoveHandler(ItemSelectedEvent,value);
        // DeleteItem routed command
        /// Informs the ListOrganizer that it should delete the item passed.
        public static readonly RoutedCommand DeleteItemCommand = new RoutedCommand("DeleteItem",typeof(ListOrganizer));
        static private void DeleteItemCommand_CommandExecuted(object sender, ExecutedRoutedEventArgs e)
            ListOrganizer obj = (ListOrganizer) sender;
            obj.OnDeleteItemExecuted( e );
        /// Called when DeleteItem executes.
        protected virtual void OnDeleteItemExecuted(ExecutedRoutedEventArgs e)
            OnDeleteItemExecutedImplementation(e);
        partial void OnDeleteItemExecutedImplementation(ExecutedRoutedEventArgs e);
        // SelectItem routed command
        /// Informs the ListOrganizer that it should select the item passed.
        public static readonly RoutedCommand SelectItemCommand = new RoutedCommand("SelectItem",typeof(ListOrganizer));
        static private void SelectItemCommand_CommandExecuted(object sender, ExecutedRoutedEventArgs e)
            obj.OnSelectItemExecuted( e );
        /// Called when SelectItem executes.
        protected virtual void OnSelectItemExecuted(ExecutedRoutedEventArgs e)
            OnSelectItemExecutedImplementation(e);
        partial void OnSelectItemExecutedImplementation(ExecutedRoutedEventArgs e);
        // DropDownButtonTemplate dependency property
        /// Identifies the DropDownButtonTemplate dependency property.
        public static readonly DependencyProperty DropDownButtonTemplateProperty = DependencyProperty.Register( "DropDownButtonTemplate", typeof(ControlTemplate), typeof(ListOrganizer), new PropertyMetadata( null, DropDownButtonTemplateProperty_PropertyChanged) );
        /// Gets or sets a value that controls the visual tree of the DropDown button.
        [Description("Gets or sets a value that controls the visual tree of the DropDown button.")]
        public ControlTemplate DropDownButtonTemplate
                return (ControlTemplate) GetValue(DropDownButtonTemplateProperty);
                SetValue(DropDownButtonTemplateProperty,value);
        static private void DropDownButtonTemplateProperty_PropertyChanged(DependencyObject o, DependencyPropertyChangedEventArgs e)
            ListOrganizer obj = (ListOrganizer) o;
            obj.OnDropDownButtonTemplateChanged( new PropertyChangedEventArgs<ControlTemplate>((ControlTemplate)e.OldValue, (ControlTemplate)e.NewValue) );
        /// Occurs when DropDownButtonTemplate property changes.
        public event EventHandler<PropertyChangedEventArgs<ControlTemplate>> DropDownButtonTemplateChanged;
        /// Called when DropDownButtonTemplate property changes.
        protected virtual void OnDropDownButtonTemplateChanged(PropertyChangedEventArgs<ControlTemplate> e)
            OnDropDownButtonTemplateChangedImplementation(e);
            RaisePropertyChangedEvent(DropDownButtonTemplateChanged, e);
        partial void OnDropDownButtonTemplateChangedImplementation(PropertyChangedEventArgs<ControlTemplate> e);
        // DropDownStyle dependency property
        /// Identifies the DropDownStyle dependency property.
        public static readonly DependencyProperty DropDownStyleProperty = DependencyProperty.Register( "DropDownStyle", typeof(Style), typeof(ListOrganizer), new PropertyMetadata( null, DropDownStyleProperty_PropertyChanged) );
        /// Gets or sets the style of the drop-down.
        [Description("Gets or sets the style of the drop-down.")]
        public Style DropDownStyle
                return (Style) GetValue(DropDownStyleProperty);
                SetValue(DropDownStyleProperty,value);
        static private void DropDownStyleProperty_PropertyChanged(DependencyObject o, DependencyPropertyChangedEventArgs e)
            obj.OnDropDownStyleChanged( new PropertyChangedEventArgs<Style>((Style)e.OldValue, (Style)e.NewValue) );
        /// Occurs when DropDownStyle property changes.
        public event EventHandler<PropertyChangedEventArgs<Style>> DropDownStyleChanged;
        /// Called when DropDownStyle property changes.
        protected virtual void OnDropDownStyleChanged(PropertyChangedEventArgs<Style> e)
            OnDropDownStyleChangedImplementation(e);
            RaisePropertyChangedEvent(DropDownStyleChanged, e);
        partial void OnDropDownStyleChangedImplementation(PropertyChangedEventArgs<Style> e);
        // HighlightedItem dependency property
        /// Identifies the HighlightedItem dependency property.
        public static readonly DependencyProperty HighlightedItemProperty = DependencyProperty.Register( "HighlightedItem", typeof(object), typeof(ListOrganizer), new PropertyMetadata( null, HighlightedItemProperty_PropertyChanged) );
        /// Gets or sets a value that controls the highlighted item in the list.
        [Description("Gets or sets a value that controls the highlighted item in the list.")]
        public object HighlightedItem
                return (object) GetValue(HighlightedItemProperty);
                SetValue(HighlightedItemProperty,value);
        static private void HighlightedItemProperty_PropertyChanged(DependencyObject o, DependencyPropertyChangedEventArgs e)
            obj.OnHighlightedItemChanged( new PropertyChangedEventArgs<object>((object)e.OldValue, (object)e.NewValue) );
        /// Occurs when HighlightedItem property changes.
        public event EventHandler<PropertyChangedEventArgs<object>> HighlightedItemChanged;
        /// Called when HighlightedItem property changes.
        protected virtual void OnHighlightedItemChanged(PropertyChangedEventArgs<object> e)
            OnHighlightedItemChangedImplementation(e);
            RaisePropertyChangedEvent(HighlightedItemChanged, e);
        partial void OnHighlightedItemChangedImplementation(PropertyChangedEventArgs<object> e);
        // ItemsSource dependency property
        /// Identifies the ItemsSource dependency property.
        public static readonly DependencyProperty ItemsSourceProperty = DependencyProperty.Register( "ItemsSource", typeof(IEnumerable), typeof(ListOrganizer), new PropertyMetadata( null, ItemsSourceProperty_PropertyChanged) );
        /// Gets or sets a value that controls the items in the list.
        [Description("Gets or sets a value that controls the items in the list.")]
        public IEnumerable ItemsSource
                return (IEnumerable) GetValue(ItemsSourceProperty);
                SetValue(ItemsSourceProperty,value);
        static private void ItemsSourceProperty_PropertyChanged(DependencyObject o, DependencyPropertyChangedEventArgs e)
            obj.OnItemsSourceChanged( new PropertyChangedEventArgs<IEnumerable>((IEnumerable)e.OldValue, (IEnumerable)e.NewValue) );
        /// Occurs when ItemsSource property changes.
        public event EventHandler<PropertyChangedEventArgs<IEnumerable>> ItemsSourceChanged;
        /// Called when ItemsSource property changes.
        protected virtual void OnItemsSourceChanged(PropertyChangedEventArgs<IEnumerable> e)
            OnItemsSourceChangedImplementation(e);
            RaisePropertyChangedEvent(ItemsSourceChanged, e);
        partial void OnItemsSourceChangedImplementation(PropertyChangedEventArgs<IEnumerable> e);
        // NoItemsText dependency property
        /// Identifies the NoItemsText dependency property.
        public static readonly DependencyProperty NoItemsTextProperty = DependencyProperty.Register( "NoItemsText", typeof(string), typeof(ListOrganizer), new PropertyMetadata( string.Empty, NoItemsTextProperty_PropertyChanged) );
        /// Gets or sets a value that appears to inform the user that there are no items in the list.
        [Description("Gets or sets a value that appears to inform the user that there are no items in the list.")]
        [Localizability(LocalizationCategory.Text, Modifiability=Modifiability.Modifiable, Readability=Readability.Readable)]
        public string NoItemsText
                return (string) GetValue(NoItemsTextProperty);
                SetValue(NoItemsTextProperty,value);
        static private void NoItemsTextProperty_PropertyChanged(DependencyObject o, DependencyPropertyChangedEventArgs e)
            obj.OnNoItemsTextChanged( new PropertyChangedEventArgs<string>((string)e.OldValue, (string)e.NewValue) );
        /// Occurs when NoItemsText property changes.
        public event EventHandler<PropertyChangedEventArgs<string>> NoItemsTextChanged;
        /// Called when NoItemsText property changes.
        protected virtual void OnNoItemsTextChanged(PropertyChangedEventArgs<string> e)
            OnNoItemsTextChangedImplementation(e);
            RaisePropertyChangedEvent(NoItemsTextChanged, e);
        partial void OnNoItemsTextChangedImplementation(PropertyChangedEventArgs<string> e);
        // TextContentPropertyName dependency property
        /// Identifies the TextContentPropertyName dependency property.
        public static readonly DependencyProperty TextContentPropertyNameProperty = DependencyProperty.Register( "TextContentPropertyName", typeof(string), typeof(ListOrganizer), new PropertyMetadata( string.Empty, TextContentPropertyNameProperty_PropertyChanged) );
        /// Gets or sets a value which dictates what binding is used to provide content for the items in the list.
        [Description("Gets or sets a value which dictates what binding is used to provide content for the items in the list.")]
        public string TextContentPropertyName
                return (string) GetValue(TextContentPropertyNameProperty);
                SetValue(TextContentPropertyNameProperty,value);
        static private void TextContentPropertyNameProperty_PropertyChanged(DependencyObject o, DependencyPropertyChangedEventArgs e)
            obj.OnTextContentPropertyNameChanged( new PropertyChangedEventArgs<string>((string)e.OldValue, (string)e.NewValue) );
        /// Occurs when TextContentPropertyName property changes.
        public event EventHandler<PropertyChangedEventArgs<string>> TextContentPropertyNameChanged;
        /// Called when TextContentPropertyName property changes.
        protected virtual void OnTextContentPropertyNameChanged(PropertyChangedEventArgs<string> e)
            OnTextContentPropertyNameChangedImplementation(e);
            RaisePropertyChangedEvent(TextContentPropertyNameChanged, e);
        partial void OnTextContentPropertyNameChangedImplementation(PropertyChangedEventArgs<string> e);
        // OnApplyTemplate
        /// Called when ApplyTemplate is called.
        public override void OnApplyTemplate()
            PreOnApplyTemplate();
            base.OnApplyTemplate();
            this.picker = WpfHelp.GetTemplateChild<PickerBase>(this,"PART_Picker");
            PostOnApplyTemplate();
        partial void PreOnApplyTemplate();
        partial void PostOnApplyTemplate();
        static ListOrganizer()
            DefaultStyleKeyProperty.OverrideMetadata(typeof(ListOrganizer), new FrameworkPropertyMetadata(typeof(ListOrganizer)));
            CommandManager.RegisterClassCommandBinding( typeof(ListOrganizer), new CommandBinding( ListOrganizer.DeleteItemCommand, DeleteItemCommand_CommandExecuted ));
            CommandManager.RegisterClassCommandBinding( typeof(ListOrganizer), new CommandBinding( ListOrganizer.SelectItemCommand, SelectItemCommand_CommandExecuted ));
