    /// This is a wrapper for exception class
    /// <see cref="System.ArgumentException"/>
    /// which provides additional information via
    /// <see cref="System.Management.Automation.IContainsErrorRecord"/>.
    /// Instances of this exception class are usually generated by the
    /// PowerShell Engine.  It is unusual for code outside the PowerShell Engine
    /// to create an instance of this class.
    public class PSArgumentException
            : ArgumentException, IContainsErrorRecord
        /// Initializes a new instance of the PSArgumentException class.
        public PSArgumentException()
        /// Per MSDN, the parameter is message.
        /// I confirm this experimentally as well.
        public PSArgumentException(string message)
        /// Note the unusual order of the construction parameters.
        /// ArgumentException has this ctor form and we imitate it here.
        public PSArgumentException(string message, string paramName)
                : base(message, paramName)
        /// Initializes a new instance of the PSArgumentException class
        /// <see cref="System.Runtime.Serialization.ISerializable"/>
        protected PSArgumentException(SerializationInfo info,
        public PSArgumentException(string message,
        /// Note that ErrorRecord.Exception is
        private readonly string _errorId = "Argument";
        /// See <see cref="System.Exception.Message"/>
            get { return string.IsNullOrEmpty(_message) ? base.Message : _message; }
