    /// Base class for object-based event registration.
    public abstract class ObjectEventRegistrationBase : PSCmdlet
        [Parameter(Position = 100)]
        private string _sourceIdentifier = Guid.NewGuid().ToString();
        /// Parameter for any action to be invoked when the event arrives.
        [Parameter(Position = 101)]
        public ScriptBlock Action
                return _action;
                _action = value;
        private ScriptBlock _action = null;
        /// Parameter for additional data to be associated with this event subscription.
        /// Parameter for the flag that determines if this subscription is used to support
        /// other subscriptions.
        public SwitchParameter SupportEvent
                return _supportEvent;
                _supportEvent = value;
        private SwitchParameter _supportEvent = new SwitchParameter();
        /// Parameter for the flag that determines whether this
        /// subscription will forward its events to the PowerShell client during remote executions.
        public SwitchParameter Forward
                return _forward;
                _forward = value;
        private SwitchParameter _forward = new SwitchParameter();
        /// Parameter to indicate that the subscriber should be auto-unregistered after being triggered for specified times.
        /// If the value is equal or less than zero, there is no limit on the number of times the event can be triggered without being unregistered.
        public int MaxTriggerCount
                return _maxTriggerCount;
                _maxTriggerCount = value <= 0 ? 0 : value;
        private int _maxTriggerCount = 0;
        protected abstract object GetSourceObject();
        protected abstract string GetSourceObjectEventName();
        /// Gets the subscriber generated by this command.
        protected PSEventSubscriber NewSubscriber
            get { return _newSubscriber; }
        private PSEventSubscriber _newSubscriber;
        /// Check arguments.
            if (((bool)_forward) && (_action != null))
                        new ArgumentException(EventingResources.ActionAndForwardNotSupported),
                        "ACTION_AND_FORWARD_NOT_SUPPORTED",
        /// Subscribe to the event on the object.
            object inputObject = PSObject.Base(GetSourceObject());
            string eventName = GetSourceObjectEventName();
                    ((inputObject != null) || (eventName != null)) &&
                    (Events.GetEventSubscribers(_sourceIdentifier).GetEnumerator().MoveNext())
                    // Detect if the event identifier already exists
                                EventingResources.SubscriberExists, _sourceIdentifier)),
                        "SUBSCRIBER_EXISTS",
                    _newSubscriber =
                        Events.SubscribeEvent(
                            eventName,
                            _sourceIdentifier, _messageData, _action, (bool)_supportEvent, (bool)_forward, _maxTriggerCount);
                    if ((_action != null) && (!(bool)_supportEvent))
                        WriteObject(_newSubscriber.Action);
                    "INVALID_REGISTRATION",
