// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
using System;
using System.Management.Automation;
namespace Application.Test
    public class Program
        /// <summary>
        /// Managed entry point shim, which starts the actual program.
        /// </summary>
        public static int Main(string[] args)
            using (PowerShell ps = PowerShell.Create())
                Console.WriteLine("\nEvaluating 'Get-Command Write-Output' in PS Core Runspace\n");
                var results = ps.AddScript("Get-Command Write-Output").Invoke();
                Console.WriteLine(results[0].ToString());
                ps.Commands.Clear();
                Console.WriteLine("\nEvaluating '([S.M.A.ActionPreference], [S.M.A.AliasAttribute]).FullName' in PS Core Runspace\n");
                results = ps.AddScript("([System.Management.Automation.ActionPreference], [System.Management.Automation.AliasAttribute]).FullName").Invoke();
                foreach (dynamic result in results)
                    Console.WriteLine(result.ToString());
using System.Xml.Linq;
namespace ConsoleApplication
        public static void Main(string[] args)
            IEnumerable<string> dirs;
            string fileFilter;
            if (args.Length == 1)
                // We are assuming resgen is run with 'dotnet run pathToResxFile.resx'.
                fileFilter = Path.GetFileName(args[0]);
                string moduleDirectory = Path.GetDirectoryName(Path.GetDirectoryName(args[0]));
                dirs = new List<string>() { moduleDirectory };
                // We are assuming resgen is run with 'dotnet run'
                // so we can use relative path to get a parent directory
                // to process all *.resx files in all project subdirectories.
                fileFilter = "*.resx";
                dirs = Directory.EnumerateDirectories("..");
            foreach (string folder in dirs)
                string moduleName = Path.GetFileName(folder);
                string resourcePath = Path.Combine(folder, "resources");
                if (Directory.Exists(resourcePath))
                    string genFolder = Path.Combine(folder, "gen");
                    if (!Directory.Exists(genFolder))
                        Directory.CreateDirectory(genFolder);
                    foreach (string resxPath in Directory.EnumerateFiles(resourcePath, fileFilter))
                        string accessModifier = "internal";
                        string className = Path.GetFileNameWithoutExtension(resxPath);
                        if (className.StartsWith("public.", StringComparison.InvariantCultureIgnoreCase))
                            accessModifier = "public";
                            className = className.Substring(className.IndexOf('.') + 1);
                        string sourceCode = GetStronglyTypeCsFileForResx(resxPath, moduleName, className, accessModifier);
                        string outPath = Path.Combine(genFolder, className + ".cs");
                        Console.WriteLine("ResGen for " + outPath);
                        File.WriteAllText(outPath, sourceCode);
        private static string GetStronglyTypeCsFileForResx(string xmlPath, string moduleName, string className, string accessModifier)
            // Example
            // className = Full.Name.Of.The.ClassFoo
            // shortClassName = ClassFoo
            // namespaceName = Full.Name.Of.The
            string shortClassName = className;
            string namespaceName = null;
            int lastIndexOfDot = className.LastIndexOf('.');
            if (lastIndexOfDot != -1)
                namespaceName = className.Substring(0, lastIndexOfDot);
                shortClassName = className.Substring(lastIndexOfDot + 1);
            var entries = new StringBuilder();
            XElement root = XElement.Parse(File.ReadAllText(xmlPath));
            foreach (var data in root.Elements("data"))
                string value = data.Value.Replace("\n", "\n    ///");
                string name = data.Attribute("name").Value.Replace(' ', '_');
                entries.AppendFormat(ENTRY, name, value, accessModifier);
            string bodyCode = string.Format(BODY, shortClassName, moduleName, entries.ToString(), className, accessModifier, accessModifier.Equals("public", StringComparison.InvariantCultureIgnoreCase) ? "public." : string.Empty);
            if (namespaceName != null)
                bodyCode = string.Format(NAMESPACE, namespaceName, bodyCode);
            string resultCode = string.Format(BANNER, bodyCode).Replace("\r\n?|\n", "\r\n");
            return resultCode;
        private static readonly string BANNER = @"
//     This code was generated by a dotnet run from src\ResGen folder.
//     To add or remove a member, edit your .resx file then rerun src\ResGen.
{0}
        private static readonly string NAMESPACE = @"
namespace {0} {{
{1}
        private static readonly string BODY = @"
///   A strongly-typed resource class, for looking up localized strings, etc.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""System.Resources.Tools.StronglyTypedResourceBuilder"", ""4.0.0.0"")]
{4} class {0} {{
    private static global::System.Resources.ResourceManager resourceMan;
    private static global::System.Globalization.CultureInfo resourceCulture;
    /// <summary>constructor</summary>
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(""Microsoft.Performance"", ""CA1811:AvoidUncalledPrivateCode"")]
    {4} {0}() {{
    ///   Returns the cached ResourceManager instance used by this class.
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    {4} static global::System.Resources.ResourceManager ResourceManager {{
        get {{
            if (resourceMan is null) {{
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(""{1}.resources.{5}{3}"", typeof({0}).Assembly);
                resourceMan = temp;
            return resourceMan;
    ///   Overrides the current threads CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    {4} static global::System.Globalization.CultureInfo Culture {{
            return resourceCulture;
        set {{
            resourceCulture = value;
    {2}
    private static readonly string ENTRY = @"
    ///   Looks up a localized string similar to {1}
    {2} static string {0} {{
            return ResourceManager.GetString(""{0}"", resourceCulture);
    /// Defines an entry point for the .NET CLI "powershell" app.
    public sealed class ManagedPSEntry
        /// Exception to signify an early startup failure.
        private sealed class StartupException : Exception
            /// Construct a new startup exception instance.
            /// <param name="callName">The name of the native call that failed.</param>
            /// <param name="exitCode">The exit code the native call returned.</param>
            public StartupException(string callName, int exitCode)
                CallName = callName;
            /// The name of the native call that failed.
            public string CallName { get; }
            /// The exit code returned by the failed native call.
        // Environment variable used to short circuit second login check
        private const string LOGIN_ENV_VAR_NAME = "__PWSH_LOGIN_CHECKED";
        private const string LOGIN_ENV_VAR_VALUE = "1";
        // Linux p/Invoke constants
        private const int LINUX_PATH_MAX = 4096;
        // MacOS p/Invoke constants
        private const int MACOS_CTL_KERN = 1;
        private const int MACOS_KERN_ARGMAX = 8;
        private const int MACOS_KERN_PROCARGS2 = 49;
        private const int MACOS_PROC_PIDPATHINFO_MAXSIZE = 4096;
            AttemptExecPwshLogin(args);
            return UnmanagedPSEntry.Start(args, args.Length);
        /// Checks whether pwsh has been started as a login shell
        /// and if so, proceeds with the login process.
        /// This method will return early if pwsh was not started as a login shell
        /// and will throw if it detects a native call has failed.
        /// In the event of success, we use an exec() call, so this method never returns.
        /// <param name="args">The startup arguments to pwsh.</param>
        private static void AttemptExecPwshLogin(string[] args)
            // If the login environment variable is set, we have already done the login logic and have been exec'd
            if (Environment.GetEnvironmentVariable(LOGIN_ENV_VAR_NAME) != null)
                Environment.SetEnvironmentVariable(LOGIN_ENV_VAR_NAME, null);
            bool isLinux = Platform.IsLinux;
            // The first byte (ASCII char) of the name of this process, used to detect '-' for login
            byte procNameFirstByte;
            // The path to the executable this process was started from
            string? pwshPath;
            // On Linux, we can simply use the /proc filesystem
            if (isLinux)
                // Read the process name byte
                using (FileStream fs = File.OpenRead("/proc/self/cmdline"))
                    procNameFirstByte = (byte)fs.ReadByte();
                // Run login detection logic
                if (!IsLogin(procNameFirstByte, args))
                // Read the symlink to the startup executable
                IntPtr linkPathPtr = Marshal.AllocHGlobal(LINUX_PATH_MAX);
                IntPtr bufSize = ReadLink("/proc/self/exe", linkPathPtr, (UIntPtr)LINUX_PATH_MAX);
                pwshPath = Marshal.PtrToStringAnsi(linkPathPtr, (int)bufSize);
                Marshal.FreeHGlobal(linkPathPtr);
                ArgumentNullException.ThrowIfNull(pwshPath);
                // exec pwsh
                ThrowOnFailure("exec", ExecPwshLogin(args, pwshPath, isMacOS: false));
            // At this point, we are on macOS
            // Set up the mib array and the query for process maximum args size
            Span<int> mib = [MACOS_CTL_KERN, MACOS_KERN_ARGMAX];
            int size = IntPtr.Size / 2;
            int argmax = 0;
            // Get the process args size
                fixed (int *mibptr = mib)
                    ThrowOnFailure(nameof(argmax), SysCtl(mibptr, mib.Length, &argmax, &size, IntPtr.Zero, 0));
            // Get the PID so we can query this process' args
            int pid = GetPid();
            // The following logic is based on https://gist.github.com/nonowarn/770696
            // Now read the process args into the allocated space
            IntPtr procargs = Marshal.AllocHGlobal(argmax);
            IntPtr executablePathPtr = IntPtr.Zero;
                mib = new int[] { MACOS_CTL_KERN, MACOS_KERN_PROCARGS2, pid };
                        ThrowOnFailure(nameof(procargs), SysCtl(mibptr, mib.Length, procargs.ToPointer(), &argmax, IntPtr.Zero, 0));
                    // The memory block we're reading is a series of null-terminated strings
                    // that looks something like this:
                    // | argc      | <int>
                    // | exec_path | ... \0
                    // | argv[0]   | ... \0
                    // | argv[1]   | ... \0
                    // We care about argv[0], since that's the name the process was started with.
                    // If argv[0][0] == '-', we have been invoked as login.
                    // Doing this, the buffer we populated also recorded `exec_path`,
                    // which is the path to our executable `pwsh`.
                    // We can reuse this value later to prevent needing to call a .NET API
                    // to generate our exec invocation.
                    // We don't care about argc's value, since argv[0] must always exist.
                    // Skip over argc, but remember where exec_path is for later
                    executablePathPtr = IntPtr.Add(procargs, sizeof(int));
                    // Skip over exec_path
                    byte *argvPtr = (byte *)executablePathPtr;
                    while (*argvPtr != 0) { argvPtr++; }
                    while (*argvPtr == 0) { argvPtr++; }
                    // First char in argv[0]
                    procNameFirstByte = *argvPtr;
                // Get the pwshPath from exec_path
                pwshPath = Marshal.PtrToStringAnsi(executablePathPtr);
                ThrowOnFailure("exec", ExecPwshLogin(args, pwshPath, isMacOS: true));
                Marshal.FreeHGlobal(procargs);
        /// Checks args to see if -Login has been specified.
        /// <param name="procNameFirstByte">The first byte of the name of the currently running process.</param>
        /// <param name="args">Arguments passed to the program.</param>
        private static bool IsLogin(
            byte procNameFirstByte,
            string[] args)
            // Process name starting with '-' means this is a login shell
            if (procNameFirstByte == 0x2D)
            // Look at the first parameter to see if it is -Login
            // NOTE: -Login is only supported as the first parameter to PowerShell
            return args.Length > 0
                && args[0].Length > 1
                && args[0][0] == '-'
                && IsParam(args[0], "login", "LOGIN");
        /// Determines if a given parameter is the one we're looking for.
        /// Assumes any prefix determines that parameter (true for -l, -c and -f).
        /// <param name="arg">The argument to check.</param>
        /// <param name="paramToCheck">The lowercase name of the parameter to check.</param>
        /// <param name="paramToCheckUpper">The uppercase name of the parameter to check.</param>
        private static bool IsParam(
            string arg,
            string paramToCheck,
            string paramToCheckUpper)
            // Quick fail if the argument is longer than the parameter
            if (arg.Length > paramToCheck.Length + 1)
            // Check arg chars in order and allow prefixes
            for (int i = 1; i < arg.Length; i++)
                if (arg[i] != paramToCheck[i - 1]
                    && arg[i] != paramToCheckUpper[i - 1])
        /// Create the exec call to /bin/{z}sh -l -c 'exec pwsh "$@"' and run it.
        /// <param name="args">The argument vector passed to pwsh.</param>
        /// <param name="isMacOS">True if we are running on macOS.</param>
        /// <param name="pwshPath">Absolute path to the pwsh executable.</param>
        /// The exit code of exec if it fails.
        /// If exec succeeds, this process is overwritten so we never actually return.
        private static int ExecPwshLogin(string[] args, string pwshPath, bool isMacOS)
            // Create input for /bin/sh that execs pwsh
            int quotedPwshPathLength = GetQuotedPathLength(pwshPath);
            string pwshInvocation = string.Create(
                quotedPwshPathLength + 10, // exec '{pwshPath}' "$@"
                (pwshPath, quotedPwshPathLength),
                CreatePwshInvocation);
            // Set up the arguments for '/bin/sh'.
            // We need to add 5 slots for the '/bin/sh' invocation parts, plus 1 slot for the null terminator at the end
            var execArgs = new string?[args.Length + 6];
            // The command arguments
            // First argument is the command name.
            // Even when executing 'zsh', we want to set this to '/bin/sh'
            // because this tells 'zsh' to run in sh emulation mode (it examines $0)
            execArgs[0] = "/bin/sh";
            execArgs[1] = "-l"; // Login flag
            execArgs[2] = "-c"; // Command parameter
            execArgs[3] = pwshInvocation; // Command to execute
            // The /bin/sh option spec looks like:
            // sh -c command_string [command_name [argument...]]
            // We must provide a command_name before arguments,
            // but this is never used since "$@" takes argv[1] - argv[n]
            // and the `exec` builtin provides its own argv[0].
            // See https://pubs.opengroup.org/onlinepubs/9699919799.2016edition/
            // Since command_name is ignored and we can't use null (it's the terminator)
            // we use empty string
            execArgs[4] = string.Empty;
            // Add the arguments passed to pwsh on the end.
            args.CopyTo(execArgs, 5);
            // A null is required by exec.
            // We can't use Environment.SetEnvironmentVariable() here.
            // See https://github.com/dotnet/corefx/issues/40130#issuecomment-519420648.
            ThrowOnFailure("setenv", SetEnv(LOGIN_ENV_VAR_NAME, LOGIN_ENV_VAR_VALUE, overwrite: true));
            // On macOS, sh doesn't support login, so we run /bin/zsh in sh emulation mode.
            if (isMacOS)
                return Exec("/bin/zsh", execArgs);
            return Exec("/bin/sh", execArgs);
        /// Gets what the length of the given string will be if it's
        /// quote escaped for /bin/sh.
        /// <param name="str">The string to quote escape.</param>
        /// <returns>The length of the string when it's quote escaped.</returns>
        private static int GetQuotedPathLength(string str)
            int length = 2;
                length++;
        /// Implements a SpanAction&lt;T&gt; for string.Create()
        /// that builds the shell invocation for the login pwsh session.
        /// <param name="strBuf">The buffer of the string to be created.</param>
        /// <param name="invocationInfo">Information used to build the required string.</param>
        private static void CreatePwshInvocation(
            Span<char> strBuf,
            (string path, int quotedLength) invocationInfo)
            // "exec "
            const string prefix = "exec ";
            prefix.AsSpan().CopyTo(strBuf);
            // The quoted path to pwsh, like "'/opt/microsoft/powershell/7/pwsh'"
            int i = prefix.Length;
            Span<char> pathSpan = strBuf.Slice(i, invocationInfo.quotedLength);
            QuoteAndWriteToSpan(invocationInfo.path, pathSpan);
            i += invocationInfo.quotedLength;
            // ' "$@"' the argument vector splat to pass pwsh arguments through
            const string suffix = " \"$@\"";
            Span<char> bufSuffix = strBuf.Slice(i);
            suffix.AsSpan().CopyTo(bufSuffix);
        /// Quotes (and sh quote escapes) a string and writes it to the given span.
        /// <param name="arg">The string to quote.</param>
        /// <param name="span">The span to write to.</param>
        private static void QuoteAndWriteToSpan(string arg, Span<char> span)
            span[0] = '\'';
            int j = 1;
            for (; i < arg.Length; i++, j++)
                char c = arg[i];
                    // /bin/sh quote escaping uses backslashes
                    span[j] = '\\';
                span[j] = c;
            span[j] = '\'';
        /// If the given exit code is negative, throws a StartupException.
        /// <param name="call">The native call that was attempted.</param>
        /// <param name="code">The exit code it returned.</param>
        private static void ThrowOnFailure(string call, int code)
            if (code < 0)
                code = Marshal.GetLastWin32Error();
                Console.Error.WriteLine($"Call to '{call}' failed with errno {code}");
                throw new StartupException(call, code);
            EntryPoint = "execv",
        private static extern int Exec(string path, string?[] args);
        /// The `readlink` POSIX syscall we use to read the symlink from /proc/self/exe
        /// to get the executable path of pwsh on Linux.
        /// <param name="pathname">The path to the symlink to read.</param>
        /// <param name="buf">Pointer to a buffer to fill with the result.</param>
        /// <param name="size">The size of the buffer we have supplied.</param>
        /// <returns>The number of bytes placed in the buffer.</returns>
            EntryPoint = "readlink",
        private static extern IntPtr ReadLink(string pathname, IntPtr buf, UIntPtr size);
        /// The `getpid` POSIX syscall we use to quickly get the current process PID on macOS.
        /// <returns>The pid of the current process.</returns>
            EntryPoint = "getpid",
        private static extern int GetPid();
        /// The `setenv` POSIX syscall used to set an environment variable in the process.
        /// <param name="value">The value of the environment variable.</param>
        /// <param name="overwrite">If true, will overwrite an existing environment variable of the same name.</param>
        /// <returns>0 if successful, -1 on error. errno indicates the reason for failure.</returns>
            EntryPoint = "setenv",
        private static extern int SetEnv(string name, string value, bool overwrite);
        /// The `sysctl` BSD sycall used to get system information on macOS.
        /// <param name="mib">The Management Information Base name, used to query information.</param>
        /// <param name="mibLength">The length of the MIB name.</param>
        /// <param name="oldp">The object passed out of sysctl (may be null)</param>
        /// <param name="oldlenp">The size of the object passed out of sysctl.</param>
        /// <param name="newp">The object passed in to sysctl.</param>
        /// <param name="newlenp">The length of the object passed in to sysctl.</param>
            EntryPoint = "sysctl",
        private static extern unsafe int SysCtl(int *mib, int mibLength, void *oldp, int *oldlenp, IntPtr newp, int newlenp);
﻿// Copyright (c) Microsoft Corporation.
using SharpFuzz;
namespace FuzzTests
    public static class Program
            FuzzTargetMethod(args);
        public static void FuzzTargetMethod(string[] args)
                Console.WriteLine("args was null");
                args = Array.Empty<string>();
                Fuzzer.LibFuzzer.Run(Target.ExtractToken);
            catch (ArgumentNullException nex)
                Console.WriteLine($"ArgumentNullException in main: {nex.Message}");
                Console.WriteLine($"Stack Trace: {nex.StackTrace}");
                Environment.Exit(1);
                Console.WriteLine($"Exception in main: {ex.Message}");
                Console.WriteLine($"Exception type: {ex.GetType()}");
                Console.WriteLine($"Stack Trace: {ex.StackTrace}");
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Extensions;
    public sealed class Program
            var argsList = new List<string>(args);
            int? partitionCount;
            int? partitionIndex;
            List<string> exclusionFilterValue;
            List<string> categoryExclusionFilterValue;
            bool getDiffableDisasm;
            // Parse and remove any additional parameters that we need that aren't part of BDN (BenchmarkDotnet)
                CommandLineOptions.ParseAndRemoveIntParameter(argsList, "--partition-count", out partitionCount);
                CommandLineOptions.ParseAndRemoveIntParameter(argsList, "--partition-index", out partitionIndex);
                CommandLineOptions.ParseAndRemoveStringsParameter(argsList, "--exclusion-filter", out exclusionFilterValue);
                CommandLineOptions.ParseAndRemoveStringsParameter(argsList, "--category-exclusion-filter", out categoryExclusionFilterValue);
                CommandLineOptions.ParseAndRemoveBooleanParameter(argsList, "--disasm-diff", out getDiffableDisasm);
                CommandLineOptions.ValidatePartitionParameters(partitionCount, partitionIndex);
                Console.WriteLine("ArgumentException: {0}", e.Message);
            return BenchmarkSwitcher
                .FromAssembly(typeof(Program).Assembly)
                .Run(
                    argsList.ToArray(),
                    RecommendedConfig.Create(
                        artifactsPath: new DirectoryInfo(Path.Combine(Path.GetDirectoryName(typeof(Program).Assembly.Location), "BenchmarkDotNet.Artifacts")),
                        mandatoryCategories: ImmutableHashSet.Create(Categories.Components, Categories.Engine),
                        partitionCount: partitionCount,
                        partitionIndex: partitionIndex,
                        exclusionFilterValue: exclusionFilterValue,
                        categoryExclusionFilterValue: categoryExclusionFilterValue,
                        getDiffableDisasm: getDiffableDisasm))
                .ToExitCode();
using Perfolizer.Mathematics.Multimodality;
using Perfolizer.Mathematics.SignificanceTesting;
using Perfolizer.Mathematics.Thresholds;
using DataTransferContracts;
using MarkdownLog;
        private const string FullBdnJsonFileExtension = "full.json";
            // we print a lot of numbers here and we want to make it always in invariant way
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
            Parser.Default.ParseArguments<CommandLineOptions>(args).WithParsed(Compare);
        private static void Compare(CommandLineOptions args)
            if (!Threshold.TryParse(args.StatisticalTestThreshold, out var testThreshold))
                Console.WriteLine($"Invalid Threshold {args.StatisticalTestThreshold}. Examples: 5%, 10ms, 100ns, 1s.");
            if (!Threshold.TryParse(args.NoiseThreshold, out var noiseThreshold))
                Console.WriteLine($"Invalid Noise Threshold {args.NoiseThreshold}. Examples: 0.3ns 1ns.");
            var notSame = GetNotSameResults(args, testThreshold, noiseThreshold).ToArray();
            if (!notSame.Any())
                Console.WriteLine($"No differences found between the benchmark results with threshold {testThreshold}.");
            PrintSummary(notSame);
            PrintTable(notSame, EquivalenceTestConclusion.Slower, args);
            PrintTable(notSame, EquivalenceTestConclusion.Faster, args);
            ExportToCsv(notSame, args.CsvPath);
            ExportToXml(notSame, args.XmlPath);
        private static IEnumerable<(string id, Benchmark baseResult, Benchmark diffResult, EquivalenceTestConclusion conclusion)> GetNotSameResults(CommandLineOptions args, Threshold testThreshold, Threshold noiseThreshold)
            foreach ((string id, Benchmark baseResult, Benchmark diffResult) in ReadResults(args)
                .Where(result => result.baseResult.Statistics != null && result.diffResult.Statistics != null)) // failures
                var baseValues = baseResult.GetOriginalValues();
                var diffValues = diffResult.GetOriginalValues();
                var userTresholdResult = StatisticalTestHelper.CalculateTost(MannWhitneyTest.Instance, baseValues, diffValues, testThreshold);
                if (userTresholdResult.Conclusion == EquivalenceTestConclusion.Same)
                var noiseResult = StatisticalTestHelper.CalculateTost(MannWhitneyTest.Instance, baseValues, diffValues, noiseThreshold);
                if (noiseResult.Conclusion == EquivalenceTestConclusion.Same)
                yield return (id, baseResult, diffResult, userTresholdResult.Conclusion);
        private static void PrintSummary((string id, Benchmark baseResult, Benchmark diffResult, EquivalenceTestConclusion conclusion)[] notSame)
            var better = notSame.Where(result => result.conclusion == EquivalenceTestConclusion.Faster);
            var worse = notSame.Where(result => result.conclusion == EquivalenceTestConclusion.Slower);
            var betterCount = better.Count();
            var worseCount = worse.Count();
            // If the baseline doesn't have the same set of tests, you wind up with Infinity in the list of diffs.
            // Exclude them for purposes of geomean.
            worse = worse.Where(x => GetRatio(x) != double.PositiveInfinity);
            better = better.Where(x => GetRatio(x) != double.PositiveInfinity);
            Console.WriteLine("summary:");
            if (betterCount > 0)
                var betterGeoMean = Math.Pow(10, better.Skip(1).Aggregate(Math.Log10(GetRatio(better.First())), (x, y) => x + Math.Log10(GetRatio(y))) / better.Count());
                Console.WriteLine($"better: {betterCount}, geomean: {betterGeoMean:F3}");
            if (worseCount > 0)
                var worseGeoMean = Math.Pow(10, worse.Skip(1).Aggregate(Math.Log10(GetRatio(worse.First())), (x, y) => x + Math.Log10(GetRatio(y))) / worse.Count());
                Console.WriteLine($"worse: {worseCount}, geomean: {worseGeoMean:F3}");
            Console.WriteLine($"total diff: {notSame.Length}");
            Console.WriteLine();
        private static void PrintTable((string id, Benchmark baseResult, Benchmark diffResult, EquivalenceTestConclusion conclusion)[] notSame, EquivalenceTestConclusion conclusion, CommandLineOptions args)
            var data = notSame
                .Where(result => result.conclusion == conclusion)
                .OrderByDescending(result => GetRatio(conclusion, result.baseResult, result.diffResult))
                .Take(args.TopCount ?? int.MaxValue)
                .Select(result => new
                    Id = result.id.Length > 80 ? result.id.Substring(0, 80) : result.id,
                    DisplayValue = GetRatio(conclusion, result.baseResult, result.diffResult),
                    BaseMedian = result.baseResult.Statistics.Median,
                    DiffMedian = result.diffResult.Statistics.Median,
                    Modality = GetModalInfo(result.baseResult) ?? GetModalInfo(result.diffResult)
            if (!data.Any())
                Console.WriteLine($"No {conclusion} results for the provided threshold = {args.StatisticalTestThreshold} and noise filter = {args.NoiseThreshold}.");
            var table = data.ToMarkdownTable().WithHeaders(conclusion.ToString(), conclusion == EquivalenceTestConclusion.Faster ? "base/diff" : "diff/base", "Base Median (ns)", "Diff Median (ns)", "Modality");
            foreach (var line in table.ToMarkdown().Split(Environment.NewLine, StringSplitOptions.RemoveEmptyEntries))
                Console.WriteLine($"| {line.TrimStart()}|"); // the table starts with \t and does not end with '|' and it looks bad so we fix it
        private static IEnumerable<(string id, Benchmark baseResult, Benchmark diffResult)> ReadResults(CommandLineOptions args)
            var baseFiles = GetFilesToParse(args.BasePath);
            var diffFiles = GetFilesToParse(args.DiffPath);
            if (!baseFiles.Any() || !diffFiles.Any())
                throw new ArgumentException($"Provided paths contained no {FullBdnJsonFileExtension} files.");
            var baseResults = baseFiles.Select(ReadFromFile);
            var diffResults = diffFiles.Select(ReadFromFile);
            var filters = args.Filters.Select(pattern => new Regex(WildcardToRegex(pattern), RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)).ToArray();
            var benchmarkIdToDiffResults = diffResults
                .SelectMany(result => result.Benchmarks)
                .Where(benchmarkResult => !filters.Any() || filters.Any(filter => filter.IsMatch(benchmarkResult.FullName)))
                .ToDictionary(benchmarkResult => benchmarkResult.FullName, benchmarkResult => benchmarkResult);
            return baseResults
                .ToDictionary(benchmarkResult => benchmarkResult.FullName, benchmarkResult => benchmarkResult) // we use ToDictionary to make sure the results have unique IDs
                .Where(baseResult => benchmarkIdToDiffResults.ContainsKey(baseResult.Key))
                .Select(baseResult => (baseResult.Key, baseResult.Value, benchmarkIdToDiffResults[baseResult.Key]));
        private static void ExportToCsv((string id, Benchmark baseResult, Benchmark diffResult, EquivalenceTestConclusion conclusion)[] notSame, FileInfo csvPath)
            if (csvPath == null)
            if (csvPath.Exists)
                csvPath.Delete();
            using (var textWriter = csvPath.CreateText())
                foreach (var (id, baseResult, diffResult, conclusion) in notSame)
                    textWriter.WriteLine($"\"{id.Replace("\"", "\"\"")}\";base;{conclusion};{string.Join(';', baseResult.GetOriginalValues())}");
                    textWriter.WriteLine($"\"{id.Replace("\"", "\"\"")}\";diff;{conclusion};{string.Join(';', diffResult.GetOriginalValues())}");
            Console.WriteLine($"CSV results exported to {csvPath.FullName}");
        private static void ExportToXml((string id, Benchmark baseResult, Benchmark diffResult, EquivalenceTestConclusion conclusion)[] notSame, FileInfo xmlPath)
            if (xmlPath == null)
                Console.WriteLine("No file given");
             if (xmlPath.Exists)
                xmlPath.Delete();
            using (XmlWriter writer = XmlWriter.Create(xmlPath.Open(FileMode.OpenOrCreate, FileAccess.Write, FileShare.Write)))
                writer.WriteStartElement("performance-tests");
                foreach (var (id, baseResult, diffResult, conclusion) in notSame.Where(x => x.conclusion == EquivalenceTestConclusion.Slower))
                    writer.WriteStartElement("test");
                    writer.WriteAttributeString("name", id);
                    writer.WriteAttributeString("type", baseResult.Type);
                    writer.WriteAttributeString("method", baseResult.Method);
                    writer.WriteAttributeString("time", "0");
                    writer.WriteAttributeString("result", "Fail");
                    writer.WriteStartElement("failure");
                    writer.WriteAttributeString("exception-type", "Regression");
                    writer.WriteElementString("message", $"{id} has regressed, was {baseResult.Statistics.Median} is {diffResult.Statistics.Median}.");
                foreach (var (id, baseResult, diffResult, conclusion) in notSame.Where(x => x.conclusion == EquivalenceTestConclusion.Faster))
                    writer.WriteAttributeString("result", "Skip");
                    writer.WriteElementString("reason", $"{id} has improved, was {baseResult.Statistics.Median} is {diffResult.Statistics.Median}.");
                writer.Flush();
            Console.WriteLine($"XML results exported to {xmlPath.FullName}");
        private static string[] GetFilesToParse(string path)
                return Directory.GetFiles(path, $"*{FullBdnJsonFileExtension}", SearchOption.AllDirectories);
            else if (File.Exists(path) || !path.EndsWith(FullBdnJsonFileExtension))
                return new[] { path };
                throw new FileNotFoundException($"Provided path does NOT exist or is not a {path} file", path);
        // code and magic values taken from BenchmarkDotNet.Analysers.MultimodalDistributionAnalyzer
        // See http://www.brendangregg.com/FrequencyTrails/modes.html
        private static string GetModalInfo(Benchmark benchmark)
            if (benchmark.Statistics.N < 12) // not enough data to tell
            double mValue = MValueCalculator.Calculate(benchmark.GetOriginalValues());
            if (mValue > 4.2)
                return "multimodal";
            else if (mValue > 3.2)
                return "bimodal";
            else if (mValue > 2.8)
                return "several?";
        private static double GetRatio((string id, Benchmark baseResult, Benchmark diffResult, EquivalenceTestConclusion conclusion) item) => GetRatio(item.conclusion, item.baseResult, item.diffResult);
        private static double GetRatio(EquivalenceTestConclusion conclusion, Benchmark baseResult, Benchmark diffResult)
            => conclusion == EquivalenceTestConclusion.Faster
                ? baseResult.Statistics.Median / diffResult.Statistics.Median
                : diffResult.Statistics.Median / baseResult.Statistics.Median;
        private static BdnResult ReadFromFile(string resultFilePath)
                return JsonConvert.DeserializeObject<BdnResult>(File.ReadAllText(resultFilePath));
            catch (JsonSerializationException)
                Console.WriteLine($"Exception while reading the {resultFilePath} file.");
        // https://stackoverflow.com/a/6907849/5852046 not perfect but should work for all we need
        private static string WildcardToRegex(string pattern) => $"^{Regex.Escape(pattern).Replace(@"\*", ".*").Replace(@"\?", ".")}$";
namespace TestService
    internal static class Program
       private static void Main()
            ServiceBase[] ServicesToRun;
            ServicesToRun = new ServiceBase[]
                new Service1()
            ServiceBase.Run(ServicesToRun);
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Server.Kestrel.Https;
using Microsoft.Extensions.Hosting;
namespace mvc
            if (args.Length != 7)
                Console.WriteLine("Required: <CertificatePath> <CertificatePassword> <HTTPPortNumber> <HTTPSPortNumberTls12> <HTTPSPortNumberTls11> <HTTPSPortNumberTls> <HTTPSPortNumberTls12>");
            BuildHost(args).Run();
        public static IHost BuildHost(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                    webBuilder.UseStartup<Startup>();
                    webBuilder.UseKestrel(options =>
                        options.AllowSynchronousIO = true;
                        options.Listen(
                            IPAddress.Loopback,
                            int.Parse(args[2]),
                            listenOptions =>
                                listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2;
                            int.Parse(args[3]),
                                var certificate = new X509Certificate2(args[0], args[1]);
                                HttpsConnectionAdapterOptions httpsOption = new HttpsConnectionAdapterOptions();
                                httpsOption.SslProtocols = SslProtocols.Tls12;
                                httpsOption.ClientCertificateMode = ClientCertificateMode.AllowCertificate;
                                httpsOption.ClientCertificateValidation = (inCertificate, inChain, inPolicy) => { return true; };
                                httpsOption.CheckCertificateRevocation = false;
                                httpsOption.ServerCertificate = certificate;
                                listenOptions.UseHttps(httpsOption);
                            int.Parse(args[4]),
                                // TLS 1.1 is obsolete. Using this value now defaults to TLS 1.2.
                            int.Parse(args[5]),
                                // TLS is obsolete. Using this value now defaults to TLS 1.2.
                            int.Parse(args[6]),
                                httpsOption.SslProtocols = SslProtocols.Tls13;
                .Build();
