 * This file contains types related to database queries, stored queries, and data requests
 * - Stored query metadata (SkipQueryInfo, SkipQueryFieldInfo)
 * - Data request specifications (SkipDataRequest, SkipDataRequestType)
 * - Learning cycle query change tracking (SkipLearningCycleQueryChange)
 * These types enable Skip to understand and work with pre-defined queries stored in the
 * MemberJunction metadata system, as well as handle dynamic data requests that Skip
 * generates during analysis. The query metadata includes information about query
 * parameters, field definitions, quality rankings, and approval status.
 * Data requests allow Skip to ask for additional data beyond what was initially provided,
 * either through custom SQL statements or by referencing stored queries. This capability
 * enables Skip to iteratively refine its analysis by gathering the exact data it needs.
 * IMPORTANT: These types implement interfaces from @memberjunction/core to ensure
 * consistency between MJ and Skip. Property names use PascalCase to match MJ conventions.
    IQueryEntityInfoBase
 * Describes the different types of data requests the Skip API server can make for additional data.
 * * sql: The Skip API server is asking for additional data to be gathered using a fully executable SQL statement
 * * stored_query: The Skip API server is asking for additional data to be gathered using a stored query that is defined in the system within the Queries entity.
export const SkipDataRequestType = {
    sql: "sql",
    stored_query: "stored_query"
export type SkipDataRequestType = typeof SkipDataRequestType[keyof typeof SkipDataRequestType];
 * This type is used to define the requested data whenever the Skip API server asks for additional data to be gathered
export class SkipDataRequest {
     * The type of request, as defined in the `SkipDataRequestType` type
    type!: SkipDataRequestType;
     * The text of the request - either a fully executable SQL statement or the name of a stored query
    text!: string;
     * For SQL requests, this is a generated programmatic name that can be used to reference this particular
     * item within a data context. The name will be unique within a given data context, generated by Skip.
    codeName?: string;
     * A description of the request, why it was requested, and what it is expected to provide
 * Metadata about individual fields within a stored query, including their data types,
 * source entity mappings, and computed field information. This helps Skip understand
 * the structure and meaning of query results.
 * Implements IQueryFieldInfoBase for consistency with MJCore types.
export class SkipQueryFieldInfo implements IQueryFieldInfoBase {
 * Parameter definitions for parameterized queries that use Nunjucks templates.
 * Each parameter represents a dynamic value that can be passed when executing the query.
 * Implements IQueryParameterInfoBase for consistency with MJCore types.
export class SkipQueryParamInfo implements IQueryParameterInfoBase {
 * Metadata about entities referenced by a query. This helps Skip understand which
 * entities are involved in each query and how they are being used.
 * Implements IQueryEntityInfoBase for consistency with MJCore types.
export class SkipQueryEntityInfo implements IQueryEntityInfoBase {
 * Complete metadata about a stored query, including its SQL, approval status, quality ranking,
 * and field definitions. This information allows Skip to understand and utilize pre-built
 * queries for analysis and reporting.
 * Implements IQueryInfoBase for consistency with MJCore types.
export class SkipQueryInfo implements IQueryInfoBase {
     * The name of the AI Model used to generate the embedding vector for this query.
    Fields: SkipQueryFieldInfo[];
    Parameters: SkipQueryParamInfo[];
    Entities?: SkipQueryEntityInfo[];
    CacheEnabled: boolean = false;
    CacheMaxSize: number;
    CacheTTLMinutes: number;
    CacheValidationSQL: string;
 * Represents a change to a query during the learning cycle process, allowing Skip
 * to add new queries, update existing ones, or mark queries for deletion based on
 * its analysis of conversation patterns and user needs.
export class SkipLearningCycleQueryChange {
    query: SkipQueryInfo;
