__all__ = ["RealtimeConversationItemAssistantMessage", "Content"]
    Base64-encoded audio bytes, these will be parsed as the format specified in the
    session output audio type configuration. This defaults to PCM 16-bit 24kHz mono
    if not specified.
    The transcript of the audio content, this will always be present if the output
    type is `audio`.
    type: Optional[Literal["output_text", "output_audio"]] = None
    The content type, `output_text` or `output_audio` depending on the session
    `output_modalities` configuration.
class RealtimeConversationItemAssistantMessage(BaseModel):
    """An assistant message item in a Realtime conversation."""
    """The role of the message sender. Always `assistant`."""
    """The type of the item. Always `message`."""
    """The unique ID of the item.
    This may be provided by the client or generated by the server.
    """Identifier for the API object being returned - always `realtime.item`.
    Optional when creating a new item.
    """The status of the item. Has no effect on the conversation."""
