 * Type definitions for QueryGen package
import { EntityInfo, EntityRelationshipInfo } from '@memberjunction/core';
 * Represents a group of related entities for query generation
export interface EntityGroup {
  entities: EntityInfo[];
  relationships: EntityRelationshipInfo[];
  primaryEntity: EntityInfo;
  // LLM-generated semantic metadata
  businessDomain: string;           // e.g., "Sales Pipeline", "Inventory Management"
  businessRationale: string;        // Why this grouping makes business sense
  expectedQuestionTypes: string[];  // e.g., ["trend_analysis", "aggregation", "comparison"]
 * Entity metadata formatted for AI prompts
export interface EntityMetadataForPrompt {
  fields: EntityFieldMetadata[];
  relationships: EntityRelationshipMetadata[];
 * Entity field metadata for prompts
export interface EntityFieldMetadata {
  relatedEntity?: string;
 * Entity relationship metadata for prompts
export interface EntityRelationshipMetadata {
  type: 'one-to-many' | 'many-to-one' | 'many-to-many';
  relatedEntity: string;
  relatedEntityView: string;
  relatedEntitySchema: string;
  foreignKeyField: string;
 * Business question generated by AI
export interface BusinessQuestion {
  complexity: 'simple' | 'medium' | 'complex';
  requiresAggregation: boolean;
  requiresJoins: boolean;
 * SQL query generated by AI
 * Note: selectClause removed - MJQueryEntity automatically creates MJQueryFieldEntity records from SQL
export interface GeneratedQuery {
  sql: string;
 * Query output field definition
export interface QueryOutputField {
 * Query parameter definition
  sampleValue: string;
 * Golden query for few-shot learning
export interface GoldenQuery {
  selectClause: QueryOutputField[];
 * Similarity search result
 * Note: nameSim excluded since queries don't have names until after generation
export interface SimilarQuery {
  query: GoldenQuery;
  fieldScores: {
    userQuestionSim: number;
    descSim: number;
    techDescSim: number;
 * Query test result
export interface QueryTestResult {
  renderedSQL?: string;
  sampleRows?: unknown[];
  attempts?: number;
 * Query evaluation result
export interface QueryEvaluation {
  answersQuestion: boolean;
  needsRefinement: boolean;
 * Refined query result
export interface RefinedQuery {
  query: GeneratedQuery;
  testResult: QueryTestResult;
  evaluation: QueryEvaluation;
  refinementCount: number;
  reachedMaxRefinements?: boolean;
 * Query category information for metadata export and database write
export interface QueryCategoryInfo {
  /** Name of the category */
  /** Parent category name (null for root categories) */
  parentName: string | null;
  /** Category description */
  /** Full category path (e.g., "Golden-Queries/Members") */
 * Validated query ready for export
export interface ValidatedQuery {
  businessQuestion: BusinessQuestion;
  entityGroup: EntityGroup;
 * Metadata export result
 * Database write result
export interface WriteResult {
  results: string[];
 * Query metadata record for MJ metadata format
 * Note: QueryFields and QueryParameters are not included here.
 * They are automatically extracted by MJQueryEntity.server.ts using
 * AI analysis of the SQL template during the Save() operation.
export interface QueryMetadataRecord {
    UserQuestion: string;
    TechnicalDescription: string;
 * Embeddings for a query or golden query
 * Note: name is excluded since queries don't have names until after generation
export interface QueryEmbeddings {
  userQuestion: number[];
  description: number[];
  technicalDescription: number[];
 * Golden query with embeddings
export interface EmbeddedGoldenQuery {
  embeddings: QueryEmbeddings;
