    #region UserActionState enum
    /// Represents the availability of an action to a user.
    public enum UserActionState
        /// Indicates that the action is enabled and allowed.
        Enabled = 0,
        /// Indicates that the action is disabled.
        Disabled = 1,
        /// Indicates that the action is not visible.
        Hidden = 2,
    #region ControlState enum
    /// Represents the ready-state of a control.
    public enum ControlState
        /// Indicates that the control is ready.
        Ready = 0,
        /// Indicates that the control has an error.
        Error = 1,
        /// Indicates that the control is refreshing its data.
        Refreshing = 2,
    #region Utilities class
    /// Provides common methods for use in the library.
    public static class Utilities
        /// Gets whether all of the items in <paramref name="items"/> are of type T.
        /// <typeparam name="T">The type to verify.</typeparam>
        /// <param name="items">The items to check.</param>
        /// <returns>Whether all of the items in <paramref name="items"/> are of type T.</returns>
        /// <exception cref="ArgumentNullException">The specified value is a null reference.</exception>
        public static bool AreAllItemsOfType<T>(IEnumerable items)
            ArgumentNullException.ThrowIfNull(items);
            foreach (object item in items)
                if (item is not T)
        /// Searches for an element that matches the specified type, and returns the first occurrence in the entire <see cref="IEnumerable"/>.
        /// <typeparam name="T">The type of the item to find.</typeparam>
        /// <param name="items">The <see cref="IEnumerable"/> to search.</param>
        /// <returns>The first element that matches the specified type, if found; otherwise, the default value for type <typeparamref name="T"/>.</returns>
        public static T Find<T>(this IEnumerable items)
                if (item is T)
                    return (T)item;
            return default(T);
        /// Method to trim the non null strings.
        /// <param name="value">String to Trim.</param>
        /// <returns>Trimmed string.</returns>
        public static string NullCheckTrim(string value)
            if (!string.IsNullOrEmpty(value))
                return value.Trim();
        // A separate copy of ResortObservableCollection is in ADMUX Utility.cs
        /// Restore the original order as far as possible.
        /// Columns not in the original set will appear at the end.
        /// Type of <paramref name="modify"/>.
        /// <param name="modify">
        /// ObservableCollection to resort to order of
        /// <paramref name="sorted"/>.
        /// <param name="sorted">
        /// Order to which <paramref name="modify"/> should be resorted.
        /// All enumerated objects must be of type T.
        /// Parameter <paramref name="sorted"/> is not generic to type T
        /// since it may be a collection of a subclass of type T,
        /// and IEnumerable'subclass is not compatible with
        /// IEnumerable'baseclass.
        public static void ResortObservableCollection<T>(
            ObservableCollection<T> modify,
            IEnumerable sorted)
            int orderedPosition = 0;
            foreach (T obj in sorted)
                T sortedObject = (T)obj;
                int foundIndex = modify.IndexOf(sortedObject);
                if (foundIndex >= 0)
                    modify.Move(foundIndex, orderedPosition);
                    orderedPosition++;
                    if (modify.Count <= orderedPosition)
                        // All objects present are in the original order
        internal static Type GetNonNullableType(this Type type)
        internal static Type GetNullableType(Type type)
            Debug.Assert(type != null, "type cannot be null");
            if (type.IsValueType && !IsNullableType(type))
                return typeof(Nullable<>).MakeGenericType(type);
        internal static bool IsNullableType(Type type)
        internal static bool IsBool(Type type)
            return GetNonNullableType(type) == typeof(bool);
        internal static bool IsNumeric(Type type)
            type = GetNonNullableType(type);
            if (!type.IsEnum)
            switch (typeCode)
        internal static bool IsArithmetic(Type type)
    internal static class ArrayUtils
    internal static class DelegateHelpers
        #region Generated Maximum Delegate Arity
        // generated by function: gen_max_delegate_arity from: generate_dynsites.py
        private const int MaximumArity = 17;
        internal static Type MakeDelegate(Type[] types)
            Debug.Assert(types != null && types.Length > 0);
            // Can only used predefined delegates if we have no byref types and
            // the arity is small enough to fit in Func<...> or Action<...>
            if (types.Length > MaximumArity || types.Any(static t => t.IsByRef))
                // return MakeCustomDelegate(types);
            Type returnType = types[types.Length - 1];
                Array.Resize(ref types, types.Length - 1);
                switch (types.Length)
                    case 0: return typeof(Action);
                    #region Generated Delegate Action Types
                    // generated by function: gen_delegate_action from: generate_dynsites.py
                    case 1: return typeof(Action<>).MakeGenericType(types);
                    case 2: return typeof(Action<,>).MakeGenericType(types);
                    case 3: return typeof(Action<,,>).MakeGenericType(types);
                    case 4: return typeof(Action<,,,>).MakeGenericType(types);
                    case 5: return typeof(Action<,,,,>).MakeGenericType(types);
                    case 6: return typeof(Action<,,,,,>).MakeGenericType(types);
                    case 7: return typeof(Action<,,,,,,>).MakeGenericType(types);
                    case 8: return typeof(Action<,,,,,,,>).MakeGenericType(types);
                    case 9: return typeof(Action<,,,,,,,,>).MakeGenericType(types);
                    case 10: return typeof(Action<,,,,,,,,,>).MakeGenericType(types);
                    case 11: return typeof(Action<,,,,,,,,,,>).MakeGenericType(types);
                    case 12: return typeof(Action<,,,,,,,,,,,>).MakeGenericType(types);
                    case 13: return typeof(Action<,,,,,,,,,,,,>).MakeGenericType(types);
                    case 14: return typeof(Action<,,,,,,,,,,,,,>).MakeGenericType(types);
                    case 15: return typeof(Action<,,,,,,,,,,,,,,>).MakeGenericType(types);
                    case 16: return typeof(Action<,,,,,,,,,,,,,,,>).MakeGenericType(types);
                    #region Generated Delegate Func Types
                    // generated by function: gen_delegate_func from: generate_dynsites.py
                    case 1: return typeof(Func<>).MakeGenericType(types);
                    case 2: return typeof(Func<,>).MakeGenericType(types);
                    case 3: return typeof(Func<,,>).MakeGenericType(types);
                    case 4: return typeof(Func<,,,>).MakeGenericType(types);
                    case 5: return typeof(Func<,,,,>).MakeGenericType(types);
                    case 6: return typeof(Func<,,,,,>).MakeGenericType(types);
                    case 7: return typeof(Func<,,,,,,>).MakeGenericType(types);
                    case 8: return typeof(Func<,,,,,,,>).MakeGenericType(types);
                    case 9: return typeof(Func<,,,,,,,,>).MakeGenericType(types);
                    case 10: return typeof(Func<,,,,,,,,,>).MakeGenericType(types);
                    case 11: return typeof(Func<,,,,,,,,,,>).MakeGenericType(types);
                    case 12: return typeof(Func<,,,,,,,,,,,>).MakeGenericType(types);
                    case 13: return typeof(Func<,,,,,,,,,,,,>).MakeGenericType(types);
                    case 14: return typeof(Func<,,,,,,,,,,,,,>).MakeGenericType(types);
                    case 15: return typeof(Func<,,,,,,,,,,,,,,>).MakeGenericType(types);
                    case 16: return typeof(Func<,,,,,,,,,,,,,,,>).MakeGenericType(types);
                    case 17: return typeof(Func<,,,,,,,,,,,,,,,,>).MakeGenericType(types);
    internal static class ScriptingRuntimeHelpers
        internal static object Int32ToObject(int i)
        internal static object BooleanToObject(bool b)
            return b ? True : False;
        internal static readonly MethodInfo BooleanToObjectMethod = typeof(ScriptingRuntimeHelpers).GetMethod("BooleanToObject");
        internal static readonly MethodInfo Int32ToObjectMethod = typeof(ScriptingRuntimeHelpers).GetMethod("Int32ToObject");
        internal static readonly object True = true;
        internal static readonly object False = false;
        internal static object GetPrimitiveDefaultValue(Type type)
                case TypeCode.Boolean: return ScriptingRuntimeHelpers.False;
                case TypeCode.SByte: return default(sbyte);
                case TypeCode.Byte: return default(byte);
                case TypeCode.Char: return default(char);
                case TypeCode.Int16: return default(Int16);
                case TypeCode.Int32: return ScriptingRuntimeHelpers.Int32ToObject(0);
                case TypeCode.Int64: return default(Int64);
                case TypeCode.UInt16: return default(UInt16);
                case TypeCode.UInt32: return default(UInt32);
                case TypeCode.UInt64: return default(UInt64);
                case TypeCode.Single: return default(Single);
                case TypeCode.Double: return default(double);
                case TypeCode.DateTime: return default(DateTime);
                case TypeCode.Decimal: return default(Decimal);
                // TypeCode.Empty:  null;
                // TypeCode.Object: default(object) == null;
                // TypeCode.DBNull: default(DBNull) == null;
                // TypeCode.String: default(string) == null;
    /// Wraps all arguments passed to a dynamic site with more arguments than can be accepted by a Func/Action delegate.
    /// The binder generating a rule for such a site should unwrap the arguments first and then perform a binding to them.
    internal sealed class ArgumentArray
        private readonly object[] _arguments;
        // the index of the first item _arguments that represents an argument:
        // the number of items in _arguments that represent the arguments:
        internal ArgumentArray(object[] arguments, int first, int count)
            _arguments = arguments;
            Count = count;
        public int Count { get; }
        public object GetArgument(int index)
            // ContractUtils.RequiresArrayIndex(_arguments, index, "index");
            return _arguments[_first + index];
        public DynamicMetaObject GetMetaObject(Expression parameter, int index)
            return DynamicMetaObject.Create(
                GetArgument(index),
                    s_getArgMethod,
                    AstUtils.Convert(parameter, typeof(ArgumentArray)),
                    AstUtils.Constant(index)
        // [CLSCompliant(false)]
        public static object GetArg(ArgumentArray array, int index)
            return array._arguments[array._first + index];
        private static readonly MethodInfo s_getArgMethod = new Func<ArgumentArray, int, object>(GetArg).GetMethodInfo();
    internal static class ExceptionHelpers
        private const string prevStackTraces = "PreviousStackTraces";
        /// Updates an exception before it's getting re-thrown so
        /// we can present a reasonable stack trace to the user.
        public static Exception UpdateForRethrow(Exception rethrow)
            List<StackTrace> prev;
            // we don't have any dynamic stack trace data, capture the data we can
            // from the raw exception object.
            StackTrace st = new StackTrace(rethrow, true);
            if (!TryGetAssociatedStackTraces(rethrow, out prev))
                prev = new List<StackTrace>();
                AssociateStackTraces(rethrow, prev);
            prev.Add(st);
            return rethrow;
        /// Returns all the stack traces associates with an exception.
        public static IList<StackTrace> GetExceptionStackTraces(Exception rethrow)
            List<StackTrace> result;
            return TryGetAssociatedStackTraces(rethrow, out result) ? result : null;
        private static void AssociateStackTraces(Exception e, List<StackTrace> traces)
            e.Data[prevStackTraces] = traces;
        private static bool TryGetAssociatedStackTraces(Exception e, out List<StackTrace> traces)
            traces = e.Data[prevStackTraces] as List<StackTrace>;
            return traces != null;
    /// A hybrid dictionary which compares based upon object identity.
    internal class HybridReferenceDictionary<TKey, TValue> where TKey : class
        private KeyValuePair<TKey, TValue>[] _keysAndValues;
        private Dictionary<TKey, TValue> _dict;
        private const int _arraySize = 10;
        public HybridReferenceDictionary()
        public HybridReferenceDictionary(int initialCapacity)
            if (initialCapacity > _arraySize)
                _dict = new Dictionary<TKey, TValue>(initialCapacity);
                _keysAndValues = new KeyValuePair<TKey, TValue>[initialCapacity];
        public bool TryGetValue(TKey key, out TValue value)
            Debug.Assert(key != null);
            if (_dict != null)
                return _dict.TryGetValue(key, out value);
            else if (_keysAndValues != null)
                for (int i = 0; i < _keysAndValues.Length; i++)
                    if (_keysAndValues[i].Key == key)
                        value = _keysAndValues[i].Value;
            value = default(TValue);
        public bool Remove(TKey key)
                return _dict.Remove(key);
                        _keysAndValues[i] = new KeyValuePair<TKey, TValue>();
                        _count--;
        public bool ContainsKey(TKey key)
                return _dict.ContainsKey(key);
                    return _dict.Count;
        public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator()
                return _dict.GetEnumerator();
            return GetEnumeratorWorker();
        private IEnumerator<KeyValuePair<TKey, TValue>> GetEnumeratorWorker()
            if (_keysAndValues != null)
                    if (_keysAndValues[i].Key != null)
                        yield return _keysAndValues[i];
        public TValue this[TKey key]
                TValue res;
                if (TryGetValue(key, out res))
                throw new KeyNotFoundException();
                    _dict[key] = value;
                                _keysAndValues[i] = new KeyValuePair<TKey, TValue>(key, value);
                            else if (_keysAndValues[i].Key == null)
                        _keysAndValues = new KeyValuePair<TKey, TValue>[_arraySize];
                        _count++;
                        _keysAndValues[index] = new KeyValuePair<TKey, TValue>(key, value);
                        _dict = new Dictionary<TKey, TValue>();
                            _dict[_keysAndValues[i].Key] = _keysAndValues[i].Value;
                        _keysAndValues = null;
    /// Provides a dictionary-like object used for caches which holds onto a maximum
    /// number of elements specified at construction time.
    /// This class is not thread safe.
    internal class CacheDict<TKey, TValue>
        private readonly Dictionary<TKey, KeyInfo> _dict = new Dictionary<TKey, KeyInfo>();
        private readonly LinkedList<TKey> _list = new LinkedList<TKey>();
        private readonly int _maxSize;
        /// Creates a dictionary-like object used for caches.
        /// <param name="maxSize">The maximum number of elements to store.</param>
        public CacheDict(int maxSize)
            _maxSize = maxSize;
        /// Tries to get the value associated with 'key', returning true if it's found and
        /// false if it's not present.
            KeyInfo storedValue;
            if (_dict.TryGetValue(key, out storedValue))
                LinkedListNode<TKey> node = storedValue.List;
                if (node.Previous != null)
                    // move us to the head of the list...
                    _list.Remove(node);
                    _list.AddFirst(node);
                value = storedValue.Value;
        /// Adds a new element to the cache, replacing and moving it to the front if the
        /// element is already present.
        public void Add(TKey key, TValue value)
            if (_dict.TryGetValue(key, out keyInfo))
                // remove original entry from the linked list
                _list.Remove(keyInfo.List);
            else if (_list.Count == _maxSize)
                // we've reached capacity, remove the last used element...
                LinkedListNode<TKey> node = _list.Last;
                _list.RemoveLast();
                bool res = _dict.Remove(node.Value);
                Debug.Assert(res);
            // add the new entry to the head of the list and into the dictionary
            LinkedListNode<TKey> listNode = new LinkedListNode<TKey>(key);
            _list.AddFirst(listNode);
            _dict[key] = new CacheDict<TKey, TValue>.KeyInfo(value, listNode);
        /// Returns the value associated with the given key, or throws KeyNotFoundException
        /// if the key is not present.
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations")]
                Add(key, value);
        private readonly struct KeyInfo
            internal readonly TValue Value;
            internal readonly LinkedListNode<TKey> List;
            internal KeyInfo(TValue value, LinkedListNode<TKey> list)
                List = list;
    internal class ThreadLocal<T>
        private StorageInfo[] _stores;                                         // array of storage indexed by managed thread ID
        private static readonly StorageInfo[] s_updating = Array.Empty<StorageInfo>();   // a marker used when updating the array
        private readonly bool _refCounted;
        public ThreadLocal()
        /// True if the caller will guarantee that all cleanup happens as the thread
        /// unwinds.
        /// This is typically used in a case where the thread local is surrounded by
        /// a try/finally block.  The try block pushes some state, the finally block
        /// restores the previous state.  Therefore when the thread exits the thread
        /// local is back to it's original state.  This allows the ThreadLocal object
        /// to not check the current owning thread on retrieval.
        public ThreadLocal(bool refCounted)
            _refCounted = refCounted;
        /// Gets or sets the value for the current thread.
        public T Value
                return GetStorageInfo().Value;
                GetStorageInfo().Value = value;
        /// Gets the current value if its not == null or calls the provided function
        /// to create a new value.
        public T GetOrCreate(Func<T> func)
            Assert.NotNull(func);
            StorageInfo si = GetStorageInfo();
            T res = si.Value;
            if (res == null)
                si.Value = res = func();
        /// Calls the provided update function with the current value and
        /// replaces the current value with the result of the function.
        public T Update(Func<T, T> updater)
            Assert.NotNull(updater);
            return si.Value = updater(si.Value);
        /// Replaces the current value with a new one and returns the old value.
        public T Update(T newValue)
            var oldValue = si.Value;
            si.Value = newValue;
            return oldValue;
        #region Storage implementation
        /// Gets the StorageInfo for the current thread.
        public StorageInfo GetStorageInfo()
            return GetStorageInfo(_stores);
        private StorageInfo GetStorageInfo(StorageInfo[] curStorage)
            int threadId = Environment.CurrentManagedThreadId;
            // fast path if we already have a value in the array
            if (curStorage != null && curStorage.Length > threadId)
                StorageInfo res = curStorage[threadId];
                if (res != null && (_refCounted || res.Thread == Thread.CurrentThread))
            return RetryOrCreateStorageInfo(curStorage);
        /// Called when the fast path storage lookup fails. if we encountered the Empty storage
        /// during the initial fast check then spin until we hit non-empty storage and try the fast
        /// path again.
        private StorageInfo RetryOrCreateStorageInfo(StorageInfo[] curStorage)
            if (curStorage == s_updating)
                // we need to retry
                while ((curStorage = _stores) == s_updating)
                    Thread.Sleep(0);
                // we now have a non-empty storage info to retry with
                return GetStorageInfo(curStorage);
            // we need to mutate the StorageInfo[] array or create a new StorageInfo
            return CreateStorageInfo();
        /// Creates the StorageInfo for the thread when one isn't already present.
        private StorageInfo CreateStorageInfo()
            // we do our own locking, tell hosts this is a bad time to interrupt us.
            Thread.BeginCriticalRegion();
            StorageInfo[] curStorage = s_updating;
                StorageInfo newInfo = new StorageInfo(Thread.CurrentThread);
                // set to updating while potentially resizing/mutating, then we'll
                // set back to the current value.
                while ((curStorage = Interlocked.Exchange(ref _stores, s_updating)) == s_updating)
                    // another thread is already updating...
                // check and make sure we have a space in the array for our value
                if (curStorage == null)
                    curStorage = new StorageInfo[threadId + 1];
                else if (curStorage.Length <= threadId)
                    StorageInfo[] newStorage = new StorageInfo[threadId + 1];
                    for (int i = 0; i < curStorage.Length; i++)
                        // leave out the threads that have exited
                        if (curStorage[i] != null && curStorage[i].Thread.IsAlive)
                            newStorage[i] = curStorage[i];
                    curStorage = newStorage;
                // create our StorageInfo in the array, the empty check ensures we're only here
                // when we need to create.
                Debug.Assert(curStorage[threadId] == null || curStorage[threadId].Thread != Thread.CurrentThread);
                return curStorage[threadId] = newInfo;
                if (curStorage != s_updating)
                    // let others access the storage again
                    Interlocked.Exchange(ref _stores, curStorage);
                Thread.EndCriticalRegion();
        /// Helper class for storing the value.  We need to track if a ManagedThreadId
        /// has been re-used so we also store the thread which owns the value.
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")] // TODO
        internal sealed class StorageInfo
            internal readonly Thread Thread;                 // the thread that owns the StorageInfo
            public T Value;                                // the current value for the owning thread
            internal StorageInfo(Thread curThread)
                Assert.NotNull(curThread);
                Thread = curThread;
    internal static class Assert
        internal static Exception Unreachable
                Debug.Fail("Unreachable");
                return new InvalidOperationException("Code supposed to be unreachable");
        public static void NotNull(object var)
            Debug.Assert(var != null);
        public static void NotNull(object var1, object var2)
            Debug.Assert(var1 != null && var2 != null);
        public static void NotNull(object var1, object var2, object var3)
            Debug.Assert(var1 != null && var2 != null && var3 != null);
        public static void NotNullItems<T>(IEnumerable<T> items) where T : class
            Debug.Assert(items != null);
                Debug.Assert(item != null);
        public static void NotEmpty(string str)
            Debug.Assert(!string.IsNullOrEmpty(str));
    internal enum ExpressionAccess
        Read = 1,
        Write = 2,
        ReadWrite = Read | Write,
        internal static Expression Constant(object value)
            return Expression.Constant(value);
        private static readonly DefaultExpression s_voidInstance = Expression.Empty();
        public static DefaultExpression Empty()
            return s_voidInstance;
        public static Expression Void(Expression expression)
            // ContractUtils.RequiresNotNull(expression, "expression");
            return Expression.Block(expression, Utils.Empty());
        public static DefaultExpression Default(Type type)
                return Empty();
            return Expression.Default(type);
        public static Expression Convert(Expression expression, Type type)
                return Expression.Block(expression, Utils.Default(type));
                return Void(expression);
            // TODO: this is not the right level for this to be at. It should
            // be pushed into languages if they really want this behavior.
            if (type == typeof(object))
                return Box(expression);
        public static Expression Box(Expression expression)
            MethodInfo m;
            if (expression.Type == typeof(int))
                m = ScriptingRuntimeHelpers.Int32ToObjectMethod;
            else if (expression.Type == typeof(bool))
                m = ScriptingRuntimeHelpers.BooleanToObjectMethod;
                m = null;
            return Expression.Convert(expression, typeof(object), m);
        public static bool IsReadWriteAssignment(this ExpressionType type)
                // unary:
                // binary - compound:
    internal static class CollectionExtension
        internal static bool TrueForAll<T>(this IEnumerable<T> collection, Predicate<T> predicate)
            // ContractUtils.RequiresNotNull(collection, "collection");
            // ContractUtils.RequiresNotNull(predicate, "predicate");
            foreach (T item in collection)
                if (!predicate(item))
        internal static TResult[] Map<TSource, TResult>(this ICollection<TSource> source, Func<TSource, TResult> selector)
            int count = source.Count;
            TResult[] result = new TResult[count];
            foreach (TSource t in source)
                result[count++] = selector(t);
        // We could probably improve the hashing here
        internal static int ListHashCode<T>(this IEnumerable<T> list)
            int h = 6551;
            foreach (T t in list)
                h ^= (h << 5) ^ cmp.GetHashCode(t);
        internal static bool ListEquals<T>(this ICollection<T> first, ICollection<T> second)
            if (first.Count != second.Count)
            var f = first.GetEnumerator();
            var s = second.GetEnumerator();
            while (f.MoveNext())
                s.MoveNext();
                if (!cmp.Equals(f.Current, s.Current))
    internal sealed class ListEqualityComparer<T> : EqualityComparer<ICollection<T>>
        internal static readonly ListEqualityComparer<T> Instance = new ListEqualityComparer<T>();
        private ListEqualityComparer() { }
        // EqualityComparer<T> handles null and object identity for us
        public override bool Equals(ICollection<T> x, ICollection<T> y)
            return x.ListEquals(y);
        public override int GetHashCode(ICollection<T> obj)
            return obj.ListHashCode();
