//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.16598
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// namespace Microsoft.Management.UI.Internal {
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HelpWindowSettings : global::System.Configuration.ApplicationSettingsBase {
        private static HelpWindowSettings defaultInstance = ((HelpWindowSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HelpWindowSettings())));
        public static HelpWindowSettings Default {
            get {
                return defaultInstance;
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HelpRemarksDisplayed
                return ((bool)(this["HelpRemarksDisplayed"]));
                this["HelpRemarksDisplayed"] = value;
        public bool HelpSyntaxDisplayed {
                return ((bool)(this["HelpSyntaxDisplayed"]));
            set {
                this["HelpSyntaxDisplayed"] = value;
        public bool HelpExamplesDisplayed {
                return ((bool)(this["HelpExamplesDisplayed"]));
                this["HelpExamplesDisplayed"] = value;
        public bool HelpSynopsysDisplayed {
                return ((bool)(this["HelpSynopsysDisplayed"]));
                this["HelpSynopsysDisplayed"] = value;
        public bool HelpDescriptionDisplayed {
                return ((bool)(this["HelpDescriptionDisplayed"]));
                this["HelpDescriptionDisplayed"] = value;
        public bool HelpParametersDisplayed {
                return ((bool)(this["HelpParametersDisplayed"]));
                this["HelpParametersDisplayed"] = value;
        public bool HelpInputsDisplayed {
                return ((bool)(this["HelpInputsDisplayed"]));
                this["HelpInputsDisplayed"] = value;
        public bool HelpOutputsDisplayed {
                return ((bool)(this["HelpOutputsDisplayed"]));
                this["HelpOutputsDisplayed"] = value;
        public bool HelpNotesDisplayed {
                return ((bool)(this["HelpNotesDisplayed"]));
                this["HelpNotesDisplayed"] = value;
        public bool HelpRelatedLinksDisplayed {
                return ((bool)(this["HelpRelatedLinksDisplayed"]));
                this["HelpRelatedLinksDisplayed"] = value;
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HelpSearchMatchCase {
                return ((bool)(this["HelpSearchMatchCase"]));
                this["HelpSearchMatchCase"] = value;
        public bool HelpSearchWholeWord {
                return ((bool)(this["HelpSearchWholeWord"]));
                this["HelpSearchWholeWord"] = value;
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double HelpWindowHeight {
                return ((double)(this["HelpWindowHeight"]));
                this["HelpWindowHeight"] = value;
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double HelpWindowWidth {
                return ((double)(this["HelpWindowWidth"]));
                this["HelpWindowWidth"] = value;
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double HelpWindowTop {
                return ((double)(this["HelpWindowTop"]));
                this["HelpWindowTop"] = value;
        public double HelpWindowLeft {
                return ((double)(this["HelpWindowLeft"]));
                this["HelpWindowLeft"] = value;
        public bool HelpWindowMaximized {
                return ((bool)(this["HelpWindowMaximized"]));
                this["HelpWindowMaximized"] = value;
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double HelpZoom {
                return ((double)(this["HelpZoom"]));
                this["HelpZoom"] = value;
