@RegisterClass(BaseFormComponent, 'MJ: Entities') // Tell MemberJunction about this class
    selector: 'gen-mjentity-form',
    templateUrl: './mjentity.form.component.html'
export class MJEntityFormComponent extends BaseFormComponent {
            { sectionKey: 'identityStructure', sectionName: 'Identity & Structure', isExpanded: true },
            { sectionKey: 'userInterfaceCustomization', sectionName: 'User Interface & Customization', isExpanded: true },
            { sectionKey: 'auditingLifecycle', sectionName: 'Auditing & Lifecycle', isExpanded: false },
            { sectionKey: 'aPISearchSettings', sectionName: 'API & Search Settings', isExpanded: false },
            { sectionKey: 'proceduresDeletion', sectionName: 'Procedures & Deletion', isExpanded: false },
            { sectionKey: 'rowStatistics', sectionName: 'Row Statistics', isExpanded: false },
            { sectionKey: 'applicationEntities', sectionName: 'Application Entities', isExpanded: false },
            { sectionKey: 'conversations', sectionName: 'Conversations', isExpanded: false },
            { sectionKey: 'datasetItems', sectionName: 'Dataset Items', isExpanded: false },
            { sectionKey: 'duplicateRuns', sectionName: 'Duplicate Runs', isExpanded: false },
            { sectionKey: 'entityCommunicationMessageTypes', sectionName: 'Entity Communication Message Types', isExpanded: false },
            { sectionKey: 'fields', sectionName: 'Fields', isExpanded: false },
            { sectionKey: 'permissions', sectionName: 'Permissions', isExpanded: false },
            { sectionKey: 'entityRecordDocuments', sectionName: 'Entity Record Documents', isExpanded: false },
            { sectionKey: 'relationships', sectionName: 'Relationships', isExpanded: false },
            { sectionKey: 'entitySettings', sectionName: 'Entity Settings', isExpanded: false },
            { sectionKey: 'fileEntityRecordLinks', sectionName: 'File Entity Record Links', isExpanded: false },
            { sectionKey: 'integrationURLFormats', sectionName: 'Integration URL Formats', isExpanded: false },
            { sectionKey: 'lists', sectionName: 'Lists', isExpanded: false },
            { sectionKey: 'queryFields', sectionName: 'Query Fields', isExpanded: false },
            { sectionKey: 'recommendationItems', sectionName: 'Recommendation Items', isExpanded: false },
            { sectionKey: 'recommendations', sectionName: 'Recommendations', isExpanded: false },
            { sectionKey: 'recordChanges', sectionName: 'Record Changes', isExpanded: false },
            { sectionKey: 'recordMergeLogs', sectionName: 'Record Merge Logs', isExpanded: false },
            { sectionKey: 'resourceTypes', sectionName: 'Resource Types', isExpanded: false },
            { sectionKey: 'taggedItems', sectionName: 'Tagged Items', isExpanded: false },
            { sectionKey: 'templateParams', sectionName: 'Template Params', isExpanded: false },
            { sectionKey: 'userApplicationEntities', sectionName: 'User Application Entities', isExpanded: false },
            { sectionKey: 'userFavorites', sectionName: 'User Favorites', isExpanded: false },
            { sectionKey: 'userRecordLogs', sectionName: 'User Record Logs', isExpanded: false },
            { sectionKey: 'userViewCategories', sectionName: 'User View Categories', isExpanded: false },
            { sectionKey: 'userViews', sectionName: 'User Views', isExpanded: false },
            { sectionKey: 'users', sectionName: 'Users', isExpanded: false },
            { sectionKey: 'mJAccessControlRules', sectionName: 'MJ: Access Control Rules', isExpanded: false },
            { sectionKey: 'queryEntities', sectionName: 'Query Entities', isExpanded: false },
            { sectionKey: 'mJRecordLinks', sectionName: 'MJ: Record Links', isExpanded: false },
            { sectionKey: 'mJVersionLabelItems', sectionName: 'MJ: Version Label Items', isExpanded: false },
            { sectionKey: 'mJVersionLabels', sectionName: 'MJ: Version Labels', isExpanded: false },
            { sectionKey: 'mJRecordLinks1', sectionName: 'MJ: Record Links', isExpanded: false },
            { sectionKey: 'mJTestRuns', sectionName: 'MJ: Test Runs', isExpanded: false }
