from typing import List, Union, Optional
from ..._types import Body, Omit, Query, Headers, NoneType, NotGiven, omit, not_given
from ...types.realtime import (
    call_refer_params,
    call_accept_params,
    call_create_params,
    call_reject_params,
from ...types.responses.response_prompt_param import ResponsePromptParam
from ...types.realtime.realtime_truncation_param import RealtimeTruncationParam
from ...types.realtime.realtime_audio_config_param import RealtimeAudioConfigParam
from ...types.realtime.realtime_tools_config_param import RealtimeToolsConfigParam
from ...types.realtime.realtime_tracing_config_param import RealtimeTracingConfigParam
from ...types.realtime.realtime_tool_choice_config_param import RealtimeToolChoiceConfigParam
from ...types.realtime.realtime_session_create_request_param import RealtimeSessionCreateRequestParam
__all__ = ["Calls", "AsyncCalls"]
class Calls(SyncAPIResource):
    def with_raw_response(self) -> CallsWithRawResponse:
        return CallsWithRawResponse(self)
    def with_streaming_response(self) -> CallsWithStreamingResponse:
        return CallsWithStreamingResponse(self)
        Create a new Realtime API call over WebRTC and receive the SDP answer needed to
        complete the peer connection.
          sdp: WebRTC Session Description Protocol (SDP) offer generated by the caller.
          session: Realtime session object configuration.
        extra_headers = {"Accept": "application/sdp", **(extra_headers or {})}
                    "sdp": sdp,
                    "session": session,
                call_create_params.CallCreateParams,
    def accept(
        call_id: str,
        type: Literal["realtime"],
        audio: RealtimeAudioConfigParam | Omit = omit,
        include: List[Literal["item.input_audio_transcription.logprobs"]] | Omit = omit,
        max_output_tokens: Union[int, Literal["inf"]] | Omit = omit,
                "gpt-realtime-1.5",
                "gpt-realtime-mini",
                "gpt-realtime-mini-2025-10-06",
                "gpt-realtime-mini-2025-12-15",
                "gpt-audio-1.5",
                "gpt-audio-mini",
                "gpt-audio-mini-2025-10-06",
                "gpt-audio-mini-2025-12-15",
        output_modalities: List[Literal["text", "audio"]] | Omit = omit,
        prompt: Optional[ResponsePromptParam] | Omit = omit,
        tool_choice: RealtimeToolChoiceConfigParam | Omit = omit,
        tools: RealtimeToolsConfigParam | Omit = omit,
        tracing: Optional[RealtimeTracingConfigParam] | Omit = omit,
        truncation: RealtimeTruncationParam | Omit = omit,
        Accept an incoming SIP call and configure the realtime session that will handle
        it.
          type: The type of session to create. Always `realtime` for the Realtime API.
          audio: Configuration for input and output audio.
          include: Additional fields to include in server outputs.
              `item.input_audio_transcription.logprobs`: Include logprobs for input audio
              transcription.
          max_output_tokens: Maximum number of output tokens for a single assistant response, inclusive of
          output_modalities: The set of modalities the model can respond with. It defaults to `["audio"]`,
              indicating that the model will respond with audio plus a transcript. `["text"]`
              can be used to make the model respond with text only. It is not possible to
              request both `text` and `audio` at the same time.
          prompt: Reference to a prompt template and its variables.
              [Learn more](https://platform.openai.com/docs/guides/text?api-mode=responses#reusable-prompts).
          tool_choice: How the model chooses tools. Provide one of the string modes or force a specific
              function/MCP tool.
          tools: Tools available to the model.
          tracing: Realtime API can write session traces to the
              [Traces Dashboard](/logs?api=traces). Set to null to disable tracing. Once
              tracing is enabled for a session, the configuration cannot be modified.
          truncation: When the number of tokens in a conversation exceeds the model's input token
              limit, the conversation be truncated, meaning messages (starting from the
              oldest) will not be included in the model's context. A 32k context model with
              4,096 max output tokens can only include 28,224 tokens in the context before
              truncation occurs.
              Clients can configure truncation behavior to truncate with a lower max token
              limit, which is an effective way to control token usage and cost.
              Truncation will reduce the number of cached tokens on the next turn (busting the
              cache), since messages are dropped from the beginning of the context. However,
              clients can also configure truncation to retain messages up to a fraction of the
              maximum context size, which will reduce the need for future truncations and thus
              improve the cache rate.
              Truncation can be disabled entirely, which means the server will never truncate
              but would instead return an error if the conversation exceeds the model's input
              token limit.
        if not call_id:
            raise ValueError(f"Expected a non-empty value for `call_id` but received {call_id!r}")
            path_template("/realtime/calls/{call_id}/accept", call_id=call_id),
                    "type": type,
                    "max_output_tokens": max_output_tokens,
                    "output_modalities": output_modalities,
                    "truncation": truncation,
                call_accept_params.CallAcceptParams,
    def hangup(
        End an active Realtime API call, whether it was initiated over SIP or WebRTC.
            path_template("/realtime/calls/{call_id}/hangup", call_id=call_id),
    def refer(
        target_uri: str,
        Transfer an active SIP call to a new destination using the SIP REFER verb.
          target_uri: URI that should appear in the SIP Refer-To header. Supports values like
              `tel:+14155550123` or `sip:agent@example.com`.
            path_template("/realtime/calls/{call_id}/refer", call_id=call_id),
            body=maybe_transform({"target_uri": target_uri}, call_refer_params.CallReferParams),
    def reject(
        status_code: int | Omit = omit,
        Decline an incoming SIP call by returning a SIP status code to the caller.
          status_code: SIP response code to send back to the caller. Defaults to `603` (Decline) when
              omitted.
            path_template("/realtime/calls/{call_id}/reject", call_id=call_id),
            body=maybe_transform({"status_code": status_code}, call_reject_params.CallRejectParams),
class AsyncCalls(AsyncAPIResource):
    def with_raw_response(self) -> AsyncCallsWithRawResponse:
        return AsyncCallsWithRawResponse(self)
    def with_streaming_response(self) -> AsyncCallsWithStreamingResponse:
        return AsyncCallsWithStreamingResponse(self)
    async def accept(
    async def hangup(
    async def refer(
            body=await async_maybe_transform({"target_uri": target_uri}, call_refer_params.CallReferParams),
    async def reject(
            body=await async_maybe_transform({"status_code": status_code}, call_reject_params.CallRejectParams),
class CallsWithRawResponse:
    def __init__(self, calls: Calls) -> None:
        self._calls = calls
            calls.create,
        self.accept = _legacy_response.to_raw_response_wrapper(
            calls.accept,
        self.hangup = _legacy_response.to_raw_response_wrapper(
            calls.hangup,
        self.refer = _legacy_response.to_raw_response_wrapper(
            calls.refer,
        self.reject = _legacy_response.to_raw_response_wrapper(
            calls.reject,
class AsyncCallsWithRawResponse:
    def __init__(self, calls: AsyncCalls) -> None:
        self.accept = _legacy_response.async_to_raw_response_wrapper(
        self.hangup = _legacy_response.async_to_raw_response_wrapper(
        self.refer = _legacy_response.async_to_raw_response_wrapper(
        self.reject = _legacy_response.async_to_raw_response_wrapper(
class CallsWithStreamingResponse:
        self.accept = to_streamed_response_wrapper(
        self.hangup = to_streamed_response_wrapper(
        self.refer = to_streamed_response_wrapper(
        self.reject = to_streamed_response_wrapper(
class AsyncCallsWithStreamingResponse:
        self.accept = async_to_streamed_response_wrapper(
        self.hangup = async_to_streamed_response_wrapper(
        self.refer = async_to_streamed_response_wrapper(
        self.reject = async_to_streamed_response_wrapper(
            f"/realtime/calls/{call_id}/accept",
            f"/realtime/calls/{call_id}/hangup",
            f"/realtime/calls/{call_id}/refer",
            f"/realtime/calls/{call_id}/reject",
