from ..completion_usage import CompletionUsage
from .chat_completion_message import ChatCompletionMessage
from .chat_completion_token_logprob import ChatCompletionTokenLogprob
__all__ = ["ChatCompletion", "Choice", "ChoiceLogprobs"]
class ChoiceLogprobs(BaseModel):
    """Log probability information for the choice."""
    content: Optional[List[ChatCompletionTokenLogprob]] = None
    """A list of message content tokens with log probability information."""
    refusal: Optional[List[ChatCompletionTokenLogprob]] = None
    """A list of message refusal tokens with log probability information."""
class Choice(BaseModel):
    finish_reason: Literal["stop", "length", "tool_calls", "content_filter", "function_call"]
    reached, `content_filter` if content was omitted due to a flag from our content
    filters, `tool_calls` if the model called a tool, or `function_call`
    (deprecated) if the model called a function.
    """The index of the choice in the list of choices."""
    logprobs: Optional[ChoiceLogprobs] = None
    """A chat completion message generated by the model."""
class ChatCompletion(BaseModel):
    Represents a chat completion response returned by model, based on the provided input.
    """A unique identifier for the chat completion."""
    choices: List[Choice]
    """A list of chat completion choices.
    Can be more than one if `n` is greater than 1.
    """The Unix timestamp (in seconds) of when the chat completion was created."""
    """The model used for the chat completion."""
    object: Literal["chat.completion"]
    """The object type, which is always `chat.completion`."""
    service_tier: Optional[Literal["auto", "default", "flex", "scale", "priority"]] = None
    """Specifies the processing type used for serving the request.
# Inference code generated from the JSON schema spec in @huggingface/tasks.
#   - script: https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/scripts/inference-codegen.ts
#   - specs:  https://github.com/huggingface/huggingface.js/tree/main/packages/tasks/src/tasks.
from typing import Any, Literal, Optional, Union
from .base import BaseInferenceType, dataclass_with_extra
@dataclass_with_extra
class ChatCompletionInputURL(BaseInferenceType):
ChatCompletionInputMessageChunkType = Literal["text", "image_url"]
class ChatCompletionInputMessageChunk(BaseInferenceType):
    type: "ChatCompletionInputMessageChunkType"
    image_url: Optional[ChatCompletionInputURL] = None
class ChatCompletionInputFunctionDefinition(BaseInferenceType):
    parameters: Any
class ChatCompletionInputToolCall(BaseInferenceType):
    function: ChatCompletionInputFunctionDefinition
class ChatCompletionInputMessage(BaseInferenceType):
    content: Optional[Union[list[ChatCompletionInputMessageChunk], str]] = None
    tool_calls: Optional[list[ChatCompletionInputToolCall]] = None
class ChatCompletionInputJSONSchema(BaseInferenceType):
    The name of the response format.
    schema: Optional[dict[str, object]] = None
class ChatCompletionInputResponseFormatText(BaseInferenceType):
class ChatCompletionInputResponseFormatJSONSchema(BaseInferenceType):
    json_schema: ChatCompletionInputJSONSchema
class ChatCompletionInputResponseFormatJSONObject(BaseInferenceType):
ChatCompletionInputGrammarType = Union[
class ChatCompletionInputStreamOptions(BaseInferenceType):
    include_usage: Optional[bool] = None
    """If set, an additional chunk will be streamed before the data: [DONE] message. The usage
    field on this chunk shows the token usage statistics for the entire request, and the
    choices field will always be an empty array. All other chunks will also include a usage
    field, but with a null value.
class ChatCompletionInputFunctionName(BaseInferenceType):
class ChatCompletionInputToolChoiceClass(BaseInferenceType):
    function: ChatCompletionInputFunctionName
ChatCompletionInputToolChoiceEnum = Literal["auto", "none", "required"]
class ChatCompletionInputTool(BaseInferenceType):
class ChatCompletionInput(BaseInferenceType):
    """Chat Completion Input.
    Auto-generated from TGI specs.
    For more details, check out
    https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/scripts/inference-tgi-import.ts.
    messages: list[ChatCompletionInputMessage]
    """A list of messages comprising the conversation so far."""
    frequency_penalty: Optional[float] = None
    """Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing
    frequency in the text so far,
    decreasing the model's likelihood to repeat the same line verbatim.
    logit_bias: Optional[list[float]] = None
    """UNUSED
    Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON
    object that maps tokens
    (specified by their token ID in the tokenizer) to an associated bias value from -100 to
    100. Mathematically,
    the bias is added to the logits generated by the model prior to sampling. The exact
    effect will vary per model,
    but values between -1 and 1 should decrease or increase likelihood of selection; values
    like -100 or 100 should
    result in a ban or exclusive selection of the relevant token.
    logprobs: Optional[bool] = None
    """Whether to return log probabilities of the output tokens or not. If true, returns the log
    probabilities of each
    output token returned in the content of message.
    """The maximum number of tokens that can be generated in the chat completion."""
    """[UNUSED] ID of the model to use. See the model endpoint compatibility table for details
    on which models work with the Chat API.
    How many chat completion choices to generate for each input message. Note that you will
    be charged based on the
    number of generated tokens across all of the choices. Keep n as 1 to minimize costs.
    presence_penalty: Optional[float] = None
    """Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they
    appear in the text so far,
    increasing the model's likelihood to talk about new topics
    response_format: Optional[ChatCompletionInputGrammarType] = None
    stop: Optional[list[str]] = None
    """Up to 4 sequences where the API will stop generating further tokens."""
    stream_options: Optional[ChatCompletionInputStreamOptions] = None
    """What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the
    output more random, while
    lower values like 0.2 will make it more focused and deterministic.
    tool_choice: Optional[Union[ChatCompletionInputToolChoiceClass, "ChatCompletionInputToolChoiceEnum"]] = None
    tool_prompt: Optional[str] = None
    """A prompt to be appended before the tools"""
    tools: Optional[list[ChatCompletionInputTool]] = None
    """A list of tools the model may call. Currently, only functions are supported as a tool.
    Use this to provide a list of
    functions the model may generate JSON inputs for.
    """An integer between 0 and 5 specifying the number of most likely tokens to return at each
    token position, each with
    an associated log probability. logprobs must be set to true if this parameter is used.
    """An alternative to sampling with temperature, called nucleus sampling, where the model
    considers the results of the
    tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10%
    probability mass are considered.
class ChatCompletionOutputTopLogprob(BaseInferenceType):
class ChatCompletionOutputLogprob(BaseInferenceType):
    top_logprobs: list[ChatCompletionOutputTopLogprob]
class ChatCompletionOutputLogprobs(BaseInferenceType):
    content: list[ChatCompletionOutputLogprob]
class ChatCompletionOutputFunctionDefinition(BaseInferenceType):
class ChatCompletionOutputToolCall(BaseInferenceType):
    function: ChatCompletionOutputFunctionDefinition
class ChatCompletionOutputMessage(BaseInferenceType):
    reasoning: Optional[str] = None
    tool_call_id: Optional[str] = None
    tool_calls: Optional[list[ChatCompletionOutputToolCall]] = None
class ChatCompletionOutputComplete(BaseInferenceType):
    message: ChatCompletionOutputMessage
    logprobs: Optional[ChatCompletionOutputLogprobs] = None
class ChatCompletionOutputUsage(BaseInferenceType):
class ChatCompletionOutput(BaseInferenceType):
    """Chat Completion Output.
    choices: list[ChatCompletionOutputComplete]
    system_fingerprint: str
    usage: ChatCompletionOutputUsage
class ChatCompletionStreamOutputFunction(BaseInferenceType):
class ChatCompletionStreamOutputDeltaToolCall(BaseInferenceType):
    function: ChatCompletionStreamOutputFunction
class ChatCompletionStreamOutputDelta(BaseInferenceType):
    tool_calls: Optional[list[ChatCompletionStreamOutputDeltaToolCall]] = None
class ChatCompletionStreamOutputTopLogprob(BaseInferenceType):
class ChatCompletionStreamOutputLogprob(BaseInferenceType):
    top_logprobs: list[ChatCompletionStreamOutputTopLogprob]
class ChatCompletionStreamOutputLogprobs(BaseInferenceType):
    content: list[ChatCompletionStreamOutputLogprob]
class ChatCompletionStreamOutputChoice(BaseInferenceType):
    delta: ChatCompletionStreamOutputDelta
    finish_reason: Optional[str] = None
    logprobs: Optional[ChatCompletionStreamOutputLogprobs] = None
class ChatCompletionStreamOutputUsage(BaseInferenceType):
class ChatCompletionStreamOutput(BaseInferenceType):
    """Chat Completion Stream Output.
    choices: list[ChatCompletionStreamOutputChoice]
    usage: Optional[ChatCompletionStreamOutputUsage] = None
