# -*- coding: utf-8 -*-
# Configuration file for the Sphinx documentation builder.
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config
# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('../'))
#sys.path.insert(0, os.path.abspath('../pyautogui'))
# -- Project information -----------------------------------------------------
project = 'PyAutoGUI'
copyright = '2019, Al Sweigart'
author = 'Al Sweigart'
# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''
# -- General configuration ---------------------------------------------------
# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'
# The master toctree document.
master_doc = 'index'
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
# -- Options for HTML output -------------------------------------------------
# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
# html_sidebars = {}
# -- Options for HTMLHelp output ---------------------------------------------
# Output file base name for HTML help builder.
htmlhelp_basename = 'PyAutoGUIdoc'
# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'PyAutoGUI.tex', 'PyAutoGUI Documentation',
     'Al Sweigart', 'manual'),
# -- Options for manual page output ------------------------------------------
# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'pyautogui', 'PyAutoGUI Documentation',
     [author], 1)
# -- Options for Texinfo output ----------------------------------------------
# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'PyAutoGUI', 'PyAutoGUI Documentation',
     author, 'PyAutoGUI', 'One line description of project.',
     'Miscellaneous'),
# tweepy documentation build configuration file, created by
# sphinx-quickstart on Sun Dec  6 11:13:52 2009.
# This file is execfile()d with the current directory set to its containing dir.
# Note that not all possible configuration values are present in this
# autogenerated file.
# All configuration values have a default; values that are commented out
# serve to show the default.
sys.path.append(os.path.abspath('.'))
sys.path.append(os.path.abspath('..'))
# Set canonical URL from the Read the Docs Domain
html_baseurl = os.environ.get("READTHEDOCS_CANONICAL_URL", "")
html_context = {}
# Tell Jinja2 templates the build is running on Read the Docs
if os.environ.get("READTHEDOCS", "") == "True":
    html_context["READTHEDOCS"] = True
# -- General configuration -----------------------------------------------------
# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
  'hoverxref.extension',
  'myst_parser',
  'sphinx.ext.autosectionlabel',
  'sphinx.ext.intersphinx',
  'sphinx.ext.napoleon',
  'sphinx_search.extension',
  'sphinx_tabs.tabs'
hoverxref_auto_ref = True
hoverxref_domains = ['py']
hoverxref_intersphinx = ['aiohttp', 'requests', 'requests_oauthlib']
autoclass_content = "both"
intersphinx_mapping = {
  'python': ('https://docs.python.org/3', None),
  'aiohttp': ('https://docs.aiohttp.org/en/stable/', None),
  'requests': ('https://requests.readthedocs.io/en/stable/', None),
  'requests_oauthlib': (
    'https://requests-oauthlib.readthedocs.io/en/latest/', None
rst_prolog = """
.. |coroutine| replace:: This function is a coroutine_.
.. _coroutine: https://docs.python.org/3/library/asyncio-task.html#coroutine
#templates_path = ['_templates']
# The suffix of source filenames.
# The encoding of source files.
#source_encoding = 'utf-8'
# General information about the project.
project = 'tweepy'
copyright = '2009-2023, Joshua Roesslein'
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
# The short X.Y version.
sys.path.insert(0, '..')
from tweepy import __version__
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__
#language = None
locale_dirs = ['locale/']
# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'
# List of documents that shouldn't be included in the build.
#unused_docs = []
# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = ['_build']
# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None
# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True
# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True
# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False
# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []
# -- Options for HTML output ---------------------------------------------------
# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
#html_theme_options = {}
# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []
# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None
# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None
# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None
# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None
html_js_files = ['expand_tabs.js']
# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'
# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True
# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}
# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}
# If false, no module index is generated.
html_use_modindex = True
# If false, no index is generated.
#html_use_index = True
# If true, the index is split into individual pages for each letter.
#html_split_index = False
# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True
# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''
# If nonempty, this is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = ''
htmlhelp_basename = 'tweepydoc'
# -- Options for LaTeX output --------------------------------------------------
# The paper size ('letter' or 'a4').
#latex_paper_size = 'letter'
#latex_font_size = '10pt'
# (source start file, target name, title, author, documentclass [howto/manual]).
  ('index', 'tweepy.tex', 'tweepy Documentation',
   'Joshua Roesslein', 'manual'),
# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None
# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False
#latex_preamble = ''
# Documents to append as an appendix to all manuals.
#latex_appendices = []
#latex_use_modindex = True
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
sys.path.insert(0, os.path.abspath('..'))
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
project = 'Instaloader'
copyright = '2023, Alexander Graf and Andre Koch-Kramer'
author = 'Alexander Graf and Andre Koch-Kramer'
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration
    "sphinx.ext.autodoc",
    "sphinx.ext.extlinks",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "sphinxcontrib.jquery",
# autodoc options
autodoc_default_options = {
    'show-inheritance': True,
    'members': True,
    'undoc-members': True,
# extlinks options
extlinks = {
    'issue': (
        'https://github.com/instaloader/instaloader/issues/%s',
        'Issue #%s'
    'example': (
        'https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/%s',
        'Example %s'
# intersphinx options
    'requests': ('https://requests.readthedocs.io/en/latest/', None),
# other options
# ignore TypeVar as it is currently unsupported by Sphinx
nitpick_ignore = [('py:class', 'instaloader.nodeiterator.T')]
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
pygments_style = 'fruity'
html_theme = 'basic'
html_logo = "logo.png"
html_css_files = ['instaloaderdoc.css']
html_js_files = ['instaloaderdoc.js']
# get release number
current_release = subprocess.check_output(["git", "describe", "--abbrev=0"]).decode("ascii")[1:-1]
date_format = "%e %b %Y" if platform.system() != "Windows" else "%d %b %Y"
current_release_date = subprocess.check_output(
    ["git", "log", "-1", "--tags", "--format=%ad", "--date=format:"+date_format]).decode("ascii")[:-1]
html_context = {'current_release': current_release, 'current_release_date': current_release_date}
# Jupyter Notebook documentation build configuration file, created by
# sphinx-quickstart on Mon Apr 13 09:51:11 2015.
# This file is execfile()d with the current directory set to its
# containing dir.
logger = logging.getLogger(__name__)
logging.basicConfig()
# DEBUG for RTD
logger.info("DEBUG:: sys.path")
logger.info("================")
for item in sys.path:
    logger.info(item)
# add repo root to sys.path
# here = root/docs/source
here = os.path.abspath(os.path.dirname(__file__))
repo_root = os.path.dirname(os.path.dirname(here))
sys.path.insert(0, repo_root)
# Copy the markdown file here
shutil.copy(os.path.join(repo_root, "CHANGELOG.md"), os.path.join(here, "changelog.md"))
# Copy the contributing file here
shutil.copy(os.path.join(repo_root, "CONTRIBUTING.md"), os.path.join(here, "contributing.md"))
logger.info("repo_root")
logger.info("=====================")
logger.info(repo_root)
# DEBUG for post insert on RTD
logger.info("DEBUG:: Post insert to sys.path")
logger.info("===============================")
# -- General configuration ------------------------------------------------
    "sphinx.ext.doctest",
    "sphinx.ext.autosummary",
    "sphinx.ext.mathjax",
    "IPython.sphinxext.ipython_console_highlighting",
    "nbsphinx",
    "sphinxcontrib_github_alt",
    "myst_parser",
    import enchant  # noqa: F401
    extensions += ["sphinxcontrib.spelling"]
myst_enable_extensions = ["html_image"]
myst_update_mathjax = False
templates_path = ["_templates"]
# source_encoding = 'utf-8-sig'
master_doc = "index"
project = "Jupyter Notebook"
copyright = "2015, Jupyter Team, https://jupyter.org"
author = "The Jupyter Team"
# ghissue config
github_project_url = "https://github.com/jupyter/notebook"
_version_py = os.path.join(here, "../../notebook/_version.py")
version_ns = {}
exec(compile(open(_version_py).read(), _version_py, "exec"), version_ns)  # noqa: S102, SIM115
version = "{}.{}".format(*version_ns["version_info"][:2])
release = version_ns["__version__"]
language = "en"
# today = ''
# today_fmt = '%B %d, %Y'
exclude_patterns = [
    "examples/Notebook/.ipynb_checkpoints",
    "examples/Notebook/nbpackage/*.ipynb",
    "examples/Notebook/nbpackage/nbs/*.ipynb",
# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None
# add_function_parentheses = True
# add_module_names = True
# show_authors = False
pygments_style = "sphinx"
# modindex_common_prefix = []
# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False
# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False
# -- Options for HTML output ----------------------------------------------
html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "header_links_before_dropdown": 5,
    "icon_links": [
            "name": "jupyter.org",
            "url": "https://jupyter.org",
            "icon": "_static/jupyter_logo.svg",
            "type": "local",
            "name": "GitHub",
            "url": "https://github.com/jupyter/notebook",
            "icon": "fab fa-github-square",
            "name": "Discourse",
            "url": "https://discourse.jupyter.org/c/notebook/31",
            "icon": "fab fa-discourse",
            "name": "Zulip",
            "url": "https://jupyter.zulipchat.com/",
            "icon": "_static/zulip-icon-square.svg",
    "logo": {
        "alt_text": "Jupyter",
        "image_light": "_static/logo-rectangle.svg",
        "image_dark": "_static/logo-rectangle-dark.svg",
    "use_edit_page_button": True,
    "navigation_with_keys": False,
# Output for github to be used in links
html_context = {
    "github_user": "jupyter",  # Username
    "github_repo": "notebook",  # Repo name
    "github_version": "main",  # Version
    "doc_path": "docs/source/",  # Path in the checkout to the docs root
# html_theme_path = []
# html_title = None
# html_short_title = None
html_logo = "examples/images/jupyter_logo.png"
# html_favicon = None
# NOTE: Sphinx's 'make html' builder will throw a warning about an unfound
#       _static directory. Do not remove or comment out html_static_path
#       since it is needed to properly generate _static in the build directory
html_static_path = ["_static"]
# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []
# html_last_updated_fmt = '%b %d, %Y'
# html_use_smartypants = True
# html_additional_pages = {}
# html_domain_indices = True
# html_use_index = True
# html_split_index = False
# html_show_sourcelink = True
# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True
# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True
# html_use_opensearch = ''
# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None
# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr'
# html_search_language = 'en'
# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}
# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'
htmlhelp_basename = "JupyterNotebookdoc"
# This will ensure that we use the correctly set environment for canonical URLs
# Old Read the Docs injections makes it point only to the default version,
# for instance /en/stable/
html_baseurl = os.environ.get("READTHEDOCS_CANONICAL_URL", "/")
# -- Options for LaTeX output ---------------------------------------------
latex_elements = {}
        master_doc,
        "JupyterNotebook.tex",
        "Jupyter Notebook Documentation",
        "https://jupyter.org",
        "manual",
# latex_logo = None
# latex_use_parts = False
# If true, show page references after internal links.
# latex_show_pagerefs = False
# If true, show URL addresses after external links.
# latex_show_urls = False
# latex_appendices = []
# latex_domain_indices = True
# -- Options for manual page output ---------------------------------------
man_pages = [(master_doc, "jupyternotebook", "Jupyter Notebook Documentation", [author], 1)]
# man_show_urls = False
# -- Options for link checks ----------------------------------------------
linkcheck_ignore = [r"http://127\.0\.0\.1/*"]
# -- Options for Texinfo output -------------------------------------------
        "JupyterNotebook",
        author,
        "One line description of project.",
        "Miscellaneous",
# texinfo_appendices = []
# texinfo_domain_indices = True
# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'
# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False
    "ipython": ("https://ipython.readthedocs.io/en/stable/", None),
    "nbconvert": ("https://nbconvert.readthedocs.io/en/latest/", None),
    "nbformat": ("https://nbformat.readthedocs.io/en/latest/", None),
    "jupyter": ("https://jupyter.readthedocs.io/en/latest/", None),
spelling_lang = "en_US"
spelling_word_list_filename = "spelling_wordlist.txt"
def setup(app):
    app.add_css_file("https://docs.jupyter.org/en/latest/_static/jupyter.css")
# Dropbox for Python documentation build configuration file, created by
# sphinx-quickstart on Fri Oct 24 13:42:45 2014.
# Assumes that the dropbox package to generate docs for is one-level above in
# the directory hierarchy. This takes precendence over other dropbox packages
# that may be in the sys.path.
import dropbox
#sys.path.insert(0, os.path.abspath('.'))
#needs_sphinx = '1.0'
    'sphinx.ext.mathjax',
    'sphinx_rtd_theme',
#source_encoding = 'utf-8-sig'
project = u'Dropbox for Python'
copyright = u'2015-2024, Dropbox, Inc.'
version = dropbox.__version__
release = dropbox.__version__
exclude_patterns = ['_build']
#keep_warnings = False
#html_extra_path = []
#html_domain_indices = True
#html_show_sphinx = True
#html_show_copyright = True
#html_file_suffix = None
htmlhelp_basename = 'DropboxforPythondoc'
#latex_elements = {
#'papersize': 'letterpaper',
#'pointsize': '10pt',
#'preamble': '',
#}
#latex_documents = [
#  ('index2', 'DropboxforPython.tex', u'Dropbox for Python Documentation',
#   u'Ken Elkabany', 'manual'),
#]
#latex_show_pagerefs = False
#latex_show_urls = False
#latex_domain_indices = True
#man_pages = [
#    ('index2', 'dropboxforpython', u'Dropbox for Python Documentation',
#     [u'Dropbox, Inc.'], 1)
#man_show_urls = False
#texinfo_documents = [
#  ('index2', 'DropboxforPython', u'Dropbox for Python Documentation',
#   u'Dropbox, Inc.', 'DropboxforPython', 'One line description of project.',
#   'Miscellaneous'),
#texinfo_appendices = []
#texinfo_domain_indices = True
#texinfo_show_urls = 'footnote'
#texinfo_no_detailmenu = False
# PyInstaller documentation build configuration file, created by
# sphinx-quickstart on Sun Mar 27 16:53:34 2016.
sys.path.insert(1, os.path.abspath('..'))
from help2rst import parser_to_rst  # noqa: E402
from PyInstaller.__main__ import generate_parser  # noqa: E402
from PyInstaller.utils.cliutils import makespec  # noqa: E402
# --  PyInstaller HACK -----------------------------------------------
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
if on_rtd:
    # running on 'Read the Docs'
    # Read the Docs is adding stuff to this file when building the
    # docs, thus the repository is modified. Remove this marker.
    if __version__.endswith('.mod'):
        __version__ = __version__[:-4]
# -- Generate CLI docs ----------------------------------------------------
# Generate CLI references for ``pyinstaller`` and ``pyi-makespec``.
# Only the first goes in the main docs with hyperref targets enabled.
# Both references are copied into the man pages but without creating hyperref
# targets (or we'd get 100s of duplicate reference errors).
for (contents, path) in [
    (parser_to_rst(generate_parser()),
     "_pyinstaller-options.tmp"),
    (parser_to_rst(generate_parser(), cross_references=False),
     "man/_pyinstaller-options.tmp"),
    (parser_to_rst(makespec.generate_parser(), cross_references=False),
     "man/_pyi-makespec-options.tmp"),
    # Avoid rewriting if no changes made. Otherwise sphinx mistakenly thinks
    # its build cache needs refreshing.
    path = Path(path)
    if not path.exists() or path.read_text() != contents:
        path.write_text(contents)
extensions = ['sphinx.ext.intersphinx',
              'sphinx_autodoc_typehints',
              'sphinxcontrib.towncrier',
              'sphinx_copybutton',
              'sphinx_inline_tabs',
              'sphinx_issues']
issues_github_path = "pyinstaller/pyinstaller"
    'matplotlib': ('https://matplotlib.org/stable/', None),
# Autodoc cross references which don't exist and should not be warned about.
nitpick_ignore = [
    ("envvar", "CC"),
    # Only applicable to AIX
    ("envvar", "OBJECT_MODE"),
    # TODO: Create autodoc-ed API references for these so that they can be
    #       cross referenced properly.
    ("py:mod", "Splash"),
    ("py:class", "TOC"),
# Don't include a preview if there are no news items. i.e. towncrier has already been ran.
towncrier_draft_include_empty = False
towncrier_draft_working_directory = os.path.abspath('..')
project = 'PyInstaller'
copyright = 'This document has been placed in the public domain.'
author = "David Cortesi, based on structure by Giovanni Bajo & William Caban based on Gordon McMillan's manual"
language = 'en'
today_fmt = '%Y-%m-%d'
exclude_patterns = ['_build', 'tools', 'source']
add_module_names = False
import sphinx_rtd_theme
    app.add_css_file('css/pyinstaller.css')
html_logo = '_static/pyinstaller-draft1a-100_trans.png'
html_favicon = '_static/pyinstaller-draft1a.ico'
# html_last_updated_fmt = '%Y-%m-%d %H:%M UTC"
htmlhelp_basename = 'PyInstallerdoc'
# Define the canonical URL if you are using a custom domain on Read the Docs
    html_context = {"READTHEDOCS": True}
    (master_doc, 'PyInstaller.tex', 'PyInstaller Documentation',
     'David Cortesi', 'manual'),
    ('man/pyinstaller', 'pyinstaller',
     'Configure and build a PyInstaller project in one run',
     ['Hartmut Goebel'], 1),
    ('man/pyi-makespec', 'pyi-makespec',
     'Create a spec file for your PyInstaller project',
     ['Hartmut Goebel'], 1)
# -- config prior to switching to sphinx
# source-link: off
# generator: off
# datestamp:
    (master_doc, 'PyInstaller', 'PyInstaller Documentation',
     author, 'PyInstaller', 'One line description of project.',
# -- Options for Epub output ----------------------------------------------
# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright
# The basename for the epub file. It defaults to the project name.
# epub_basename = project
# The HTML theme for the epub output. Since the default themes are not optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
# epub_theme = 'epub'
# The language of the text. It defaults to the language option
# or 'en' if the language is not set.
# epub_language = ''
# The scheme of the identifier. Typical schemes are ISBN or URL.
# epub_scheme = ''
# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
# epub_identifier = ''
# A unique identification for the text.
# epub_uid = ''
# A tuple containing the cover image and cover page html template filenames.
# epub_cover = ()
# A sequence of (type, uri, title) tuples for the guide element of content.opf.
# epub_guide = ()
# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_pre_files = []
# HTML files shat should be inserted after the pages created by sphinx.
# epub_post_files = []
# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']
# The depth of the table of contents in toc.ncx.
# epub_tocdepth = 3
# Allow duplicate toc entries.
# epub_tocdup = True
# Choose between 'default' and 'includehidden'.
# epub_tocscope = 'default'
# Fix unsupported image types using the Pillow.
# epub_fix_images = False
# Scale large images.
# epub_max_image_width = 0
# epub_show_urls = 'inline'
# epub_use_index = True
# Pyinstaller Sphinx hook test documentation build configuration file, created by
# sphinx-quickstart on Tue Jun 30 07:56:01 2015.
project = u'Pyinstaller Sphinx hook test'
copyright = u'2012-2015, Bryan A. Jones'
author = u'Bryan A. Jones'
version = '0.0'
release = '0.0'
language = 'fr'
    # try to use optional theme
    import alabaster
    html_theme = 'alabaster'
    html_theme = 'default'
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#html_search_language = 'en'
#html_search_options = {'type': 'default'}
#html_search_scorer = 'scorer.js'
htmlhelp_basename = 'PyinstallerSphinxhooktestdoc'
#'figure_align': 'htbp',
  (master_doc, 'PyinstallerSphinxhooktest.tex', u'Pyinstaller Sphinx hook test Documentation',
   u'Bryan A. Jones', 'manual'),
    (master_doc, 'pyinstallersphinxhooktest', u'Pyinstaller Sphinx hook test Documentation',
  (master_doc, 'PyinstallerSphinxhooktest', u'Pyinstaller Sphinx hook test Documentation',
   author, 'PyinstallerSphinxhooktest', 'One line description of project.',
"""Functions for use in URLsconfs."""
    RegexPattern,
    RoutePattern,
def include(arg, namespace=None):
    if isinstance(arg, tuple):
        # Callable returning a namespace hint.
            urlconf_module, app_name = arg
            if namespace:
                    "Cannot override the namespace for a dynamic module that "
                    "provides a namespace."
                "Passing a %d-tuple to include() is not supported. Pass a "
                "2-tuple containing the list of patterns and app_name, and "
                "provide the namespace argument to include() instead." % len(arg)
        # No namespace hint - use manually provided namespace.
        urlconf_module = arg
    if isinstance(urlconf_module, str):
        urlconf_module = import_module(urlconf_module)
    patterns = getattr(urlconf_module, "urlpatterns", urlconf_module)
    app_name = getattr(urlconf_module, "app_name", app_name)
    if namespace and not app_name:
            "Specifying a namespace in include() without providing an app_name "
            "is not supported. Set the app_name attribute in the included "
            "module, or pass a 2-tuple containing the list of patterns and "
            "app_name instead.",
    namespace = namespace or app_name
    # Make sure the patterns can be iterated through (without this, some
    # testcases will break).
    if isinstance(patterns, (list, tuple)):
        for url_pattern in patterns:
            pattern = getattr(url_pattern, "pattern", None)
            if isinstance(pattern, LocalePrefixPattern):
                    "Using i18n_patterns in an included URLconf is not allowed."
    return (urlconf_module, app_name, namespace)
def _path(route, view, kwargs=None, name=None, Pattern=None):
    from django.views import View
    if kwargs is not None and not isinstance(kwargs, dict):
            f"kwargs argument must be a dict, but got {kwargs.__class__.__name__}."
    if isinstance(view, (list, tuple)):
        # For include(...) processing.
        pattern = Pattern(route, is_endpoint=False)
        urlconf_module, app_name, namespace = view
        return URLResolver(
            urlconf_module,
            app_name=app_name,
            namespace=namespace,
    elif callable(view):
        pattern = Pattern(route, name=name, is_endpoint=True)
        return URLPattern(pattern, view, kwargs, name)
    elif isinstance(view, View):
        view_cls_name = view.__class__.__name__
            f"view must be a callable, pass {view_cls_name}.as_view(), not "
            f"{view_cls_name}()."
            "view must be a callable or a list/tuple in the case of include()."
path = partial(_path, Pattern=RoutePattern)
re_path = partial(_path, Pattern=RegexPattern)
# Django documentation build configuration file, created by
# sphinx-quickstart on Thu Mar 27 09:06:53 2008.
# This file is execfile()d with the current directory set to its containing
# dir.
# The contents of this file are pickled, so don't put values in the namespace
# that aren't picklable (module imports are okay, they're removed
# automatically).
from os.path import abspath, dirname, join
from sphinx import version_info as sphinx_version
# Workaround for sphinx-build recursion limit overflow:
# pickle.dump(doctree, f, pickle.HIGHEST_PROTOCOL)
#  RuntimeError: maximum recursion depth exceeded while pickling an object
# Python's default allowed recursion depth is 1000 but this isn't enough for
# building docs/ref/settings.txt sometimes.
# https://groups.google.com/g/sphinx-dev/c/MtRf64eGtv4/discussion
sys.setrecursionlimit(2000)
# Make sure we get the version of this copy of Django
sys.path.insert(1, dirname(dirname(abspath(__file__))))
sys.path.append(abspath(join(dirname(__file__), "_ext")))
# Use the module to GitHub url resolver, but import it after the _ext directoy
# it lives in has been added to sys.path.
import github_links  # NOQA
# -- General configuration --
needs_sphinx = "4.5.0"
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
    "djangodocs",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.linkcode",
# AutosectionLabel settings.
# Uses a <page>:<label> schema which doesn't work for duplicate sub-section
# labels, so set max depth.
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 2
# Linkcheck settings.
linkcheck_ignore = [
    # Special-use addresses and domain names. (RFC 6761/6890)
    r"^https?://(?:127\.0\.0\.1|\[::1\])(?::\d+)?/",
    r"^https?://(?:[^/.]+\.)*example\.(?:com|net|org)(?::\d+)?/",
    r"^https?://(?:[^/.]+\.)*(?:example|invalid|localhost|test)(?::\d+)?/",
    # Pages that are inaccessible because they require authentication.
    r"^https://github\.com/[^/]+/[^/]+/fork",
    r"^https://code\.djangoproject\.com/github/login",
    r"^https://code\.djangoproject\.com/newticket",
    r"^https://(?:code|www)\.djangoproject\.com/admin/",
    r"^https://www\.djangoproject\.com/community/add/blogs/",
    r"^https://www\.google\.com/webmasters/tools/ping",
    r"^https://search\.google\.com/search-console/welcome",
    # Fragments used to dynamically switch content or populate fields.
    r"^https://web\.libera\.chat/#",
    r"^https://github\.com/[^#]+#L\d+-L\d+$",
    r"^https://help\.apple\.com/itc/podcasts_connect/#/itc",
    # Anchors on certain pages with missing a[name] attributes.
    r"^https://tools\.ietf\.org/html/rfc1123\.html#section-",
# Spelling check needs an additional module that is not installed by default.
# Add it only if spelling check is requested so docs can be generated without
if "spelling" in sys.argv:
    extensions.append("sphinxcontrib.spelling")
# Spelling language.
# Location of word list.
spelling_word_list_filename = "spelling_wordlist"
spelling_warning = True
# templates_path = []
source_suffix = {".txt": "restructuredtext"}
# The root toctree document.
root_doc = "contents"
# Disable auto-created table of contents entries for all domain objects (e.g.
# functions, classes, attributes, etc.) in Sphinx 5.2+.
toc_object_entries = False
# General substitutions.
project = "Django"
copyright = "Django Software Foundation and contributors"
version = "6.1"
    from django import VERSION, get_version
    release = version
    def django_release():
        pep440ver = get_version()
        if VERSION[3:5] == ("alpha", 0) and "dev" not in pep440ver:
            return pep440ver + ".dev"
        return pep440ver
    release = django_release()
# The "development version" of Django
django_next_version = "6.1"
    "bpo": ("https://bugs.python.org/issue?@action=redirect&bpo=%s", "bpo-%s"),
    "commit": ("https://github.com/django/django/commit/%s", "%s"),
    "pypi": ("https://pypi.org/project/%s/", "%s"),
    # A file or directory. GitHub redirects from blob to tree if needed.
    "source": ("https://github.com/django/django/blob/main/%s", "%s"),
    "ticket": ("https://code.djangoproject.com/ticket/%s", "#%s"),
if sphinx_version < (8, 1):
    extlinks["cve"] = ("https://www.cve.org/CVERecord?id=CVE-%s", "CVE-%s")
# language = None
# Location for .po/.mo translation files used when language is set
locale_dirs = ["locale/"]
today_fmt = "%B %d, %Y"
exclude_patterns = ["_build", "_theme", "requirements.txt"]
default_role = "default-role-error"
add_function_parentheses = True
show_authors = False
pygments_style = "trac"
# Links to Python's docs should reference the most recent version of the 3.x
# branch, which is located at this URL.
    "python": ("https://docs.python.org/3", None),
    "sphinx": ("https://www.sphinx-doc.org/en/master", None),
    "psycopg": ("https://www.psycopg.org/psycopg3/docs", None),
# Python's docs don't change every week.
intersphinx_cache_limit = 90  # days
# The 'versionadded' and 'versionchanged' directives are overridden.
suppress_warnings = ["app.add_directive", "epub.duplicated_toc_entry"]
# -- Options for HTML output --
# The theme to use for HTML and HTML Help pages. See the documentation for
html_theme = "djangodocs"
# further. For a list of options available for each theme, see the
html_theme_path = ["_theme"]
# The name for this set of Sphinx documents. If None, it defaults to
# A shorter title for the navigation bar. Default is the same as html_title.
# html_logo = None
# docs. This file should be a Windows icon file (.ico) being 16x16 or 32x32
# html_static_path = ["_static"]
html_last_updated_fmt = "%b %d, %Y"
# Content template for the index page.
# html_index = ''
html_additional_pages = {}
# contain a <link> tag referring to it. The value of this option must be the
htmlhelp_basename = "Djangodoc"
modindex_common_prefix = ["django."]
# Appended to every page
rst_epilog = """
.. |django-users| replace:: :ref:`django-users <django-users-mailing-list>`
.. |django-developers| replace:: :ref:`django-developers <django-developers-mailing-list>`
.. |django-announce| replace:: :ref:`django-announce <django-announce-mailing-list>`
.. |django-updates| replace:: :ref:`django-updates <django-updates-mailing-list>`
"""  # NOQA
# -- Options for LaTeX output --
# Use XeLaTeX for Unicode support.
latex_engine = "xelatex"
latex_use_xindy = False
# Set font for CJK and fallbacks for unicode characters.
    "fontpkg": r"""
        \setmainfont{Symbola}
    "preamble": r"""
        \usepackage[UTF8]{ctex}
        \xeCJKDeclareCharClass{HalfLeft}{"2018, "201C}
        \xeCJKDeclareCharClass{HalfRight}{
            "00B7, "2019, "201D, "2013, "2014, "2025, "2026, "2E3A
        \usepackage{newunicodechar}
        \newunicodechar{π}{\ensuremath{\pi}}
        \newunicodechar{≤}{\ensuremath{\le}}
        \newunicodechar{≥}{\ensuremath{\ge}}
        \newunicodechar{♥}{\ensuremath{\heartsuit}}
        \newunicodechar{…}{\ensuremath{\ldots}}
# (source start file, target name, title, author, document class).
# latex_documents = []
        "contents",
        "django.tex",
        "Django Documentation",
        "Django Software Foundation",
# -- Options for manual page output --
        "ref/django-admin",
        "django-admin",
        "Utility script for the Django web framework",
        ["Django Software Foundation"],
# -- Options for Texinfo output --
# List of tuples (startdocname, targetname, title, author, dir_entry,
# description, category, toctree_only)
        root_doc,
        "django",
        "Django",
        "Documentation of the Django framework",
        "Web development",
# -- Options for Epub output --
epub_author = "Django Software Foundation"
epub_publisher = "Django Software Foundation"
# epub_basename = 'Django'
# The HTML theme for the epub output. Since the default themes are not
# optimized for small screen space, using the same theme for HTML and epub
# output is usually not wise. This defaults to 'epub', a theme designed to save
# visual space.
epub_theme = "djangodocs-epub"
# or en if the language is not set.
# The unique identifier of the text. This can be an ISBN number
epub_cover = ("", "epub-cover.html")
# HTML files that should be inserted after the pages created by sphinx.
# epub_exclude_files = []
# Fix unsupported image types using the PIL.
def version_github_linkcode_resolve(domain, info):
    return github_links.github_linkcode_resolve(
        domain, info, version=version, next_version=django_next_version
linkcode_resolve = version_github_linkcode_resolve
# This file only contains a selection of the most common options. For a full
# list see the documentation:
sys.path.insert(0, os.path.abspath('../..'))
# mock deps with system level requirements.
autodoc_mock_imports = ["soundfile"]
project = 'TTS'
copyright = "2021 Coqui GmbH, 2020 TTS authors"
author = 'Coqui GmbH'
with open("../../TTS/VERSION", "r") as ver:
    version = ver.read().strip()
# The main toctree document.
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    "sphinx_copybutton",
    "sphinx_inline_tabs",
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'TODO/*']
source_suffix = [".rst", ".md"]
myst_enable_extensions = ['linkify',]
# 'sphinxcontrib.katex',
# 'sphinx.ext.autosectionlabel',
# autosectionlabel throws warnings if section names are duplicated.
# The following tells autosectionlabel to not throw a warning for
# duplicated section names that are in different documents.
autodoc_inherit_docstrings = False
# Disable displaying type annotations, these can be very verbose
autodoc_typehints = 'none'
# Enable overriding of function signatures in the first line of the docstring.
autodoc_docstring_signature = True
napoleon_custom_sections = [('Shapes', 'shape')]
html_theme = 'furo'
html_tite = "TTS"
    "light_logo": "logo.png",
    "dark_logo": "logo.png",
    "sidebar_hide_name": True,
html_sidebars = {
        '**': [
               "sidebar/scroll-start.html",
    "sidebar/brand.html",
    "sidebar/search.html",
    "sidebar/navigation.html",
    "sidebar/ethical-ads.html",
    "sidebar/scroll-end.html",
