from .embedding import Embedding
__all__ = ["CreateEmbeddingResponse", "Usage"]
class Usage(BaseModel):
    """The usage information for the request."""
    """The number of tokens used by the prompt."""
    """The total number of tokens used by the request."""
class CreateEmbeddingResponse(BaseModel):
    data: List[Embedding]
    """The list of embeddings generated by the model."""
    """The name of the model used to generate the embedding."""
    object: Literal["list"]
    """The object type, which is always "list"."""
    usage: Usage
