 * Full entity rename map for MemberJunction v5.0 migration.
 * Contains old/new mappings for entity names, class names, and code names.
 * This data was generated from the MJ core schema and is embedded directly
 * in the package (compiled into JS) so it ships with npm distributions
 * without needing a separate JSON copy step.
 * Total entries: 272
/** A single entry in the entity rename map. */
export interface EntityRenameEntry {
    oldName: string;
    newName: string;
    nameChanged: boolean;
    oldClassName: string;
    newClassName: string;
    classNameChanged: boolean;
    oldCodeName: string;
    newCodeName: string;
    codeNameChanged: boolean;
 * The complete rename map for all 272 MJ core entities.
 * Each entry maps old names to new names across three dimensions:
 * - Entity names (e.g., "Actions" -> "MJ: Actions")
 * - Class names (e.g., "ActionEntity" -> "MJActionEntity")
 * - Code names (e.g., "Actions" -> "MJActions")
export const ENTITY_RENAME_MAP: EntityRenameEntry[] = [
        "oldName": "Action Authorizations",
        "newName": "MJ: Action Authorizations",
        "nameChanged": true,
        "oldClassName": "ActionAuthorization",
        "newClassName": "MJActionAuthorization",
        "classNameChanged": true,
        "oldCodeName": "ActionAuthorizations",
        "newCodeName": "MJActionAuthorizations",
        "codeNameChanged": true
        "oldName": "Action Categories",
        "newName": "MJ: Action Categories",
        "oldClassName": "ActionCategory",
        "newClassName": "MJActionCategory",
        "oldCodeName": "ActionCategories",
        "newCodeName": "MJActionCategories",
        "oldName": "Action Context Types",
        "newName": "MJ: Action Context Types",
        "oldClassName": "ActionContextType",
        "newClassName": "MJActionContextType",
        "oldCodeName": "ActionContextTypes",
        "newCodeName": "MJActionContextTypes",
        "oldName": "Action Contexts",
        "newName": "MJ: Action Contexts",
        "oldClassName": "ActionContext",
        "newClassName": "MJActionContext",
        "oldCodeName": "ActionContexts",
        "newCodeName": "MJActionContexts",
        "oldName": "Action Execution Logs",
        "newName": "MJ: Action Execution Logs",
        "oldClassName": "ActionExecutionLog",
        "newClassName": "MJActionExecutionLog",
        "oldCodeName": "ActionExecutionLogs",
        "newCodeName": "MJActionExecutionLogs",
        "oldName": "Action Filters",
        "newName": "MJ: Action Filters",
        "oldClassName": "ActionFilter",
        "newClassName": "MJActionFilter",
        "oldCodeName": "ActionFilters",
        "newCodeName": "MJActionFilters",
        "oldName": "Action Libraries",
        "newName": "MJ: Action Libraries",
        "oldClassName": "ActionLibrary",
        "newClassName": "MJActionLibrary",
        "oldCodeName": "ActionLibraries",
        "newCodeName": "MJActionLibraries",
        "oldName": "Action Params",
        "newName": "MJ: Action Params",
        "oldClassName": "ActionParam",
        "newClassName": "MJActionParam",
        "oldCodeName": "ActionParams",
        "newCodeName": "MJActionParams",
        "oldName": "Action Result Codes",
        "newName": "MJ: Action Result Codes",
        "oldClassName": "ActionResultCode",
        "newClassName": "MJActionResultCode",
        "oldCodeName": "ActionResultCodes",
        "newCodeName": "MJActionResultCodes",
        "oldName": "Actions",
        "newName": "MJ: Actions",
        "oldClassName": "Action",
        "newClassName": "MJAction",
        "oldCodeName": "Actions",
        "newCodeName": "MJActions",
        "oldName": "AI Actions",
        "newName": "MJ: AI Actions",
        "oldClassName": "AIAction",
        "newClassName": "MJAIAction",
        "oldCodeName": "AIActions",
        "newCodeName": "MJAIActions",
        "oldName": "AI Agent Actions",
        "newName": "MJ: AI Agent Actions",
        "oldClassName": "AIAgentAction",
        "newClassName": "MJAIAgentAction",
        "oldCodeName": "AIAgentActions",
        "newCodeName": "MJAIAgentActions",
        "oldName": "AI Agent Learning Cycles",
        "newName": "MJ: AI Agent Learning Cycles",
        "oldClassName": "AIAgentLearningCycle",
        "newClassName": "MJAIAgentLearningCycle",
        "oldCodeName": "AIAgentLearningCycles",
        "newCodeName": "MJAIAgentLearningCycles",
        "oldName": "AI Agent Models",
        "newName": "MJ: AI Agent Models",
        "oldClassName": "AIAgentModel",
        "newClassName": "MJAIAgentModel",
        "oldCodeName": "AIAgentModels",
        "newCodeName": "MJAIAgentModels",
        "oldName": "AI Agent Note Types",
        "newName": "MJ: AI Agent Note Types",
        "oldClassName": "AIAgentNoteType",
        "newClassName": "MJAIAgentNoteType",
        "oldCodeName": "AIAgentNoteTypes",
        "newCodeName": "MJAIAgentNoteTypes",
        "oldName": "AI Agent Notes",
        "newName": "MJ: AI Agent Notes",
        "oldClassName": "AIAgentNote",
        "newClassName": "MJAIAgentNote",
        "oldCodeName": "AIAgentNotes",
        "newCodeName": "MJAIAgentNotes",
        "oldName": "AI Agent Requests",
        "newName": "MJ: AI Agent Requests",
        "oldClassName": "AIAgentRequest",
        "newClassName": "MJAIAgentRequest",
        "oldCodeName": "AIAgentRequests",
        "newCodeName": "MJAIAgentRequests",
        "oldName": "AI Agents",
        "newName": "MJ: AI Agents",
        "oldClassName": "AIAgent",
        "newClassName": "MJAIAgent",
        "oldCodeName": "AIAgents",
        "newCodeName": "MJAIAgents",
        "oldName": "AI Model Actions",
        "newName": "MJ: AI Model Actions",
        "oldClassName": "AIModelAction",
        "newClassName": "MJAIModelAction",
        "oldCodeName": "AIModelActions",
        "newCodeName": "MJAIModelActions",
        "oldName": "AI Model Types",
        "newName": "MJ: AI Model Types",
        "oldClassName": "AIModelType",
        "newClassName": "MJAIModelType",
        "oldCodeName": "AIModelTypes",
        "newCodeName": "MJAIModelTypes",
        "oldName": "AI Models",
        "newName": "MJ: AI Models",
        "oldClassName": "AIModel",
        "newClassName": "MJAIModel",
        "oldCodeName": "AIModels",
        "newCodeName": "MJAIModels",
        "oldName": "AI Prompt Categories",
        "newName": "MJ: AI Prompt Categories",
        "oldClassName": "AIPromptCategory",
        "newClassName": "MJAIPromptCategory",
        "oldCodeName": "AIPromptCategories",
        "newCodeName": "MJAIPromptCategories",
        "oldName": "AI Prompt Types",
        "newName": "MJ: AI Prompt Types",
        "oldClassName": "AIPromptType",
        "newClassName": "MJAIPromptType",
        "oldCodeName": "AIPromptTypes",
        "newCodeName": "MJAIPromptTypes",
        "oldName": "AI Prompts",
        "newName": "MJ: AI Prompts",
        "oldClassName": "AIPrompt",
        "newClassName": "MJAIPrompt",
        "oldCodeName": "AIPrompts",
        "newCodeName": "MJAIPrompts",
        "oldName": "AI Result Cache",
        "newName": "MJ: AI Result Cache",
        "oldClassName": "AIResultCache",
        "newClassName": "MJAIResultCache",
        "oldCodeName": "AIResultCache",
        "newCodeName": "MJAIResultCache",
        "oldName": "Application Entities",
        "newName": "MJ: Application Entities",
        "oldClassName": "ApplicationEntity",
        "newClassName": "MJApplicationEntity",
        "oldCodeName": "ApplicationEntities",
        "newCodeName": "MJApplicationEntities",
        "oldName": "Application Settings",
        "newName": "MJ: Application Settings",
        "oldClassName": "ApplicationSetting",
        "newClassName": "MJApplicationSetting",
        "oldCodeName": "ApplicationSettings",
        "newCodeName": "MJApplicationSettings",
        "oldName": "Applications",
        "newName": "MJ: Applications",
        "oldClassName": "Application",
        "newClassName": "MJApplication",
        "oldCodeName": "Applications",
        "newCodeName": "MJApplications",
        "oldName": "Audit Log Types",
        "newName": "MJ: Audit Log Types",
        "oldClassName": "AuditLogType",
        "newClassName": "MJAuditLogType",
        "oldCodeName": "AuditLogTypes",
        "newCodeName": "MJAuditLogTypes",
        "oldName": "Audit Logs",
        "newName": "MJ: Audit Logs",
        "oldClassName": "AuditLog",
        "newClassName": "MJAuditLog",
        "oldCodeName": "AuditLogs",
        "newCodeName": "MJAuditLogs",
        "oldName": "Authorization Roles",
        "newName": "MJ: Authorization Roles",
        "oldClassName": "AuthorizationRole",
        "newClassName": "MJAuthorizationRole",
        "oldCodeName": "AuthorizationRoles",
        "newCodeName": "MJAuthorizationRoles",
        "oldName": "Authorizations",
        "newName": "MJ: Authorizations",
        "oldClassName": "Authorization",
        "newClassName": "MJAuthorization",
        "oldCodeName": "Authorizations",
        "newCodeName": "MJAuthorizations",
        "oldName": "Communication Base Message Types",
        "newName": "MJ: Communication Base Message Types",
        "oldClassName": "CommunicationBaseMessageType",
        "newClassName": "MJCommunicationBaseMessageType",
        "oldCodeName": "CommunicationBaseMessageTypes",
        "newCodeName": "MJCommunicationBaseMessageTypes",
        "oldName": "Communication Logs",
        "newName": "MJ: Communication Logs",
        "oldClassName": "CommunicationLog",
        "newClassName": "MJCommunicationLog",
        "oldCodeName": "CommunicationLogs",
        "newCodeName": "MJCommunicationLogs",
        "oldName": "Communication Provider Message Types",
        "newName": "MJ: Communication Provider Message Types",
        "oldClassName": "CommunicationProviderMessageType",
        "newClassName": "MJCommunicationProviderMessageType",
        "oldCodeName": "CommunicationProviderMessageTypes",
        "newCodeName": "MJCommunicationProviderMessageTypes",
        "oldName": "Communication Providers",
        "newName": "MJ: Communication Providers",
        "oldClassName": "CommunicationProvider",
        "newClassName": "MJCommunicationProvider",
        "oldCodeName": "CommunicationProviders",
        "newCodeName": "MJCommunicationProviders",
        "oldName": "Communication Runs",
        "newName": "MJ: Communication Runs",
        "oldClassName": "CommunicationRun",
        "newClassName": "MJCommunicationRun",
        "oldCodeName": "CommunicationRuns",
        "newCodeName": "MJCommunicationRuns",
        "oldName": "Companies",
        "newName": "MJ: Companies",
        "oldClassName": "Company",
        "newClassName": "MJCompany",
        "oldCodeName": "Companies",
        "newCodeName": "MJCompanies",
        "oldName": "Company Integration Record Maps",
        "newName": "MJ: Company Integration Record Maps",
        "oldClassName": "CompanyIntegrationRecordMap",
        "newClassName": "MJCompanyIntegrationRecordMap",
        "oldCodeName": "CompanyIntegrationRecordMaps",
        "newCodeName": "MJCompanyIntegrationRecordMaps",
        "oldName": "Company Integration Run API Logs",
        "newName": "MJ: Company Integration Run API Logs",
        "oldClassName": "CompanyIntegrationRunAPILog",
        "newClassName": "MJCompanyIntegrationRunAPILog",
        "oldCodeName": "CompanyIntegrationRunAPILogs",
        "newCodeName": "MJCompanyIntegrationRunAPILogs",
        "oldName": "Company Integration Run Details",
        "newName": "MJ: Company Integration Run Details",
        "oldClassName": "CompanyIntegrationRunDetail",
        "newClassName": "MJCompanyIntegrationRunDetail",
        "oldCodeName": "CompanyIntegrationRunDetails",
        "newCodeName": "MJCompanyIntegrationRunDetails",
        "oldName": "Company Integration Runs",
        "newName": "MJ: Company Integration Runs",
        "oldClassName": "CompanyIntegrationRun",
        "newClassName": "MJCompanyIntegrationRun",
        "oldCodeName": "CompanyIntegrationRuns",
        "newCodeName": "MJCompanyIntegrationRuns",
        "oldName": "Company Integrations",
        "newName": "MJ: Company Integrations",
        "oldClassName": "CompanyIntegration",
        "newClassName": "MJCompanyIntegration",
        "oldCodeName": "CompanyIntegrations",
        "newCodeName": "MJCompanyIntegrations",
        "oldName": "Content File Types",
        "newName": "MJ: Content File Types",
        "oldClassName": "ContentFileType",
        "newClassName": "MJContentFileType",
        "oldCodeName": "ContentFileTypes",
        "newCodeName": "MJContentFileTypes",
        "oldName": "Content Item Attributes",
        "newName": "MJ: Content Item Attributes",
        "oldClassName": "ContentItemAttribute",
        "newClassName": "MJContentItemAttribute",
        "oldCodeName": "ContentItemAttributes",
        "newCodeName": "MJContentItemAttributes",
        "oldName": "Content Item Tags",
        "newName": "MJ: Content Item Tags",
        "oldClassName": "ContentItemTag",
        "newClassName": "MJContentItemTag",
        "oldCodeName": "ContentItemTags",
        "newCodeName": "MJContentItemTags",
        "oldName": "Content Items",
        "newName": "MJ: Content Items",
        "oldClassName": "ContentItem",
        "newClassName": "MJContentItem",
        "oldCodeName": "ContentItems",
        "newCodeName": "MJContentItems",
        "oldName": "Content Process Runs",
        "newName": "MJ: Content Process Runs",
        "oldClassName": "ContentProcessRun",
        "newClassName": "MJContentProcessRun",
        "oldCodeName": "ContentProcessRuns",
        "newCodeName": "MJContentProcessRuns",
        "oldName": "Content Source Params",
        "newName": "MJ: Content Source Params",
        "oldClassName": "ContentSourceParam",
        "newClassName": "MJContentSourceParam",
        "oldCodeName": "ContentSourceParams",
        "newCodeName": "MJContentSourceParams",
        "oldName": "Content Source Type Params",
        "newName": "MJ: Content Source Type Params",
        "oldClassName": "ContentSourceTypeParam",
        "newClassName": "MJContentSourceTypeParam",
        "oldCodeName": "ContentSourceTypeParams",
        "newCodeName": "MJContentSourceTypeParams",
        "oldName": "Content Source Types",
        "newName": "MJ: Content Source Types",
        "oldClassName": "ContentSourceType",
        "newClassName": "MJContentSourceType",
        "oldCodeName": "ContentSourceTypes",
        "newCodeName": "MJContentSourceTypes",
        "oldName": "Content Sources",
        "newName": "MJ: Content Sources",
        "oldClassName": "ContentSource",
        "newClassName": "MJContentSource",
        "oldCodeName": "ContentSources",
        "newCodeName": "MJContentSources",
        "oldName": "Content Type Attributes",
        "newName": "MJ: Content Type Attributes",
        "oldClassName": "ContentTypeAttribute",
        "newClassName": "MJContentTypeAttribute",
        "oldCodeName": "ContentTypeAttributes",
        "newCodeName": "MJContentTypeAttributes",
        "oldName": "Content Types",
        "newName": "MJ: Content Types",
        "oldClassName": "ContentType",
        "newClassName": "MJContentType",
        "oldCodeName": "ContentTypes",
        "newCodeName": "MJContentTypes",
        "oldName": "Conversation Details",
        "newName": "MJ: Conversation Details",
        "oldClassName": "ConversationDetail",
        "newClassName": "MJConversationDetail",
        "oldCodeName": "ConversationDetails",
        "newCodeName": "MJConversationDetails",
        "oldName": "Conversations",
        "newName": "MJ: Conversations",
        "oldClassName": "Conversation",
        "newClassName": "MJConversation",
        "oldCodeName": "Conversations",
        "newCodeName": "MJConversations",
        "oldName": "Dashboard Categories",
        "newName": "MJ: Dashboard Categories",
        "oldClassName": "DashboardCategory",
        "newClassName": "MJDashboardCategory",
        "oldCodeName": "DashboardCategories",
        "newCodeName": "MJDashboardCategories",
        "oldName": "Dashboards",
        "newName": "MJ: Dashboards",
        "oldClassName": "Dashboard",
        "newClassName": "MJDashboard",
        "oldCodeName": "Dashboards",
        "newCodeName": "MJDashboards",
        "oldName": "Data Context Items",
        "newName": "MJ: Data Context Items",
        "oldClassName": "DataContextItem",
        "newClassName": "MJDataContextItem",
        "oldCodeName": "DataContextItems",
        "newCodeName": "MJDataContextItems",
        "oldName": "Data Contexts",
        "newName": "MJ: Data Contexts",
        "oldClassName": "DataContext",
        "newClassName": "MJDataContext",
        "oldCodeName": "DataContexts",
        "newCodeName": "MJDataContexts",
        "oldName": "Dataset Items",
        "newName": "MJ: Dataset Items",
        "oldClassName": "DatasetItem",
        "newClassName": "MJDatasetItem",
        "oldCodeName": "DatasetItems",
        "newCodeName": "MJDatasetItems",
        "oldName": "Datasets",
        "newName": "MJ: Datasets",
        "oldClassName": "Dataset",
        "newClassName": "MJDataset",
        "oldCodeName": "Datasets",
        "newCodeName": "MJDatasets",
        "oldName": "Duplicate Run Detail Matches",
        "newName": "MJ: Duplicate Run Detail Matches",
        "oldClassName": "DuplicateRunDetailMatch",
        "newClassName": "MJDuplicateRunDetailMatch",
        "oldCodeName": "DuplicateRunDetailMatches",
        "newCodeName": "MJDuplicateRunDetailMatches",
        "oldName": "Duplicate Run Details",
        "newName": "MJ: Duplicate Run Details",
        "oldClassName": "DuplicateRunDetail",
        "newClassName": "MJDuplicateRunDetail",
        "oldCodeName": "DuplicateRunDetails",
        "newCodeName": "MJDuplicateRunDetails",
        "oldName": "Duplicate Runs",
        "newName": "MJ: Duplicate Runs",
        "oldClassName": "DuplicateRun",
        "newClassName": "MJDuplicateRun",
        "oldCodeName": "DuplicateRuns",
        "newCodeName": "MJDuplicateRuns",
        "oldName": "Employee Company Integrations",
        "newName": "MJ: Employee Company Integrations",
        "oldClassName": "EmployeeCompanyIntegration",
        "newClassName": "MJEmployeeCompanyIntegration",
        "oldCodeName": "EmployeeCompanyIntegrations",
        "newCodeName": "MJEmployeeCompanyIntegrations",
        "oldName": "Employee Roles",
        "newName": "MJ: Employee Roles",
        "oldClassName": "EmployeeRole",
        "newClassName": "MJEmployeeRole",
        "oldCodeName": "EmployeeRoles",
        "newCodeName": "MJEmployeeRoles",
        "oldName": "Employee Skills",
        "newName": "MJ: Employee Skills",
        "oldClassName": "EmployeeSkill",
        "newClassName": "MJEmployeeSkill",
        "oldCodeName": "EmployeeSkills",
        "newCodeName": "MJEmployeeSkills",
        "oldName": "Employees",
        "newName": "MJ: Employees",
        "oldClassName": "Employee",
        "newClassName": "MJEmployee",
        "oldCodeName": "Employees",
        "newCodeName": "MJEmployees",
        "oldName": "Entities",
        "newName": "MJ: Entities",
        "oldClassName": "Entity",
        "newClassName": "MJEntity",
        "oldCodeName": "Entities",
        "newCodeName": "MJEntities",
        "oldName": "Entity Action Filters",
        "newName": "MJ: Entity Action Filters",
        "oldClassName": "EntityActionFilter",
        "newClassName": "MJEntityActionFilter",
        "oldCodeName": "EntityActionFilters",
        "newCodeName": "MJEntityActionFilters",
        "oldName": "Entity Action Invocation Types",
        "newName": "MJ: Entity Action Invocation Types",
        "oldClassName": "EntityActionInvocationType",
        "newClassName": "MJEntityActionInvocationType",
        "oldCodeName": "EntityActionInvocationTypes",
        "newCodeName": "MJEntityActionInvocationTypes",
        "oldName": "Entity Action Invocations",
        "newName": "MJ: Entity Action Invocations",
        "oldClassName": "EntityActionInvocation",
        "newClassName": "MJEntityActionInvocation",
        "oldCodeName": "EntityActionInvocations",
        "newCodeName": "MJEntityActionInvocations",
        "oldName": "Entity Action Params",
        "newName": "MJ: Entity Action Params",
        "oldClassName": "EntityActionParam",
        "newClassName": "MJEntityActionParam",
        "oldCodeName": "EntityActionParams",
        "newCodeName": "MJEntityActionParams",
        "oldName": "Entity Actions",
        "newName": "MJ: Entity Actions",
        "oldClassName": "EntityAction",
        "newClassName": "MJEntityAction",
        "oldCodeName": "EntityActions",
        "newCodeName": "MJEntityActions",
        "oldName": "Entity AI Actions",
        "newName": "MJ: Entity AI Actions",
        "oldClassName": "EntityAIAction",
        "newClassName": "MJEntityAIAction",
        "oldCodeName": "EntityAIActions",
        "newCodeName": "MJEntityAIActions",
        "oldName": "Entity Communication Fields",
        "newName": "MJ: Entity Communication Fields",
        "oldClassName": "EntityCommunicationField",
        "newClassName": "MJEntityCommunicationField",
        "oldCodeName": "EntityCommunicationFields",
        "newCodeName": "MJEntityCommunicationFields",
        "oldName": "Entity Communication Message Types",
        "newName": "MJ: Entity Communication Message Types",
        "oldClassName": "EntityCommunicationMessageType",
        "newClassName": "MJEntityCommunicationMessageType",
        "oldCodeName": "EntityCommunicationMessageTypes",
        "newCodeName": "MJEntityCommunicationMessageTypes",
        "oldName": "Entity Document Runs",
        "newName": "MJ: Entity Document Runs",
        "oldClassName": "EntityDocumentRun",
        "newClassName": "MJEntityDocumentRun",
        "oldCodeName": "EntityDocumentRuns",
        "newCodeName": "MJEntityDocumentRuns",
        "oldName": "Entity Document Settings",
        "newName": "MJ: Entity Document Settings",
        "oldClassName": "EntityDocumentSetting",
        "newClassName": "MJEntityDocumentSetting",
        "oldCodeName": "EntityDocumentSettings",
        "newCodeName": "MJEntityDocumentSettings",
        "oldName": "Entity Document Types",
        "newName": "MJ: Entity Document Types",
        "oldClassName": "EntityDocumentType",
        "newClassName": "MJEntityDocumentType",
        "oldCodeName": "EntityDocumentTypes",
        "newCodeName": "MJEntityDocumentTypes",
        "oldName": "Entity Documents",
        "newName": "MJ: Entity Documents",
        "oldClassName": "EntityDocument",
        "newClassName": "MJEntityDocument",
        "oldCodeName": "EntityDocuments",
        "newCodeName": "MJEntityDocuments",
        "oldName": "Entity Field Values",
        "newName": "MJ: Entity Field Values",
        "oldClassName": "EntityFieldValue",
        "newClassName": "MJEntityFieldValue",
        "oldCodeName": "EntityFieldValues",
        "newCodeName": "MJEntityFieldValues",
        "oldName": "Entity Fields",
        "newName": "MJ: Entity Fields",
        "oldClassName": "EntityField",
        "newClassName": "MJEntityField",
        "oldCodeName": "EntityFields",
        "newCodeName": "MJEntityFields",
        "oldName": "Entity Permissions",
        "newName": "MJ: Entity Permissions",
        "oldClassName": "EntityPermission",
        "newClassName": "MJEntityPermission",
        "oldCodeName": "EntityPermissions",
        "newCodeName": "MJEntityPermissions",
        "oldName": "Entity Record Documents",
        "newName": "MJ: Entity Record Documents",
        "oldClassName": "EntityRecordDocument",
        "newClassName": "MJEntityRecordDocument",
        "oldCodeName": "EntityRecordDocuments",
        "newCodeName": "MJEntityRecordDocuments",
        "oldName": "Entity Relationship Display Components",
        "newName": "MJ: Entity Relationship Display Components",
        "oldClassName": "EntityRelationshipDisplayComponent",
        "newClassName": "MJEntityRelationshipDisplayComponent",
        "oldCodeName": "EntityRelationshipDisplayComponents",
        "newCodeName": "MJEntityRelationshipDisplayComponents",
        "oldName": "Entity Relationships",
        "newName": "MJ: Entity Relationships",
        "oldClassName": "EntityRelationship",
        "newClassName": "MJEntityRelationship",
        "oldCodeName": "EntityRelationships",
        "newCodeName": "MJEntityRelationships",
        "oldName": "Entity Settings",
        "newName": "MJ: Entity Settings",
        "oldClassName": "EntitySetting",
        "newClassName": "MJEntitySetting",
        "oldCodeName": "EntitySettings",
        "newCodeName": "MJEntitySettings",
        "oldName": "Error Logs",
        "newName": "MJ: Error Logs",
        "oldClassName": "ErrorLog",
        "newClassName": "MJErrorLog",
        "oldCodeName": "ErrorLogs",
        "newCodeName": "MJErrorLogs",
        "oldName": "Explorer Navigation Items",
        "newName": "MJ: Explorer Navigation Items",
        "oldClassName": "ExplorerNavigationItem",
        "newClassName": "MJExplorerNavigationItem",
        "oldCodeName": "ExplorerNavigationItems",
        "newCodeName": "MJExplorerNavigationItems",
        "oldName": "File Categories",
        "newName": "MJ: File Categories",
        "oldClassName": "FileCategory",
        "newClassName": "MJFileCategory",
        "oldCodeName": "FileCategories",
        "newCodeName": "MJFileCategories",
        "oldName": "File Entity Record Links",
        "newName": "MJ: File Entity Record Links",
        "oldClassName": "FileEntityRecordLink",
        "newClassName": "MJFileEntityRecordLink",
        "oldCodeName": "FileEntityRecordLinks",
        "newCodeName": "MJFileEntityRecordLinks",
        "oldName": "File Storage Providers",
        "newName": "MJ: File Storage Providers",
        "oldClassName": "FileStorageProvider",
        "newClassName": "MJFileStorageProvider",
        "oldCodeName": "FileStorageProviders",
        "newCodeName": "MJFileStorageProviders",
        "oldName": "Files",
        "newName": "MJ: Files",
        "oldClassName": "File",
        "newClassName": "MJFile",
        "oldCodeName": "Files",
        "newCodeName": "MJFiles",
        "oldName": "Generated Code Categories",
        "newName": "MJ: Generated Code Categories",
        "oldClassName": "GeneratedCodeCategory",
        "newClassName": "MJGeneratedCodeCategory",
        "oldCodeName": "GeneratedCodeCategories",
        "newCodeName": "MJGeneratedCodeCategories",
        "oldName": "Generated Codes",
        "newName": "MJ: Generated Codes",
        "oldClassName": "GeneratedCode",
        "newClassName": "MJGeneratedCode",
        "oldCodeName": "GeneratedCodes",
        "newCodeName": "MJGeneratedCodes",
        "oldName": "Integration URL Formats",
        "newName": "MJ: Integration URL Formats",
        "oldClassName": "IntegrationURLFormat",
        "newClassName": "MJIntegrationURLFormat",
        "oldCodeName": "IntegrationURLFormats",
        "newCodeName": "MJIntegrationURLFormats",
        "oldName": "Integrations",
        "newName": "MJ: Integrations",
        "oldClassName": "Integration",
        "newClassName": "MJIntegration",
        "oldCodeName": "Integrations",
        "newCodeName": "MJIntegrations",
        "oldName": "Libraries",
        "newName": "MJ: Libraries",
        "oldClassName": "Library",
        "newClassName": "MJLibrary",
        "oldCodeName": "Libraries",
        "newCodeName": "MJLibraries",
        "oldName": "Library Items",
        "newName": "MJ: Library Items",
        "oldClassName": "LibraryItem",
        "newClassName": "MJLibraryItem",
        "oldCodeName": "LibraryItems",
        "newCodeName": "MJLibraryItems",
        "oldName": "List Categories",
        "newName": "MJ: List Categories",
        "oldClassName": "ListCategory",
        "newClassName": "MJListCategory",
        "oldCodeName": "ListCategories",
        "newCodeName": "MJListCategories",
        "oldName": "List Details",
        "newName": "MJ: List Details",
        "oldClassName": "ListDetail",
        "newClassName": "MJListDetail",
        "oldCodeName": "ListDetails",
        "newCodeName": "MJListDetails",
        "oldName": "Lists",
        "newName": "MJ: Lists",
        "oldClassName": "List",
        "newClassName": "MJList",
        "oldCodeName": "Lists",
        "newCodeName": "MJLists",
        "oldName": "MJ: Access Control Rules",
        "newName": "MJ: Access Control Rules",
        "nameChanged": false,
        "oldClassName": "AccessControlRule",
        "newClassName": "MJAccessControlRule",
        "oldCodeName": "MJ_AccessControlRules",
        "newCodeName": "MJAccessControlRules",
        "oldName": "MJ: AI Agent Artifact Types",
        "newName": "MJ: AI Agent Artifact Types",
        "oldClassName": "AIAgentArtifactType",
        "newClassName": "MJAIAgentArtifactType",
        "oldCodeName": "MJ_AIAgentArtifactTypes",
        "newCodeName": "MJAIAgentArtifactTypes",
        "oldName": "MJ: AI Agent Configurations",
        "newName": "MJ: AI Agent Configurations",
        "oldClassName": "AIAgentConfiguration",
        "newClassName": "MJAIAgentConfiguration",
        "oldCodeName": "MJ_AIAgentConfigurations",
        "newCodeName": "MJAIAgentConfigurations",
        "oldName": "MJ: AI Agent Data Sources",
        "newName": "MJ: AI Agent Data Sources",
        "oldClassName": "AIAgentDataSource",
        "newClassName": "MJAIAgentDataSource",
        "oldCodeName": "MJ_AIAgentDataSources",
        "newCodeName": "MJAIAgentDataSources",
        "oldName": "MJ: AI Agent Examples",
        "newName": "MJ: AI Agent Examples",
        "oldClassName": "AIAgentExample",
        "newClassName": "MJAIAgentExample",
        "oldCodeName": "MJ_AIAgentExamples",
        "newCodeName": "MJAIAgentExamples",
        "oldName": "MJ: AI Agent Modalities",
        "newName": "MJ: AI Agent Modalities",
        "oldClassName": "AIAgentModality",
        "newClassName": "MJAIAgentModality",
        "oldCodeName": "MJ_AIAgentModalities",
        "newCodeName": "MJAIAgentModalities",
        "oldName": "MJ: AI Agent Permissions",
        "newName": "MJ: AI Agent Permissions",
        "oldClassName": "AIAgentPermission",
        "newClassName": "MJAIAgentPermission",
        "oldCodeName": "MJ_AIAgentPermissions",
        "newCodeName": "MJAIAgentPermissions",
        "oldName": "MJ: AI Agent Prompts",
        "newName": "MJ: AI Agent Prompts",
        "oldClassName": "AIAgentPrompt",
        "newClassName": "MJAIAgentPrompt",
        "oldCodeName": "MJ_AIAgentPrompts",
        "newCodeName": "MJAIAgentPrompts",
        "oldName": "MJ: AI Agent Relationships",
        "newName": "MJ: AI Agent Relationships",
        "oldClassName": "AIAgentRelationship",
        "newClassName": "MJAIAgentRelationship",
        "oldCodeName": "MJ_AIAgentRelationships",
        "newCodeName": "MJAIAgentRelationships",
        "oldName": "MJ: AI Agent Run Medias",
        "newName": "MJ: AI Agent Run Medias",
        "oldClassName": "AIAgentRunMedia",
        "newClassName": "MJAIAgentRunMedia",
        "oldCodeName": "MJ_AIAgentRunMedias",
        "newCodeName": "MJAIAgentRunMedias",
        "oldName": "MJ: AI Agent Run Steps",
        "newName": "MJ: AI Agent Run Steps",
        "oldClassName": "AIAgentRunStep",
        "newClassName": "MJAIAgentRunStep",
        "oldCodeName": "MJ_AIAgentRunSteps",
        "newCodeName": "MJAIAgentRunSteps",
        "oldName": "MJ: AI Agent Runs",
        "newName": "MJ: AI Agent Runs",
        "oldClassName": "AIAgentRun",
        "newClassName": "MJAIAgentRun",
        "oldCodeName": "MJ_AIAgentRuns",
        "newCodeName": "MJAIAgentRuns",
        "oldName": "MJ: AI Agent Step Paths",
        "newName": "MJ: AI Agent Step Paths",
        "oldClassName": "AIAgentStepPath",
        "newClassName": "MJAIAgentStepPath",
        "oldCodeName": "MJ_AIAgentStepPaths",
        "newCodeName": "MJAIAgentStepPaths",
        "oldName": "MJ: AI Agent Steps",
        "newName": "MJ: AI Agent Steps",
        "oldClassName": "AIAgentStep",
        "newClassName": "MJAIAgentStep",
        "oldCodeName": "MJ_AIAgentSteps",
        "newCodeName": "MJAIAgentSteps",
        "oldName": "MJ: AI Agent Types",
        "newName": "MJ: AI Agent Types",
        "oldClassName": "AIAgentType",
        "newClassName": "MJAIAgentType",
        "oldCodeName": "MJ_AIAgentTypes",
        "newCodeName": "MJAIAgentTypes",
        "oldName": "MJ: AI Architectures",
        "newName": "MJ: AI Architectures",
        "oldClassName": "AIArchitecture",
        "newClassName": "MJAIArchitecture",
        "oldCodeName": "MJ_AIArchitectures",
        "newCodeName": "MJAIArchitectures",
        "oldName": "MJ: AI Configuration Params",
        "newName": "MJ: AI Configuration Params",
        "oldClassName": "AIConfigurationParam",
        "newClassName": "MJAIConfigurationParam",
        "oldCodeName": "MJ_AIConfigurationParams",
        "newCodeName": "MJAIConfigurationParams",
        "oldName": "MJ: AI Configurations",
        "newName": "MJ: AI Configurations",
        "oldClassName": "AIConfiguration",
        "newClassName": "MJAIConfiguration",
        "oldCodeName": "MJ_AIConfigurations",
        "newCodeName": "MJAIConfigurations",
        "oldName": "MJ: AI Credential Bindings",
        "newName": "MJ: AI Credential Bindings",
        "oldClassName": "AICredentialBinding",
        "newClassName": "MJAICredentialBinding",
        "oldCodeName": "MJ_AICredentialBindings",
        "newCodeName": "MJAICredentialBindings",
        "oldName": "MJ: AI Modalities",
        "newName": "MJ: AI Modalities",
        "oldClassName": "AIModality",
        "newClassName": "MJAIModality",
        "oldCodeName": "MJ_AIModalities",
        "newCodeName": "MJAIModalities",
        "oldName": "MJ: AI Model Architectures",
        "newName": "MJ: AI Model Architectures",
        "oldClassName": "AIModelArchitecture",
        "newClassName": "MJAIModelArchitecture",
        "oldCodeName": "MJ_AIModelArchitectures",
        "newCodeName": "MJAIModelArchitectures",
        "oldName": "MJ: AI Model Costs",
        "newName": "MJ: AI Model Costs",
        "oldClassName": "AIModelCost",
        "newClassName": "MJAIModelCost",
        "oldCodeName": "MJ_AIModelCosts",
        "newCodeName": "MJAIModelCosts",
        "oldName": "MJ: AI Model Modalities",
        "newName": "MJ: AI Model Modalities",
        "oldClassName": "AIModelModality",
        "newClassName": "MJAIModelModality",
        "oldCodeName": "MJ_AIModelModalities",
        "newCodeName": "MJAIModelModalities",
        "oldName": "MJ: AI Model Price Types",
        "newName": "MJ: AI Model Price Types",
        "oldClassName": "AIModelPriceType",
        "newClassName": "MJAIModelPriceType",
        "oldCodeName": "MJ_AIModelPriceTypes",
        "newCodeName": "MJAIModelPriceTypes",
        "oldName": "MJ: AI Model Price Unit Types",
        "newName": "MJ: AI Model Price Unit Types",
        "oldClassName": "AIModelPriceUnitType",
        "newClassName": "MJAIModelPriceUnitType",
        "oldCodeName": "MJ_AIModelPriceUnitTypes",
        "newCodeName": "MJAIModelPriceUnitTypes",
        "oldName": "MJ: AI Model Vendors",
        "newName": "MJ: AI Model Vendors",
        "oldClassName": "AIModelVendor",
        "newClassName": "MJAIModelVendor",
        "oldCodeName": "MJ_AIModelVendors",
        "newCodeName": "MJAIModelVendors",
        "oldName": "MJ: AI Prompt Models",
        "newName": "MJ: AI Prompt Models",
        "oldClassName": "AIPromptModel",
        "newClassName": "MJAIPromptModel",
        "oldCodeName": "MJ_AIPromptModels",
        "newCodeName": "MJAIPromptModels",
        "oldName": "MJ: AI Prompt Run Medias",
        "newName": "MJ: AI Prompt Run Medias",
        "oldClassName": "AIPromptRunMedia",
        "newClassName": "MJAIPromptRunMedia",
        "oldCodeName": "MJ_AIPromptRunMedias",
        "newCodeName": "MJAIPromptRunMedias",
        "oldName": "MJ: AI Prompt Runs",
        "newName": "MJ: AI Prompt Runs",
        "oldClassName": "AIPromptRun",
        "newClassName": "MJAIPromptRun",
        "oldCodeName": "MJ_AIPromptRuns",
        "newCodeName": "MJAIPromptRuns",
        "oldName": "MJ: AI Vendor Type Definitions",
        "newName": "MJ: AI Vendor Type Definitions",
        "oldClassName": "AIVendorTypeDefinition",
        "newClassName": "MJAIVendorTypeDefinition",
        "oldCodeName": "MJ_AIVendorTypeDefinitions",
        "newCodeName": "MJAIVendorTypeDefinitions",
        "oldName": "MJ: AI Vendor Types",
        "newName": "MJ: AI Vendor Types",
        "oldClassName": "AIVendorType",
        "newClassName": "MJAIVendorType",
        "oldCodeName": "MJ_AIVendorTypes",
        "newCodeName": "MJAIVendorTypes",
        "oldName": "MJ: AI Vendors",
        "newName": "MJ: AI Vendors",
        "oldClassName": "AIVendor",
        "newClassName": "MJAIVendor",
        "oldCodeName": "MJ_AIVendors",
        "newCodeName": "MJAIVendors",
        "oldName": "MJ: API Application Scopes",
        "newName": "MJ: API Application Scopes",
        "oldClassName": "APIApplicationScope",
        "newClassName": "MJAPIApplicationScope",
        "oldCodeName": "MJ_APIApplicationScopes",
        "newCodeName": "MJAPIApplicationScopes",
        "oldName": "MJ: API Applications",
        "newName": "MJ: API Applications",
        "oldClassName": "APIApplication",
        "newClassName": "MJAPIApplication",
        "oldCodeName": "MJ_APIApplications",
        "newCodeName": "MJAPIApplications",
        "oldName": "MJ: API Key Applications",
        "newName": "MJ: API Key Applications",
        "oldClassName": "APIKeyApplication",
        "newClassName": "MJAPIKeyApplication",
        "oldCodeName": "MJ_APIKeyApplications",
        "newCodeName": "MJAPIKeyApplications",
        "oldName": "MJ: API Key Scopes",
        "newName": "MJ: API Key Scopes",
        "oldClassName": "APIKeyScope",
        "newClassName": "MJAPIKeyScope",
        "oldCodeName": "MJ_APIKeyScopes",
        "newCodeName": "MJAPIKeyScopes",
        "oldName": "MJ: API Key Usage Logs",
        "newName": "MJ: API Key Usage Logs",
        "oldClassName": "APIKeyUsageLog",
        "newClassName": "MJAPIKeyUsageLog",
        "oldCodeName": "MJ_APIKeyUsageLogs",
        "newCodeName": "MJAPIKeyUsageLogs",
        "oldName": "MJ: API Keys",
        "newName": "MJ: API Keys",
        "oldClassName": "APIKey",
        "newClassName": "MJAPIKey",
        "oldCodeName": "MJ_APIKeys",
        "newCodeName": "MJAPIKeys",
        "oldName": "MJ: API Scopes",
        "newName": "MJ: API Scopes",
        "oldClassName": "APIScope",
        "newClassName": "MJAPIScope",
        "oldCodeName": "MJ_APIScopes",
        "newCodeName": "MJAPIScopes",
        "oldName": "MJ: Artifact Permissions",
        "newName": "MJ: Artifact Permissions",
        "oldClassName": "ArtifactPermission",
        "newClassName": "MJArtifactPermission",
        "oldCodeName": "MJ_ArtifactPermissions",
        "newCodeName": "MJArtifactPermissions",
        "oldName": "MJ: Artifact Types",
        "newName": "MJ: Artifact Types",
        "oldClassName": "ArtifactType",
        "newClassName": "MJArtifactType",
        "oldCodeName": "MJ_ArtifactTypes",
        "newCodeName": "MJArtifactTypes",
        "oldName": "MJ: Artifact Uses",
        "newName": "MJ: Artifact Uses",
        "oldClassName": "ArtifactUse",
        "newClassName": "MJArtifactUse",
        "oldCodeName": "MJ_ArtifactUses",
        "newCodeName": "MJArtifactUses",
        "oldName": "MJ: Artifact Version Attributes",
        "newName": "MJ: Artifact Version Attributes",
        "oldClassName": "ArtifactVersionAttribute",
        "newClassName": "MJArtifactVersionAttribute",
        "oldCodeName": "MJ_ArtifactVersionAttributes",
        "newCodeName": "MJArtifactVersionAttributes",
        "oldName": "MJ: Artifact Versions",
        "newName": "MJ: Artifact Versions",
        "oldClassName": "ArtifactVersion",
        "newClassName": "MJArtifactVersion",
        "oldCodeName": "MJ_ArtifactVersions",
        "newCodeName": "MJArtifactVersions",
        "oldName": "MJ: Artifacts",
        "newName": "MJ: Artifacts",
        "oldClassName": "Artifact",
        "newClassName": "MJArtifact",
        "oldCodeName": "MJ_Artifacts",
        "newCodeName": "MJArtifacts",
        "oldName": "MJ: Collection Artifacts",
        "newName": "MJ: Collection Artifacts",
        "oldClassName": "CollectionArtifact",
        "newClassName": "MJCollectionArtifact",
        "oldCodeName": "MJ_CollectionArtifacts",
        "newCodeName": "MJCollectionArtifacts",
        "oldName": "MJ: Collection Permissions",
        "newName": "MJ: Collection Permissions",
        "oldClassName": "CollectionPermission",
        "newClassName": "MJCollectionPermission",
        "oldCodeName": "MJ_CollectionPermissions",
        "newCodeName": "MJCollectionPermissions",
        "oldName": "MJ: Collections",
        "newName": "MJ: Collections",
        "oldClassName": "Collection",
        "newClassName": "MJCollection",
        "oldCodeName": "MJ_Collections",
        "newCodeName": "MJCollections",
        "oldName": "MJ: Component Dependencies",
        "newName": "MJ: Component Dependencies",
        "oldClassName": "ComponentDependency",
        "newClassName": "MJComponentDependency",
        "oldCodeName": "MJ_ComponentDependencies",
        "newCodeName": "MJComponentDependencies",
        "oldName": "MJ: Component Libraries",
        "newName": "MJ: Component Libraries",
        "oldClassName": "ComponentLibrary",
        "newClassName": "MJComponentLibrary",
        "oldCodeName": "MJ_ComponentLibraries",
        "newCodeName": "MJComponentLibraries",
        "oldName": "MJ: Component Library Links",
        "newName": "MJ: Component Library Links",
        "oldClassName": "ComponentLibraryLink",
        "newClassName": "MJComponentLibraryLink",
        "oldCodeName": "MJ_ComponentLibraryLinks",
        "newCodeName": "MJComponentLibraryLinks",
        "oldName": "MJ: Component Registries",
        "newName": "MJ: Component Registries",
        "oldClassName": "ComponentRegistry",
        "newClassName": "MJComponentRegistry",
        "oldCodeName": "MJ_ComponentRegistries",
        "newCodeName": "MJComponentRegistries",
        "oldName": "MJ: Components",
        "newName": "MJ: Components",
        "oldClassName": "Component",
        "newClassName": "MJComponent",
        "oldCodeName": "MJ_Components",
        "newCodeName": "MJComponents",
        "oldName": "MJ: Conversation Artifact Permissions",
        "newName": "MJ: Conversation Artifact Permissions",
        "oldClassName": "ConversationArtifactPermission",
        "newClassName": "MJConversationArtifactPermission",
        "oldCodeName": "MJ_ConversationArtifactPermissions",
        "newCodeName": "MJConversationArtifactPermissions",
        "oldName": "MJ: Conversation Artifact Versions",
        "newName": "MJ: Conversation Artifact Versions",
        "oldClassName": "ConversationArtifactVersion",
        "newClassName": "MJConversationArtifactVersion",
        "oldCodeName": "MJ_ConversationArtifactVersions",
        "newCodeName": "MJConversationArtifactVersions",
        "oldName": "MJ: Conversation Artifacts",
        "newName": "MJ: Conversation Artifacts",
        "oldClassName": "ConversationArtifact",
        "newClassName": "MJConversationArtifact",
        "oldCodeName": "MJ_ConversationArtifacts",
        "newCodeName": "MJConversationArtifacts",
        "oldName": "MJ: Conversation Detail Artifacts",
        "newName": "MJ: Conversation Detail Artifacts",
        "oldClassName": "ConversationDetailArtifact",
        "newClassName": "MJConversationDetailArtifact",
        "oldCodeName": "MJ_ConversationDetailArtifacts",
        "newCodeName": "MJConversationDetailArtifacts",
        "oldName": "MJ: Conversation Detail Attachments",
        "newName": "MJ: Conversation Detail Attachments",
        "oldClassName": "ConversationDetailAttachment",
        "newClassName": "MJConversationDetailAttachment",
        "oldCodeName": "MJ_ConversationDetailAttachments",
        "newCodeName": "MJConversationDetailAttachments",
        "oldName": "MJ: Conversation Detail Ratings",
        "newName": "MJ: Conversation Detail Ratings",
        "oldClassName": "ConversationDetailRating",
        "newClassName": "MJConversationDetailRating",
        "oldCodeName": "MJ_ConversationDetailRatings",
        "newCodeName": "MJConversationDetailRatings",
        "oldName": "MJ: Credential Categories",
        "newName": "MJ: Credential Categories",
        "oldClassName": "CredentialCategory",
        "newClassName": "MJCredentialCategory",
        "oldCodeName": "MJ_CredentialCategories",
        "newCodeName": "MJCredentialCategories",
        "oldName": "MJ: Credential Types",
        "newName": "MJ: Credential Types",
        "oldClassName": "CredentialType",
        "newClassName": "MJCredentialType",
        "oldCodeName": "MJ_CredentialTypes",
        "newCodeName": "MJCredentialTypes",
        "oldName": "MJ: Credentials",
        "newName": "MJ: Credentials",
        "oldClassName": "Credential",
        "newClassName": "MJCredential",
        "oldCodeName": "MJ_Credentials",
        "newCodeName": "MJCredentials",
        "oldName": "MJ: Dashboard Category Links",
        "newName": "MJ: Dashboard Category Links",
        "oldClassName": "DashboardCategoryLink",
        "newClassName": "MJDashboardCategoryLink",
        "oldCodeName": "MJ_DashboardCategoryLinks",
        "newCodeName": "MJDashboardCategoryLinks",
        "oldName": "MJ: Dashboard Category Permissions",
        "newName": "MJ: Dashboard Category Permissions",
        "oldClassName": "DashboardCategoryPermission",
        "newClassName": "MJDashboardCategoryPermission",
        "oldCodeName": "MJ_DashboardCategoryPermissions",
        "newCodeName": "MJDashboardCategoryPermissions",
        "oldName": "MJ: Dashboard Part Types",
        "newName": "MJ: Dashboard Part Types",
        "oldClassName": "DashboardPartType",
        "newClassName": "MJDashboardPartType",
        "oldCodeName": "MJ_DashboardPartTypes",
        "newCodeName": "MJDashboardPartTypes",
        "oldName": "MJ: Dashboard Permissions",
        "newName": "MJ: Dashboard Permissions",
        "oldClassName": "DashboardPermission",
        "newClassName": "MJDashboardPermission",
        "oldCodeName": "MJ_DashboardPermissions",
        "newCodeName": "MJDashboardPermissions",
        "oldName": "MJ: Dashboard User Preferences",
        "newName": "MJ: Dashboard User Preferences",
        "oldClassName": "DashboardUserPreference",
        "newClassName": "MJDashboardUserPreference",
        "oldCodeName": "MJ_DashboardUserPreferences",
        "newCodeName": "MJDashboardUserPreferences",
        "oldName": "MJ: Dashboard User States",
        "newName": "MJ: Dashboard User States",
        "oldClassName": "DashboardUserState",
        "newClassName": "MJDashboardUserState",
        "oldCodeName": "MJ_DashboardUserStates",
        "newCodeName": "MJDashboardUserStates",
        "oldName": "MJ: Encryption Algorithms",
        "newName": "MJ: Encryption Algorithms",
        "oldClassName": "EncryptionAlgorithm",
        "newClassName": "MJEncryptionAlgorithm",
        "oldCodeName": "MJ_EncryptionAlgorithms",
        "newCodeName": "MJEncryptionAlgorithms",
        "oldName": "MJ: Encryption Key Sources",
        "newName": "MJ: Encryption Key Sources",
        "oldClassName": "EncryptionKeySource",
        "newClassName": "MJEncryptionKeySource",
        "oldCodeName": "MJ_EncryptionKeySources",
        "newCodeName": "MJEncryptionKeySources",
        "oldName": "MJ: Encryption Keys",
        "newName": "MJ: Encryption Keys",
        "oldClassName": "EncryptionKey",
        "newClassName": "MJEncryptionKey",
        "oldCodeName": "MJ_EncryptionKeys",
        "newCodeName": "MJEncryptionKeys",
        "oldName": "MJ: Environments",
        "newName": "MJ: Environments",
        "oldClassName": "Environment",
        "newClassName": "MJEnvironment",
        "oldCodeName": "MJ_Environments",
        "newCodeName": "MJEnvironments",
        "oldName": "MJ: File Storage Accounts",
        "newName": "MJ: File Storage Accounts",
        "oldClassName": "FileStorageAccount",
        "newClassName": "MJFileStorageAccount",
        "oldCodeName": "MJ_FileStorageAccounts",
        "newCodeName": "MJFileStorageAccounts",
        "oldName": "MJ: List Invitations",
        "newName": "MJ: List Invitations",
        "oldClassName": "ListInvitation",
        "newClassName": "MJListInvitation",
        "oldCodeName": "MJ_ListInvitations",
        "newCodeName": "MJListInvitations",
        "oldName": "MJ: List Shares",
        "newName": "MJ: List Shares",
        "oldClassName": "ListShare",
        "newClassName": "MJListShare",
        "oldCodeName": "MJ_ListShares",
        "newCodeName": "MJListShares",
        "oldName": "MJ: MCP Server Connection Permissions",
        "newName": "MJ: MCP Server Connection Permissions",
        "oldClassName": "MCPServerConnectionPermission",
        "newClassName": "MJMCPServerConnectionPermission",
        "oldCodeName": "MJ_MCPServerConnectionPermissions",
        "newCodeName": "MJMCPServerConnectionPermissions",
        "oldName": "MJ: MCP Server Connection Tools",
        "newName": "MJ: MCP Server Connection Tools",
        "oldClassName": "MCPServerConnectionTool",
        "newClassName": "MJMCPServerConnectionTool",
        "oldCodeName": "MJ_MCPServerConnectionTools",
        "newCodeName": "MJMCPServerConnectionTools",
        "oldName": "MJ: MCP Server Connections",
        "newName": "MJ: MCP Server Connections",
        "oldClassName": "MCPServerConnection",
        "newClassName": "MJMCPServerConnection",
        "oldCodeName": "MJ_MCPServerConnections",
        "newCodeName": "MJMCPServerConnections",
        "oldName": "MJ: MCP Server Tools",
        "newName": "MJ: MCP Server Tools",
        "oldClassName": "MCPServerTool",
        "newClassName": "MJMCPServerTool",
        "oldCodeName": "MJ_MCPServerTools",
        "newCodeName": "MJMCPServerTools",
        "oldName": "MJ: MCP Servers",
        "newName": "MJ: MCP Servers",
        "oldClassName": "MCPServer",
        "newClassName": "MJMCPServer",
        "oldCodeName": "MJ_MCPServers",
        "newCodeName": "MJMCPServers",
        "oldName": "MJ: MCP Tool Execution Logs",
        "newName": "MJ: MCP Tool Execution Logs",
        "oldClassName": "MCPToolExecutionLog",
        "newClassName": "MJMCPToolExecutionLog",
        "oldCodeName": "MJ_MCPToolExecutionLogs",
        "newCodeName": "MJMCPToolExecutionLogs",
        "oldName": "MJ: O Auth Auth Server Metadata Caches",
        "newName": "MJ: O Auth Auth Server Metadata Caches",
        "oldClassName": "OAuthAuthServerMetadataCache",
        "newClassName": "MJOAuthAuthServerMetadataCache",
        "oldCodeName": "MJ_OAuthAuthServerMetadataCaches",
        "newCodeName": "MJOAuthAuthServerMetadataCaches",
        "oldName": "MJ: O Auth Authorization States",
        "newName": "MJ: O Auth Authorization States",
        "oldClassName": "OAuthAuthorizationState",
        "newClassName": "MJOAuthAuthorizationState",
        "oldCodeName": "MJ_OAuthAuthorizationStates",
        "newCodeName": "MJOAuthAuthorizationStates",
        "oldName": "MJ: O Auth Client Registrations",
        "newName": "MJ: O Auth Client Registrations",
        "oldClassName": "OAuthClientRegistration",
        "newClassName": "MJOAuthClientRegistration",
        "oldCodeName": "MJ_OAuthClientRegistrations",
        "newCodeName": "MJOAuthClientRegistrations",
        "oldName": "MJ: O Auth Tokens",
        "newName": "MJ: O Auth Tokens",
        "oldClassName": "OAuthToken",
        "newClassName": "MJOAuthToken",
        "oldCodeName": "MJ_OAuthTokens",
        "newCodeName": "MJOAuthTokens",
        "oldName": "MJ: Projects",
        "newName": "MJ: Projects",
        "oldClassName": "Project",
        "newClassName": "MJProject",
        "oldCodeName": "MJ_Projects",
        "newCodeName": "MJProjects",
        "oldName": "MJ: Public Links",
        "newName": "MJ: Public Links",
        "oldClassName": "PublicLink",
        "newClassName": "MJPublicLink",
        "oldCodeName": "MJ_PublicLinks",
        "newCodeName": "MJPublicLinks",
        "oldName": "MJ: Query Parameters",
        "newName": "MJ: Query Parameters",
        "oldClassName": "QueryParameter",
        "newClassName": "MJQueryParameter",
        "oldCodeName": "MJ_QueryParameters",
        "newCodeName": "MJQueryParameters",
        "oldName": "MJ: Record Links",
        "newName": "MJ: Record Links",
        "oldClassName": "RecordLink",
        "newClassName": "MJRecordLink",
        "oldCodeName": "MJ_RecordLinks",
        "newCodeName": "MJRecordLinks",
        "oldName": "MJ: Report User States",
        "newName": "MJ: Report User States",
        "oldClassName": "ReportUserState",
        "newClassName": "MJReportUserState",
        "oldCodeName": "MJ_ReportUserStates",
        "newCodeName": "MJReportUserStates",
        "oldName": "MJ: Report Versions",
        "newName": "MJ: Report Versions",
        "oldClassName": "ReportVersion",
        "newClassName": "MJReportVersion",
        "oldCodeName": "MJ_ReportVersions",
        "newCodeName": "MJReportVersions",
        "oldName": "MJ: Scheduled Job Runs",
        "newName": "MJ: Scheduled Job Runs",
        "oldClassName": "ScheduledJobRun",
        "newClassName": "MJScheduledJobRun",
        "oldCodeName": "MJ_ScheduledJobRuns",
        "newCodeName": "MJScheduledJobRuns",
        "oldName": "MJ: Scheduled Job Types",
        "newName": "MJ: Scheduled Job Types",
        "oldClassName": "ScheduledJobType",
        "newClassName": "MJScheduledJobType",
        "oldCodeName": "MJ_ScheduledJobTypes",
        "newCodeName": "MJScheduledJobTypes",
        "oldName": "MJ: Scheduled Jobs",
        "newName": "MJ: Scheduled Jobs",
        "oldClassName": "ScheduledJob",
        "newClassName": "MJScheduledJob",
        "oldCodeName": "MJ_ScheduledJobs",
        "newCodeName": "MJScheduledJobs",
        "oldName": "MJ: Task Dependencies",
        "newName": "MJ: Task Dependencies",
        "oldClassName": "TaskDependency",
        "newClassName": "MJTaskDependency",
        "oldCodeName": "MJ_TaskDependencies",
        "newCodeName": "MJTaskDependencies",
        "oldName": "MJ: Task Types",
        "newName": "MJ: Task Types",
        "oldClassName": "TaskType",
        "newClassName": "MJTaskType",
        "oldCodeName": "MJ_TaskTypes",
        "newCodeName": "MJTaskTypes",
        "oldName": "MJ: Tasks",
        "newName": "MJ: Tasks",
        "oldClassName": "Task",
        "newClassName": "MJTask",
        "oldCodeName": "MJ_Tasks",
        "newCodeName": "MJTasks",
        "oldName": "MJ: Test Rubrics",
        "newName": "MJ: Test Rubrics",
        "oldClassName": "TestRubric",
        "newClassName": "MJTestRubric",
        "oldCodeName": "MJ_TestRubrics",
        "newCodeName": "MJTestRubrics",
        "oldName": "MJ: Test Run Feedbacks",
        "newName": "MJ: Test Run Feedbacks",
        "oldClassName": "TestRunFeedback",
        "newClassName": "MJTestRunFeedback",
        "oldCodeName": "MJ_TestRunFeedbacks",
        "newCodeName": "MJTestRunFeedbacks",
        "oldName": "MJ: Test Runs",
        "newName": "MJ: Test Runs",
        "oldClassName": "TestRun",
        "newClassName": "MJTestRun",
        "oldCodeName": "MJ_TestRuns",
        "newCodeName": "MJTestRuns",
        "oldName": "MJ: Test Suite Runs",
        "newName": "MJ: Test Suite Runs",
        "oldClassName": "TestSuiteRun",
        "newClassName": "MJTestSuiteRun",
        "oldCodeName": "MJ_TestSuiteRuns",
        "newCodeName": "MJTestSuiteRuns",
        "oldName": "MJ: Test Suite Tests",
        "newName": "MJ: Test Suite Tests",
        "oldClassName": "TestSuiteTest",
        "newClassName": "MJTestSuiteTest",
        "oldCodeName": "MJ_TestSuiteTests",
        "newCodeName": "MJTestSuiteTests",
        "oldName": "MJ: Test Suites",
        "newName": "MJ: Test Suites",
        "oldClassName": "TestSuite",
        "newClassName": "MJTestSuite",
        "oldCodeName": "MJ_TestSuites",
        "newCodeName": "MJTestSuites",
        "oldName": "MJ: Test Types",
        "newName": "MJ: Test Types",
        "oldClassName": "TestType",
        "newClassName": "MJTestType",
        "oldCodeName": "MJ_TestTypes",
        "newCodeName": "MJTestTypes",
        "oldName": "MJ: Tests",
        "newName": "MJ: Tests",
        "oldClassName": "Test",
        "newClassName": "MJTest",
        "oldCodeName": "MJ_Tests",
        "newCodeName": "MJTests",
        "oldName": "MJ: User Notification Preferences",
        "newName": "MJ: User Notification Preferences",
        "oldClassName": "UserNotificationPreference",
        "newClassName": "MJUserNotificationPreference",
        "oldCodeName": "MJ_UserNotificationPreferences",
        "newCodeName": "MJUserNotificationPreferences",
        "oldName": "MJ: User Notification Types",
        "newName": "MJ: User Notification Types",
        "oldClassName": "UserNotificationType",
        "newClassName": "MJUserNotificationType",
        "oldCodeName": "MJ_UserNotificationTypes",
        "newCodeName": "MJUserNotificationTypes",
        "oldName": "MJ: User Settings",
        "newName": "MJ: User Settings",
        "oldClassName": "UserSetting",
        "newClassName": "MJUserSetting",
        "oldCodeName": "MJ_UserSettings",
        "newCodeName": "MJUserSettings",
        "oldName": "MJ: Version Label Items",
        "newName": "MJ: Version Label Items",
        "oldClassName": "VersionLabelItem",
        "newClassName": "MJVersionLabelItem",
        "oldCodeName": "MJ_VersionLabelItems",
        "newCodeName": "MJVersionLabelItems",
        "oldName": "MJ: Version Label Restores",
        "newName": "MJ: Version Label Restores",
        "oldClassName": "VersionLabelRestore",
        "newClassName": "MJVersionLabelRestore",
        "oldCodeName": "MJ_VersionLabelRestores",
        "newCodeName": "MJVersionLabelRestores",
        "oldName": "MJ: Version Labels",
        "newName": "MJ: Version Labels",
        "oldClassName": "VersionLabel",
        "newClassName": "MJVersionLabel",
        "oldCodeName": "MJ_VersionLabels",
        "newCodeName": "MJVersionLabels",
        "oldName": "Output Delivery Types",
        "newName": "MJ: Output Delivery Types",
        "oldClassName": "OutputDeliveryType",
        "newClassName": "MJOutputDeliveryType",
        "oldCodeName": "OutputDeliveryTypes",
        "newCodeName": "MJOutputDeliveryTypes",
        "oldName": "Output Format Types",
        "newName": "MJ: Output Format Types",
        "oldClassName": "OutputFormatType",
        "newClassName": "MJOutputFormatType",
        "oldCodeName": "OutputFormatTypes",
        "newCodeName": "MJOutputFormatTypes",
        "oldName": "Output Trigger Types",
        "newName": "MJ: Output Trigger Types",
        "oldClassName": "OutputTriggerType",
        "newClassName": "MJOutputTriggerType",
        "oldCodeName": "OutputTriggerTypes",
        "newCodeName": "MJOutputTriggerTypes",
        "oldName": "Queries",
        "newName": "MJ: Queries",
        "oldClassName": "Query",
        "newClassName": "MJQuery",
        "oldCodeName": "Queries",
        "newCodeName": "MJQueries",
        "oldName": "Query Categories",
        "newName": "MJ: Query Categories",
        "oldClassName": "QueryCategory",
        "newClassName": "MJQueryCategory",
        "oldCodeName": "QueryCategories",
        "newCodeName": "MJQueryCategories",
        "oldName": "Query Entities",
        "newName": "MJ: Query Entities",
        "oldClassName": "QueryEntity",
        "newClassName": "MJQueryEntity",
        "oldCodeName": "QueryEntities",
        "newCodeName": "MJQueryEntities",
        "oldName": "Query Fields",
        "newName": "MJ: Query Fields",
        "oldClassName": "QueryField",
        "newClassName": "MJQueryField",
        "oldCodeName": "QueryFields",
        "newCodeName": "MJQueryFields",
        "oldName": "Query Permissions",
        "newName": "MJ: Query Permissions",
        "oldClassName": "QueryPermission",
        "newClassName": "MJQueryPermission",
        "oldCodeName": "QueryPermissions",
        "newCodeName": "MJQueryPermissions",
        "oldName": "Queue Tasks",
        "newName": "MJ: Queue Tasks",
        "oldClassName": "QueueTask",
        "newClassName": "MJQueueTask",
        "oldCodeName": "QueueTasks",
        "newCodeName": "MJQueueTasks",
        "oldName": "Queue Types",
        "newName": "MJ: Queue Types",
        "oldClassName": "QueueType",
        "newClassName": "MJQueueType",
        "oldCodeName": "QueueTypes",
        "newCodeName": "MJQueueTypes",
        "oldName": "Queues",
        "newName": "MJ: Queues",
        "oldClassName": "Queue",
        "newClassName": "MJQueue",
        "oldCodeName": "Queues",
        "newCodeName": "MJQueues",
        "oldName": "Recommendation Items",
        "newName": "MJ: Recommendation Items",
        "oldClassName": "RecommendationItem",
        "newClassName": "MJRecommendationItem",
        "oldCodeName": "RecommendationItems",
        "newCodeName": "MJRecommendationItems",
        "oldName": "Recommendation Providers",
        "newName": "MJ: Recommendation Providers",
        "oldClassName": "RecommendationProvider",
        "newClassName": "MJRecommendationProvider",
        "oldCodeName": "RecommendationProviders",
        "newCodeName": "MJRecommendationProviders",
        "oldName": "Recommendation Runs",
        "newName": "MJ: Recommendation Runs",
        "oldClassName": "RecommendationRun",
        "newClassName": "MJRecommendationRun",
        "oldCodeName": "RecommendationRuns",
        "newCodeName": "MJRecommendationRuns",
        "oldName": "Recommendations",
        "newName": "MJ: Recommendations",
        "oldClassName": "Recommendation",
        "newClassName": "MJRecommendation",
        "oldCodeName": "Recommendations",
        "newCodeName": "MJRecommendations",
        "oldName": "Record Change Replay Runs",
        "newName": "MJ: Record Change Replay Runs",
        "oldClassName": "RecordChangeReplayRun",
        "newClassName": "MJRecordChangeReplayRun",
        "oldCodeName": "RecordChangeReplayRuns",
        "newCodeName": "MJRecordChangeReplayRuns",
        "oldName": "Record Changes",
        "newName": "MJ: Record Changes",
        "oldClassName": "RecordChange",
        "newClassName": "MJRecordChange",
        "oldCodeName": "RecordChanges",
        "newCodeName": "MJRecordChanges",
        "oldName": "Record Merge Deletion Logs",
        "newName": "MJ: Record Merge Deletion Logs",
        "oldClassName": "RecordMergeDeletionLog",
        "newClassName": "MJRecordMergeDeletionLog",
        "oldCodeName": "RecordMergeDeletionLogs",
        "newCodeName": "MJRecordMergeDeletionLogs",
        "oldName": "Record Merge Logs",
        "newName": "MJ: Record Merge Logs",
        "oldClassName": "RecordMergeLog",
        "newClassName": "MJRecordMergeLog",
        "oldCodeName": "RecordMergeLogs",
        "newCodeName": "MJRecordMergeLogs",
        "oldName": "Report Categories",
        "newName": "MJ: Report Categories",
        "oldClassName": "ReportCategory",
        "newClassName": "MJReportCategory",
        "oldCodeName": "ReportCategories",
        "newCodeName": "MJReportCategories",
        "oldName": "Report Snapshots",
        "newName": "MJ: Report Snapshots",
        "oldClassName": "ReportSnapshot",
        "newClassName": "MJReportSnapshot",
        "oldCodeName": "ReportSnapshots",
        "newCodeName": "MJReportSnapshots",
        "oldName": "Reports",
        "newName": "MJ: Reports",
        "oldClassName": "Report",
        "newClassName": "MJReport",
        "oldCodeName": "Reports",
        "newCodeName": "MJReports",
        "oldName": "Resource Links",
        "newName": "MJ: Resource Links",
        "oldClassName": "ResourceLink",
        "newClassName": "MJResourceLink",
        "oldCodeName": "ResourceLinks",
        "newCodeName": "MJResourceLinks",
        "oldName": "Resource Permissions",
        "newName": "MJ: Resource Permissions",
        "oldClassName": "ResourcePermission",
        "newClassName": "MJResourcePermission",
        "oldCodeName": "ResourcePermissions",
        "newCodeName": "MJResourcePermissions",
        "oldName": "Resource Types",
        "newName": "MJ: Resource Types",
        "oldClassName": "ResourceType",
        "newClassName": "MJResourceType",
        "oldCodeName": "ResourceTypes",
        "newCodeName": "MJResourceTypes",
        "oldName": "Roles",
        "newName": "MJ: Roles",
        "oldClassName": "Role",
        "newClassName": "MJRole",
        "oldCodeName": "Roles",
        "newCodeName": "MJRoles",
        "oldName": "Row Level Security Filters",
        "newName": "MJ: Row Level Security Filters",
        "oldClassName": "RowLevelSecurityFilter",
        "newClassName": "MJRowLevelSecurityFilter",
        "oldCodeName": "RowLevelSecurityFilters",
        "newCodeName": "MJRowLevelSecurityFilters",
        "oldName": "Scheduled Action Params",
        "newName": "MJ: Scheduled Action Params",
        "oldClassName": "ScheduledActionParam",
        "newClassName": "MJScheduledActionParam",
        "oldCodeName": "ScheduledActionParams",
        "newCodeName": "MJScheduledActionParams",
        "oldName": "Scheduled Actions",
        "newName": "MJ: Scheduled Actions",
        "oldClassName": "ScheduledAction",
        "newClassName": "MJScheduledAction",
        "oldCodeName": "ScheduledActions",
        "newCodeName": "MJScheduledActions",
        "oldName": "Schema Info",
        "newName": "MJ: Schema Info",
        "oldClassName": "SchemaInfo",
        "newClassName": "MJSchemaInfo",
        "oldCodeName": "SchemaInfo",
        "newCodeName": "MJSchemaInfo",
        "oldName": "Skills",
        "newName": "MJ: Skills",
        "oldClassName": "Skill",
        "newClassName": "MJSkill",
        "oldCodeName": "Skills",
        "newCodeName": "MJSkills",
        "oldName": "Tagged Items",
        "newName": "MJ: Tagged Items",
        "oldClassName": "TaggedItem",
        "newClassName": "MJTaggedItem",
        "oldCodeName": "TaggedItems",
        "newCodeName": "MJTaggedItems",
        "oldName": "Tags",
        "newName": "MJ: Tags",
        "oldClassName": "Tag",
        "newClassName": "MJTag",
        "oldCodeName": "Tags",
        "newCodeName": "MJTags",
        "oldName": "Template Categories",
        "newName": "MJ: Template Categories",
        "oldClassName": "TemplateCategory",
        "newClassName": "MJTemplateCategory",
        "oldCodeName": "TemplateCategories",
        "newCodeName": "MJTemplateCategories",
        "oldName": "Template Content Types",
        "newName": "MJ: Template Content Types",
        "oldClassName": "TemplateContentType",
        "newClassName": "MJTemplateContentType",
        "oldCodeName": "TemplateContentTypes",
        "newCodeName": "MJTemplateContentTypes",
        "oldName": "Template Contents",
        "newName": "MJ: Template Contents",
        "oldClassName": "TemplateContent",
        "newClassName": "MJTemplateContent",
        "oldCodeName": "TemplateContents",
        "newCodeName": "MJTemplateContents",
        "oldName": "Template Params",
        "newName": "MJ: Template Params",
        "oldClassName": "TemplateParam",
        "newClassName": "MJTemplateParam",
        "oldCodeName": "TemplateParams",
        "newCodeName": "MJTemplateParams",
        "oldName": "Templates",
        "newName": "MJ: Templates",
        "oldClassName": "Template",
        "newClassName": "MJTemplate",
        "oldCodeName": "Templates",
        "newCodeName": "MJTemplates",
        "oldName": "User Application Entities",
        "newName": "MJ: User Application Entities",
        "oldClassName": "UserApplicationEntity",
        "newClassName": "MJUserApplicationEntity",
        "oldCodeName": "UserApplicationEntities",
        "newCodeName": "MJUserApplicationEntities",
        "oldName": "User Applications",
        "newName": "MJ: User Applications",
        "oldClassName": "UserApplication",
        "newClassName": "MJUserApplication",
        "oldCodeName": "UserApplications",
        "newCodeName": "MJUserApplications",
        "oldName": "User Favorites",
        "newName": "MJ: User Favorites",
        "oldClassName": "UserFavorite",
        "newClassName": "MJUserFavorite",
        "oldCodeName": "UserFavorites",
        "newCodeName": "MJUserFavorites",
        "oldName": "User Notifications",
        "newName": "MJ: User Notifications",
        "oldClassName": "UserNotification",
        "newClassName": "MJUserNotification",
        "oldCodeName": "UserNotifications",
        "newCodeName": "MJUserNotifications",
        "oldName": "User Record Logs",
        "newName": "MJ: User Record Logs",
        "oldClassName": "UserRecordLog",
        "newClassName": "MJUserRecordLog",
        "oldCodeName": "UserRecordLogs",
        "newCodeName": "MJUserRecordLogs",
        "oldName": "User Roles",
        "newName": "MJ: User Roles",
        "oldClassName": "UserRole",
        "newClassName": "MJUserRole",
        "oldCodeName": "UserRoles",
        "newCodeName": "MJUserRoles",
        "oldName": "User View Categories",
        "newName": "MJ: User View Categories",
        "oldClassName": "UserViewCategory",
        "newClassName": "MJUserViewCategory",
        "oldCodeName": "UserViewCategories",
        "newCodeName": "MJUserViewCategories",
        "oldName": "User View Run Details",
        "newName": "MJ: User View Run Details",
        "oldClassName": "UserViewRunDetail",
        "newClassName": "MJUserViewRunDetail",
        "oldCodeName": "UserViewRunDetails",
        "newCodeName": "MJUserViewRunDetails",
        "oldName": "User View Runs",
        "newName": "MJ: User View Runs",
        "oldClassName": "UserViewRun",
        "newClassName": "MJUserViewRun",
        "oldCodeName": "UserViewRuns",
        "newCodeName": "MJUserViewRuns",
        "oldName": "User Views",
        "newName": "MJ: User Views",
        "oldClassName": "UserView",
        "newClassName": "MJUserView",
        "oldCodeName": "UserViews",
        "newCodeName": "MJUserViews",
        "oldName": "Users",
        "newName": "MJ: Users",
        "oldClassName": "User",
        "newClassName": "MJUser",
        "oldCodeName": "Users",
        "newCodeName": "MJUsers",
        "oldName": "Vector Databases",
        "newName": "MJ: Vector Databases",
        "oldClassName": "VectorDatabase",
        "newClassName": "MJVectorDatabase",
        "oldCodeName": "VectorDatabases",
        "newCodeName": "MJVectorDatabases",
        "oldName": "Vector Indexes",
        "newName": "MJ: Vector Indexes",
        "oldClassName": "VectorIndex",
        "newClassName": "MJVectorIndex",
        "oldCodeName": "VectorIndexes",
        "newCodeName": "MJVectorIndexes",
        "oldName": "Version Installations",
        "newName": "MJ: Version Installations",
        "oldClassName": "VersionInstallation",
        "newClassName": "MJVersionInstallation",
        "oldCodeName": "VersionInstallations",
        "newCodeName": "MJVersionInstallations",
        "oldName": "Workflow Engines",
        "newName": "MJ: Workflow Engines",
        "oldClassName": "WorkflowEngine",
        "newClassName": "MJWorkflowEngine",
        "oldCodeName": "WorkflowEngines",
        "newCodeName": "MJWorkflowEngines",
        "oldName": "Workflow Runs",
        "newName": "MJ: Workflow Runs",
        "oldClassName": "WorkflowRun",
        "newClassName": "MJWorkflowRun",
        "oldCodeName": "WorkflowRuns",
        "newCodeName": "MJWorkflowRuns",
        "oldName": "Workflows",
        "newName": "MJ: Workflows",
        "oldClassName": "Workflow",
        "newClassName": "MJWorkflow",
        "oldCodeName": "Workflows",
        "newCodeName": "MJWorkflows",
        "oldName": "Workspace Items",
        "newName": "MJ: Workspace Items",
        "oldClassName": "WorkspaceItem",
        "newClassName": "MJWorkspaceItem",
        "oldCodeName": "WorkspaceItems",
        "newCodeName": "MJWorkspaceItems",
        "oldName": "Workspaces",
        "newName": "MJ: Workspaces",
        "oldClassName": "Workspace",
        "newClassName": "MJWorkspace",
        "oldCodeName": "Workspaces",
        "newCodeName": "MJWorkspaces",
