from .image import Image
__all__ = ["ImagesResponse", "Usage", "UsageInputTokensDetails", "UsageOutputTokensDetails"]
class UsageOutputTokensDetails(BaseModel):
    """The output token details for the image generation."""
    """The number of image output tokens generated by the model."""
    """The number of text output tokens generated by the model."""
    """For `gpt-image-1` only, the token usage information for the image generation."""
    """The number of output tokens generated by the model."""
    output_tokens_details: Optional[UsageOutputTokensDetails] = None
class ImagesResponse(BaseModel):
    """The response from the image generation endpoint."""
    """The Unix timestamp (in seconds) of when the image was created."""
    background: Optional[Literal["transparent", "opaque"]] = None
    """The background parameter used for the image generation.
    Either `transparent` or `opaque`.
    data: Optional[List[Image]] = None
    """The list of generated images."""
    output_format: Optional[Literal["png", "webp", "jpeg"]] = None
    """The output format of the image generation. Either `png`, `webp`, or `jpeg`."""
    quality: Optional[Literal["low", "medium", "high"]] = None
    """The quality of the image generated. Either `low`, `medium`, or `high`."""
    size: Optional[Literal["1024x1024", "1024x1536", "1536x1024"]] = None
    """The size of the image generated.
    Either `1024x1024`, `1024x1536`, or `1536x1024`.
    usage: Optional[Usage] = None
