import { UserInfo, Metadata, RunView, LogError, LogStatus } from '@memberjunction/core';
import { MJAIAgentNoteEntity, MJAIAgentExampleEntity } from '@memberjunction/core-entities';
import { ExecuteAgentParams, AIAgentEntityExtended, AgentConfiguration, BaseAgentNextStep } from '@memberjunction/ai-core-plus';
 * Result of a cleanup operation
interface CleanupResult {
    notesArchived: number;
    examplesArchived: number;
    notesExpired: number;
    examplesExpired: number;
 * Memory Cleanup Agent - archives stale notes and examples based on retention policies.
 * This agent runs on a daily schedule and:
 * 1. Archives notes not accessed within NoteRetentionDays (per agent config, default 90)
 * 2. Archives examples with SuccessScore < 50 after ExampleRetentionDays (default 180)
 * 3. Archives any items past their ExpiresAt timestamp
 * Only processes auto-generated items (IsAutoGenerated = true) to preserve manual entries.
export class MemoryCleanupAgent extends BaseAgent {
    private readonly DEFAULT_NOTE_RETENTION_DAYS = 90;
    private readonly DEFAULT_EXAMPLE_RETENTION_DAYS = 180;
    private readonly LOW_SUCCESS_SCORE_THRESHOLD = 50;
     * Main entry point for the cleanup agent
        LogStatus('MemoryCleanupAgent: Starting cleanup process');
        const contextUser = params.contextUser!;
        const result: CleanupResult = {
            notesArchived: 0,
            examplesArchived: 0,
            notesExpired: 0,
            examplesExpired: 0,
            // Process expired items first (these have explicit ExpiresAt timestamps)
            await this.archiveExpiredItems(result, contextUser);
            // Then process stale items based on retention policies
            await this.archiveStaleItems(result, contextUser);
            const summary = this.buildSummary(result);
            LogStatus(`MemoryCleanupAgent: Cleanup completed - ${summary}`);
            const finalStep: BaseAgentNextStep<P> = {
                message: summary
            return { finalStep, stepCount: 1 };
            const errorMessage = error instanceof Error ? error.message : String(error);
            LogError('MemoryCleanupAgent: Cleanup failed', undefined, error);
                message: `Cleanup failed: ${errorMessage}`
     * Archive items that have passed their ExpiresAt timestamp
    private async archiveExpiredItems(result: CleanupResult, contextUser: UserInfo): Promise<void> {
        // Archive expired notes
        const expiredNotes = await this.queryExpiredNotes(now, contextUser);
        for (const note of expiredNotes) {
            const archived = await this.archiveNote(note, 'Expired', contextUser);
            if (archived) {
                result.notesExpired++;
                result.errors.push(`Failed to archive expired note ${note.ID}`);
        // Archive expired examples
        const expiredExamples = await this.queryExpiredExamples(now, contextUser);
        for (const example of expiredExamples) {
            const archived = await this.archiveExample(example, 'Expired', contextUser);
                result.examplesExpired++;
                result.errors.push(`Failed to archive expired example ${example.ID}`);
     * Archive items based on per-agent retention policies
    private async archiveStaleItems(result: CleanupResult, contextUser: UserInfo): Promise<void> {
        // Get all agents with auto-archive enabled
        const agents = AIEngine.Instance.Agents.filter(a =>
            a.Status === 'Active' &&
            this.getAutoArchiveEnabled(a)
            const noteRetentionDays = this.getNoteRetentionDays(agent);
            const exampleRetentionDays = this.getExampleRetentionDays(agent);
            // Archive stale notes for this agent
            const staleNotes = await this.queryStaleNotes(agent.ID, noteRetentionDays, contextUser);
            for (const note of staleNotes) {
                const archived = await this.archiveNote(note, `Stale (${noteRetentionDays} days)`, contextUser);
                    result.notesArchived++;
                    result.errors.push(`Failed to archive stale note ${note.ID}`);
            // Archive stale low-scoring examples for this agent
            const staleExamples = await this.queryStaleExamples(agent.ID, exampleRetentionDays, contextUser);
            for (const example of staleExamples) {
                const archived = await this.archiveExample(example, `Stale low-score (${exampleRetentionDays} days)`, contextUser);
                    result.examplesArchived++;
                    result.errors.push(`Failed to archive stale example ${example.ID}`);
     * Query for notes past their ExpiresAt timestamp
    private async queryExpiredNotes(now: string, contextUser: UserInfo): Promise<MJAIAgentNoteEntity[]> {
            ExtraFilter: `Status = 'Active' AND ExpiresAt IS NOT NULL AND ExpiresAt < '${now}'`,
            MaxRows: 1000,
        return result.Success ? result.Results : [];
     * Query for examples past their ExpiresAt timestamp
    private async queryExpiredExamples(now: string, contextUser: UserInfo): Promise<MJAIAgentExampleEntity[]> {
        const result = await rv.RunView<MJAIAgentExampleEntity>({
            EntityName: 'MJ: AI Agent Examples',
     * Query for stale auto-generated notes (not accessed within retention period)
    private async queryStaleNotes(
        retentionDays: number,
    ): Promise<MJAIAgentNoteEntity[]> {
        const cutoffDate = this.getCutoffDate(retentionDays);
        // Query notes that are:
        // - For this agent
        // - Auto-generated (don't archive manual notes)
        // - Active status
        // - Last accessed before cutoff (or never accessed and created before cutoff)
            ExtraFilter: `
                AgentID = '${agentId}'
                AND IsAutoGenerated = 1
                AND Status = 'Active'
                AND (
                    (LastAccessedAt IS NOT NULL AND LastAccessedAt < '${cutoffDate}')
                    OR (LastAccessedAt IS NULL AND __mj_CreatedAt < '${cutoffDate}')
            MaxRows: 500,
     * Query for stale auto-generated examples with low success scores
    private async queryStaleExamples(
    ): Promise<MJAIAgentExampleEntity[]> {
        // Query examples that are:
        // - Auto-generated
        // - Low success score (< 50)
                AND SuccessScore < ${this.LOW_SUCCESS_SCORE_THRESHOLD}
     * Archive a note by setting its status to 'Archived'
    private async archiveNote(
        note: MJAIAgentNoteEntity,
        reason: string,
    ): Promise<boolean> {
            note.Status = 'Archived' as 'Active' | 'Pending' | 'Revoked'; // TypeScript doesn't know about new status yet
            note.Comments = `${note.Comments ? note.Comments + '\n' : ''}[Archived by Memory Cleanup Agent: ${reason} on ${new Date().toISOString()}]`;
            const saved = await note.Save();
                LogStatus(`MemoryCleanupAgent: Archived note ${note.ID} - ${reason}`);
            return saved;
            LogError(`MemoryCleanupAgent: Failed to archive note ${note.ID}`, undefined, error);
     * Archive an example by setting its status to 'Archived'
    private async archiveExample(
        example: MJAIAgentExampleEntity,
            example.Status = 'Archived' as 'Active' | 'Pending' | 'Revoked';
            example.Comments = `${example.Comments ? example.Comments + '\n' : ''}[Archived by Memory Cleanup Agent: ${reason} on ${new Date().toISOString()}]`;
            const saved = await example.Save();
                LogStatus(`MemoryCleanupAgent: Archived example ${example.ID} - ${reason}`);
            LogError(`MemoryCleanupAgent: Failed to archive example ${example.ID}`, undefined, error);
     * Get note retention days for an agent (uses agent config or default)
    private getNoteRetentionDays(agent: AIAgentEntityExtended): number {
        // Check if agent has NoteRetentionDays property using GetAll() for plain object access
        const agentData = agent.GetAll();
        const retention = agentData['NoteRetentionDays'];
        if (typeof retention === 'number' && retention > 0) {
            return retention;
        return this.DEFAULT_NOTE_RETENTION_DAYS;
     * Get example retention days for an agent (uses agent config or default)
    private getExampleRetentionDays(agent: AIAgentEntityExtended): number {
        const retention = agentData['ExampleRetentionDays'];
        return this.DEFAULT_EXAMPLE_RETENTION_DAYS;
     * Check if auto-archive is enabled for an agent
    private getAutoArchiveEnabled(agent: AIAgentEntityExtended): boolean {
        const enabled = agentData['AutoArchiveEnabled'];
        // Default to true if not explicitly set to false
        return enabled !== false;
     * Calculate cutoff date (now - retentionDays)
    private getCutoffDate(retentionDays: number): string {
        const cutoff = new Date();
        cutoff.setDate(cutoff.getDate() - retentionDays);
        return cutoff.toISOString();
     * Build summary message for cleanup results
    private buildSummary(result: CleanupResult): string {
        if (result.notesArchived > 0) {
            parts.push(`${result.notesArchived} stale notes archived`);
        if (result.examplesArchived > 0) {
            parts.push(`${result.examplesArchived} stale examples archived`);
        if (result.notesExpired > 0) {
            parts.push(`${result.notesExpired} expired notes archived`);
        if (result.examplesExpired > 0) {
            parts.push(`${result.examplesExpired} expired examples archived`);
        if (parts.length === 0) {
            parts.push('No items needed archiving');
        if (result.errors.length > 0) {
            parts.push(`${result.errors.length} errors encountered`);
        return parts.join(', ');
