from ....pagination import SyncCursorPage, AsyncCursorPage
from ...._base_client import (
from ....types.beta.threads import message_list_params, message_create_params, message_update_params
from ....types.beta.threads.message import Message
from ....types.shared_params.metadata import Metadata
from ....types.beta.threads.message_deleted import MessageDeleted
from ....types.beta.threads.message_content_part_param import MessageContentPartParam
__all__ = ["Messages", "AsyncMessages"]
class Messages(SyncAPIResource):
    def with_raw_response(self) -> MessagesWithRawResponse:
        return MessagesWithRawResponse(self)
    def with_streaming_response(self) -> MessagesWithStreamingResponse:
        return MessagesWithStreamingResponse(self)
    @typing_extensions.deprecated("The Assistants API is deprecated in favor of the Responses API")
        content: Union[str, Iterable[MessageContentPartParam]],
        role: Literal["user", "assistant"],
        attachments: Optional[Iterable[message_create_params.Attachment]] | Omit = omit,
    ) -> Message:
        Create a message.
          content: The text contents of the message.
          role:
              The role of the entity that is creating the message. Allowed values include:
              - `user`: Indicates the message is sent by an actual user and should be used in
                most cases to represent user-generated messages.
              - `assistant`: Indicates the message is generated by the assistant. Use this
                value to insert messages from the assistant into the conversation.
          attachments: A list of files attached to the message, and the tools they should be added to.
            path_template("/threads/{thread_id}/messages", thread_id=thread_id),
                    "content": content,
                    "role": role,
                    "attachments": attachments,
                message_create_params.MessageCreateParams,
            cast_to=Message,
        message_id: str,
        Retrieve a message.
        if not message_id:
            raise ValueError(f"Expected a non-empty value for `message_id` but received {message_id!r}")
            path_template("/threads/{thread_id}/messages/{message_id}", thread_id=thread_id, message_id=message_id),
        Modifies a message.
            body=maybe_transform({"metadata": metadata}, message_update_params.MessageUpdateParams),
        run_id: str | Omit = omit,
    ) -> SyncCursorPage[Message]:
        Returns a list of messages for a given thread.
          after: A cursor for use in pagination. `after` is an object ID that defines your place
          run_id: Filter messages by the run ID that generated them.
            page=SyncCursorPage[Message],
                        "run_id": run_id,
                    message_list_params.MessageListParams,
            model=Message,
    ) -> MessageDeleted:
        Deletes a message.
            cast_to=MessageDeleted,
class AsyncMessages(AsyncAPIResource):
    def with_raw_response(self) -> AsyncMessagesWithRawResponse:
        return AsyncMessagesWithRawResponse(self)
    def with_streaming_response(self) -> AsyncMessagesWithStreamingResponse:
        return AsyncMessagesWithStreamingResponse(self)
            body=await async_maybe_transform({"metadata": metadata}, message_update_params.MessageUpdateParams),
    ) -> AsyncPaginator[Message, AsyncCursorPage[Message]]:
            page=AsyncCursorPage[Message],
class MessagesWithRawResponse:
    def __init__(self, messages: Messages) -> None:
        self._messages = messages
                messages.create,  # pyright: ignore[reportDeprecated],
                messages.retrieve,  # pyright: ignore[reportDeprecated],
                messages.update,  # pyright: ignore[reportDeprecated],
                messages.list,  # pyright: ignore[reportDeprecated],
                messages.delete,  # pyright: ignore[reportDeprecated],
class AsyncMessagesWithRawResponse:
    def __init__(self, messages: AsyncMessages) -> None:
class MessagesWithStreamingResponse:
class AsyncMessagesWithStreamingResponse:
from ....types.chat.completions import message_list_params
from ....types.chat.chat_completion_store_message import ChatCompletionStoreMessage
    ) -> SyncCursorPage[ChatCompletionStoreMessage]:
        """Get the messages in a stored chat completion.
        Only Chat Completions that have
        been created with the `store` parameter set to `true` will be returned.
          after: Identifier for the last message from the previous pagination request.
          limit: Number of messages to retrieve.
          order: Sort order for messages by timestamp. Use `asc` for ascending order or `desc`
              for descending order. Defaults to `asc`.
            path_template("/chat/completions/{completion_id}/messages", completion_id=completion_id),
            page=SyncCursorPage[ChatCompletionStoreMessage],
            model=ChatCompletionStoreMessage,
    ) -> AsyncPaginator[ChatCompletionStoreMessage, AsyncCursorPage[ChatCompletionStoreMessage]]:
            page=AsyncCursorPage[ChatCompletionStoreMessage],
            messages.list,
# Levels
DEBUG = 10
INFO = 20
WARNING = 30
ERROR = 40
CRITICAL = 50
class CheckMessage:
    def __init__(self, level, msg, hint=None, obj=None, id=None):
            raise TypeError("The first argument should be level.")
        self.level = level
        self.hint = hint
        self.obj = obj
        return isinstance(other, self.__class__) and all(
            getattr(self, attr) == getattr(other, attr)
            for attr in ["level", "msg", "hint", "obj", "id"]
        if self.obj is None:
            obj = "?"
        elif isinstance(self.obj, models.base.ModelBase):
            # We need to hardcode ModelBase and Field cases because its __str__
            # method doesn't return "applabel.modellabel" and cannot be
            # changed.
            obj = self.obj._meta.label
            obj = str(self.obj)
        id = "(%s) " % self.id if self.id else ""
        hint = "\n\tHINT: %s" % self.hint if self.hint else ""
        return "%s: %s%s%s" % (obj, id, self.msg, hint)
        return "<%s: level=%r, msg=%r, hint=%r, obj=%r, id=%r>" % (
            self.__class__.__name__,
            self.level,
            self.msg,
            self.hint,
            self.obj,
            self.id,
    def is_serious(self, level=ERROR):
        return self.level >= level
    def is_silenced(self):
        return self.id in settings.SILENCED_SYSTEM_CHECKS
class Debug(CheckMessage):
        super().__init__(DEBUG, *args, **kwargs)
class Info(CheckMessage):
        super().__init__(INFO, *args, **kwargs)
class Warning(CheckMessage):
        super().__init__(WARNING, *args, **kwargs)
class Error(CheckMessage):
        super().__init__(ERROR, *args, **kwargs)
class Critical(CheckMessage):
        super().__init__(CRITICAL, *args, **kwargs)
    SystemMessageChunk,
"""Redefined messages as a work-around for pydantic issue with AnyStr.
The code below creates version of pydantic models
that will work in unit tests with AnyStr as id field
Please note that the `id` field is assigned AFTER the model is created
to workaround an issue with pydantic ignoring the __eq__ method on
subclassed strings.
from langchain_core.messages import HumanMessage, ToolMessage
from tests.unit_tests.agents.any_str import AnyStr
def _AnyIdHumanMessage(**kwargs: Any) -> HumanMessage:  # noqa: N802
    """Create a human message with an any id field."""
    message = HumanMessage(**kwargs)
    message.id = AnyStr()
def _AnyIdToolMessage(**kwargs: Any) -> ToolMessage:  # noqa: N802
    """Create a tool message with an any id field."""
    message = ToolMessage(**kwargs)
Provide the class Message and its subclasses.
    message = ''
    message_args = ()
    def __init__(self, filename, loc):
        self.lineno = loc.lineno
        self.col = loc.col_offset
        return '{}:{}:{}: {}'.format(self.filename, self.lineno, self.col+1,
                                     self.message % self.message_args)
class UnusedImport(Message):
    message = '%r imported but unused'
    def __init__(self, filename, loc, name):
        Message.__init__(self, filename, loc)
        self.message_args = (name,)
class RedefinedWhileUnused(Message):
    message = 'redefinition of unused %r from line %r'
    def __init__(self, filename, loc, name, orig_loc):
        self.message_args = (name, orig_loc.lineno)
class ImportShadowedByLoopVar(Message):
    message = 'import %r from line %r shadowed by loop variable'
class ImportStarNotPermitted(Message):
    message = "'from %s import *' only allowed at module level"
    def __init__(self, filename, loc, modname):
        self.message_args = (modname,)
class ImportStarUsed(Message):
    message = "'from %s import *' used; unable to detect undefined names"
class ImportStarUsage(Message):
    message = "%r may be undefined, or defined from star imports: %s"
    def __init__(self, filename, loc, name, from_list):
        self.message_args = (name, from_list)
class UndefinedName(Message):
    message = 'undefined name %r'
class DoctestSyntaxError(Message):
    message = 'syntax error in doctest'
    def __init__(self, filename, loc, position=None):
        if position:
            (self.lineno, self.col) = position
        self.message_args = ()
class UndefinedExport(Message):
    message = 'undefined name %r in __all__'
class UndefinedLocal(Message):
    message = 'local variable %r {0} referenced before assignment'
    default = 'defined in enclosing scope on line %r'
    builtin = 'defined as a builtin'
        if orig_loc is None:
            self.message = self.message.format(self.builtin)
            self.message_args = name
            self.message = self.message.format(self.default)
class DuplicateArgument(Message):
    message = 'duplicate argument %r in function definition'
class MultiValueRepeatedKeyLiteral(Message):
    message = 'dictionary key %r repeated with different values'
    def __init__(self, filename, loc, key):
        self.message_args = (key,)
class MultiValueRepeatedKeyVariable(Message):
    message = 'dictionary key variable %s repeated with different values'
class LateFutureImport(Message):
    message = 'from __future__ imports must occur at the beginning of the file'
class FutureFeatureNotDefined(Message):
    """An undefined __future__ feature name was imported."""
    message = 'future feature %s is not defined'
class UnusedVariable(Message):
    Indicates that a variable has been explicitly assigned to but not actually
    message = 'local variable %r is assigned to but never used'
    def __init__(self, filename, loc, names):
        self.message_args = (names,)
class UnusedAnnotation(Message):
    Indicates that a variable has been explicitly annotated to but not actually
    message = 'local variable %r is annotated but never used'
class UnusedIndirectAssignment(Message):
    """A `global` or `nonlocal` statement where the name is never reassigned"""
    message = '`%s %s` is unused: name is never assigned in scope'
        self.message_args = (type(loc).__name__.lower(), name)
class ReturnOutsideFunction(Message):
    Indicates a return statement outside of a function/method.
    message = '\'return\' outside function'
class YieldOutsideFunction(Message):
    Indicates a yield or yield from statement outside of a function/method.
    message = '\'yield\' outside function'
# For whatever reason, Python gives different error messages for these two. We
# match the Python error message exactly.
class ContinueOutsideLoop(Message):
    Indicates a continue statement outside of a while or for loop.
    message = '\'continue\' not properly in loop'
class BreakOutsideLoop(Message):
    Indicates a break statement outside of a while or for loop.
    message = '\'break\' outside loop'
class DefaultExceptNotLast(Message):
    Indicates an except: block as not the last exception handler.
    message = 'default \'except:\' must be last'
class TwoStarredExpressions(Message):
    Two or more starred expressions in an assignment (a, *b, *c = d).
    message = 'two starred expressions in assignment'
class TooManyExpressionsInStarredAssignment(Message):
    Too many expressions in an assignment with star-unpacking
    message = 'too many expressions in star-unpacking assignment'
class IfTuple(Message):
    Conditional test is a non-empty tuple literal, which are always True.
    message = '\'if tuple literal\' is always true, perhaps remove accidental comma?'
class AssertTuple(Message):
    Assertion test is a non-empty tuple literal, which are always True.
    message = 'assertion is always true, perhaps remove parentheses?'
class ForwardAnnotationSyntaxError(Message):
    message = 'syntax error in forward annotation %r'
    def __init__(self, filename, loc, annotation):
        self.message_args = (annotation,)
class RaiseNotImplemented(Message):
    message = "'raise NotImplemented' should be 'raise NotImplementedError'"
class InvalidPrintSyntax(Message):
    message = 'use of >> is invalid with print function'
class IsLiteral(Message):
    message = 'use ==/!= to compare constant literals (str, bytes, int, float, tuple)'
class FStringMissingPlaceholders(Message):
    message = 'f-string is missing placeholders'
class TStringMissingPlaceholders(Message):
    message = 't-string is missing placeholders'
class StringDotFormatExtraPositionalArguments(Message):
    message = "'...'.format(...) has unused arguments at position(s): %s"
    def __init__(self, filename, loc, extra_positions):
        self.message_args = (extra_positions,)
class StringDotFormatExtraNamedArguments(Message):
    message = "'...'.format(...) has unused named argument(s): %s"
    def __init__(self, filename, loc, extra_keywords):
        self.message_args = (extra_keywords,)
class StringDotFormatMissingArgument(Message):
    message = "'...'.format(...) is missing argument(s) for placeholder(s): %s"
    def __init__(self, filename, loc, missing_arguments):
        self.message_args = (missing_arguments,)
class StringDotFormatMixingAutomatic(Message):
    message = "'...'.format(...) mixes automatic and manual numbering"
class StringDotFormatInvalidFormat(Message):
    message = "'...'.format(...) has invalid format string: %s"
    def __init__(self, filename, loc, error):
        self.message_args = (error,)
class PercentFormatInvalidFormat(Message):
    message = "'...' %% ... has invalid format string: %s"
class PercentFormatMixedPositionalAndNamed(Message):
    message = "'...' %% ... has mixed positional and named placeholders"
class PercentFormatUnsupportedFormatCharacter(Message):
    message = "'...' %% ... has unsupported format character %r"
    def __init__(self, filename, loc, c):
        self.message_args = (c,)
class PercentFormatPositionalCountMismatch(Message):
    message = "'...' %% ... has %d placeholder(s) but %d substitution(s)"
    def __init__(self, filename, loc, n_placeholders, n_substitutions):
        self.message_args = (n_placeholders, n_substitutions)
class PercentFormatExtraNamedArguments(Message):
    message = "'...' %% ... has unused named argument(s): %s"
class PercentFormatMissingArgument(Message):
    message = "'...' %% ... is missing argument(s) for placeholder(s): %s"
class PercentFormatExpectedMapping(Message):
    message = "'...' %% ... expected mapping but got sequence"
class PercentFormatExpectedSequence(Message):
    message = "'...' %% ... expected sequence but got mapping"
class PercentFormatStarRequiresSequence(Message):
    message = "'...' %% ... `*` specifier requires sequence"
            f"/threads/{thread_id}/messages",
            f"/threads/{thread_id}/messages/{message_id}",
            f"/chat/completions/{completion_id}/messages",
