 * App: @memberjunction/ng-bootstrap
 * Dependency tree: 513 packages walked, 14 contain @RegisterClass
// @memberjunction/actions-base (2 classes)
    EntityActionEntityExtended,
} from '@memberjunction/actions-base';
// @memberjunction/ai-core-plus (7 classes)
    AIAgentEntityExtended,
    AIAgentRunEntityExtended,
    AIAgentRunStepEntityExtended,
    AIModelEntityExtended,
    AIPromptCategoryEntityExtended,
    AIPromptEntityExtended,
    AIPromptRunEntityExtended,
// @memberjunction/ai-engine-base (4 classes)
    AICredentialBindingEntityExtended,
} from '@memberjunction/ai-engine-base';
// @memberjunction/communication-types (1 classes)
    CommunicationProviderEntityExtended,
} from '@memberjunction/communication-types';
// @memberjunction/core-entities (282 classes)
    ComponentEntityExtended,
    DashboardEntityExtended,
    EntityEntityExtended,
    EntityFieldEntityExtended,
    EnvironmentEntityExtended,
    ListDetailEntityExtended,
    MJAIActionEntity,
    MJAIAgentArtifactTypeEntity,
    MJAIAgentLearningCycleEntity,
    MJAIAgentModelEntity,
    MJAIAgentNoteTypeEntity,
    MJAIAgentRequestEntity,
    MJAIAgentRunMediaEntity,
    MJAIAgentRunStepEntity,
    MJAIArchitectureEntity,
    MJAIModelArchitectureEntity,
    MJAIModelModalityEntity,
    MJAIPromptCategoryEntity,
    MJAIPromptEntity,
    MJAIPromptModelEntity,
    MJAIPromptRunEntity,
    MJAIPromptRunMediaEntity,
    MJAIPromptTypeEntity,
    MJAIResultCacheEntity,
    MJAIVendorTypeDefinitionEntity,
    MJAIVendorTypeEntity,
    MJAPIKeyUsageLogEntity,
    MJAccessControlRuleEntity,
    MJActionAuthorizationEntity,
    MJActionContextEntity,
    MJActionContextTypeEntity,
    MJActionExecutionLogEntity,
    MJActionFilterEntity,
    MJActionLibraryEntity,
    MJActionResultCodeEntity,
    MJApplicationEntity,
    MJApplicationEntityEntity,
    MJApplicationSettingEntity,
    MJArtifactEntity,
    MJArtifactPermissionEntity,
    MJArtifactTypeEntity,
    MJArtifactUseEntity,
    MJArtifactVersionAttributeEntity,
    MJArtifactVersionEntity,
    MJAuditLogEntity,
    MJAuditLogTypeEntity,
    MJAuthorizationEntity,
    MJAuthorizationRoleEntity,
    MJCollectionArtifactEntity,
    MJCollectionEntity,
    MJCollectionPermissionEntity,
    MJCommunicationBaseMessageTypeEntity,
    MJCommunicationLogEntity,
    MJCommunicationProviderEntity,
    MJCommunicationProviderMessageTypeEntity,
    MJCommunicationRunEntity,
    MJCompanyEntity,
    MJCompanyIntegrationEntity,
    MJCompanyIntegrationRecordMapEntity,
    MJCompanyIntegrationRunAPILogEntity,
    MJCompanyIntegrationRunDetailEntity,
    MJCompanyIntegrationRunEntity,
    MJComponentDependencyEntity,
    MJComponentEntity,
    MJComponentLibraryEntity,
    MJComponentLibraryLinkEntity,
    MJComponentRegistryEntity,
    MJContentFileTypeEntity,
    MJContentItemAttributeEntity,
    MJContentItemEntity,
    MJContentItemTagEntity,
    MJContentProcessRunEntity,
    MJContentSourceEntity,
    MJContentSourceParamEntity,
    MJContentSourceTypeEntity,
    MJContentSourceTypeParamEntity,
    MJContentTypeAttributeEntity,
    MJContentTypeEntity,
    MJConversationArtifactEntity,
    MJConversationArtifactPermissionEntity,
    MJConversationArtifactVersionEntity,
    MJConversationDetailArtifactEntity,
    MJConversationEntity,
    MJCredentialCategoryEntity,
    MJCredentialEntity,
    MJCredentialTypeEntity,
    MJDashboardCategoryEntity,
    MJDashboardCategoryLinkEntity,
    MJDashboardCategoryPermissionEntity,
    MJDashboardEntity,
    MJDashboardPartTypeEntity,
    MJDashboardPermissionEntity,
    MJDashboardUserPreferenceEntity,
    MJDashboardUserStateEntity,
    MJDataContextEntity,
    MJDataContextItemEntity,
    MJDatasetEntity,
    MJDatasetItemEntity,
    MJDuplicateRunDetailEntity,
    MJDuplicateRunDetailMatchEntity,
    MJDuplicateRunEntity,
    MJEmployeeCompanyIntegrationEntity,
    MJEmployeeEntity,
    MJEmployeeRoleEntity,
    MJEmployeeSkillEntity,
    MJEncryptionAlgorithmEntity,
    MJEncryptionKeyEntity,
    MJEncryptionKeySourceEntity,
    MJEntityAIActionEntity,
    MJEntityActionEntity,
    MJEntityActionFilterEntity,
    MJEntityActionInvocationEntity,
    MJEntityActionInvocationTypeEntity,
    MJEntityActionParamEntity,
    MJEntityCommunicationFieldEntity,
    MJEntityCommunicationMessageTypeEntity,
    MJEntityDocumentEntity,
    MJEntityDocumentRunEntity,
    MJEntityDocumentSettingEntity,
    MJEntityDocumentTypeEntity,
    MJEntityEntity,
    MJEntityFieldEntity,
    MJEntityFieldValueEntity,
    MJEntityPermissionEntity,
    MJEntityRecordDocumentEntity,
    MJEntityRelationshipDisplayComponentEntity,
    MJEntityRelationshipEntity,
    MJEntitySettingEntity,
    MJEnvironmentEntity,
    MJErrorLogEntity,
    MJExplorerNavigationItemEntity,
    MJFileCategoryEntity,
    MJFileEntityRecordLinkEntity,
    MJFileStorageAccountEntity,
    MJGeneratedCodeCategoryEntity,
    MJGeneratedCodeEntity,
    MJIntegrationEntity,
    MJIntegrationURLFormatEntity,
    MJLibraryEntity,
    MJLibraryItemEntity,
    MJListCategoryEntity,
    MJListDetailEntity,
    MJListEntity,
    MJListInvitationEntity,
    MJListShareEntity,
    MJMCPServerConnectionPermissionEntity,
    MJMCPServerConnectionToolEntity,
    MJMCPToolExecutionLogEntity,
    MJOAuthAuthServerMetadataCacheEntity,
    MJOAuthAuthorizationStateEntity,
    MJOAuthClientRegistrationEntity,
    MJOAuthTokenEntity,
    MJOutputDeliveryTypeEntity,
    MJOutputFormatTypeEntity,
    MJOutputTriggerTypeEntity,
    MJProjectEntity,
    MJPublicLinkEntity,
    MJQueryCategoryEntity,
    MJQueryEntity,
    MJQueryEntityEntity,
    MJQueryFieldEntity,
    MJQueryParameterEntity,
    MJQueryPermissionEntity,
    MJQueueEntity,
    MJQueueTaskEntity,
    MJQueueTypeEntity,
    MJRecommendationEntity,
    MJRecommendationItemEntity,
    MJRecommendationProviderEntity,
    MJRecommendationRunEntity,
    MJRecordChangeEntity,
    MJRecordChangeReplayRunEntity,
    MJRecordLinkEntity,
    MJRecordMergeDeletionLogEntity,
    MJRecordMergeLogEntity,
    MJReportCategoryEntity,
    MJReportEntity,
    MJReportSnapshotEntity,
    MJReportUserStateEntity,
    MJReportVersionEntity,
    MJResourceLinkEntity,
    MJResourcePermissionEntity,
    MJResourceTypeEntity,
    MJRoleEntity,
    MJRowLevelSecurityFilterEntity,
    MJScheduledActionEntity,
    MJScheduledActionParamEntity,
    MJScheduledJobEntity,
    MJScheduledJobRunEntity,
    MJScheduledJobTypeEntity,
    MJSchemaInfoEntity,
    MJSkillEntity,
    MJTagEntity,
    MJTaggedItemEntity,
    MJTaskDependencyEntity,
    MJTaskEntity,
    MJTaskTypeEntity,
    MJTemplateCategoryEntity,
    MJTemplateContentEntity,
    MJTemplateContentTypeEntity,
    MJTemplateEntity,
    MJTemplateParamEntity,
    MJTestEntity,
    MJTestRubricEntity,
    MJTestRunEntity,
    MJTestRunFeedbackEntity,
    MJTestSuiteEntity,
    MJTestSuiteRunEntity,
    MJTestSuiteTestEntity,
    MJTestTypeEntity,
    MJUserApplicationEntity,
    MJUserApplicationEntityEntity,
    MJUserEntity,
    MJUserFavoriteEntity,
    MJUserNotificationEntity,
    MJUserNotificationPreferenceEntity,
    MJUserNotificationTypeEntity,
    MJUserRecordLogEntity,
    MJUserRoleEntity,
    MJUserSettingEntity,
    MJUserViewCategoryEntity,
    MJUserViewEntity,
    MJUserViewRunDetailEntity,
    MJUserViewRunEntity,
    MJVectorDatabaseEntity,
    MJVectorIndexEntity,
    MJVersionInstallationEntity,
    MJVersionLabelEntity,
    MJVersionLabelItemEntity,
    MJVersionLabelRestoreEntity,
    MJWorkflowEngineEntity,
    MJWorkflowEntity,
    MJWorkflowRunEntity,
    MJWorkspaceEntity,
    MJWorkspaceItemEntity,
    ResourcePermissionEntityExtended,
    ScheduledActionEntityExtended,
    TemplateEntityExtended,
    UserViewEntityExtended,
// @memberjunction/entity-communications-base (1 classes)
    EntityCommunicationMessageTypeExtended,
} from '@memberjunction/entity-communications-base';
// @memberjunction/ng-artifacts (6 classes)
    CodeArtifactViewerComponent,
    ComponentArtifactViewerComponent,
    HtmlArtifactViewerComponent,
    JsonArtifactViewerComponent,
    MarkdownArtifactViewerComponent,
    SvgArtifactViewerComponent,
} from '@memberjunction/ng-artifacts';
// @memberjunction/ng-auth-services (3 classes)
    MJAuth0Provider,
    MJMSALProvider,
    MJOktaProvider,
} from '@memberjunction/ng-auth-services';
// @memberjunction/ng-core-entity-forms (1 classes)
    FlowAgentFormSectionComponent,
} from '@memberjunction/ng-core-entity-forms';
// @memberjunction/ng-dashboard-viewer (8 classes)
    ArtifactConfigPanelComponent,
    ArtifactPartComponent,
    QueryConfigPanelComponent,
    QueryPartComponent,
    ViewConfigPanelComponent,
    ViewPartComponent,
    WebURLConfigPanelComponent,
    WebURLPartComponent,
} from '@memberjunction/ng-dashboard-viewer';
// @memberjunction/ng-dashboards (52 classes)
    APIKeysResourceComponent,
    ActionExplorerComponent,
    ActionsOverviewComponent,
    AgentConfigurationComponent,
    CodeManagementComponent,
    CommunicationDashboardComponent,
    CommunicationLogsResourceComponent,
    CommunicationMonitorResourceComponent,
    CommunicationProvidersResourceComponent,
    CommunicationRunsResourceComponent,
    CommunicationTemplatesResourceComponent,
    ComponentStudioDashboardComponent,
    CredentialsAuditResourceComponent,
    CredentialsCategoriesResourceComponent,
    CredentialsDashboardComponent,
    CredentialsListResourceComponent,
    CredentialsOverviewResourceComponent,
    CredentialsTypesResourceComponent,
    DashboardBrowserResourceComponent,
    DataExplorerDashboardComponent,
    DataExplorerResourceComponent,
    EntityAdminDashboardComponent,
    EntityIntegrationComponent,
    ExecutionMonitoringComponent,
    HomeApplication,
    HomeDashboardComponent,
    ListsBrowseResource,
    ListsCategoriesResource,
    ListsMyListsResource,
    ListsOperationsResource,
    MCPDashboardComponent,
    ModelManagementComponent,
    PromptManagementComponent,
    QueryBrowserResourceComponent,
    ScheduledActionsComponent,
    SchedulingActivityResourceComponent,
    SchedulingDashboardComponent,
    SchedulingJobsResourceComponent,
    SchedulingOverviewResourceComponent,
    SecurityPermissionsComponent,
    SystemConfigurationComponent,
    SystemDiagnosticsComponent,
    TestingAnalyticsResourceComponent,
    TestingDashboardComponent,
    TestingDashboardTabResourceComponent,
    TestingExplorerResourceComponent,
    TestingReviewResourceComponent,
    TestingRunsResourceComponent,
    VersionHistoryDiffResourceComponent,
    VersionHistoryGraphResourceComponent,
    VersionHistoryLabelsResourceComponent,
    VersionHistoryRestoreResourceComponent,
} from '@memberjunction/ng-dashboards';
// @memberjunction/ng-explorer-core (8 classes)
    ArtifactResource,
    ChatConversationsResource,
    DashboardResource,
    EntityRecordResource,
    ListDetailResource,
    QueryResource,
    SearchResultsResource,
    UserViewResource,
} from '@memberjunction/ng-explorer-core';
// @memberjunction/ng-explorer-settings (6 classes)
    ApplicationManagementComponent,
    EntityPermissionsComponent,
    RoleManagementComponent,
    SettingsComponent,
    SqlLoggingComponent,
    UserManagementComponent,
} from '@memberjunction/ng-explorer-settings';
// @memberjunction/ng-file-storage (1 classes)
    FileBrowserResource,
} from '@memberjunction/ng-file-storage';
export const CLASS_REGISTRATIONS_COUNT = 382;
    '@memberjunction/actions-base',
    '@memberjunction/ai-core-plus',
    '@memberjunction/ai-engine-base',
    '@memberjunction/communication-types',
    '@memberjunction/core-entities',
    '@memberjunction/entity-communications-base',
    '@memberjunction/ng-artifacts',
    '@memberjunction/ng-auth-services',
    '@memberjunction/ng-core-entity-forms',
    '@memberjunction/ng-dashboard-viewer',
    '@memberjunction/ng-dashboards',
    '@memberjunction/ng-explorer-core',
    '@memberjunction/ng-explorer-settings',
    '@memberjunction/ng-file-storage',
 * Pre-built class registrations manifest for all @memberjunction/* packages.
 * External consumers import this to prevent tree-shaking of MJ's dynamically
 * registered classes. This file is generated at MJ build time and ships with
 * the @memberjunction/server-bootstrap package.
 * Usage in your MJAPI entry point:
 *   import '@memberjunction/server-bootstrap/mj-class-registrations';
export * from './generated/mj-class-registrations.js';
 * App: @memberjunction/server-bootstrap
 * Dependency tree: 959 packages walked, 55 contain @RegisterClass
// @memberjunction/actions (3 classes)
} from '@memberjunction/actions';
// @memberjunction/actions-apollo (2 classes)
    ApolloEnrichmentAccountsAction,
    ApolloEnrichmentContactsAction,
} from '@memberjunction/actions-apollo';
// @memberjunction/actions-bizapps-accounting (8 classes)
    CreateQuickBooksJournalEntryAction,
    GetBusinessCentralCustomersAction,
    GetBusinessCentralGLAccountsAction,
    GetBusinessCentralGeneralLedgerEntriesAction,
    GetBusinessCentralSalesInvoicesAction,
    GetQuickBooksAccountBalancesAction,
    GetQuickBooksGLCodesAction,
    GetQuickBooksTransactionsAction,
} from '@memberjunction/actions-bizapps-accounting';
// @memberjunction/actions-bizapps-crm (22 classes)
    AssociateContactToCompanyAction,
    CreateCompanyAction,
    CreateContactAction,
    CreateDealAction,
    CreateTaskAction,
    DeleteContactAction,
    GetActivitiesByContactAction,
    GetCompanyAction,
    GetContactAction,
    GetDealAction,
    GetDealsByCompanyAction,
    GetDealsByContactAction,
    GetUpcomingTasksAction,
    LogActivityAction,
    MergeContactsAction,
    SearchCompaniesAction,
    SearchContactsAction,
    SearchDealsAction,
    UpdateCompanyAction,
    UpdateContactAction,
    UpdateDealAction,
    UpdateTaskAction,
} from '@memberjunction/actions-bizapps-crm';
// @memberjunction/actions-bizapps-formbuilders (30 classes)
    CreateJotFormAction,
    CreateSurveyMonkeyAction,
    CreateTypeformAction,
    ExportGoogleFormsCSVAction,
    ExportJotFormCSVAction,
    ExportSurveyMonkeyCSVAction,
    ExportTypeformCSVAction,
    GetGoogleFormAction,
    GetGoogleFormsStatisticsAction,
    GetJotFormAction,
    GetJotFormStatisticsAction,
    GetJotFormSubmissionsAction,
    GetSingleGoogleFormsResponseAction,
    GetSingleJotFormSubmissionAction,
    GetSingleSurveyMonkeyResponseAction,
    GetSingleTypeformResponseAction,
    GetSurveyMonkeyDetailsAction,
    GetSurveyMonkeyResponsesAction,
    GetSurveyMonkeyStatisticsAction,
    GetTypeformAction,
    GetTypeformFileContentAction,
    GetTypeformFormsAction,
    GetTypeformResponsesAction,
    GetTypeformStatisticsAction,
    UpdateJotFormAction,
    UpdateSurveyMonkeyAction,
    UpdateTypeformAction,
    WatchNewJotFormSubmissionsAction,
    WatchNewSurveyMonkeyResponsesAction,
    WatchNewTypeformResponsesAction,
} from '@memberjunction/actions-bizapps-formbuilders';
// @memberjunction/actions-bizapps-lms (12 classes)
    CreateUserAction as CreateUserAction_actions_bizapps_lms,
    EnrollUserAction,
    GetCertificatesAction,
    GetCourseAnalyticsAction,
    GetLearnWorldsCourseDetailsAction,
    GetLearnWorldsCoursesAction,
    GetLearnWorldsUserDetailsAction,
    GetLearnWorldsUserProgressAction,
    GetLearnWorldsUsersAction,
    GetQuizResultsAction,
    GetUserEnrollmentsAction,
    UpdateUserProgressAction,
} from '@memberjunction/actions-bizapps-lms';
// @memberjunction/actions-bizapps-social (65 classes)
    BufferCreatePostAction,
    BufferDeletePostAction,
    BufferGetAnalyticsAction,
    BufferGetPendingPostsAction,
    BufferGetProfilesAction,
    BufferGetSentPostsAction,
    BufferReorderQueueAction,
    BufferSearchPostsAction,
    CreateVideoPostAction,
    FacebookBoostPostAction,
    FacebookCreateAlbumAction,
    FacebookCreatePostAction,
    FacebookGetPageInsightsAction,
    FacebookGetPagePostsAction,
    FacebookGetPostInsightsAction,
    FacebookRespondToCommentsAction,
    FacebookSchedulePostAction,
    FacebookSearchPostsAction,
    GetAccountAnalyticsAction,
    GetCommentsAction,
    GetTrendingHashtagsAction,
    GetUserVideosAction,
    GetVideoAnalyticsAction,
    HootSuiteBulkSchedulePostsAction,
    HootSuiteCreateScheduledPostAction,
    HootSuiteDeleteScheduledPostAction,
    HootSuiteGetAnalyticsAction,
    HootSuiteGetScheduledPostsAction,
    HootSuiteGetSocialProfilesAction,
    HootSuiteSearchPostsAction,
    HootSuiteUpdateScheduledPostAction,
    InstagramCreatePostAction,
    InstagramCreateStoryAction,
    InstagramGetAccountInsightsAction,
    InstagramGetBusinessPostsAction,
    InstagramGetCommentsAction,
    InstagramGetPostInsightsAction,
    InstagramSchedulePostAction,
    InstagramSearchPostsAction,
    LinkedInCreateArticleAction,
    LinkedInCreatePostAction,
    LinkedInGetFollowersAction,
    LinkedInGetOrganizationPostsAction,
    LinkedInGetPersonalPostsAction,
    LinkedInGetPostAnalyticsAction,
    LinkedInSchedulePostAction,
    LinkedInSearchPostsAction,
    SearchVideosAction,
    TwitterCreateThreadAction,
    TwitterCreateTweetAction,
    TwitterDeleteTweetAction,
    TwitterGetAnalyticsAction,
    TwitterGetMentionsAction,
    TwitterGetTimelineAction,
    TwitterScheduleTweetAction,
    TwitterSearchTweetsAction,
    YouTubeCreatePlaylistAction,
    YouTubeGetChannelAnalyticsAction,
    YouTubeGetChannelVideosAction,
    YouTubeGetCommentsAction,
    YouTubeGetVideoAnalyticsAction,
    YouTubeScheduleVideoAction,
    YouTubeSearchVideosAction,
    YouTubeUpdateVideoMetadataAction,
    YouTubeUploadVideoAction,
} from '@memberjunction/actions-bizapps-social';
// @memberjunction/ai-agent-manager (3 classes)
    AgentArchitectAgent,
    AgentBuilderAgent,
    PlanningDesignerAgent,
} from '@memberjunction/ai-agent-manager';
// @memberjunction/ai-agents (3 classes)
    FlowAgentType,
    LoopAgentType,
    MemoryManagerAgent,
} from '@memberjunction/ai-agents';
// @memberjunction/ai-anthropic (1 classes)
    AnthropicLLM,
} from '@memberjunction/ai-anthropic';
// @memberjunction/ai-azure (2 classes)
    AzureEmbedding,
    AzureLLM,
} from '@memberjunction/ai-azure';
// @memberjunction/ai-bedrock (2 classes)
    BedrockEmbedding,
    BedrockLLM,
} from '@memberjunction/ai-bedrock';
// @memberjunction/ai-betty-bot (1 classes)
    BettyBotLLM,
} from '@memberjunction/ai-betty-bot';
// @memberjunction/ai-blackforestlabs (1 classes)
    FLUXImageGenerator,
} from '@memberjunction/ai-blackforestlabs';
// @memberjunction/ai-cerebras (1 classes)
    CerebrasLLM,
} from '@memberjunction/ai-cerebras';
// @memberjunction/ai-cohere (1 classes)
} from '@memberjunction/ai-cohere';
// @memberjunction/ai-elevenlabs (1 classes)
    ElevenLabsAudioGenerator,
} from '@memberjunction/ai-elevenlabs';
// @memberjunction/ai-fireworks (1 classes)
    FireworksLLM,
} from '@memberjunction/ai-fireworks';
// @memberjunction/ai-gemini (2 classes)
    GeminiImageGenerator,
    GeminiLLM,
} from '@memberjunction/ai-gemini';
// @memberjunction/ai-groq (1 classes)
    GroqLLM,
} from '@memberjunction/ai-groq';
// @memberjunction/ai-heygen (1 classes)
    HeyGenVideoGenerator,
} from '@memberjunction/ai-heygen';
// @memberjunction/ai-lmstudio (1 classes)
    LMStudioLLM,
} from '@memberjunction/ai-lmstudio';
// @memberjunction/ai-local-embeddings (1 classes)
    LocalEmbedding,
} from '@memberjunction/ai-local-embeddings';
// @memberjunction/ai-mistral (2 classes)
    MistralEmbedding,
    MistralLLM,
} from '@memberjunction/ai-mistral';
// @memberjunction/ai-ollama (2 classes)
    OllamaEmbedding,
    OllamaLLM,
} from '@memberjunction/ai-ollama';
// @memberjunction/ai-openai (4 classes)
    OpenAIAudioGenerator,
    OpenAIEmbedding,
    OpenAIImageGenerator,
    OpenAILLM,
} from '@memberjunction/ai-openai';
// @memberjunction/ai-openrouter (1 classes)
    OpenRouterLLM,
} from '@memberjunction/ai-openrouter';
// @memberjunction/ai-recommendations-rex (1 classes)
    RexRecommendationsProvider,
} from '@memberjunction/ai-recommendations-rex';
// @memberjunction/ai-reranker (1 classes)
// @memberjunction/ai-vectors-pinecone (1 classes)
    PineconeDatabase,
} from '@memberjunction/ai-vectors-pinecone';
// @memberjunction/ai-vertex (1 classes)
    VertexLLM,
} from '@memberjunction/ai-vertex';
// @memberjunction/ai-xai (1 classes)
    xAILLM,
} from '@memberjunction/ai-xai';
// @memberjunction/ai-zhipu (1 classes)
    ZhipuLLM,
} from '@memberjunction/ai-zhipu';
// @memberjunction/communication-ms-graph (1 classes)
    MSGraphProvider,
} from '@memberjunction/communication-ms-graph';
// @memberjunction/communication-sendgrid (1 classes)
    SendGridProvider,
} from '@memberjunction/communication-sendgrid';
// @memberjunction/content-autotagging (4 classes)
    AutotagBaseEngine,
    AutotagLocalFileSystem,
    AutotagRSSFeed,
    AutotagWebsite,
} from '@memberjunction/content-autotagging';
// @memberjunction/core-actions (95 classes)
    APIRateLimiterAction,
    AddRecordsToListAction,
    AggregateDataAction,
    AssignUserRolesAction,
    BusinessDaysCalculatorAction,
    CSVParserAction,
    CalculateExpressionAction,
    CensusDataLookupAction,
    CheckUserPermissionAction,
    ColorConverterAction,
    ConditionalAction,
    CopyObjectAction,
    CreateDirectoryAction,
    CreateEmployeeAction,
    CreateListAction,
    CreateMermaidDiagramAction,
    CreateRecordAction,
    CreateSVGChartAction,
    CreateSVGDiagramAction,
    CreateSVGInfographicAction,
    CreateSVGNetworkAction,
    CreateSVGSketchDiagramAction,
    CreateSVGWordCloudAction,
    CreateUserAction as CreateUserAction_core_actions,
    Create_Conversation_Record_Action,
    DataMapperAction,
    DelayAction,
    DeleteDirectoryAction,
    DeleteObjectAction,
    DeleteRecordAction,
    DirectoryExistsAction,
    ExcelReaderAction,
    ExcelWriterAction,
    ExecuteAIPromptAction,
    ExecuteCodeAction,
    ExecuteMCPToolAction,
    ExecuteResearchQueryAction,
    ExploreDatabaseSchemaAction,
    ExternalChangeDetectionAction,
    FileCompressAction,
    FindBestActionAction,
    FindBestAgentAction,
    GammaGeneratePresentationAction,
    GenerateImageAction,
    GetDownloadUrlAction,
    GetFileContentAction,
    GetListRecordsAction,
    GetMetadataAction,
    GetObjectAction,
    GetRecordAction,
    GetRecordListMembershipAction,
    GetStockPriceAction,
    GetUploadUrlAction,
    GetWeatherAction,
    Get_AI_Model_Cost_Action,
    GoogleCustomSearchAction,
    GraphQLQueryAction,
    HTTPRequestAction,
    IPGeolocationAction,
    JSONTransformAction,
    ListMCPToolsAction,
    ListObjectsAction,
    ListStorageAccountsAction,
    LoadAgentSpecAction,
    LoopAction,
    MCPToolAction,
    MoveObjectAction,
    OAuthFlowAction,
    ObjectExistsAction,
    PDFExtractorAction,
    PDFGeneratorAction,
    ParallelExecuteAction,
    PasswordStrengthAction,
    PerplexitySearchAction,
    QRCodeAction,
    RemoveRecordsFromListAction,
    RetryAction,
    SearchStorageFilesAction,
    SendSingleMessageAction,
    SlackWebhookAction,
    SummarizeContentAction,
    SyncMCPToolsAction,
    TeamsWebhookAction,
    TestMCPConnectionAction,
    TextAnalyzerAction,
    URLLinkValidatorAction,
    URLMetadataExtractorAction,
    UnitConverterAction,
    UpdateListItemStatusAction,
    UpdateRecordAction,
    ValidateEmailUniqueAction,
    VectorizeEntityAction,
    WebPageContentAction,
    WebSearchAction,
    XMLParserAction,
} from '@memberjunction/core-actions';
// @memberjunction/core-entities-server (14 classes)
    AIAgentExampleEntityExtended,
    AIAgentNoteEntityExtended,
    AIPromptEntityExtendedServer,
    AIPromptRunEntityServer,
    ActionEntityServerEntity,
    ApplicationEntityServerEntity,
    ArtifactVersionExtended,
    ComponentEntityExtended_Server,
    ConversationDetailEntityServer,
    DuplicateRunEntity_Server,
    QueryEntityExtended,
    ReportEntity_Server,
    TemplateContentEntityExtended,
    UserViewEntity_Server,
} from '@memberjunction/core-entities-server';
// @memberjunction/data-context-server (1 classes)
    DataContextItemServer,
} from '@memberjunction/data-context-server';
// @memberjunction/doc-utils (2 classes)
    LibraryEntityExtended,
    LibraryItemEntityExtended,
} from '@memberjunction/doc-utils';
// @memberjunction/encryption (6 classes)
    AWSKMSKeySource,
    AzureKeyVaultKeySource,
    ConfigFileKeySource,
    EnableFieldEncryptionAction,
    EnvVarKeySource,
    RotateEncryptionKeyAction,
} from '@memberjunction/encryption';
// @memberjunction/queue (2 classes)
    AIActionQueue,
    EntityAIActionQueue,
} from '@memberjunction/queue';
// @memberjunction/scheduling-actions (6 classes)
    CreateScheduledJobAction,
    DeleteScheduledJobAction,
    ExecuteScheduledJobNowAction,
    GetScheduledJobStatisticsAction,
    QueryScheduledJobsAction,
    UpdateScheduledJobAction,
} from '@memberjunction/scheduling-actions';
// @memberjunction/scheduling-engine (2 classes)
    ActionScheduledJobDriver,
    AgentScheduledJobDriver,
} from '@memberjunction/scheduling-engine';
// @memberjunction/scheduling-engine-base (1 classes)
    ScheduledJobEntityExtended,
} from '@memberjunction/scheduling-engine-base';
// @memberjunction/server (2 classes)
    EntityPermissionsEntity_Server,
    SkipProxyAgent,
// @memberjunction/storage (7 classes)
    AWSFileStorage,
    AzureFileStorage,
    BoxFileStorage,
    DropboxFileStorage,
    GoogleDriveFileStorage,
    GoogleFileStorage,
    SharePointFileStorage,
// @memberjunction/templates (2 classes)
    AIPromptExtension,
    TemplateEmbedExtension,
} from '@memberjunction/templates';
// @memberjunction/testing-engine (1 classes)
    AgentEvalDriver,
} from '@memberjunction/testing-engine';
    CreateUserAction_actions_bizapps_lms,
    CreateUserAction_core_actions,
export const CLASS_REGISTRATIONS_COUNT = 624;
    '@memberjunction/actions',
    '@memberjunction/actions-apollo',
    '@memberjunction/actions-bizapps-accounting',
    '@memberjunction/actions-bizapps-crm',
    '@memberjunction/actions-bizapps-formbuilders',
    '@memberjunction/actions-bizapps-lms',
    '@memberjunction/actions-bizapps-social',
    '@memberjunction/ai-agent-manager',
    '@memberjunction/ai-agents',
    '@memberjunction/ai-anthropic',
    '@memberjunction/ai-azure',
    '@memberjunction/ai-bedrock',
    '@memberjunction/ai-betty-bot',
    '@memberjunction/ai-blackforestlabs',
    '@memberjunction/ai-cerebras',
    '@memberjunction/ai-cohere',
    '@memberjunction/ai-elevenlabs',
    '@memberjunction/ai-fireworks',
    '@memberjunction/ai-gemini',
    '@memberjunction/ai-groq',
    '@memberjunction/ai-heygen',
    '@memberjunction/ai-lmstudio',
    '@memberjunction/ai-local-embeddings',
    '@memberjunction/ai-mistral',
    '@memberjunction/ai-ollama',
    '@memberjunction/ai-openai',
    '@memberjunction/ai-openrouter',
    '@memberjunction/ai-recommendations-rex',
    '@memberjunction/ai-reranker',
    '@memberjunction/ai-vectors-pinecone',
    '@memberjunction/ai-vertex',
    '@memberjunction/ai-xai',
    '@memberjunction/ai-zhipu',
    '@memberjunction/communication-ms-graph',
    '@memberjunction/communication-sendgrid',
    '@memberjunction/content-autotagging',
    '@memberjunction/core-actions',
    '@memberjunction/core-entities-server',
    '@memberjunction/data-context-server',
    '@memberjunction/doc-utils',
    '@memberjunction/encryption',
    '@memberjunction/queue',
    '@memberjunction/scheduling-actions',
    '@memberjunction/scheduling-engine',
    '@memberjunction/scheduling-engine-base',
    '@memberjunction/server',
    '@memberjunction/storage',
    '@memberjunction/templates',
    '@memberjunction/testing-engine',
 * Pre-built class registrations manifest for @memberjunction/* packages (lite variant).
 * Excludes ESM-incompatible packages:
 * - communication-* (depends on @microsoft/microsoft-graph-client which has ESM directory import issues)
 * - storage (also depends on @microsoft/microsoft-graph-client)
 * - content-autotagging, entity-communications-base, queue
 * Usage in your entry point:
 *   import '@memberjunction/server-bootstrap-lite/mj-class-registrations';
 * App: @memberjunction/server-bootstrap-lite
 * Dependency tree: 710 packages walked, 47 contain @RegisterClass
export const CLASS_REGISTRATIONS_COUNT = 605;
