from ...shared.metadata import Metadata
from .realtime_response_usage import RealtimeResponseUsage
from .realtime_response_status import RealtimeResponseStatus
__all__ = ["RealtimeResponse"]
class RealtimeResponse(BaseModel):
    """The unique ID of the response."""
    conversation_id: Optional[str] = None
    Which conversation the response is added to, determined by the `conversation`
    field in the `response.create` event. If `auto`, the response will be added to
    the default conversation and the value of `conversation_id` will be an id like
    `conv_1234`. If `none`, the response will not be added to any conversation and
    the value of `conversation_id` will be `null`. If responses are being triggered
    by server VAD, the response will be added to the default conversation, thus the
    `conversation_id` will be an id like `conv_1234`.
    max_output_tokens: Union[int, Literal["inf"], None] = None
    Maximum number of output tokens for a single assistant response, inclusive of
    tool calls, that was used in this response.
    modalities: Optional[List[Literal["text", "audio"]]] = None
    """The set of modalities the model used to respond.
    If there are multiple modalities, the model will pick one, for example if
    `modalities` is `["text", "audio"]`, the model could be responding in either
    text or audio.
    object: Optional[Literal["realtime.response"]] = None
    """The object type, must be `realtime.response`."""
    output: Optional[List[ConversationItem]] = None
    """The list of output items generated by the response."""
    output_audio_format: Optional[Literal["pcm16", "g711_ulaw", "g711_alaw"]] = None
    """The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`."""
    status: Optional[Literal["completed", "cancelled", "failed", "incomplete", "in_progress"]] = None
    The final status of the response (`completed`, `cancelled`, `failed`, or
    `incomplete`, `in_progress`).
    status_details: Optional[RealtimeResponseStatus] = None
    """Additional details about the status."""
    """Sampling temperature for the model, limited to [0.6, 1.2]. Defaults to 0.8."""
    usage: Optional[RealtimeResponseUsage] = None
    """Usage statistics for the Response, this will correspond to billing.
    A Realtime API session will maintain a conversation context and append new Items
    to the Conversation, thus output from previous turns (text and audio tokens)
    will become the input for later turns.
    voice: Union[str, Literal["alloy", "ash", "ballad", "coral", "echo", "sage", "shimmer", "verse"], None] = None
    The voice the model used to respond. Current voice options are `alloy`, `ash`,
    `ballad`, `coral`, `echo`, `sage`, `shimmer`, and `verse`.
__all__ = ["RealtimeResponse", "Audio", "AudioOutput"]
class AudioOutput(BaseModel):
    voice: Union[
        str, Literal["alloy", "ash", "ballad", "coral", "echo", "sage", "shimmer", "verse", "marin", "cedar"], None
    `coral`, `echo`, `sage`, `shimmer`, `verse`, `marin`, and `cedar`. We recommend
    `marin` and `cedar` for best quality.
class Audio(BaseModel):
    """Configuration for audio output."""
    output: Optional[AudioOutput] = None
    """The unique ID of the response, will look like `resp_1234`."""
    audio: Optional[Audio] = None
    automatically by VAD the response will be added to the default conversation
    output_modalities: Optional[List[Literal["text", "audio"]]] = None
    The set of modalities the model used to respond, currently the only possible
    values are `[\"audio\"]`, `[\"text\"]`. Audio output always include a text
    transcript. Setting the output to mode `text` will disable audio output from the
