__all__ = ["ResponseFunctionToolCallOutputItem", "OutputOutputContentList"]
class ResponseFunctionToolCallOutputItem(BaseModel):
    """The unique ID of the function call tool output."""
    The output from the function call generated by your code. Can be a string or an
    list of output content.
    """The type of the function tool call output. Always `function_call_output`."""
