__all__ = ["ResponseFunctionToolCall"]
class ResponseFunctionToolCall(BaseModel):
    """A tool call to run a function.
    [function calling guide](https://platform.openai.com/docs/guides/function-calling) for more information.
    """A JSON string of the arguments to pass to the function."""
    """The unique ID of the function tool call generated by the model."""
    """The name of the function to run."""
    """The type of the function tool call. Always `function_call`."""
    """The unique ID of the function tool call."""
    """The namespace of the function to run."""
