from .response_local_environment import ResponseLocalEnvironment
from .response_container_reference import ResponseContainerReference
__all__ = ["ResponseFunctionShellToolCall", "Action", "Environment"]
class Action(BaseModel):
    """The shell commands and limits that describe how to run the tool call."""
    commands: List[str]
    max_output_length: Optional[int] = None
    """Optional maximum number of characters to return from each command."""
    """Optional timeout in milliseconds for the commands."""
    Union[ResponseLocalEnvironment, ResponseContainerReference, None], PropertyInfo(discriminator="type")
class ResponseFunctionShellToolCall(BaseModel):
    """A tool call that executes one or more shell commands in a managed environment."""
    """The unique ID of the shell tool call.
    """The unique ID of the shell tool call generated by the model."""
    """Represents the use of a local environment to perform shell actions."""
    """The status of the shell call.
    One of `in_progress`, `completed`, or `incomplete`.
    type: Literal["shell_call"]
    """The type of the item. Always `shell_call`."""
