from .response_input_file_content_param import ResponseInputFileContentParam
from .response_input_text_content_param import ResponseInputTextContentParam
from .response_input_image_content_param import ResponseInputImageContentParam
__all__ = ["ResponseFunctionCallOutputItemListParam", "ResponseFunctionCallOutputItemParam"]
ResponseFunctionCallOutputItemParam: TypeAlias = Union[
    ResponseInputTextContentParam, ResponseInputImageContentParam, ResponseInputFileContentParam
ResponseFunctionCallOutputItemListParam: TypeAlias = List[ResponseFunctionCallOutputItemParam]
