    "ResponseFunctionShellToolCallOutput",
    "OutputOutcome",
    "OutputOutcomeTimeout",
    "OutputOutcomeExit",
class OutputOutcomeTimeout(BaseModel):
class OutputOutcomeExit(BaseModel):
    """Exit code from the shell process."""
OutputOutcome: TypeAlias = Annotated[Union[OutputOutcomeTimeout, OutputOutcomeExit], PropertyInfo(discriminator="type")]
    """The content of a shell tool call output that was emitted."""
    outcome: OutputOutcome
    Represents either an exit outcome (with an exit code) or a timeout outcome for a
    shell call output chunk.
    """The standard error output that was captured."""
    """The standard output that was captured."""
class ResponseFunctionShellToolCallOutput(BaseModel):
    """The output of a shell tool call that was emitted."""
    """The unique ID of the shell call output.
    """The maximum length of the shell command output.
    This is generated by the model and should be passed back with the raw output.
    output: List[Output]
    """An array of shell call output contents"""
    """The status of the shell call output.
    type: Literal["shell_call_output"]
    """The type of the shell call output. Always `shell_call_output`."""
