from .tool import Tool
from .response_error import ResponseError
from .response_prompt import ResponsePrompt
from .response_status import ResponseStatus
from .tool_choice_mcp import ToolChoiceMcp
from ..shared.reasoning import Reasoning
from .tool_choice_shell import ToolChoiceShell
from .tool_choice_types import ToolChoiceTypes
from .tool_choice_custom import ToolChoiceCustom
from .response_input_item import ResponseInputItem
from .tool_choice_allowed import ToolChoiceAllowed
from .response_text_config import ResponseTextConfig
from .tool_choice_function import ToolChoiceFunction
from ..shared.responses_model import ResponsesModel
from .tool_choice_apply_patch import ToolChoiceApplyPatch
__all__ = ["Response", "IncompleteDetails", "ToolChoice", "Conversation"]
    """Details about why the response is incomplete."""
    reason: Optional[Literal["max_output_tokens", "content_filter"]] = None
    """The reason why the response is incomplete."""
    ToolChoiceAllowed,
    ToolChoiceTypes,
    ToolChoiceFunction,
    ToolChoiceMcp,
    ToolChoiceCustom,
    ToolChoiceApplyPatch,
    ToolChoiceShell,
    """The conversation that this response belonged to.
    Input items and output items from this response were automatically added to this conversation.
    """The unique ID of the conversation that this response was associated with."""
    """Unique identifier for this Response."""
    created_at: float
    """Unix timestamp (in seconds) of when this Response was created."""
    error: Optional[ResponseError] = None
    """An error object returned when the model fails to generate a Response."""
    instructions: Union[str, List[ResponseInputItem], None] = None
    """A system (or developer) message inserted into the model's context.
    model: ResponsesModel
    object: Literal["response"]
    """The object type of this resource - always set to `response`."""
    """An array of content items generated by the model.
    - The length and order of items in the `output` array is dependent on the
      model's response.
    - Rather than accessing the first item in the `output` array and assuming it's
      an `assistant` message with the content generated by the model, you might
      consider using the `output_text` property where supported in SDKs.
    How the model should select which tool (or tools) to use when generating a
    background: Optional[bool] = None
    Whether to run the model response in the background.
    completed_at: Optional[float] = None
    Unix timestamp (in seconds) of when this Response was completed. Only present
    when the status is `completed`.
    conversation: Optional[Conversation] = None
    Input items and output items from this response were automatically added to this
    max_output_tokens: Optional[int] = None
    An upper bound for the number of tokens that can be generated for a response,
    max_tool_calls: Optional[int] = None
    The maximum number of total calls to built-in tools that can be processed in a
    prompt_cache_key: Optional[str] = None
    prompt_cache_retention: Optional[Literal["in-memory", "24h"]] = None
    reasoning: Optional[Reasoning] = None
    """**gpt-5 and o-series models only**
    safety_identifier: Optional[str] = None
    status: Optional[ResponseStatus] = None
    """The status of the response generation.
    One of `completed`, `failed`, `in_progress`, `cancelled`, `queued`, or
    `incomplete`.
    text: Optional[ResponseTextConfig] = None
    top_logprobs: Optional[int] = None
    truncation: Optional[Literal["auto", "disabled"]] = None
    usage: Optional[ResponseUsage] = None
    breakdown of output tokens, and the total tokens used.
    def output_text(self) -> str:
        """Convenience property that aggregates all `output_text` items from the `output` list.
        If no `output_text` content blocks exist, then an empty string is returned.
        texts: List[str] = []
                    if content.type == "output_text":
                        texts.append(content.text)
        return "".join(texts)
from http.client import responses
from django.core import signals, signing
from django.core.exceptions import DisallowedRedirect
from django.core.serializers.json import DjangoJSONEncoder
from django.http.cookie import SimpleCookie
from django.utils.datastructures import CaseInsensitiveMapping
from django.utils.http import (
    MAX_URL_REDIRECT_LENGTH,
    content_disposition_header,
    http_date,
_charset_from_content_type_re = _lazy_re_compile(
    r";\s*charset=(?P<charset>[^\s;]+)", re.I
class ResponseHeaders(CaseInsensitiveMapping):
        Populate the initial data using __setitem__ to ensure values are
        correctly encoded.
        self._store = {}
            for header, value in self._unpack_items(data):
                self[header] = value
    def _convert_to_charset(self, value, charset, mime_encode=False):
        Convert headers key/value to ascii/latin-1 native strings.
        `charset` must be 'ascii' or 'latin-1'. If `mime_encode` is True and
        `value` can't be represented in the given charset, apply MIME-encoding.
                # Ensure string is valid in given charset
                value.encode(charset)
            elif isinstance(value, bytes):
                # Convert bytestring using given charset
                value = value.decode(charset)
                # Ensure string is valid in given charset.
            if "\n" in value or "\r" in value:
                    f"Header values can't contain newlines (got {value!r})"
        except UnicodeError as e:
            # Encoding to a string of the specified charset failed, but we
            # don't know what type that value was, or if it contains newlines,
            # which we may need to check for before sending it to be
            # encoded for multiple character sets.
            if (isinstance(value, bytes) and (b"\n" in value or b"\r" in value)) or (
                isinstance(value, str) and ("\n" in value or "\r" in value)
            if mime_encode:
                value = Header(value, "utf-8", maxlinelen=sys.maxsize).encode()
                e.reason += ", HTTP response headers must be in %s format" % charset
        self.pop(key)
        key = self._convert_to_charset(key, "ascii")
        value = self._convert_to_charset(value, "latin-1", mime_encode=True)
        self._store[key.lower()] = (key, value)
    def pop(self, key, default=None):
        return self._store.pop(key.lower(), default)
        if key not in self:
class BadHeaderError(ValueError):
class HttpResponseBase:
    An HTTP response base class with dictionary-accessed headers.
    This class doesn't handle content. It should not be used directly.
    Use the HttpResponse and StreamingHttpResponse subclasses instead.
    status_code = 200
        self, content_type=None, status=None, reason=None, charset=None, headers=None
        self.headers = ResponseHeaders(headers)
        self._charset = charset
        if "Content-Type" not in self.headers:
            if content_type is None:
                content_type = f"text/html; charset={self.charset}"
            self.headers["Content-Type"] = content_type
        elif content_type:
                "'headers' must not contain 'Content-Type' when the "
                "'content_type' parameter is provided."
        self._resource_closers = []
        # This parameter is set by the handler. It's necessary to preserve the
        # historical behavior of request_finished.
        self._handler_class = None
        self.cookies = SimpleCookie()
        self.closed = False
                self.status_code = int(status)
                raise TypeError("HTTP status code must be an integer.")
            if not 100 <= self.status_code <= 599:
                raise ValueError("HTTP status code must be an integer from 100 to 599.")
        self._reason_phrase = reason
    def reason_phrase(self):
        if self._reason_phrase is not None:
            return self._reason_phrase
        # Leave self._reason_phrase unset in order to use the default
        # reason phrase for status code.
        return responses.get(self.status_code, "Unknown Status Code")
    @reason_phrase.setter
    def reason_phrase(self, value):
        self._reason_phrase = value
    def charset(self):
        if self._charset is not None:
            return self._charset
        # The Content-Type header may not yet be set, because the charset is
        # being inserted *into* it.
        if content_type := self.headers.get("Content-Type"):
            if matched := _charset_from_content_type_re.search(content_type):
                # Extract the charset and strip its double quotes.
                # Note that having parsed it from the Content-Type, we don't
                # store it back into the _charset for later intentionally, to
                # allow for the Content-Type to be switched again later.
                return matched["charset"].replace('"', "")
        return settings.DEFAULT_CHARSET
    @charset.setter
    def charset(self, value):
        self._charset = value
    def serialize_headers(self):
        """HTTP headers as a bytestring."""
        return b"\r\n".join(
                key.encode("ascii") + b": " + value.encode("latin-1")
                for key, value in self.headers.items()
    __bytes__ = serialize_headers
    def _content_type_for_repr(self):
            ', "%s"' % self.headers["Content-Type"]
            if "Content-Type" in self.headers
    def __setitem__(self, header, value):
        self.headers[header] = value
    def __delitem__(self, header):
        del self.headers[header]
    def __getitem__(self, header):
        return self.headers[header]
    def has_header(self, header):
        """Case-insensitive check for a header."""
        return header in self.headers
    __contains__ = has_header
        return self.headers.items()
    def get(self, header, alternate=None):
        return self.headers.get(header, alternate)
    def set_cookie(
        value="",
        max_age=None,
        path="/",
        domain=None,
        secure=False,
        httponly=False,
        samesite=None,
        Set a cookie.
        ``expires`` can be:
        - a string in the correct format,
        - a naive ``datetime.datetime`` object in UTC,
        - an aware ``datetime.datetime`` object in any time zone.
        If it is a ``datetime.datetime`` object then calculate ``max_age``.
        ``max_age`` can be:
        - int/float specifying seconds,
        - ``datetime.timedelta`` object.
        self.cookies[key] = value
            if isinstance(expires, datetime.datetime):
                if timezone.is_naive(expires):
                    expires = timezone.make_aware(expires, datetime.UTC)
                delta = expires - datetime.datetime.now(tz=datetime.UTC)
                # Add one second so the date matches exactly (a fraction of
                # time gets lost between converting to a timedelta and
                # then the date string).
                delta += datetime.timedelta(seconds=1)
                # Just set max_age - the max_age logic will set expires.
                expires = None
                if max_age is not None:
                    raise ValueError("'expires' and 'max_age' can't be used together.")
                max_age = max(0, delta.days * 86400 + delta.seconds)
                self.cookies[key]["expires"] = expires
            self.cookies[key]["expires"] = ""
            if isinstance(max_age, datetime.timedelta):
                max_age = max_age.total_seconds()
            self.cookies[key]["max-age"] = int(max_age)
            # IE requires expires, so set it if hasn't been already.
            if not expires:
                self.cookies[key]["expires"] = http_date(time.time() + max_age)
            self.cookies[key]["path"] = path
        if domain is not None:
            self.cookies[key]["domain"] = domain
            self.cookies[key]["secure"] = True
        if httponly:
            self.cookies[key]["httponly"] = True
        if samesite:
            if samesite.lower() not in ("lax", "none", "strict"):
                raise ValueError('samesite must be "lax", "none", or "strict".')
            self.cookies[key]["samesite"] = samesite
        """Set a header unless it has already been set."""
        self.headers.setdefault(key, value)
    def set_signed_cookie(self, key, value, salt="", **kwargs):
        value = signing.get_cookie_signer(salt=key + salt).sign(value)
        return self.set_cookie(key, value, **kwargs)
    def delete_cookie(self, key, path="/", domain=None, samesite=None):
        # Browsers can ignore the Set-Cookie header if the cookie doesn't use
        # the secure flag and:
        # - the cookie name starts with "__Host-" or "__Secure-", or
        # - the samesite is "none".
        secure = key.startswith(("__Secure-", "__Host-")) or (
            samesite and samesite.lower() == "none"
        self.set_cookie(
            max_age=0,
            domain=domain,
            secure=secure,
            expires="Thu, 01 Jan 1970 00:00:00 GMT",
            samesite=samesite,
    # Common methods used by subclasses
    def make_bytes(self, value):
        """Turn a value into a bytestring encoded in the output charset."""
        # Per PEP 3333, this response body must be bytes. To avoid returning
        # an instance of a subclass, this function returns `bytes(value)`.
        # This doesn't make a copy when `value` already contains bytes.
        # Handle string types -- we can't rely on force_bytes here because:
        # - Python attempts str conversion first
        # - when self._charset != 'utf-8' it re-encodes the content
        if isinstance(value, (bytes, memoryview)):
            return bytes(value)
            return bytes(value.encode(self.charset))
        # Handle non-string types.
        return str(value).encode(self.charset)
    # These methods partially implement the file-like object interface.
    # See https://docs.python.org/library/io.html#io.IOBase
    # The WSGI server must call this method upon completion of the request.
    # http://blog.dscpl.com.au/2012/10/obligations-for-calling-close-on.html
        for closer in self._resource_closers:
                closer()
        # Free resources that were still referenced.
        self._resource_closers.clear()
        self.closed = True
        signals.request_finished.send(sender=self._handler_class)
    def write(self, content):
        raise OSError("This %s instance is not writable" % self.__class__.__name__)
        raise OSError(
            "This %s instance cannot tell its position" % self.__class__.__name__
    # These methods partially implement a stream-like object interface.
class HttpResponse(HttpResponseBase):
    An HTTP response class with a string as content.
    This content can be read, appended to, or replaced.
    streaming = False
    def __init__(self, content=b"", *args, **kwargs):
        # Content is a bytestring. See the `content` property methods.
        return "<%(cls)s status_code=%(status_code)d%(content_type)s>" % {
            "status_code": self.status_code,
            "content_type": self._content_type_for_repr,
    def serialize(self):
        """Full HTTP message, including headers, as a bytestring."""
        return self.serialize_headers() + b"\r\n\r\n" + self.content
    __bytes__ = serialize
        return b"".join(self._container)
    @content.setter
    def content(self, value):
        # Consume iterators upon assignment to allow repeated iteration.
        if hasattr(value, "__iter__") and not isinstance(
            value, (bytes, memoryview, str)
            content = b"".join(self.make_bytes(chunk) for chunk in value)
            if hasattr(value, "close"):
                    value.close()
            content = self.make_bytes(value)
        # Create a list of properly encoded bytestrings to support write().
        self._container = [content]
        self.__dict__.pop("text", None)
        return self.content.decode(self.charset or "utf-8")
        return iter(self._container)
        self._container.append(self.make_bytes(content))
        return len(self.content)
        return self.content
            self.write(line)
class StreamingHttpResponse(HttpResponseBase):
    A streaming HTTP response class with an iterator as content.
    This should only be iterated once, when the response is streamed to the
    client. However, it can be appended to or replaced with a new iterator
    that wraps the original content (or yields entirely new content).
    streaming = True
    def __init__(self, streaming_content=(), *args, **kwargs):
        # `streaming_content` should be an iterable of bytestrings.
        # See the `streaming_content` property methods.
        self.streaming_content = streaming_content
            "cls": self.__class__.__qualname__,
            "This %s instance has no `content` attribute. Use "
            "`streaming_content` instead." % self.__class__.__name__
            "This %s instance has no `text` attribute." % self.__class__.__name__
    def streaming_content(self):
        if self.is_async:
            # pull to lexical scope to capture fixed reference in case
            # streaming_content is set again later.
            _iterator = self._iterator
            async def awrapper():
                async for part in _iterator:
                    yield self.make_bytes(part)
            return awrapper()
            return map(self.make_bytes, self._iterator)
    @streaming_content.setter
    def streaming_content(self, value):
        self._set_streaming_content(value)
    def _set_streaming_content(self, value):
        # Ensure we can never iterate on "value" more than once.
            self._iterator = iter(value)
            self.is_async = False
            self._iterator = aiter(value)
            self.is_async = True
            self._resource_closers.append(value.close)
            return iter(self.streaming_content)
                "StreamingHttpResponse must consume asynchronous iterators in order to "
                "serve them synchronously. Use a synchronous iterator instead.",
            # async iterator. Consume in async_to_sync and map back.
            async def to_list(_iterator):
                as_list = []
                async for chunk in _iterator:
                    as_list.append(chunk)
                return as_list
            return map(self.make_bytes, iter(async_to_sync(to_list)(self._iterator)))
    async def __aiter__(self):
            async for part in self.streaming_content:
                yield part
                "StreamingHttpResponse must consume synchronous iterators in order to "
                "serve them asynchronously. Use an asynchronous iterator instead.",
            # sync iterator. Consume via sync_to_async and yield via async
            # generator.
            for part in await sync_to_async(list)(self.streaming_content):
        return b"".join(self.streaming_content)
class FileResponse(StreamingHttpResponse):
    A streaming HTTP response class optimized for files.
    def __init__(self, *args, as_attachment=False, filename="", **kwargs):
        self.as_attachment = as_attachment
        self.filename = filename
        self._no_explicit_content_type = (
            "content_type" not in kwargs or kwargs["content_type"] is None
        if not hasattr(value, "read"):
            self.file_to_stream = None
            return super()._set_streaming_content(value)
        self.file_to_stream = filelike = value
        if hasattr(filelike, "close"):
            self._resource_closers.append(filelike.close)
        value = iter(lambda: filelike.read(self.block_size), b"")
        self.set_headers(filelike)
        super()._set_streaming_content(value)
    def set_headers(self, filelike):
        Set some common response headers (Content-Length, Content-Type, and
        Content-Disposition) based on the `filelike` response content.
        filename = getattr(filelike, "name", "")
        filename = filename if isinstance(filename, str) else ""
        seekable = hasattr(filelike, "seek") and (
            not hasattr(filelike, "seekable") or filelike.seekable()
        if hasattr(filelike, "tell"):
            if seekable:
                initial_position = filelike.tell()
                filelike.seek(0, io.SEEK_END)
                self.headers["Content-Length"] = filelike.tell() - initial_position
                filelike.seek(initial_position)
            elif hasattr(filelike, "getbuffer"):
                self.headers["Content-Length"] = (
                    filelike.getbuffer().nbytes - filelike.tell()
            elif os.path.exists(filename):
                    os.path.getsize(filename) - filelike.tell()
        elif seekable:
            self.headers["Content-Length"] = sum(
                iter(lambda: len(filelike.read(self.block_size)), 0)
            filelike.seek(-int(self.headers["Content-Length"]), io.SEEK_END)
        filename = os.path.basename(self.filename or filename)
        if self._no_explicit_content_type:
                content_type, encoding = mimetypes.guess_type(filename)
                # Encoding isn't set to prevent browsers from automatically
                # uncompressing files.
                content_type = {
                    "br": "application/x-brotli",
                    "bzip2": "application/x-bzip",
                    "compress": "application/x-compress",
                    "gzip": "application/gzip",
                    "xz": "application/x-xz",
                }.get(encoding, content_type)
                self.headers["Content-Type"] = (
                    content_type or "application/octet-stream"
                self.headers["Content-Type"] = "application/octet-stream"
        if content_disposition := content_disposition_header(
            self.as_attachment, filename
            self.headers["Content-Disposition"] = content_disposition
class HttpResponseRedirectBase(HttpResponse):
    allowed_schemes = ["http", "https", "ftp"]
    def __init__(self, redirect_to, preserve_request=False, *args, **kwargs):
        self["Location"] = iri_to_uri(redirect_to)
        redirect_to_str = str(redirect_to)
        if len(redirect_to_str) > MAX_URL_REDIRECT_LENGTH:
            raise DisallowedRedirect(
                f"Unsafe redirect exceeding {MAX_URL_REDIRECT_LENGTH} characters"
        parsed = urlsplit(redirect_to_str)
        if preserve_request:
            self.status_code = self.status_code_preserve_request
        if parsed.scheme and parsed.scheme not in self.allowed_schemes:
                "Unsafe redirect to URL with protocol '%s'" % parsed.scheme
    url = property(lambda self: self["Location"])
            '<%(cls)s status_code=%(status_code)d%(content_type)s, url="%(url)s">'
                "url": self.url,
class HttpResponseRedirect(HttpResponseRedirectBase):
    status_code = 302
    status_code_preserve_request = 307
class HttpResponsePermanentRedirect(HttpResponseRedirectBase):
    status_code = 301
    status_code_preserve_request = 308
class HttpResponseNotModified(HttpResponse):
    status_code = 304
        del self["content-type"]
    @HttpResponse.content.setter
                "You cannot set content to a 304 (Not Modified) response"
        self._container = []
class HttpResponseBadRequest(HttpResponse):
    status_code = 400
class HttpResponseNotFound(HttpResponse):
    status_code = 404
class HttpResponseForbidden(HttpResponse):
    status_code = 403
class HttpResponseNotAllowed(HttpResponse):
    status_code = 405
    def __init__(self, permitted_methods, *args, **kwargs):
        self["Allow"] = ", ".join(permitted_methods)
        return "<%(cls)s [%(methods)s] status_code=%(status_code)d%(content_type)s>" % {
            "methods": self["Allow"],
class HttpResponseGone(HttpResponse):
    status_code = 410
class HttpResponseServerError(HttpResponse):
    status_code = 500
class Http404(Exception):
class JsonResponse(HttpResponse):
    An HTTP response class that consumes data to be serialized to JSON.
    :param data: Data to be dumped into json. By default only ``dict`` objects
      are allowed to be passed due to a security flaw before ECMAScript 5. See
      the ``safe`` parameter for more information.
    :param encoder: Should be a json encoder class. Defaults to
      ``django.core.serializers.json.DjangoJSONEncoder``.
    :param safe: Controls if only ``dict`` objects may be serialized. Defaults
      to ``True``.
    :param json_dumps_params: A dictionary of kwargs passed to json.dumps().
        encoder=DjangoJSONEncoder,
        safe=True,
        json_dumps_params=None,
        if safe and not isinstance(data, dict):
                "In order to allow non-dict objects to be serialized set the "
                "safe parameter to False."
        if json_dumps_params is None:
            json_dumps_params = {}
        kwargs.setdefault("content_type", "application/json")
        data = json.dumps(data, cls=encoder, **json_dumps_params)
        super().__init__(content=data, **kwargs)
from django.http import HttpResponse
from .loader import get_template, select_template
class ContentNotRenderedError(Exception):
class SimpleTemplateResponse(HttpResponse):
    rendering_attrs = ["template_name", "context_data", "_post_render_callbacks"]
        content_type=None,
        charset=None,
        # It would seem obvious to call these next two members 'template' and
        # 'context', but those names are reserved as part of the test Client
        # API. To avoid the name collision, we use different names.
        self.template_name = template
        self.context_data = context
        self._post_render_callbacks = []
        # _request stores the current request object in subclasses that know
        # about requests, like TemplateResponse. It's defined in the base class
        # to minimize code duplication.
        # It's called self._request because self.request gets overwritten by
        # django.test.client.Client. Unlike template_name and context_data,
        # _request should not be considered part of the public API.
        self._request = None
        # content argument doesn't make sense here because it will be replaced
        # with rendered template so we always pass empty string in order to
        # prevent errors and provide shorter signature.
        super().__init__("", content_type, status, charset=charset, headers=headers)
        # _is_rendered tracks whether the template and context has been baked
        # into a final response.
        # Super __init__ doesn't know any better than to set self.content to
        # the empty string we just gave it, which wrongly sets _is_rendered
        # True, so we initialize it to False after the call to super __init__.
        self._is_rendered = False
        Raise an exception if trying to pickle an unrendered response. Pickle
        only rendered data, not the data used to construct the response.
        if not self._is_rendered:
            raise ContentNotRenderedError(
                "The response content must be rendered before it can be pickled."
        for attr in self.rendering_attrs:
            if attr in obj_dict:
                del obj_dict[attr]
    def resolve_template(self, template):
        """Accept a template object, path-to-template, or list of paths."""
        if isinstance(template, (list, tuple)):
            return select_template(template, using=self.using)
        elif isinstance(template, str):
            return get_template(template, using=self.using)
    def resolve_context(self, context):
    def rendered_content(self):
        """Return the freshly rendered content for the template and context
        described by the TemplateResponse.
        This *does not* set the final content of the response. To set the
        response content, you must either call render(), or set the
        content explicitly using the value of this property.
        template = self.resolve_template(self.template_name)
        context = self.resolve_context(self.context_data)
        return template.render(context, self._request)
    def add_post_render_callback(self, callback):
        """Add a new post-rendering callback.
        If the response has already been rendered,
        invoke the callback immediately.
        if self._is_rendered:
            callback(self)
            self._post_render_callbacks.append(callback)
    def render(self):
        """Render (thereby finalizing) the content of the response.
        If the content has already been rendered, this is a no-op.
        Return the baked response instance.
        retval = self
            self.content = self.rendered_content
            for post_callback in self._post_render_callbacks:
                newretval = post_callback(retval)
                if newretval is not None:
                    retval = newretval
    def is_rendered(self):
        return self._is_rendered
                "The response content must be rendered before it can be iterated over."
        return super().__iter__()
                "The response content must be rendered before it can be accessed."
        return super().content
        """Set the content for the response."""
        HttpResponse.content.fset(self, value)
        self._is_rendered = True
class TemplateResponse(SimpleTemplateResponse):
    rendering_attrs = [*SimpleTemplateResponse.rendering_attrs, "_request"]
            template, context, content_type, status, charset, using, headers=headers
from socket import error as SocketError
from socket import timeout as SocketTimeout
from . import util
from ._collections import HTTPHeaderDict
from .connection import BaseSSLError, HTTPException
    BodyNotHttplibCompatible,
    InvalidChunkLength,
    ResponseNotChunked,
from .packages import six
from .util.response import is_fp_closed, is_response_to_head
class DeflateDecoder(object):
        self._first_try = True
        self._data = b""
        self._obj = zlib.decompressobj()
        return getattr(self._obj, name)
    def decompress(self, data):
        if not self._first_try:
            return self._obj.decompress(data)
        self._data += data
            decompressed = self._obj.decompress(data)
            if decompressed:
                self._first_try = False
            return decompressed
        except zlib.error:
            self._obj = zlib.decompressobj(-zlib.MAX_WBITS)
                return self.decompress(self._data)
class GzipDecoderState(object):
    FIRST_MEMBER = 0
    OTHER_MEMBERS = 1
    SWALLOW_DATA = 2
class GzipDecoder(object):
        self._obj = zlib.decompressobj(16 + zlib.MAX_WBITS)
        self._state = GzipDecoderState.FIRST_MEMBER
        ret = bytearray()
        if self._state == GzipDecoderState.SWALLOW_DATA or not data:
            return bytes(ret)
                ret += self._obj.decompress(data)
                previous_state = self._state
                # Ignore data after the first error
                self._state = GzipDecoderState.SWALLOW_DATA
                if previous_state == GzipDecoderState.OTHER_MEMBERS:
                    # Allow trailing garbage acceptable in other gzip clients
            data = self._obj.unused_data
            self._state = GzipDecoderState.OTHER_MEMBERS
if brotli is not None:
    class BrotliDecoder(object):
        # Supports both 'brotlipy' and 'Brotli' packages
        # since they share an import name. The top branches
        # are for 'brotlipy' and bottom branches for 'Brotli'
            self._obj = brotli.Decompressor()
            if hasattr(self._obj, "decompress"):
                self.decompress = self._obj.decompress
                self.decompress = self._obj.process
            if hasattr(self._obj, "flush"):
                return self._obj.flush()
class MultiDecoder(object):
    From RFC7231:
        If one or more encodings have been applied to a representation, the
        sender that applied the encodings MUST generate a Content-Encoding
        header field that lists the content codings in the order in which
        they were applied.
    def __init__(self, modes):
        self._decoders = [_get_decoder(m.strip()) for m in modes.split(",")]
        return self._decoders[0].flush()
        for d in reversed(self._decoders):
            data = d.decompress(data)
def _get_decoder(mode):
    if "," in mode:
        return MultiDecoder(mode)
    if mode == "gzip":
        return GzipDecoder()
    if brotli is not None and mode == "br":
        return BrotliDecoder()
    return DeflateDecoder()
class HTTPResponse(io.IOBase):
    HTTP Response container.
    Backwards-compatible with :class:`http.client.HTTPResponse` but the response ``body`` is
    loaded and decoded on-demand when the ``data`` property is accessed.  This
    class is also compatible with the Python standard library's :mod:`io`
    module, and can hence be treated as a readable object in the context of that
    framework.
    Extra parameters for behaviour not present in :class:`http.client.HTTPResponse`:
    :param preload_content:
        If True, the response's body will be preloaded during construction.
    :param decode_content:
        If True, will attempt to decode the body based on the
        'content-encoding' header.
    :param original_response:
        When this HTTPResponse wrapper is generated from an :class:`http.client.HTTPResponse`
        object, it's convenient to include the original for debug purposes. It's
        otherwise unused.
    :param retries:
        The retries contains the last :class:`~urllib3.util.retry.Retry` that
        was used during the request.
    :param enforce_content_length:
        Enforce content length checking. Body returned by server must match
        value of Content-Length header, if present. Otherwise, raise error.
    CONTENT_DECODERS = ["gzip", "deflate"]
        CONTENT_DECODERS += ["br"]
    REDIRECT_STATUSES = [301, 302, 303, 307, 308]
        status=0,
        version=0,
        strict=0,
        preload_content=True,
        decode_content=True,
        original_response=None,
        pool=None,
        msg=None,
        retries=None,
        enforce_content_length=False,
        request_method=None,
        request_url=None,
        auto_close=True,
        if isinstance(headers, HTTPHeaderDict):
            self.headers = HTTPHeaderDict(headers)
        self.strict = strict
        self.decode_content = decode_content
        self.enforce_content_length = enforce_content_length
        self.auto_close = auto_close
        self._decoder = None
        self._body = None
        self._fp = None
        self._original_response = original_response
        self._fp_bytes_read = 0
        if body and isinstance(body, (six.string_types, bytes)):
            self._body = body
        self._pool = pool
            self._fp = body
        # Are we using the chunked-style of transfer encoding?
        self.chunked = False
        self.chunk_left = None
        tr_enc = self.headers.get("transfer-encoding", "").lower()
        # Don't incur the penalty of creating a list and then discarding it
        encodings = (enc.strip() for enc in tr_enc.split(","))
        if "chunked" in encodings:
            self.chunked = True
        # Determine length of response
        self.length_remaining = self._init_length(request_method)
        # If requested, preload the body.
        if preload_content and not self._body:
            self._body = self.read(decode_content=decode_content)
    def get_redirect_location(self):
        Should we redirect and where to?
        :returns: Truthy redirect location string if we got a redirect status
            code and valid location. ``None`` if redirect status and no
            location. ``False`` if not a redirect status code.
        if self.status in self.REDIRECT_STATUSES:
            return self.headers.get("location")
    def release_conn(self):
        if not self._pool or not self._connection:
        self._pool._put_conn(self._connection)
        self._connection = None
    def drain_conn(self):
        Read and discard any remaining HTTP response data in the response connection.
        Unread data in the HTTPResponse connection blocks the connection from being released back to the pool.
        except (HTTPError, SocketError, BaseSSLError, HTTPException):
        # For backwards-compat with earlier urllib3 0.4 and earlier.
        if self._body:
            return self._body
        if self._fp:
            return self.read(cache_content=True)
    def connection(self):
        return self._connection
    def isclosed(self):
        return is_fp_closed(self._fp)
        Obtain the number of bytes pulled over the wire so far. May differ from
        the amount of content returned by :meth:``urllib3.response.HTTPResponse.read``
        if bytes are encoded on the wire (e.g, compressed).
        return self._fp_bytes_read
    def _init_length(self, request_method):
        Set initial length value for Response content if available.
        length = self.headers.get("content-length")
            if self.chunked:
                # This Response will fail with an IncompleteRead if it can't be
                # received as chunked. This method falls back to attempt reading
                # the response before raising an exception.
                    "Received response with both Content-Length and "
                    "Transfer-Encoding set. This is expressly forbidden "
                    "by RFC 7230 sec 3.3.2. Ignoring Content-Length and "
                    "attempting to process response as Transfer-Encoding: "
                    "chunked."
                # RFC 7230 section 3.3.2 specifies multiple content lengths can
                # be sent in a single Content-Length header
                # (e.g. Content-Length: 42, 42). This line ensures the values
                # are all valid ints and that as long as the `set` length is 1,
                # all values are the same. Otherwise, the header is invalid.
                lengths = set([int(val) for val in length.split(",")])
                if len(lengths) > 1:
                        "Content-Length contained multiple "
                        "unmatching values (%s)" % length
                length = lengths.pop()
        # Convert status to int for comparison
        # In some cases, httplib returns a status of "_UNKNOWN"
            status = int(self.status)
            status = 0
        # Check for responses that shouldn't include a body
        if status in (204, 304) or 100 <= status < 200 or request_method == "HEAD":
            length = 0
        return length
    def _init_decoder(self):
        Set-up the _decoder attribute if necessary.
        # Note: content-encoding value should be case-insensitive, per RFC 7230
        # Section 3.2
        content_encoding = self.headers.get("content-encoding", "").lower()
        if self._decoder is None:
            if content_encoding in self.CONTENT_DECODERS:
                self._decoder = _get_decoder(content_encoding)
            elif "," in content_encoding:
                encodings = [
                    e.strip()
                    for e in content_encoding.split(",")
                    if e.strip() in self.CONTENT_DECODERS
                if len(encodings):
    DECODER_ERROR_CLASSES = (IOError, zlib.error)
        DECODER_ERROR_CLASSES += (brotli.error,)
    def _decode(self, data, decode_content, flush_decoder):
        Decode the data passed in and potentially flush the decoder.
        if not decode_content:
            if self._decoder:
                data = self._decoder.decompress(data)
        except self.DECODER_ERROR_CLASSES as e:
            raise DecodeError(
                "Received response with content-encoding: %s, but "
                "failed to decode it." % content_encoding,
        if flush_decoder:
            data += self._flush_decoder()
    def _flush_decoder(self):
        Flushes the decoder. Should only be called if the decoder is actually
        being used.
            buf = self._decoder.decompress(b"")
            return buf + self._decoder.flush()
    def _error_catcher(self):
        Catch low-level python exceptions, instead re-raising urllib3
        variants, so that low-level exceptions are not leaked in the
        high-level api.
        On exit, release the connection back to the pool.
        clean_exit = False
            except SocketTimeout:
                # FIXME: Ideally we'd like to include the url in the ReadTimeoutError but
                # there is yet no clean way to get at it from this context.
                raise ReadTimeoutError(self._pool, None, "Read timed out.")
            except BaseSSLError as e:
                # FIXME: Is there a better way to differentiate between SSLErrors?
                if "read operation timed out" not in str(e):
                    # SSL errors related to framing/MAC get wrapped and reraised here
                    raise SSLError(e)
            except (HTTPException, SocketError) as e:
                # This includes IncompleteRead.
                raise ProtocolError("Connection broken: %r" % e, e)
            # If no exception is thrown, we should avoid cleaning up
            # unnecessarily.
            clean_exit = True
            # If we didn't terminate cleanly, we need to throw away our
            if not clean_exit:
                # The response may not be closed but we're not going to use it
                # anymore so close it now to ensure that the connection is
                # released back to the pool.
                if self._original_response:
                    self._original_response.close()
                # Closing the response may not actually be sufficient to close
                # everything, so if we have a hold of the connection close that
                # too.
                if self._connection:
                    self._connection.close()
            # If we hold the original response but it's closed now, we should
            # return the connection back to the pool.
            if self._original_response and self._original_response.isclosed():
                self.release_conn()
    def _fp_read(self, amt):
        Read a response with the thought that reading the number of bytes
        larger than can fit in a 32-bit int at a time via SSL in some
        known cases leads to an overflow error that has to be prevented
        if `amt` or `self.length_remaining` indicate that a problem may
        happen.
        The known cases:
          * 3.8 <= CPython < 3.9.7 because of a bug
            https://github.com/urllib3/urllib3/issues/2513#issuecomment-1152559900.
          * urllib3 injected with pyOpenSSL-backed SSL-support.
          * CPython < 3.10 only when `amt` does not fit 32-bit int.
        assert self._fp
        c_int_max = 2 ** 31 - 1
                (amt and amt > c_int_max)
                or (self.length_remaining and self.length_remaining > c_int_max)
            and not util.IS_SECURETRANSPORT
            and (util.IS_PYOPENSSL or sys.version_info < (3, 10))
            buffer = io.BytesIO()
            # Besides `max_chunk_amt` being a maximum chunk size, it
            # affects memory overhead of reading a response by this
            # method in CPython.
            # `c_int_max` equal to 2 GiB - 1 byte is the actual maximum
            # chunk size that does not lead to an overflow error, but
            # 256 MiB is a compromise.
            max_chunk_amt = 2 ** 28
            while amt is None or amt != 0:
                if amt is not None:
                    chunk_amt = min(amt, max_chunk_amt)
                    amt -= chunk_amt
                    chunk_amt = max_chunk_amt
                data = self._fp.read(chunk_amt)
                buffer.write(data)
                del data  # to reduce peak memory usage by `max_chunk_amt`.
            return buffer.getvalue()
            # StringIO doesn't like amt=None
            return self._fp.read(amt) if amt is not None else self._fp.read()
    def read(self, amt=None, decode_content=None, cache_content=False):
        Similar to :meth:`http.client.HTTPResponse.read`, but with two additional
        parameters: ``decode_content`` and ``cache_content``.
        :param amt:
            How much of the content to read. If specified, caching is skipped
            because it doesn't make sense to cache partial content as the full
        :param cache_content:
            If True, will save the returned data such that the same result is
            returned despite of the state of the underlying file object. This
            is useful if you want the ``.data`` property to continue working
            after having ``.read()`` the file object. (Overridden if ``amt`` is
            set.)
        self._init_decoder()
        if decode_content is None:
            decode_content = self.decode_content
        if self._fp is None:
        flush_decoder = False
        fp_closed = getattr(self._fp, "closed", False)
        with self._error_catcher():
            data = self._fp_read(amt) if not fp_closed else b""
            if amt is None:
                flush_decoder = True
                cache_content = False
                    amt != 0 and not data
                ):  # Platform-specific: Buggy versions of Python.
                    # Close the connection when no data is returned
                    # This is redundant to what httplib/http.client _should_
                    # already do.  However, versions of python released before
                    # December 15, 2012 (http://bugs.python.org/issue16298) do
                    # not properly close the connection in all cases. There is
                    # no harm in redundantly calling close.
                    self._fp.close()
                    if self.enforce_content_length and self.length_remaining not in (
                        # This is an edge case that httplib failed to cover due
                        # to concerns of backward compatibility. We're
                        # addressing it here to make sure IncompleteRead is
                        # raised during streaming, so all calls with incorrect
                        # Content-Length are caught.
                        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
            self._fp_bytes_read += len(data)
            if self.length_remaining is not None:
                self.length_remaining -= len(data)
            data = self._decode(data, decode_content, flush_decoder)
            if cache_content:
                self._body = data
    def stream(self, amt=2 ** 16, decode_content=None):
        A generator wrapper for the read() method. A call will block until
        ``amt`` bytes have been read from the connection or until the
        connection is closed.
            How much of the content to read. The generator will return up to
            much data per iteration, but may return less. This is particularly
            likely when using compressed data. However, the empty string will
            never be returned.
        if self.chunked and self.supports_chunked_reads():
            for line in self.read_chunked(amt, decode_content=decode_content):
            while not is_fp_closed(self._fp):
                data = self.read(amt=amt, decode_content=decode_content)
    def from_httplib(ResponseCls, r, **response_kw):
        Given an :class:`http.client.HTTPResponse` instance ``r``, return a
        corresponding :class:`urllib3.response.HTTPResponse` object.
        Remaining parameters are passed to the HTTPResponse constructor, along
        with ``original_response=r``.
        headers = r.msg
        if not isinstance(headers, HTTPHeaderDict):
            if six.PY2:
                headers = HTTPHeaderDict.from_httplib(headers)
                headers = HTTPHeaderDict(headers.items())
        # HTTPResponse objects in Python 3 don't have a .strict attribute
        strict = getattr(r, "strict", 0)
        resp = ResponseCls(
            body=r,
            status=r.status,
            version=r.version,
            reason=r.reason,
            original_response=r,
            **response_kw
    # Backwards-compatibility methods for http.client.HTTPResponse
    def getheaders(self):
            "HTTPResponse.getheaders() is deprecated and will be removed "
            "in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.",
            "HTTPResponse.getheader() is deprecated and will be removed "
            "in urllib3 v2.1.0. Instead use HTTPResponse.headers.get(name, default).",
        return self.headers.get(name, default)
    # Backwards compatibility for http.cookiejar
    # Overrides from io.IOBase
        if not self.auto_close:
            io.IOBase.close(self)
            return io.IOBase.closed.__get__(self)
        elif self._fp is None:
        elif hasattr(self._fp, "isclosed"):
            return self._fp.isclosed()
        elif hasattr(self._fp, "closed"):
            return self._fp.closed
            raise IOError("HTTPResponse has no file to get a fileno from")
        elif hasattr(self._fp, "fileno"):
            return self._fp.fileno()
            raise IOError(
                "The file-like object this HTTPResponse is wrapped "
                "around has no file descriptor"
            self._fp is not None
            and hasattr(self._fp, "flush")
            and not getattr(self._fp, "closed", False)
            return self._fp.flush()
        # This method is required for `io` module compatibility.
        temp = self.read(len(b))
        if len(temp) == 0:
            b[: len(temp)] = temp
            return len(temp)
    def supports_chunked_reads(self):
        Checks if the underlying file-like object looks like a
        :class:`http.client.HTTPResponse` object. We do this by testing for
        the fp attribute. If it is present we assume it returns raw chunks as
        processed by read_chunked().
        return hasattr(self._fp, "fp")
    def _update_chunk_length(self):
        # First, we'll figure out length of a chunk and then
        # we'll try to read it from socket.
        if self.chunk_left is not None:
        line = self._fp.fp.readline()
        line = line.split(b";", 1)[0]
            self.chunk_left = int(line, 16)
            # Invalid chunked protocol response, abort.
            raise InvalidChunkLength(self, line)
    def _handle_chunk(self, amt):
        returned_chunk = None
            chunk = self._fp._safe_read(self.chunk_left)
            returned_chunk = chunk
            self._fp._safe_read(2)  # Toss the CRLF at the end of the chunk.
        elif amt < self.chunk_left:
            value = self._fp._safe_read(amt)
            self.chunk_left = self.chunk_left - amt
            returned_chunk = value
        elif amt == self.chunk_left:
        else:  # amt > self.chunk_left
            returned_chunk = self._fp._safe_read(self.chunk_left)
        return returned_chunk
    def read_chunked(self, amt=None, decode_content=None):
        Similar to :meth:`HTTPResponse.read`, but with an additional
        parameter: ``decode_content``.
        # FIXME: Rewrite this method and make it a class with a better structured logic.
        if not self.chunked:
            raise ResponseNotChunked(
                "Response is not chunked. "
                "Header 'transfer-encoding: chunked' is missing."
        if not self.supports_chunked_reads():
            raise BodyNotHttplibCompatible(
                "Body should be http.client.HTTPResponse like. "
                "It should have have an fp attribute which returns raw chunks."
            # Don't bother reading the body of a HEAD request.
            if self._original_response and is_response_to_head(self._original_response):
            # If a response is already read and closed
            # then return immediately.
            if self._fp.fp is None:
                self._update_chunk_length()
                if self.chunk_left == 0:
                chunk = self._handle_chunk(amt)
                decoded = self._decode(
                    chunk, decode_content=decode_content, flush_decoder=False
                    yield decoded
            if decode_content:
                # On CPython and PyPy, we should never need to flush the
                # decoder. However, on Jython we *might* need to, so
                # lets defensively do it anyway.
                decoded = self._flush_decoder()
                if decoded:  # Platform-specific: Jython.
            # Chunk content ends with \r\n: discard it.
                    # Some sites may not end with '\r\n'.
                if line == b"\r\n":
            # We read everything; close the "file".
        Returns the URL that was the source of this response.
        If the request that generated this response redirected, this method
        will return the final redirect location.
        if self.retries is not None and len(self.retries.history):
            return self.retries.history[-1].redirect_location
            return self._request_url
        buffer = []
        for chunk in self.stream(decode_content=True):
            if b"\n" in chunk:
                chunk = chunk.split(b"\n")
                yield b"".join(buffer) + chunk[0] + b"\n"
                for x in chunk[1:-1]:
                    yield x + b"\n"
                if chunk[-1]:
                    buffer = [chunk[-1]]
                buffer.append(chunk)
        if buffer:
            yield b"".join(buffer)
from email.errors import MultipartInvariantViolationDefect, StartBoundaryNotFoundDefect
from ..exceptions import HeaderParsingError
from ..packages.six.moves import http_client as httplib
def is_fp_closed(obj):
    Checks whether a given file-like object is closed.
    :param obj:
        The file-like object to check.
        # Check `isclosed()` first, in case Python3 doesn't set `closed`.
        # GH Issue #928
        return obj.isclosed()
        # Check via the official file-like-object way.
        return obj.closed
        # Check if the object is a container for another file-like object that
        # gets released on exhaustion (e.g. HTTPResponse).
        return obj.fp is None
    raise ValueError("Unable to determine whether fp is closed.")
def assert_header_parsing(headers):
    Asserts whether all headers have been successfully parsed.
    Extracts encountered errors from the result of parsing headers.
    Only works on Python 3.
    :param http.client.HTTPMessage headers: Headers to verify.
    :raises urllib3.exceptions.HeaderParsingError:
        If parsing errors are found.
    # This will fail silently if we pass in the wrong kind of parameter.
    # To make debugging easier add an explicit check.
    if not isinstance(headers, httplib.HTTPMessage):
        raise TypeError("expected httplib.Message, got {0}.".format(type(headers)))
    defects = getattr(headers, "defects", None)
    get_payload = getattr(headers, "get_payload", None)
    unparsed_data = None
    if get_payload:
        # get_payload is actually email.message.Message.get_payload;
        # we're only interested in the result if it's not a multipart message
        if not headers.is_multipart():
            payload = get_payload()
            if isinstance(payload, (bytes, str)):
                unparsed_data = payload
    if defects:
        # httplib is assuming a response body is available
        # when parsing headers even when httplib only sends
        # header data to parse_headers() This results in
        # defects on multipart responses in particular.
        # See: https://github.com/urllib3/urllib3/issues/800
        # So we ignore the following defects:
        # - StartBoundaryNotFoundDefect:
        #     The claimed start boundary was never found.
        # - MultipartInvariantViolationDefect:
        #     A message claimed to be a multipart but no subparts were found.
        defects = [
            defect
            for defect in defects
            if not isinstance(
                defect, (StartBoundaryNotFoundDefect, MultipartInvariantViolationDefect)
    if defects or unparsed_data:
        raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
def is_response_to_head(response):
    Checks whether the request of a response has been a HEAD-request.
    Handles the quirks of AppEngine.
    :param http.client.HTTPResponse response:
        Response to check if the originating request
        used 'HEAD' as a method.
    # FIXME: Can we do this somehow without accessing private httplib _method?
    method = response._method
    if isinstance(method, int):  # Platform-specific: Appengine
        return method == 3
    return method.upper() == "HEAD"
import json as _json
from http.client import HTTPMessage as _HttplibHTTPMessage
from http.client import HTTPResponse as _HttplibHTTPResponse
    from ._base_connection import BaseHTTPConnection
        import brotlicffi as brotli  # type: ignore[import-not-found]
        import brotli  # type: ignore[import-not-found]
from .connection import BaseSSLError, HTTPConnection, HTTPException
    DependencyWarning,
    from .connectionpool import HTTPConnectionPool
class ContentDecoder:
    def decompress(self, data: bytes, max_length: int = -1) -> bytes:
    def has_unconsumed_tail(self) -> bool:
    def flush(self) -> bytes:
class DeflateDecoder(ContentDecoder):
        self._first_try_data = b""
        self._unfed_data = b""
        data = self._unfed_data + data
        if not data and not self._obj.unconsumed_tail:
        original_max_length = max_length
        if original_max_length < 0:
            max_length = 0
        elif original_max_length == 0:
            # We should not pass 0 to the zlib decompressor because 0 is
            # the default value that will make zlib decompress without a
            # length limit.
            # Data should be stored for subsequent calls.
            self._unfed_data = data
        # Subsequent calls always reuse `self._obj`. zlib requires
        # passing the unconsumed tail if decompression is to continue.
            return self._obj.decompress(
                self._obj.unconsumed_tail + data, max_length=max_length
        # First call tries with RFC 1950 ZLIB format.
        self._first_try_data += data
            decompressed = self._obj.decompress(data, max_length=max_length)
        # On failure, it falls back to RFC 1951 DEFLATE format.
                return self.decompress(
                    self._first_try_data, max_length=original_max_length
        return bool(self._unfed_data) or (
            bool(self._obj.unconsumed_tail) and not self._first_try
class GzipDecoderState:
class GzipDecoder(ContentDecoder):
        self._unconsumed_tail = b""
        if self._state == GzipDecoderState.SWALLOW_DATA:
        if max_length == 0:
            self._unconsumed_tail += data
        # zlib requires passing the unconsumed tail to the subsequent
        # call if decompression is to continue.
        data = self._unconsumed_tail + data
        if not data and self._obj.eof:
                ret += self._obj.decompress(
                    data, max_length=max(max_length - len(ret), 0)
            self._unconsumed_tail = data = (
                self._obj.unconsumed_tail or self._obj.unused_data
            if max_length > 0 and len(ret) >= max_length:
            # When the end of a gzip member is reached, a new decompressor
            # must be created for unused (possibly future) data.
            if self._obj.eof:
        return bool(self._unconsumed_tail)
    class BrotliDecoder(ContentDecoder):
                setattr(self, "_decompress", self._obj.decompress)
                setattr(self, "_decompress", self._obj.process)
        # Requires Brotli >= 1.2.0 for `output_buffer_limit`.
        def _decompress(self, data: bytes, output_buffer_limit: int = -1) -> bytes:
                if max_length > 0:
                    return self._decompress(data, output_buffer_limit=max_length)
                    return self._decompress(data)
                # Fallback for Brotli/brotlicffi/brotlipy versions without
                # the `output_buffer_limit` parameter.
                    "Brotli >= 1.2.0 is required to prevent decompression bombs.",
                return not self._obj.can_accept_more_data()
                return self._obj.flush()  # type: ignore[no-any-return]
        from compression import zstd
        from backports import zstd
    HAS_ZSTD = False
    HAS_ZSTD = True
    class ZstdDecoder(ContentDecoder):
            self._obj = zstd.ZstdDecompressor()
            if not data and not self.has_unconsumed_tail:
                data = self._obj.unused_data + data
            part = self._obj.decompress(data, max_length=max_length)
            length = len(part)
            data_parts = [part]
            # Every loop iteration is supposed to read data from a separate frame.
            # The loop breaks when:
            #   - enough data is read;
            #   - no more unused data is available;
            #   - end of the last read frame has not been reached (i.e.,
            #     more data has to be fed).
                self._obj.eof
                and self._obj.unused_data
                and (max_length < 0 or length < max_length)
                unused_data = self._obj.unused_data
                if not self._obj.needs_input:
                part = self._obj.decompress(
                    unused_data,
                    max_length=(max_length - length) if max_length > 0 else -1,
                if part_length := len(part):
                    data_parts.append(part)
                    length += part_length
                elif self._obj.needs_input:
            return b"".join(data_parts)
            return not (self._obj.needs_input or self._obj.eof) or bool(
                self._obj.unused_data
            if not self._obj.eof:
                raise DecodeError("Zstandard data is incomplete")
class MultiDecoder(ContentDecoder):
    # Maximum allowed number of chained HTTP encodings in the
    # Content-Encoding header.
    max_decode_links = 5
    def __init__(self, modes: str) -> None:
        encodings = [m.strip() for m in modes.split(",")]
        if len(encodings) > self.max_decode_links:
                "Too many content encodings in the chain: "
                f"{len(encodings)} > {self.max_decode_links}"
        self._decoders = [_get_decoder(e) for e in encodings]
        if max_length <= 0:
        # Every while loop iteration goes through all decoders once.
        # It exits when enough data is read or no more data can be read.
        # It is possible that the while loop iteration does not produce
        # any data because we retrieve up to `max_length` from every
        # decoder, and the amount of bytes may be insufficient for the
        # next decoder to produce enough/any output.
            any_data = False
                data = d.decompress(data, max_length=max_length - len(ret))
                    any_data = True
                # We should not break when no data is returned because
                # next decoders may produce data even with empty input.
            ret += data
            if not any_data or len(ret) >= max_length:
        return any(d.has_unconsumed_tail for d in self._decoders)
def _get_decoder(mode: str) -> ContentDecoder:
    # According to RFC 9110 section 8.4.1.3, recipients should
    # consider x-gzip equivalent to gzip
    if mode in ("gzip", "x-gzip"):
    if HAS_ZSTD and mode == "zstd":
        return ZstdDecoder()
class BytesQueueBuffer:
    """Memory-efficient bytes buffer
    To return decoded data in read() and still follow the BufferedIOBase API, we need a
    buffer to always return the correct amount of bytes.
    This buffer should be filled using calls to put()
    Our maximum memory usage is determined by the sum of the size of:
     * self.buffer, which contains the full data
     * the largest chunk that we will copy in get()
        self.buffer: typing.Deque[bytes | memoryview[bytes]] = collections.deque()
        self._size: int = 0
    def put(self, data: bytes) -> None:
        self.buffer.append(data)
        self._size += len(data)
    def get(self, n: int) -> bytes:
        if n == 0:
        elif not self.buffer:
            raise RuntimeError("buffer is empty")
        elif n < 0:
            raise ValueError("n should be > 0")
        if len(self.buffer[0]) == n and isinstance(self.buffer[0], bytes):
            self._size -= n
            return self.buffer.popleft()
        fetched = 0
        ret = io.BytesIO()
        while fetched < n:
            remaining = n - fetched
            chunk = self.buffer.popleft()
            chunk_length = len(chunk)
            if remaining < chunk_length:
                chunk = memoryview(chunk)
                left_chunk, right_chunk = chunk[:remaining], chunk[remaining:]
                ret.write(left_chunk)
                self.buffer.appendleft(right_chunk)
                self._size -= remaining
                ret.write(chunk)
                self._size -= chunk_length
            fetched += chunk_length
            if not self.buffer:
        return ret.getvalue()
    def get_all(self) -> bytes:
        buffer = self.buffer
        if not buffer:
            assert self._size == 0
        if len(buffer) == 1:
            result = buffer.pop()
            if isinstance(result, memoryview):
                result = result.tobytes()
            ret.writelines(buffer.popleft() for _ in range(len(buffer)))
            result = ret.getvalue()
        self._size = 0
class BaseHTTPResponse(io.IOBase):
    CONTENT_DECODERS = ["gzip", "x-gzip", "deflate"]
    if HAS_ZSTD:
        CONTENT_DECODERS += ["zstd"]
    DECODER_ERROR_CLASSES: tuple[type[Exception], ...] = (IOError, zlib.error)
        DECODER_ERROR_CLASSES += (zstd.ZstdError,)
        headers: typing.Mapping[str, str] | typing.Mapping[bytes, bytes] | None = None,
        status: int,
        version: int,
        version_string: str,
        reason: str | None,
        decode_content: bool,
        request_url: str | None,
        retries: Retry | None = None,
            self.headers = HTTPHeaderDict(headers)  # type: ignore[arg-type]
        self.version_string = version_string
        self._has_decoded_content = False
        self._request_url: str | None = request_url
        self._decoder: ContentDecoder | None = None
        self.length_remaining: int | None
    def get_redirect_location(self) -> str | None | typing.Literal[False]:
    def data(self) -> bytes:
    def json(self) -> typing.Any:
        Deserializes the body of the HTTP response as a Python object.
        The body of the HTTP response must be encoded using UTF-8, as per
        `RFC 8529 Section 8.1 <https://www.rfc-editor.org/rfc/rfc8259#section-8.1>`_.
        To use a custom JSON decoder pass the result of :attr:`HTTPResponse.data` to
        your custom decoder instead.
        If the body of the HTTP response is not decodable to UTF-8, a
        `UnicodeDecodeError` will be raised. If the body of the HTTP response is not a
        valid JSON document, a `json.JSONDecodeError` will be raised.
        Read more :ref:`here <json_content>`.
        :returns: The body of the HTTP response as a Python object.
        data = self.data.decode("utf-8")
        return _json.loads(data)
    def url(self) -> str | None:
    def url(self, url: str | None) -> None:
    def connection(self) -> BaseHTTPConnection | None:
    def retries(self) -> Retry | None:
        return self._retries
    @retries.setter
    def retries(self, retries: Retry | None) -> None:
        # Override the request_url if retries has a redirect location.
        if retries is not None and retries.history:
            self.url = retries.history[-1].redirect_location
        self._retries = retries
        self, amt: int | None = 2**16, decode_content: bool | None = None
    ) -> typing.Iterator[bytes]:
    def read(
        amt: int | None = None,
        decode_content: bool | None = None,
        cache_content: bool = False,
    def read1(
    def read_chunked(
    def release_conn(self) -> None:
    def drain_conn(self) -> None:
    def shutdown(self) -> None:
    def _init_decoder(self) -> None:
                if encodings:
    def _decode(
        decode_content: bool | None,
        flush_decoder: bool,
        max_length: int | None = None,
            if self._has_decoded_content:
                    "Calling read(decode_content=False) is not supported after "
                    "read(decode_content=True) was called."
        if max_length is None or flush_decoder:
            max_length = -1
                data = self._decoder.decompress(data, max_length=max_length)
                self._has_decoded_content = True
    def _flush_decoder(self) -> bytes:
            return self._decoder.decompress(b"") + self._decoder.flush()
    # Compatibility methods for `io` module
    def readinto(self, b: bytearray) -> int:
    # Methods used by dependent libraries
    def getheaders(self) -> HTTPHeaderDict:
    def getheader(self, name: str, default: str | None = None) -> str | None:
    # Compatibility method for http.cookiejar
    def info(self) -> HTTPHeaderDict:
    def geturl(self) -> str | None:
class HTTPResponse(BaseHTTPResponse):
        body: _TYPE_BODY = "",
        status: int = 0,
        version: int = 0,
        version_string: str = "HTTP/?",
        preload_content: bool = True,
        decode_content: bool = True,
        original_response: _HttplibHTTPResponse | None = None,
        pool: HTTPConnectionPool | None = None,
        connection: HTTPConnection | None = None,
        msg: _HttplibHTTPMessage | None = None,
        enforce_content_length: bool = True,
        request_method: str | None = None,
        request_url: str | None = None,
        auto_close: bool = True,
        sock_shutdown: typing.Callable[[int], None] | None = None,
            version_string=version_string,
            reason=reason,
            request_url=request_url,
        self._fp: _HttplibHTTPResponse | None = None
        if body and isinstance(body, (str, bytes)):
            self._fp = body  # type: ignore[assignment]
        self._sock_shutdown = sock_shutdown
        self.chunk_left: int | None = None
        # Used to return the correct amount of bytes for partial read()s
        self._decoded_buffer = BytesQueueBuffer()
            self.read(
                # Do not spend resources decoding the content unless
                # decoding has already been initiated.
                decode_content=self._has_decoded_content,
        except (HTTPError, OSError, BaseSSLError, HTTPException):
            return self._body  # type: ignore[return-value]
        return None  # type: ignore[return-value]
    def connection(self) -> HTTPConnection | None:
    def isclosed(self) -> bool:
    def tell(self) -> int:
    def _init_length(self, request_method: str | None) -> int | None:
        length: int | None
        content_length: str | None = self.headers.get("content-length")
        if content_length is not None:
                lengths = {int(val) for val in content_length.split(",")}
                        "unmatching values (%s)" % content_length
        else:  # if content_length is None
    def _error_catcher(self) -> typing.Generator[None]:
            except SocketTimeout as e:
                raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
                    raise SSLError(e) from e
                    e.expected is not None
                    and e.partial is not None
                    and e.expected == -e.partial
                    arg = "Response may not contain content."
                    arg = f"Connection broken: {e!r}"
                raise ProtocolError(arg, e) from e
            except (HTTPException, OSError) as e:
                raise ProtocolError(f"Connection broken: {e!r}", e) from e
    def _fp_read(
        read1: bool = False,
          * CPython < 3.9.7 because of a bug
        c_int_max = 2**31 - 1
                amt is None
                and self.length_remaining
                and self.length_remaining > c_int_max
        ) and (util.IS_PYOPENSSL or sys.version_info < (3, 10)):
            if read1:
                return self._fp.read1(c_int_max)
            max_chunk_amt = 2**28
        elif read1:
            return self._fp.read1(amt) if amt is not None else self._fp.read1()
    def _raw_read(
        Reads `amt` of bytes from the socket.
            data = self._fp_read(amt, read1=read1) if not fp_closed else b""
            if amt is not None and amt != 0 and not data:
                # Platform-specific: Buggy versions of Python.
                    self.enforce_content_length
                    and self.length_remaining is not None
                    and self.length_remaining != 0
            elif read1 and (
                (amt != 0 and not data) or self.length_remaining == len(data)
                # All data has been read, but `self._fp.read1` in
                # CPython 3.12 and older doesn't always close
                # `http.client.HTTPResponse`, so we close it here.
                # See https://github.com/python/cpython/issues/113199
        if amt and amt < 0:
            # Negative numbers and `None` should be treated the same.
            amt = None
        elif amt is not None:
            if self._decoder and self._decoder.has_unconsumed_tail:
                decoded_data = self._decode(
                    decode_content,
                    flush_decoder=False,
                    max_length=amt - len(self._decoded_buffer),
                self._decoded_buffer.put(decoded_data)
            if len(self._decoded_buffer) >= amt:
                return self._decoded_buffer.get(amt)
        data = self._raw_read(amt)
        flush_decoder = amt is None or (amt != 0 and not data)
            not data
            and len(self._decoded_buffer) == 0
            and not (self._decoder and self._decoder.has_unconsumed_tail)
            # do not waste memory on buffer when not decoding
                flush_decoder,
            while len(self._decoded_buffer) < amt and data:
                # TODO make sure to initially read enough data to get past the headers
                # For example, the GZ file header takes 10 bytes, we don't want to read
                # it one byte at a time
            data = self._decoded_buffer.get(amt)
        Similar to ``http.client.HTTPResponse.read1`` and documented
        in :meth:`io.BufferedReader.read1`, but with an additional parameter:
        ``decode_content``.
            How much of the content to read.
        # try and respond without going to the network
                    "Calling read1(decode_content=False) is not supported after "
                    "read1(decode_content=True) was called."
                self._decoder
                and self._decoder.has_unconsumed_tail
                and (amt is None or len(self._decoded_buffer) < amt)
                    max_length=(
                        amt - len(self._decoded_buffer) if amt is not None else None
            if len(self._decoded_buffer) > 0:
                    return self._decoded_buffer.get_all()
        if amt == 0:
        # FIXME, this method's type doesn't say returning None is possible
        data = self._raw_read(amt, read1=True)
        if not decode_content or data is None:
            flush_decoder = not data
                data, decode_content, flush_decoder, max_length=amt
            if decoded_data or flush_decoder:
            data = self._raw_read(8192, read1=True)
    ) -> typing.Generator[bytes]:
            yield from self.read_chunked(amt, decode_content=decode_content)
                not is_fp_closed(self._fp)
                or len(self._decoded_buffer) > 0
                or (self._decoder and self._decoder.has_unconsumed_tail)
    def readable(self) -> bool:
        if not self._sock_shutdown:
            raise ValueError("Cannot shutdown socket as self._sock_shutdown is not set")
        if self._connection is None:
                "Cannot shutdown as connection has already been released to the pool"
        self._sock_shutdown(socket.SHUT_RD)
        self._sock_shutdown = None
        if not self.closed and self._fp:
    def closed(self) -> bool:
            return io.IOBase.closed.__get__(self)  # type: ignore[no-any-return]
    def fileno(self) -> int:
            raise OSError("HTTPResponse has no file to get a fileno from")
    def flush(self) -> None:
    def supports_chunked_reads(self) -> bool:
    def _update_chunk_length(self) -> None:
        line = self._fp.fp.readline()  # type: ignore[union-attr]
                raise InvalidChunkLength(self, line) from None
                # Truncated at start of next chunk
                raise ProtocolError("Response ended prematurely") from None
    def _handle_chunk(self, amt: int | None) -> bytes:
            chunk = self._fp._safe_read(self.chunk_left)  # type: ignore[union-attr]
            self._fp._safe_read(2)  # type: ignore[union-attr] # Toss the CRLF at the end of the chunk.
        elif self.chunk_left is not None and amt < self.chunk_left:
            value = self._fp._safe_read(amt)  # type: ignore[union-attr]
            returned_chunk = self._fp._safe_read(self.chunk_left)  # type: ignore[union-attr]
        return returned_chunk  # type: ignore[no-any-return]
        self, amt: int | None = None, decode_content: bool | None = None
            if self._fp.fp is None:  # type: ignore[union-attr]
                # Negative numbers and `None` should be treated the same,
                # but httplib handles only `None` correctly.
                # First, check if any data is left in the decoder's buffer.
                    chunk = b""
                    max_length=amt,
            while self._fp is not None:
        self._request_url = url
    def __iter__(self) -> typing.Iterator[bytes]:
        buffer: list[bytes] = []
                chunks = chunk.split(b"\n")
                yield b"".join(buffer) + chunks[0] + b"\n"
                for x in chunks[1:-1]:
                if chunks[-1]:
                    buffer = [chunks[-1]]
from http.client import HTTPException as HTTPException
from ...exceptions import InvalidHeader, TimeoutError
from ...response import BaseHTTPResponse
from ...util.retry import Retry
from .request import EmscriptenRequest
    from ..._base_connection import BaseHTTPConnection, BaseHTTPSConnection
class EmscriptenResponse:
    headers: dict[str, str]
    body: IOBase | bytes
    request: EmscriptenRequest
class EmscriptenHttpResponseWrapper(BaseHTTPResponse):
        internal_response: EmscriptenResponse,
        connection: BaseHTTPConnection | BaseHTTPSConnection | None = None,
        self._pool = None  # set by pool class
        self._response = internal_response
        self._url = url
        self._closed = False
            headers=internal_response.headers,
            status=internal_response.status_code,
            request_url=url,
            version_string="HTTP/?",
            reason="",
        self.length_remaining = self._init_length(self._response.request.method)
        self.length_is_certain = False
    def connection(self) -> BaseHTTPConnection | BaseHTTPSConnection | None:
            self.status in (204, 304)
            or 100 <= self.status < 200
            or request_method == "HEAD"
        decode_content: bool | None = None,  # ignored because browser decodes always
            self._closed
            or self._response is None
            or (isinstance(self._response.body, IOBase) and self._response.body.closed)
            # body has been preloaded as a string by XmlHttpRequest
            if not isinstance(self._response.body, IOBase):
                self.length_remaining = len(self._response.body)
                self.length_is_certain = True
                # wrap body in IOStream
                self._response.body = BytesIO(self._response.body)
            if amt is not None and amt >= 0:
                # don't cache partial content
                data = self._response.body.read(amt)
            else:  # read all we can (and cache it)
                data = self._response.body.read()
                self.length_remaining = max(self.length_remaining - len(data), 0)
            if len(data) == 0 or (
                self.length_is_certain and self.length_remaining == 0
                # definitely finished reading, close response stream
                self._response.body.close()
            return typing.cast(bytes, data)
        # chunked is handled by browser
            bytes = self.read(amt, decode_content)
            if not bytes:
            yield bytes
        if not self._closed:
            if isinstance(self._response.body, IOBase):
            self._closed = True
        Catch Emscripten specific exceptions thrown by fetch.py,
        instead re-raising urllib3 variants, so that low-level exceptions
        are not leaked in the high-level api.
        from .fetch import _RequestError, _TimeoutError  # avoid circular import
        except _TimeoutError as e:
            raise TimeoutError(str(e))
        except _RequestError as e:
            raise HTTPException(str(e))
                # anymore so close it now
                    isinstance(self._response.body, IOBase)
                    and not self._response.body.closed
                # release the connection back to the pool
                # If we have read everything from the response stream,
                    and self._response.body.closed
import http.client as httplib
def is_fp_closed(obj: object) -> bool:
        return obj.isclosed()  # type: ignore[no-any-return, attr-defined]
        return obj.closed  # type: ignore[no-any-return, attr-defined]
        return obj.fp is None  # type: ignore[attr-defined]
def assert_header_parsing(headers: httplib.HTTPMessage) -> None:
        raise TypeError(f"expected httplib.Message, got {type(headers)}.")
        payload = headers.get_payload()
        for defect in headers.defects
def is_response_to_head(response: httplib.HTTPResponse) -> bool:
    method_str = response._method  # type: str  # type: ignore[attr-defined]
    return method_str.upper() == "HEAD"
