from .easy_input_message import EasyInputMessage
from .response_compaction_item_param import ResponseCompactionItemParam
from .response_tool_search_output_item_param import ResponseToolSearchOutputItemParam
from .response_function_call_output_item_list import ResponseFunctionCallOutputItemList
from .response_function_shell_call_output_content import ResponseFunctionShellCallOutputContent
    "ResponseInputItem",
    "ComputerCallOutput",
    "ComputerCallOutputAcknowledgedSafetyCheck",
    "FunctionCallOutput",
    "ToolSearchCall",
    "ShellCall",
    "ShellCallAction",
    "ShellCallEnvironment",
    "ShellCallOutput",
    "ApplyPatchCall",
    "ApplyPatchCallOperation",
    "ApplyPatchCallOperationCreateFile",
    "ApplyPatchCallOperationDeleteFile",
    "ApplyPatchCallOperationUpdateFile",
    "ApplyPatchCallOutput",
    "ItemReference",
    precedence over instructions given with the `user` role.
    content: ResponseInputMessageContentList
    A list of one or many input items to the model, containing different content
    types.
    role: Literal["user", "system", "developer"]
    """The role of the message input. One of `user`, `system`, or `developer`."""
    """The type of the message input. Always set to `message`."""
class ComputerCallOutputAcknowledgedSafetyCheck(BaseModel):
class ComputerCallOutput(BaseModel):
    """The output of a computer tool call."""
    """The ID of the computer tool call output."""
    acknowledged_safety_checks: Optional[List[ComputerCallOutputAcknowledgedSafetyCheck]] = None
class FunctionCallOutput(BaseModel):
    """The output of a function tool call."""
    output: Union[str, ResponseFunctionCallOutputItemList]
    """Text, image, or file output of the function tool call."""
    """The unique ID of the function tool call output.
class ToolSearchCall(BaseModel):
    arguments: object
    """The arguments supplied to the tool search call."""
    type: Literal["tool_search_call"]
    """The item type. Always `tool_search_call`."""
    """The unique ID of this tool search call."""
    """The unique ID of the tool search call generated by the model."""
    execution: Optional[Literal["server", "client"]] = None
    """Whether tool search was executed by the server or by the client."""
    """The status of the tool search call."""
class ShellCallAction(BaseModel):
    """Ordered shell commands for the execution environment to run."""
    Maximum number of UTF-8 characters to capture from combined stdout and stderr
    output.
    """Maximum wall-clock time in milliseconds to allow the shell commands to run."""
ShellCallEnvironment: TypeAlias = Annotated[
    Union[LocalEnvironment, ContainerReference, None], PropertyInfo(discriminator="type")
class ShellCall(BaseModel):
    """A tool representing a request to execute one or more shell commands."""
    action: ShellCallAction
    environment: Optional[ShellCallEnvironment] = None
    """The environment to execute the shell commands in."""
class ShellCallOutput(BaseModel):
    """The streamed output items emitted by a shell tool call."""
    output: List[ResponseFunctionShellCallOutputContent]
    Captured chunks of stdout and stderr output, along with their associated
    outcomes.
    """The type of the item. Always `shell_call_output`."""
    """The unique ID of the shell tool call output.
    The maximum number of UTF-8 characters captured for this shell call's combined
    """The status of the shell call output."""
class ApplyPatchCallOperationCreateFile(BaseModel):
    """Instruction for creating a new file via the apply_patch tool."""
    """Unified diff content to apply when creating the file."""
    """Path of the file to create relative to the workspace root."""
    """The operation type. Always `create_file`."""
class ApplyPatchCallOperationDeleteFile(BaseModel):
    """Instruction for deleting an existing file via the apply_patch tool."""
    """Path of the file to delete relative to the workspace root."""
    """The operation type. Always `delete_file`."""
class ApplyPatchCallOperationUpdateFile(BaseModel):
    """Instruction for updating an existing file via the apply_patch tool."""
    """Unified diff content to apply to the existing file."""
    """Path of the file to update relative to the workspace root."""
    """The operation type. Always `update_file`."""
ApplyPatchCallOperation: TypeAlias = Annotated[
    Union[ApplyPatchCallOperationCreateFile, ApplyPatchCallOperationDeleteFile, ApplyPatchCallOperationUpdateFile],
class ApplyPatchCall(BaseModel):
    A tool call representing a request to create, delete, or update files using diff patches.
    operation: ApplyPatchCallOperation
    The specific create, delete, or update instruction for the apply_patch tool
class ApplyPatchCallOutput(BaseModel):
    """The streamed output emitted by an apply patch tool call."""
    Optional human-readable log text from the apply patch tool (e.g., patch results
    or errors).
class ItemReference(BaseModel):
    """An internal identifier for an item to reference."""
    """The ID of the item to reference."""
    type: Optional[Literal["item_reference"]] = None
    """The type of item to reference. Always `item_reference`."""
ResponseInputItem: TypeAlias = Annotated[
        EasyInputMessage,
        ResponseOutputMessage,
        ComputerCallOutput,
        FunctionCallOutput,
        ToolSearchCall,
        ResponseToolSearchOutputItemParam,
        ResponseCompactionItemParam,
        ShellCall,
        ShellCallOutput,
        ApplyPatchCall,
        ApplyPatchCallOutput,
        ItemReference,
