from .response_function_call_output_item import ResponseFunctionCallOutputItem
__all__ = ["ResponseFunctionCallOutputItemList"]
ResponseFunctionCallOutputItemList: TypeAlias = List[ResponseFunctionCallOutputItem]
