__all__ = ["ResponseCompactionItem"]
class ResponseCompactionItem(BaseModel):
    A compaction item generated by the [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
    """The unique ID of the compaction item."""
    encrypted_content: str
    """The encrypted content that was produced by compaction."""
    type: Literal["compaction"]
    """The type of the item. Always `compaction`."""
    """The identifier of the actor that created the item."""
