VERSION: str = __version__
# Copyright 2021 Google LLC
__version__ = "2.193.0"
with open(path.join(here, 'version.txt'), encoding='utf-8') as f:
    __version__ = f.read()
# Autogenerated by devscripts/update-version.py
__version__ = '2026.03.17'
RELEASE_GIT_HEAD = '04d6974f502bbdfaed72c624344f262e30ad9708'
VARIANT = None
UPDATE_HINT = None
CHANNEL = 'stable'
ORIGIN = 'yt-dlp/yt-dlp'
_pkg_version = '2026.03.17'
# Private, stable API for detecting the Python implementation.
PYPY = sys.implementation.name == "pypy"
# Private, stable API for detecting the Python version. PYXY means "Python X.Y
# or later". So that third-party apps can use these values, each constant
# should remain as long as the oldest supported Django version supports that
# Python version.
PY38 = sys.version_info >= (3, 8)
PY39 = sys.version_info >= (3, 9)
PY310 = sys.version_info >= (3, 10)
PY311 = sys.version_info >= (3, 11)
PY312 = sys.version_info >= (3, 12)
PY313 = sys.version_info >= (3, 13)
PY314 = sys.version_info >= (3, 14)
PY315 = sys.version_info >= (3, 15)
def get_version(version=None):
    """Return a PEP 440-compliant version number from VERSION."""
    version = get_complete_version(version)
    # Now build the two parts of the version number:
    # main = X.Y[.Z]
    # sub = .devN - for pre-alpha releases
    #     | {a|b|rc}N - for alpha, beta, and rc releases
    main = get_main_version(version)
    sub = ""
    if version[3] == "alpha" and version[4] == 0:
        git_changeset = get_git_changeset()
        if git_changeset:
            sub = ".dev%s" % git_changeset
    elif version[3] != "final":
        mapping = {"alpha": "a", "beta": "b", "rc": "rc"}
        sub = mapping[version[3]] + str(version[4])
    return main + sub
def get_main_version(version=None):
    """Return main version (X.Y[.Z]) from VERSION."""
    parts = 2 if version[2] == 0 else 3
    return ".".join(str(x) for x in version[:parts])
def get_complete_version(version=None):
    Return a tuple of the django version. If version argument is non-empty,
    check for correctness of the tuple provided.
        from django import VERSION as version
        assert len(version) == 5
        assert version[3] in ("alpha", "beta", "rc", "final")
def get_docs_version(version=None):
    if version[3] != "final":
        return "dev"
        return "%d.%d" % version[:2]
def get_git_changeset():
    """Return a numeric identifier of the latest git changeset.
    The result is the UTC timestamp of the changeset in YYYYMMDDHHMMSS format.
    This value isn't guaranteed to be unique, but collisions are very unlikely,
    so it's sufficient for generating the development version numbers.
    # Repository may not be found if __file__ is undefined, e.g. in a frozen
    # module.
    if "__file__" not in globals():
    repo_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    git_log = subprocess.run(
        "git log --pretty=format:%ct --quiet -1 HEAD",
        cwd=repo_dir,
        text=True,
    timestamp = git_log.stdout
    tz = datetime.UTC
        timestamp = datetime.datetime.fromtimestamp(int(timestamp), tz=tz)
    return timestamp.strftime("%Y%m%d%H%M%S")
version_component_re = _lazy_re_compile(r"(\d+|[a-z]+|\.)")
def get_version_tuple(version):
    Return a tuple of version numbers (e.g. (1, 2, 3)) from the version
    string (e.g. '1.2.3').
    version_numbers = []
    for item in version_component_re.split(version):
        if item and item != ".":
                component = int(item)
                version_numbers.append(component)
    return tuple(version_numbers)
"""langchain-core version information and utilities."""
VERSION = "1.2.23"
from typing import Callable, Iterator, List, Optional, SupportsInt, Tuple, Union
from ._structures import Infinity, InfinityType, NegativeInfinity, NegativeInfinityType
__all__ = ["parse", "Version", "LegacyVersion", "InvalidVersion", "VERSION_PATTERN"]
InfiniteTypes = Union[InfinityType, NegativeInfinityType]
PrePostDevType = Union[InfiniteTypes, Tuple[str, int]]
SubLocalType = Union[InfiniteTypes, int, str]
LocalType = Union[
    NegativeInfinityType,
    Tuple[
            SubLocalType,
            Tuple[SubLocalType, str],
            Tuple[NegativeInfinityType, SubLocalType],
        ...,
CmpKey = Tuple[
    int, Tuple[int, ...], PrePostDevType, PrePostDevType, PrePostDevType, LocalType
LegacyCmpKey = Tuple[int, Tuple[str, ...]]
VersionComparisonMethod = Callable[
    [Union[CmpKey, LegacyCmpKey], Union[CmpKey, LegacyCmpKey]], bool
_Version = collections.namedtuple(
    "_Version", ["epoch", "release", "dev", "pre", "post", "local"]
def parse(version: str) -> Union["LegacyVersion", "Version"]:
    Parse the given version string and return either a :class:`Version` object
    or a :class:`LegacyVersion` object depending on if the given version is
    a valid PEP 440 version or a legacy version.
        return Version(version)
        return LegacyVersion(version)
class InvalidVersion(ValueError):
    An invalid version was found, users should refer to PEP 440.
class _BaseVersion:
    _key: Union[CmpKey, LegacyCmpKey]
        return hash(self._key)
    # Please keep the duplicated `isinstance` check
    # in the six comparisons hereunder
    # unless you find a way to avoid adding overhead function calls.
    def __lt__(self, other: "_BaseVersion") -> bool:
        if not isinstance(other, _BaseVersion):
        return self._key < other._key
    def __le__(self, other: "_BaseVersion") -> bool:
        return self._key <= other._key
        return self._key == other._key
    def __ge__(self, other: "_BaseVersion") -> bool:
        return self._key >= other._key
    def __gt__(self, other: "_BaseVersion") -> bool:
        return self._key > other._key
    def __ne__(self, other: object) -> bool:
        return self._key != other._key
class LegacyVersion(_BaseVersion):
    def __init__(self, version: str) -> None:
        self._version = str(version)
        self._key = _legacy_cmpkey(self._version)
            "Creating a LegacyVersion has been deprecated and will be "
            "removed in the next major release",
        return f"<LegacyVersion('{self}')>"
    def public(self) -> str:
    def base_version(self) -> str:
    def epoch(self) -> int:
    def release(self) -> None:
    def pre(self) -> None:
    def post(self) -> None:
    def dev(self) -> None:
    def local(self) -> None:
    def is_prerelease(self) -> bool:
    def is_postrelease(self) -> bool:
    def is_devrelease(self) -> bool:
_legacy_version_component_re = re.compile(r"(\d+ | [a-z]+ | \.| -)", re.VERBOSE)
_legacy_version_replacement_map = {
    "pre": "c",
    "preview": "c",
    "-": "final-",
    "rc": "c",
    "dev": "@",
def _parse_version_parts(s: str) -> Iterator[str]:
    for part in _legacy_version_component_re.split(s):
        part = _legacy_version_replacement_map.get(part, part)
        if not part or part == ".":
        if part[:1] in "0123456789":
            # pad for numeric comparison
            yield part.zfill(8)
            yield "*" + part
    # ensure that alpha/beta/candidate are before final
    yield "*final"
def _legacy_cmpkey(version: str) -> LegacyCmpKey:
    # We hardcode an epoch of -1 here. A PEP 440 version can only have a epoch
    # greater than or equal to 0. This will effectively put the LegacyVersion,
    # which uses the defacto standard originally implemented by setuptools,
    # as before all PEP 440 versions.
    epoch = -1
    # This scheme is taken from pkg_resources.parse_version setuptools prior to
    # it's adoption of the packaging library.
    parts: List[str] = []
    for part in _parse_version_parts(version.lower()):
        if part.startswith("*"):
            # remove "-" before a prerelease tag
            if part < "*final":
                while parts and parts[-1] == "*final-":
                    parts.pop()
            # remove trailing zeros from each series of numeric parts
            while parts and parts[-1] == "00000000":
        parts.append(part)
    return epoch, tuple(parts)
# Deliberately not anchored to the start and end of the string, to make it
# easier for 3rd party code to reuse
VERSION_PATTERN = r"""
    v?
        (?:(?P<epoch>[0-9]+)!)?                           # epoch
        (?P<release>[0-9]+(?:\.[0-9]+)*)                  # release segment
        (?P<pre>                                          # pre-release
            [-_\.]?
            (?P<pre_l>(a|b|c|rc|alpha|beta|pre|preview))
            (?P<pre_n>[0-9]+)?
        (?P<post>                                         # post release
            (?:-(?P<post_n1>[0-9]+))
                (?P<post_l>post|rev|r)
                (?P<post_n2>[0-9]+)?
        (?P<dev>                                          # dev release
            (?P<dev_l>dev)
            (?P<dev_n>[0-9]+)?
    (?:\+(?P<local>[a-z0-9]+(?:[-_\.][a-z0-9]+)*))?       # local version
class Version(_BaseVersion):
    _regex = re.compile(r"^\s*" + VERSION_PATTERN + r"\s*$", re.VERBOSE | re.IGNORECASE)
        # Validate the version and parse it into pieces
        match = self._regex.search(version)
            raise InvalidVersion(f"Invalid version: '{version}'")
        # Store the parsed out pieces of the version
        self._version = _Version(
            epoch=int(match.group("epoch")) if match.group("epoch") else 0,
            release=tuple(int(i) for i in match.group("release").split(".")),
            pre=_parse_letter_version(match.group("pre_l"), match.group("pre_n")),
            post=_parse_letter_version(
                match.group("post_l"), match.group("post_n1") or match.group("post_n2")
            dev=_parse_letter_version(match.group("dev_l"), match.group("dev_n")),
            local=_parse_local_version(match.group("local")),
        # Generate a key which will be used for sorting
        self._key = _cmpkey(
            self._version.epoch,
            self._version.release,
            self._version.pre,
            self._version.post,
            self._version.dev,
            self._version.local,
        return f"<Version('{self}')>"
        if self.epoch != 0:
            parts.append(f"{self.epoch}!")
        parts.append(".".join(str(x) for x in self.release))
        if self.pre is not None:
            parts.append("".join(str(x) for x in self.pre))
        if self.post is not None:
            parts.append(f".post{self.post}")
        if self.dev is not None:
            parts.append(f".dev{self.dev}")
        if self.local is not None:
            parts.append(f"+{self.local}")
        _epoch: int = self._version.epoch
        return _epoch
    def release(self) -> Tuple[int, ...]:
        _release: Tuple[int, ...] = self._version.release
        return _release
    def pre(self) -> Optional[Tuple[str, int]]:
        _pre: Optional[Tuple[str, int]] = self._version.pre
        return _pre
    def post(self) -> Optional[int]:
        return self._version.post[1] if self._version.post else None
    def dev(self) -> Optional[int]:
        return self._version.dev[1] if self._version.dev else None
    def local(self) -> Optional[str]:
        if self._version.local:
            return ".".join(str(x) for x in self._version.local)
        return str(self).split("+", 1)[0]
        return self.dev is not None or self.pre is not None
        return self.post is not None
        return self.dev is not None
    def major(self) -> int:
        return self.release[0] if len(self.release) >= 1 else 0
    def minor(self) -> int:
        return self.release[1] if len(self.release) >= 2 else 0
    def micro(self) -> int:
        return self.release[2] if len(self.release) >= 3 else 0
def _parse_letter_version(
    letter: str, number: Union[str, bytes, SupportsInt]
) -> Optional[Tuple[str, int]]:
    if letter:
        # We consider there to be an implicit 0 in a pre-release if there is
        # not a numeral associated with it.
        if number is None:
            number = 0
        # We normalize any letters to their lower case form
        letter = letter.lower()
        # We consider some words to be alternate spellings of other words and
        # in those cases we want to normalize the spellings to our preferred
        # spelling.
        if letter == "alpha":
            letter = "a"
        elif letter == "beta":
            letter = "b"
        elif letter in ["c", "pre", "preview"]:
            letter = "rc"
        elif letter in ["rev", "r"]:
            letter = "post"
        return letter, int(number)
    if not letter and number:
        # We assume if we are given a number, but we are not given a letter
        # then this is using the implicit post release syntax (e.g. 1.0-1)
_local_version_separators = re.compile(r"[\._-]")
def _parse_local_version(local: str) -> Optional[LocalType]:
    Takes a string like abc.1.twelve and turns it into ("abc", 1, "twelve").
    if local is not None:
            part.lower() if not part.isdigit() else int(part)
            for part in _local_version_separators.split(local)
def _cmpkey(
    epoch: int,
    release: Tuple[int, ...],
    pre: Optional[Tuple[str, int]],
    post: Optional[Tuple[str, int]],
    dev: Optional[Tuple[str, int]],
    local: Optional[Tuple[SubLocalType]],
) -> CmpKey:
    # When we compare a release version, we want to compare it with all of the
    # trailing zeros removed. So we'll use a reverse the list, drop all the now
    # leading zeros until we come to something non zero, then take the rest
    # re-reverse it back into the correct order and make it a tuple and use
    # that for our sorting key.
    _release = tuple(
        reversed(list(itertools.dropwhile(lambda x: x == 0, reversed(release))))
    # We need to "trick" the sorting algorithm to put 1.0.dev0 before 1.0a0.
    # We'll do this by abusing the pre segment, but we _only_ want to do this
    # if there is not a pre or a post segment. If we have one of those then
    # the normal sorting rules will handle this case correctly.
    if pre is None and post is None and dev is not None:
        _pre: PrePostDevType = NegativeInfinity
    # Versions without a pre-release (except as noted above) should sort after
    # those with one.
    elif pre is None:
        _pre = Infinity
        _pre = pre
    # Versions without a post segment should sort before those with one.
    if post is None:
        _post: PrePostDevType = NegativeInfinity
        _post = post
    # Versions without a development segment should sort after those with one.
    if dev is None:
        _dev: PrePostDevType = Infinity
        _dev = dev
    if local is None:
        # Versions without a local segment should sort before those with one.
        _local: LocalType = NegativeInfinity
        # Versions with a local segment need that segment parsed to implement
        # the sorting rules in PEP440.
        # - Alpha numeric segments sort before numeric segments
        # - Alpha numeric segments sort lexicographically
        # - Numeric segments sort numerically
        # - Shorter versions sort before longer versions when the prefixes
        #   match exactly
        _local = tuple(
            (i, "") if isinstance(i, int) else (NegativeInfinity, i) for i in local
    return epoch, _release, _pre, _post, _dev, _local
    __version__ = pkg_resources.get_distribution('setuptools').version
    __version__ = 'unknown'
# distutils/version.py
# Implements multiple version numbering conventions for the
# Python Module Distribution Utilities.
# $Id$
"""Provides classes to represent module version numbers (one class for
each style of version numbering).  There are currently two such classes
implemented: StrictVersion and LooseVersion.
Every version number class implements the following interface:
  * the 'parse' method takes a string and parses it to some internal
    representation; if the string is an invalid version number,
    'parse' raises a ValueError exception
  * the class constructor takes an optional string argument which,
    if supplied, is passed to 'parse'
  * __str__ reconstructs the string that was passed to 'parse' (or
    an equivalent string -- ie. one that will generate an equivalent
    version number instance)
  * __repr__ generates Python code to recreate the version number instance
  * _cmp compares the current instance with either another instance
    of the same class or a string (which will be parsed to an instance
    of the same class, thus must follow the same rules)
def suppress_known_deprecation():
    with warnings.catch_warnings(record=True) as ctx:
        warnings.filterwarnings(
            action='default',
            category=DeprecationWarning,
            message="distutils Version classes are deprecated.",
class Version:
    """Abstract base class for version numbering classes.  Just provides
    constructor (__init__) and reproducer (__repr__), because those
    seem to be the same for all version numbering classes; and route
    rich comparisons to _cmp.
    def __init__(self, vstring=None):
        if vstring:
            self.parse(vstring)
            "distutils Version classes are deprecated. "
            "Use packaging.version instead.",
        return "%s ('%s')" % (self.__class__.__name__, str(self))
        c = self._cmp(other)
        if c is NotImplemented:
        return c == 0
        return c < 0
        return c <= 0
        return c > 0
        return c >= 0
# Interface for version-number classes -- must be implemented
# by the following classes (the concrete ones -- Version should
# be treated as an abstract class).
#    __init__ (string) - create and take same action as 'parse'
#                        (string parameter is optional)
#    parse (string)    - convert a string representation to whatever
#                        internal representation is appropriate for
#                        this style of version numbering
#    __str__ (self)    - convert back to a string; should be very similar
#                        (if not identical to) the string supplied to parse
#    __repr__ (self)   - generate Python code to recreate
#                        the instance
#    _cmp (self, other) - compare two version numbers ('other' may
#                        be an unparsed version string, or another
#                        instance of your version class)
class StrictVersion(Version):
    """Version numbering for anal retentives and software idealists.
    Implements the standard interface for version number classes as
    described above.  A version number consists of two or three
    dot-separated numeric components, with an optional "pre-release" tag
    on the end.  The pre-release tag consists of the letter 'a' or 'b'
    followed by a number.  If the numeric components of two version
    numbers are equal, then one with a pre-release tag will always
    be deemed earlier (lesser) than one without.
    The following are valid version numbers (shown in the order that
    would be obtained by sorting according to the supplied cmp function):
        0.4       0.4.0  (these two are equivalent)
        0.4.1
        0.5a1
        0.5b3
        0.5
        0.9.6
        1.0
        1.0.4a3
        1.0.4b1
        1.0.4
    The following are examples of invalid version numbers:
        2.7.2.2
        1.3.a4
        1.3pl1
        1.3c4
    The rationale for this version numbering system will be explained
    in the distutils documentation.
    version_re = re.compile(
        r'^(\d+) \. (\d+) (\. (\d+))? ([ab](\d+))?$', re.VERBOSE | re.ASCII
    def parse(self, vstring):
        match = self.version_re.match(vstring)
            raise ValueError("invalid version number '%s'" % vstring)
        (major, minor, patch, prerelease, prerelease_num) = match.group(1, 2, 4, 5, 6)
        if patch:
            self.version = tuple(map(int, [major, minor, patch]))
            self.version = tuple(map(int, [major, minor])) + (0,)
        if prerelease:
            self.prerelease = (prerelease[0], int(prerelease_num))
            self.prerelease = None
        if self.version[2] == 0:
            vstring = '.'.join(map(str, self.version[0:2]))
            vstring = '.'.join(map(str, self.version))
        if self.prerelease:
            vstring = vstring + self.prerelease[0] + str(self.prerelease[1])
        return vstring
    def _cmp(self, other):
            with suppress_known_deprecation():
                other = StrictVersion(other)
        elif not isinstance(other, StrictVersion):
        if self.version != other.version:
            # numeric versions don't match
            # prerelease stuff doesn't matter
            if self.version < other.version:
        # have to compare prerelease
        # case 1: neither has prerelease; they're equal
        # case 2: self has prerelease, other doesn't; other is greater
        # case 3: self doesn't have prerelease, other does: self is greater
        # case 4: both have prerelease: must compare them!
        if not self.prerelease and not other.prerelease:
        elif self.prerelease and not other.prerelease:
        elif not self.prerelease and other.prerelease:
        elif self.prerelease and other.prerelease:
            if self.prerelease == other.prerelease:
            elif self.prerelease < other.prerelease:
            assert False, "never get here"
# end class StrictVersion
# The rules according to Greg Stein:
# 1) a version number has 1 or more numbers separated by a period or by
#    sequences of letters. If only periods, then these are compared
#    left-to-right to determine an ordering.
# 2) sequences of letters are part of the tuple for comparison and are
#    compared lexicographically
# 3) recognize the numeric components may have leading zeroes
# The LooseVersion class below implements these rules: a version number
# string is split up into a tuple of integer and string components, and
# comparison is a simple tuple comparison.  This means that version
# numbers behave in a predictable and obvious way, but a way that might
# not necessarily be how people *want* version numbers to behave.  There
# wouldn't be a problem if people could stick to purely numeric version
# numbers: just split on period and compare the numbers as tuples.
# However, people insist on putting letters into their version numbers;
# the most common purpose seems to be:
#   - indicating a "pre-release" version
#     ('alpha', 'beta', 'a', 'b', 'pre', 'p')
#   - indicating a post-release patch ('p', 'pl', 'patch')
# but of course this can't cover all version number schemes, and there's
# no way to know what a programmer means without asking him.
# The problem is what to do with letters (and other non-numeric
# characters) in a version number.  The current implementation does the
# obvious and predictable thing: keep them as strings and compare
# lexically within a tuple comparison.  This has the desired effect if
# an appended letter sequence implies something "post-release":
# eg. "0.99" < "0.99pl14" < "1.0", and "5.001" < "5.001m" < "5.002".
# However, if letters in a version number imply a pre-release version,
# the "obvious" thing isn't correct.  Eg. you would expect that
# "1.5.1" < "1.5.2a2" < "1.5.2", but under the tuple/lexical comparison
# implemented here, this just isn't so.
# Two possible solutions come to mind.  The first is to tie the
# comparison algorithm to a particular set of semantic rules, as has
# been done in the StrictVersion class above.  This works great as long
# as everyone can go along with bondage and discipline.  Hopefully a
# (large) subset of Python module programmers will agree that the
# particular flavour of bondage and discipline provided by StrictVersion
# provides enough benefit to be worth using, and will submit their
# version numbering scheme to its domination.  The free-thinking
# anarchists in the lot will never give in, though, and something needs
# to be done to accommodate them.
# Perhaps a "moderately strict" version class could be implemented that
# lets almost anything slide (syntactically), and makes some heuristic
# assumptions about non-digits in version number strings.  This could
# sink into special-case-hell, though; if I was as talented and
# idiosyncratic as Larry Wall, I'd go ahead and implement a class that
# somehow knows that "1.2.1" < "1.2.2a2" < "1.2.2" < "1.2.2pl3", and is
# just as happy dealing with things like "2g6" and "1.13++".  I don't
# think I'm smart enough to do it right though.
# In any case, I've coded the test suite for this module (see
# ../test/test_version.py) specifically to fail on things like comparing
# "1.2a2" and "1.2".  That's not because the *code* is doing anything
# wrong, it's because the simple, obvious design doesn't match my
# complicated, hairy expectations for real-world version numbers.  It
# would be a snap to fix the test suite to say, "Yep, LooseVersion does
# the Right Thing" (ie. the code matches the conception).  But I'd rather
# have a conception that matches common notions about version numbers.
class LooseVersion(Version):
    """Version numbering for anarchists and software realists.
    described above.  A version number consists of a series of numbers,
    separated by either periods or strings of letters.  When comparing
    version numbers, the numeric components will be compared
    numerically, and the alphabetic components lexically.  The following
    are all valid version numbers, in no particular order:
        1.5.1
        1.5.2b2
        161
        3.10a
        8.02
        3.4j
        1996.07.12
        3.2.pl0
        3.1.1.6
        2g6
        11g
        0.960923
        2.2beta29
        1.13++
        5.5.kw
        2.0b1pl0
    In fact, there is no such thing as an invalid version number under
    this scheme; the rules for comparison are simple and predictable,
    but may not always give the results you want (for some definition
    of "want").
    component_re = re.compile(r'(\d+ | [a-z]+ | \.)', re.VERBOSE)
        # I've given up on thinking I can reconstruct the version string
        # from the parsed tuple -- so I just store the string here for
        # use by __str__
        self.vstring = vstring
        components = [x for x in self.component_re.split(vstring) if x and x != '.']
        for i, obj in enumerate(components):
                components[i] = int(obj)
        self.version = components
        return self.vstring
        return "LooseVersion ('%s')" % str(self)
            other = LooseVersion(other)
        elif not isinstance(other, LooseVersion):
        if self.version == other.version:
        if self.version > other.version:
# end class LooseVersion
.. testsetup::
    from pip._vendor.packaging.version import parse, Version
    SupportsInt,
    from typing_extensions import Self, Unpack
    from warnings import deprecated as _deprecated
elif typing.TYPE_CHECKING:
    from typing_extensions import deprecated as _deprecated
    def _deprecated(message: str) -> object:
        def decorator(func: object) -> object:
_LETTER_NORMALIZATION = {
    "alpha": "a",
    "beta": "b",
    "c": "rc",
    "pre": "rc",
    "preview": "rc",
    "rev": "post",
    "r": "post",
__all__ = ["VERSION_PATTERN", "InvalidVersion", "Version", "parse"]
LocalType = Tuple[Union[int, str], ...]
CmpPrePostDevType = Union[InfinityType, NegativeInfinityType, Tuple[str, int]]
CmpLocalType = Union[
    Tuple[Union[Tuple[int, str], Tuple[NegativeInfinityType, Union[int, str]]], ...],
    Tuple[int, ...],
    CmpPrePostDevType,
    CmpLocalType,
VersionComparisonMethod = Callable[[CmpKey, CmpKey], bool]
class _VersionReplace(TypedDict, total=False):
    epoch: int | None
    release: tuple[int, ...] | None
    pre: tuple[Literal["a", "b", "rc"], int] | None
    post: int | None
    dev: int | None
    local: str | None
def parse(version: str) -> Version:
    """Parse the given version string.
    >>> parse('1.0.dev1')
    <Version('1.0.dev1')>
    :param version: The version string to parse.
    :raises InvalidVersion: When the version string is not a valid version.
    """Raised when a version string is not a valid version.
    >>> Version("invalid")
    packaging.version.InvalidVersion: Invalid version: 'invalid'
    # This can also be a normal member (see the packaging_legacy package);
    # we are just requiring it to be readable. Actually defining a property
    # has runtime effect on subclasses, so it's typing only.
        def _key(self) -> tuple[Any, ...]: ...
    def __lt__(self, other: _BaseVersion) -> bool:
    def __le__(self, other: _BaseVersion) -> bool:
    def __ge__(self, other: _BaseVersion) -> bool:
    def __gt__(self, other: _BaseVersion) -> bool:
# Note that ++ doesn't behave identically on CPython and PyPy, so not using it here
_VERSION_PATTERN = r"""
    v?+                                                   # optional leading v
        (?:(?P<epoch>[0-9]+)!)?+                          # epoch
        (?P<release>[0-9]+(?:\.[0-9]+)*+)                 # release segment
            [._-]?+
            (?P<pre_l>alpha|a|beta|b|preview|pre|c|rc)
        )?+
                [._-]?
    (?:\+
        (?P<local>                                        # local version
            [a-z0-9]+
            (?:[._-][a-z0-9]+)*+
_VERSION_PATTERN_OLD = _VERSION_PATTERN.replace("*+", "*").replace("?+", "?")
# Possessive qualifiers were added in Python 3.11.
# CPython 3.11.0-3.11.4 had a bug: https://github.com/python/cpython/pull/107795
# Older PyPy also had a bug.
VERSION_PATTERN = (
    _VERSION_PATTERN_OLD
    if (sys.implementation.name == "cpython" and sys.version_info < (3, 11, 5))
    or (sys.implementation.name == "pypy" and sys.version_info < (3, 11, 13))
    or sys.version_info < (3, 11)
    else _VERSION_PATTERN
A string containing the regular expression used to match a valid version.
The pattern is not anchored at either end, and is intended for embedding in larger
expressions (for example, matching a version number as part of a file name). The
regular expression should be compiled with the ``re.VERBOSE`` and ``re.IGNORECASE``
flags set.
:meta hide-value:
# Validation pattern for local version in replace()
_LOCAL_PATTERN = re.compile(r"[a-z0-9]+(?:[._-][a-z0-9]+)*", re.IGNORECASE)
def _validate_epoch(value: object, /) -> int:
    epoch = value or 0
    if isinstance(epoch, int) and epoch >= 0:
        return epoch
    msg = f"epoch must be non-negative integer, got {epoch}"
    raise InvalidVersion(msg)
def _validate_release(value: object, /) -> tuple[int, ...]:
    release = (0,) if value is None else value
        isinstance(release, tuple)
        and len(release) > 0
        and all(isinstance(i, int) and i >= 0 for i in release)
    msg = f"release must be a non-empty tuple of non-negative integers, got {release}"
def _validate_pre(value: object, /) -> tuple[Literal["a", "b", "rc"], int] | None:
        isinstance(value, tuple)
        and len(value) == 2
        and value[0] in ("a", "b", "rc")
        and isinstance(value[1], int)
        and value[1] >= 0
    msg = f"pre must be a tuple of ('a'|'b'|'rc', non-negative int), got {value}"
def _validate_post(value: object, /) -> tuple[Literal["post"], int] | None:
    if isinstance(value, int) and value >= 0:
        return ("post", value)
    msg = f"post must be non-negative integer, got {value}"
def _validate_dev(value: object, /) -> tuple[Literal["dev"], int] | None:
        return ("dev", value)
    msg = f"dev must be non-negative integer, got {value}"
def _validate_local(value: object, /) -> LocalType | None:
    if isinstance(value, str) and _LOCAL_PATTERN.fullmatch(value):
        return _parse_local_version(value)
    msg = f"local must be a valid version string, got {value!r}"
# Backward compatibility for internals before 26.0. Do not use.
class _Version(NamedTuple):
    epoch: int
    release: tuple[int, ...]
    dev: tuple[str, int] | None
    pre: tuple[str, int] | None
    post: tuple[str, int] | None
    local: LocalType | None
    """This class abstracts handling of a project's versions.
    A :class:`Version` instance is comparison aware and can be compared and
    sorted using the standard Python interfaces.
    >>> v1 = Version("1.0a5")
    >>> v2 = Version("1.0")
    >>> v1
    <Version('1.0a5')>
    >>> v2
    <Version('1.0')>
    >>> v1 < v2
    >>> v1 == v2
    >>> v1 > v2
    >>> v1 >= v2
    >>> v1 <= v2
    __slots__ = ("_dev", "_epoch", "_key_cache", "_local", "_post", "_pre", "_release")
    __match_args__ = ("_str",)
    _regex = re.compile(r"\s*" + VERSION_PATTERN + r"\s*", re.VERBOSE | re.IGNORECASE)
    _epoch: int
    _release: tuple[int, ...]
    _dev: tuple[str, int] | None
    _pre: tuple[str, int] | None
    _post: tuple[str, int] | None
    _local: LocalType | None
    _key_cache: CmpKey | None
        """Initialize a Version object.
        :param version:
            The string representation of a version which will be parsed and normalized
            before use.
        :raises InvalidVersion:
            If the ``version`` does not conform to PEP 440 in any way then this
            exception will be raised.
        match = self._regex.fullmatch(version)
            raise InvalidVersion(f"Invalid version: {version!r}")
        self._epoch = int(match.group("epoch")) if match.group("epoch") else 0
        self._release = tuple(map(int, match.group("release").split(".")))
        self._pre = _parse_letter_version(match.group("pre_l"), match.group("pre_n"))
        self._post = _parse_letter_version(
        self._dev = _parse_letter_version(match.group("dev_l"), match.group("dev_n"))
        self._local = _parse_local_version(match.group("local"))
        # Key which will be used for sorting
        self._key_cache = None
    def __replace__(self, **kwargs: Unpack[_VersionReplace]) -> Self:
        epoch = _validate_epoch(kwargs["epoch"]) if "epoch" in kwargs else self._epoch
        release = (
            _validate_release(kwargs["release"])
            if "release" in kwargs
            else self._release
        pre = _validate_pre(kwargs["pre"]) if "pre" in kwargs else self._pre
        post = _validate_post(kwargs["post"]) if "post" in kwargs else self._post
        dev = _validate_dev(kwargs["dev"]) if "dev" in kwargs else self._dev
        local = _validate_local(kwargs["local"]) if "local" in kwargs else self._local
            epoch == self._epoch
            and release == self._release
            and pre == self._pre
            and post == self._post
            and dev == self._dev
            and local == self._local
        new_version = self.__class__.__new__(self.__class__)
        new_version._key_cache = None
        new_version._epoch = epoch
        new_version._release = release
        new_version._pre = pre
        new_version._post = post
        new_version._dev = dev
        new_version._local = local
        return new_version
    def _key(self) -> CmpKey:
        if self._key_cache is None:
            self._key_cache = _cmpkey(
                self._epoch,
                self._release,
                self._pre,
                self._dev,
                self._local,
        return self._key_cache
    @_deprecated("Version._version is private and will be removed soon")
    def _version(self) -> _Version:
        return _Version(
            self._epoch, self._release, self._dev, self._pre, self._post, self._local
    @_version.setter
    def _version(self, value: _Version) -> None:
        self._epoch = value.epoch
        self._release = value.release
        self._dev = value.dev
        self._pre = value.pre
        self._post = value.post
        self._local = value.local
        """A representation of the Version that shows all internal state.
        >>> Version('1.0.0')
        <Version('1.0.0')>
        """A string representation of the version that can be round-tripped.
        >>> str(Version("1.0a5"))
        '1.0a5'
        # This is a hot function, so not calling self.base_version
        version = ".".join(map(str, self.release))
        if self.epoch:
            version = f"{self.epoch}!{version}"
            version += "".join(map(str, self.pre))
            version += f".post{self.post}"
            version += f".dev{self.dev}"
            version += f"+{self.local}"
    def _str(self) -> str:
        """Internal property for match_args"""
        """The epoch of the version.
        >>> Version("2.0.0").epoch
        >>> Version("1!2.0.0").epoch
        return self._epoch
    def release(self) -> tuple[int, ...]:
        """The components of the "release" segment of the version.
        >>> Version("1.2.3").release
        (1, 2, 3)
        >>> Version("2.0.0").release
        (2, 0, 0)
        >>> Version("1!2.0.0.post0").release
        Includes trailing zeroes but not the epoch or any pre-release / development /
        post-release suffixes.
        return self._release
    def pre(self) -> tuple[str, int] | None:
        """The pre-release segment of the version.
        >>> print(Version("1.2.3").pre)
        >>> Version("1.2.3a1").pre
        ('a', 1)
        >>> Version("1.2.3b1").pre
        ('b', 1)
        >>> Version("1.2.3rc1").pre
        ('rc', 1)
        return self._pre
    def post(self) -> int | None:
        """The post-release number of the version.
        >>> print(Version("1.2.3").post)
        >>> Version("1.2.3.post1").post
        return self._post[1] if self._post else None
    def dev(self) -> int | None:
        """The development number of the version.
        >>> print(Version("1.2.3").dev)
        >>> Version("1.2.3.dev1").dev
        return self._dev[1] if self._dev else None
    def local(self) -> str | None:
        """The local version segment of the version.
        >>> print(Version("1.2.3").local)
        >>> Version("1.2.3+abc").local
        if self._local:
            return ".".join(str(x) for x in self._local)
        """The public portion of the version.
        >>> Version("1.2.3").public
        '1.2.3'
        >>> Version("1.2.3+abc").public
        >>> Version("1!1.2.3dev1+abc").public
        '1!1.2.3.dev1'
        """The "base version" of the version.
        >>> Version("1.2.3").base_version
        >>> Version("1.2.3+abc").base_version
        >>> Version("1!1.2.3dev1+abc").base_version
        '1!1.2.3'
        The "base version" is the public version of the project without any pre or post
        release markers.
        release_segment = ".".join(map(str, self.release))
        return f"{self.epoch}!{release_segment}" if self.epoch else release_segment
        """Whether this version is a pre-release.
        >>> Version("1.2.3").is_prerelease
        >>> Version("1.2.3a1").is_prerelease
        >>> Version("1.2.3b1").is_prerelease
        >>> Version("1.2.3rc1").is_prerelease
        >>> Version("1.2.3dev1").is_prerelease
        """Whether this version is a post-release.
        >>> Version("1.2.3").is_postrelease
        >>> Version("1.2.3.post1").is_postrelease
        """Whether this version is a development release.
        >>> Version("1.2.3").is_devrelease
        >>> Version("1.2.3.dev1").is_devrelease
        """The first item of :attr:`release` or ``0`` if unavailable.
        >>> Version("1.2.3").major
        """The second item of :attr:`release` or ``0`` if unavailable.
        >>> Version("1.2.3").minor
        >>> Version("1").minor
        """The third item of :attr:`release` or ``0`` if unavailable.
        >>> Version("1.2.3").micro
        >>> Version("1").micro
class _TrimmedRelease(Version):
    def __init__(self, version: str | Version) -> None:
        if isinstance(version, Version):
            self._epoch = version._epoch
            self._release = version._release
            self._dev = version._dev
            self._pre = version._pre
            self._post = version._post
            self._local = version._local
            self._key_cache = version._key_cache
        super().__init__(version)  # pragma: no cover
        Release segment without any trailing zeros.
        >>> _TrimmedRelease('1.0.0').release
        (1,)
        >>> _TrimmedRelease('0.0').release
        (0,)
        # This leaves one 0.
        rel = super().release
        len_release = len(rel)
        i = len_release
        while i > 1 and rel[i - 1] == 0:
            i -= 1
        return rel if i == len_release else rel[:i]
    letter: str | None, number: str | bytes | SupportsInt | None
) -> tuple[str, int] | None:
        letter = _LETTER_NORMALIZATION.get(letter, letter)
        return letter, int(number or 0)
    if number:
        return "post", int(number)
def _parse_local_version(local: str | None) -> LocalType | None:
    release: tuple[int, ...],
    pre: tuple[str, int] | None,
    post: tuple[str, int] | None,
    dev: tuple[str, int] | None,
    local: LocalType | None,
    # trailing zeros removed. We will use this for our sorting key.
    len_release = len(release)
    while i and release[i - 1] == 0:
    _release = release if i == len_release else release[:i]
        _pre: CmpPrePostDevType = NegativeInfinity
        _post: CmpPrePostDevType = NegativeInfinity
        _dev: CmpPrePostDevType = Infinity
        _local: CmpLocalType = NegativeInfinity
# file generated by setuptools-scm
# don't change, don't track in version control
    "__version_tuple__",
    "version_tuple",
    "__commit_id__",
    "commit_id",
TYPE_CHECKING = False
    from typing import Tuple
    VERSION_TUPLE = Tuple[Union[int, str], ...]
    COMMIT_ID = Union[str, None]
    VERSION_TUPLE = object
    COMMIT_ID = object
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID
__version__ = version = '4.5.1'
__version_tuple__ = version_tuple = (4, 5, 1)
__commit_id__ = commit_id = None
    from packaging.version import parse, Version
version = "1.26.4"
full_version = version
git_revision = "9815c16f449e12915ef35a8255329ba26dacd5c0"
release = 'dev' not in version and '+' not in version
short_version = version.split("+")[0]
__version__ = '0.13.0'
# For backward-compatibility with earlier versions of json5:
VERSION = __version__
__version__ = version = '3.20.3'
__version_tuple__ = version_tuple = (3, 20, 3)
Expose version
__version__ = "3.4.4"
VERSION = __version__.split(".")
"""`tqdm` version detector. Precedence: installed dist, git, 'UNKNOWN'."""
    from importlib.metadata import PackageNotFoundError, version
except ImportError:  # py<3.8
    from importlib_metadata import PackageNotFoundError, version
    __version__ = version('tqdm')
except PackageNotFoundError:
Module to expose more detailed version info for the installed `scipy`
version = "1.15.3"
short_version = version.split('.dev')[0]
git_revision = "e29dcb65a2040f04819b426a04b60d44a8f69c04"
if not release:
    version = full_version
from ._rust_notify import __version__
__all__ = ('VERSION',)
"""The `version` module holds the version information for Pydantic."""
from pydantic_core import __version__ as __pydantic_core_version__
__all__ = 'VERSION', 'version_info'
VERSION = '2.12.5'
"""The version of Pydantic.
This version specifier is guaranteed to be compliant with the [specification],
introduced by [PEP 440].
[specification]: https://packaging.python.org/en/latest/specifications/version-specifiers/
[PEP 440]: https://peps.python.org/pep-0440/
# Keep this in sync with the version constraint in the `pyproject.toml` dependencies:
_COMPATIBLE_PYDANTIC_CORE_VERSION = '2.41.5'
def version_short() -> str:
    """Return the `major.minor` part of Pydantic version.
    It returns '2.1' if Pydantic version is '2.1.1'.
    return '.'.join(VERSION.split('.')[:2])
def version_info() -> str:
    """Return complete version information for Pydantic and its dependencies."""
    import pydantic_core._pydantic_core as pdc
    from ._internal import _git as git
    # get data about packages that are closely related to pydantic, use pydantic or often conflict with pydantic
    package_names = {
        'email-validator',
        'fastapi',
        'mypy',
        'pydantic-extra-types',
        'pydantic-settings',
        'pyright',
        'typing_extensions',
    related_packages = []
    for dist in importlib.metadata.distributions():
        name = dist.metadata['Name']
        if name in package_names:
            related_packages.append(f'{name}-{dist.version}')
    pydantic_dir = Path(__file__).parents[1].resolve()
    most_recent_commit = (
        git.git_revision(pydantic_dir) if git.is_git_repo(pydantic_dir) and git.have_git() else 'unknown'
        'pydantic version': VERSION,
        'pydantic-core version': __pydantic_core_version__,
        'pydantic-core build': getattr(pdc, 'build_info', None) or pdc.build_profile,  # pyright: ignore[reportPrivateImportUsage]
        'python version': sys.version,
        'platform': platform.platform(),
        'related packages': ' '.join(related_packages),
        'commit': most_recent_commit,
    return '\n'.join('{:>30} {}'.format(k + ':', str(v).replace('\n', ' ')) for k, v in info.items())
def check_pydantic_core_version() -> bool:
    """Check that the installed `pydantic-core` dependency is compatible."""
    return __pydantic_core_version__ == _COMPATIBLE_PYDANTIC_CORE_VERSION
def _ensure_pydantic_core_version() -> None:  # pragma: no cover
    if not check_pydantic_core_version():
        raise_error = True
        # Do not raise the error if pydantic is installed in editable mode (i.e. in development):
        if sys.version_info >= (3, 13):  # origin property added in 3.13
            from importlib.metadata import distribution
            dist = distribution('pydantic')
            if getattr(getattr(dist.origin, 'dir_info', None), 'editable', False):
                raise_error = False
        if raise_error:
            raise SystemError(
                f'The installed pydantic-core version ({__pydantic_core_version__}) is incompatible '
                f'with the current pydantic version, which requires {_COMPATIBLE_PYDANTIC_CORE_VERSION}. '
                "If you encounter this error, make sure that you haven't upgraded pydantic-core manually."
def parse_mypy_version(version: str) -> tuple[int, int, int]:
    """Parse `mypy` string version to a 3-tuple of ints.
    It parses normal version like `1.11.0` and extra info followed by a `+` sign
    like `1.11.0+dev.d6d9d8cd4f27c52edac1f537e236ec48a01e54cb.dirty`.
        version: The mypy version string.
        A triple of ints, e.g. `(1, 11, 0)`.
    return tuple(map(int, version.partition('+')[0].split('.')))  # pyright: ignore[reportReturnType]
__all__ = 'compiled', 'VERSION', 'version_info'
VERSION = '1.10.21'
    import cython  # type: ignore
    compiled: bool = False
        compiled = cython.compiled
        compiled = False
    optional_deps = []
    for p in ('devtools', 'dotenv', 'email-validator', 'typing-extensions'):
            import_module(p.replace('-', '_'))
        optional_deps.append(p)
        'pydantic compiled': compiled,
        'install path': Path(__file__).resolve().parent,
        'optional deps. installed': optional_deps,
VERSION = "7.8.6"
    print(VERSION, end="")  # noqa: T201
